import { v4 as uuid } from "uuid"
import { Puzzle } from "../../types/Puzzle"
const puzzleList: Puzzle[] = [
  { id: uuid(), category: "Event", value: "CABINET MEETING" },
  { id: uuid(), category: "Event", value: "BLIND DATE" },
  { id: uuid(), category: "Event", value: "SURPRISE BIRTHDAY PARTY" },
  { id: uuid(), category: "Event", value: "EUROPEAN VACATION" },
  { id: uuid(), category: "Event", value: "NEW HAMPSHIRE PRIMARY" },
  { id: uuid(), category: "Event", value: "SUPER BOWL SUNDAY" },
  { id: uuid(), category: "Event", value: "NEW YORK CITY MARATHON" },
  { id: uuid(), category: "Event", value: "BOY SCOUT JAMBOREE" },
  { id: uuid(), category: "Event", value: "PROSPECTING FOR GOLD" },
  { id: uuid(), category: "Event", value: "SPENDING TIME BEHIND BARS" },
  { id: uuid(), category: "Event", value: "LABOR DAY WEEKEND" },
  { id: uuid(), category: "Event", value: "CHINA'S STUDENT REBELLION" },
  { id: uuid(), category: "Event", value: "MAJOR CATASTROPHE" },
  { id: uuid(), category: "Event", value: "LUNCH BREAK" },
  { id: uuid(), category: "Event", value: "EXXON'S ALASKA OIL SPILL" },
  { id: uuid(), category: "Event", value: "CLAMBAKE" },
  { id: uuid(), category: "Event", value: "COLLEGE ALUMNI DINNER" },
  { id: uuid(), category: "Event", value: "SHUCKING CORN" },
  { id: uuid(), category: "Event", value: "WINTER CARNIVAL" },
  { id: uuid(), category: "Event", value: "SINGING IN THE SHOWER" },
  { id: uuid(), category: "Event", value: "THE NORMAN CONQUEST" },
  { id: uuid(), category: "Event", value: "TROPICAL STORM" },
  { id: uuid(), category: "Event", value: "SIT-DOWN DINNER" },
  { id: uuid(), category: "Event", value: "DRAG RACE" },
  { id: uuid(), category: "Event", value: "BOXING MATCH" },
  { id: uuid(), category: "Event", value: "HAVING ONE LAST FLING" },
  { id: uuid(), category: "Event", value: "UNDER HOUSE ARREST" },
  { id: uuid(), category: "Event", value: "ACT OF GOD" },
  { id: uuid(), category: "Event", value: "ESKIMO PIE" },
  { id: uuid(), category: "Event", value: "CANDLELIGHT VIGIL" },
  { id: uuid(), category: "Event", value: "NATIONAL TELEPHONE SURVEY" },
  { id: uuid(), category: "Event", value: "BREAKING THE SPEED LIMIT" },
  { id: uuid(), category: "Event", value: "CLOUDBURST" },
  { id: uuid(), category: "Event", value: "SLIPPED ON A BANANA PEEL" },
  { id: uuid(), category: "Event", value: "PILLOW FIGHT" },
  { id: uuid(), category: "Event", value: "VANNA'S PREGNANT" },
  { id: uuid(), category: "Event", value: "TOURNAMENT OF ROSES" },
  { id: uuid(), category: "Event", value: "AUCTION" },
  { id: uuid(), category: "Event", value: "JULIA ROBERTS MARRIES LYLE LOVETT" },
  {
    id: uuid(),
    category: "Event",
    value: "CHANGING OF THE GUARD OF BUCKINGHAM PALACE",
  },
  { id: uuid(), category: "Event", value: "NAPPING IN THE HAMMOCK" },
  { id: uuid(), category: "Event", value: "PITCHED A NO-HITTER" },
  { id: uuid(), category: "Event", value: "BANK ROBBERY" },
  { id: uuid(), category: "Event", value: "LOCKING YOUR KEYS IN YOUR CAR" },
  { id: uuid(), category: "Event", value: "WOODSTOCK NINETY-FOUR" },
  { id: uuid(), category: "Event", value: "DARNING SOCKS" },
  { id: uuid(), category: "Event", value: "SHORT DRIVE TO WORK" },
  { id: uuid(), category: "Event", value: "ACHIEVING A PLACE IN HISTORY" },
  { id: uuid(), category: "Event", value: "LIFELONG ROMANCE" },
  { id: uuid(), category: "Event", value: "RODEO" },
  {
    id: uuid(),
    category: "Event",
    value: "TELEVISION ADDRESS FROM THE OVAL OFFICE",
  },
  { id: uuid(), category: "Event", value: "JUNE WEDDING" },
  { id: uuid(), category: "Event", value: "HALF-TIME SHOW" },
  { id: uuid(), category: "Event", value: "COFFEE BREAK" },
  { id: uuid(), category: "Event", value: "CROSSING THE PICKET LINE" },
  { id: uuid(), category: "Event", value: "GOING OUT OF BUSINESS SALE" },
  { id: uuid(), category: "Event", value: "MEMORIAL DAY WEEKEND" },
  { id: uuid(), category: "Event", value: "WEEKEND IN PALM SPRINGS" },
  { id: uuid(), category: "Event", value: "PULLING AN ALL-NIGHTER" },
  { id: uuid(), category: "Event", value: "THE LOUISIANA PURCHASE" },
  { id: uuid(), category: "Event", value: "VOLCANIC ERUPTION" },
  { id: uuid(), category: "Event", value: "TROPICAL STORM" },
  { id: uuid(), category: "Event", value: "PRIMARY ELECTION" },
  { id: uuid(), category: "Event", value: "DAWN" },
  { id: uuid(), category: "Event", value: "APRIL FOOLS' DAY" },
  { id: uuid(), category: "Event", value: "TWO THUMBS UP FROM SISKEL & EBERT" },
  { id: uuid(), category: "Event", value: "EASTER PARADE DOWN FIFTH AVENUE" },
  {
    id: uuid(),
    category: "Event",
    value: "SUMMER OLYMPIC GAMES OPENING CEREMONY",
  },
  { id: uuid(), category: "Event", value: "BABY'S FIRST HAIRCUT" },
  { id: uuid(), category: "Event", value: "MAKING THE COVER OF TIME MAGAZINE" },
  { id: uuid(), category: "Event", value: "COMPLETE MAKEOVER" },
  {
    id: uuid(),
    category: "Event",
    value: "QUALIFYING FOR THE U.S. OLYMPIC TEAM",
  },
  { id: uuid(), category: "Event", value: "HEAT WAVE" },
  { id: uuid(), category: "Event", value: "PICNIC" },
  { id: uuid(), category: "Event", value: "TOUR DE FRANCE" },
  {
    id: uuid(),
    category: "Event",
    value: "PONCE DE LEON SEEKS THE FOUNTAIN OF YOUTH",
  },
  { id: uuid(), category: "Event", value: "ARMED FORCES DAY" },
  { id: uuid(), category: "Event", value: "FINAL JEOPARDY" },
  { id: uuid(), category: "Event", value: "LANDMARK SUPREME COURT DECISION" },
  {
    id: uuid(),
    category: "Event",
    value: "DISCOVERY OF GOLD AT SMUTTER'S MILL",
  },
  { id: uuid(), category: "Event", value: "EARNING A MASTER'S DEGREE" },
  { id: uuid(), category: "Event", value: "FIRST DAY OF WINTER" },
  { id: uuid(), category: "Event", value: "SALMON SWIMMING UPSTREAM TO SPAWN" },
  { id: uuid(), category: "Event", value: "JURY DUTY" },
  { id: uuid(), category: "Event", value: "TRADING PLACES" },
  { id: uuid(), category: "Event", value: "HITTING THE SNOOZE BUTTON" },
  { id: uuid(), category: "Event", value: "HAVING BREAKFAST IN BED" },
  { id: uuid(), category: "Event", value: "PLAYING CHARADES" },
  { id: uuid(), category: "Event", value: "CHILDBIRTH" },
  { id: uuid(), category: "Event", value: "BAKE SALE" },
  { id: uuid(), category: "Event", value: "WHITE HOUSE PRESS CONFERENCE" },
  { id: uuid(), category: "Event", value: "BREAKING THE SOUND BARRIER" },
  { id: uuid(), category: "Event", value: "COUNTY FAIR" },
  { id: uuid(), category: "Event", value: "NIGHTFALL" },
  {
    id: uuid(),
    category: "Event",
    value: "BENJAMIN FRANKLIN'S FAMOUS KITE EXPERIMENT",
  },
  { id: uuid(), category: "Event", value: "EATING A PHILLY CHEESESTEAK" },
  { id: uuid(), category: "Event", value: "PAYING OFF YOUR STUDENT LOAN" },
  { id: uuid(), category: "Event", value: "PAYDAY" },
  { id: uuid(), category: "Event", value: "SCANDAL" },
  { id: uuid(), category: "Event", value: "POTLUCK DINNER" },
  { id: uuid(), category: "Event", value: "FLUFFING UP PILLOWS" },
  { id: uuid(), category: "Event", value: "A QUIET EVENING AT HOME" },
  { id: uuid(), category: "Event", value: "A GUTSY DAY" },
  { id: uuid(), category: "Event", value: "BUYING YOUR FIRST HOME" },
  { id: uuid(), category: "Event", value: "A MOONLIT NIGHT" },
  { id: uuid(), category: "Event", value: "VALENTINE'S DAY DANCE" },
  { id: uuid(), category: "Event", value: "BREAKING OPEN THE PINATA" },
  { id: uuid(), category: "Event", value: "A RAINY DAY" },
  { id: uuid(), category: "Event", value: "ON-THE-SPOT DECISION" },
  { id: uuid(), category: "Event", value: "LOSING YOUR UMBRELLA" },
  { id: uuid(), category: "Event", value: "GETTING YOUR FAMILY PHOTO FRAMED" },
  {
    id: uuid(),
    category: "Event",
    value: "CELEBRATING A FIFTIETH WEDDING ANNIVERSARY",
  },
  { id: uuid(), category: "Event", value: "SCRUBBING" },
  { id: uuid(), category: "Event", value: "SEMESTER BREAK" },
  { id: uuid(), category: "Event", value: "BREAKING NEWS" },
  { id: uuid(), category: "Event", value: "SWIMMING WITH DOLPHINS" },
  { id: uuid(), category: "Event", value: "STARING OFF INTO SPACE" },
  {
    id: uuid(),
    category: "Event",
    value: "A QUIET EVENING STROLL ALONG THE BOARDWALK",
  },
  { id: uuid(), category: "Event", value: "SHOPPING ONLINE" },
  { id: uuid(), category: "Event", value: "FINDING A SOLUTION" },
  { id: uuid(), category: "Event", value: "PLAYING A PRANK" },
  { id: uuid(), category: "Event", value: "RIDING THE SUBWAY INTO MANHATTAN" },
  { id: uuid(), category: "Event", value: "BAKING A CAKE" },
  { id: uuid(), category: "Event", value: "PRE-GAME WARM-UP" },
  { id: uuid(), category: "Event", value: "LOUNGING POOLSIDE" },
  { id: uuid(), category: "Event", value: "CAMPING OUT UNDER THE STARS" },
  { id: uuid(), category: "Event", value: "HOUSE WARMING PARTY" },
  { id: uuid(), category: "Event", value: "CATCHING A FRISBEE" },
  {
    id: uuid(),
    category: "Event",
    value: "STROLLING BAREFOOT ALONG THE BEACH AT SUNSET",
  },
  {
    id: uuid(),
    category: "Event",
    value: "HAVING YOUR TIRES ROTATED AND BALANCED",
  },
  { id: uuid(), category: "Event", value: "A NIGHT ON THE TOWN" },
  { id: uuid(), category: "Event", value: "RENTING A MOVIE ON DVD" },
  { id: uuid(), category: "Event", value: "SINGING OFF-KEY" },
  { id: uuid(), category: "Event", value: "EATING ON THE RUN" },
  { id: uuid(), category: "Event", value: "ASKING FOR A RAISE" },
  { id: uuid(), category: "Event", value: "PIANO RECITAL" },
  { id: uuid(), category: "Event", value: "MAKING SNOW ANGELS" },
  { id: uuid(), category: "Event", value: "DRIVING TO WORK" },
  { id: uuid(), category: "Event", value: "HUMMING A TUNE" },
  { id: uuid(), category: "Event", value: "MEXICAN HAT DANCE" },
  { id: uuid(), category: "Event", value: "WILD CARD PLAYOFF GAME" },
  { id: uuid(), category: "Event", value: "GIVING A HIGH-FIVE" },
  { id: uuid(), category: "Event", value: "PARALLEL PARKING" },
  { id: uuid(), category: "Event", value: "SOAKING IN A HOT TUB" },
  { id: uuid(), category: "Event", value: "A COMMAND PERFORMANCE" },
  { id: uuid(), category: "Event", value: "TRAINING FOR THE WINTER OLYMPICS" },
  { id: uuid(), category: "Event", value: "MAIDEN VOYAGE" },
  { id: uuid(), category: "Event", value: "FLYING A KITE" },
  { id: uuid(), category: "Event", value: "TAKING THE DAY OFF" },
  { id: uuid(), category: "Event", value: "ENDING ON A HIGH NOTE" },
  { id: uuid(), category: "Event", value: "HAVING THE TIME OF YOUR LIFE" },
  { id: uuid(), category: "Event", value: "LIMBO CONTEST" },
  { id: uuid(), category: "Event", value: "SLEEPING SOUNDLY" },
  { id: uuid(), category: "Event", value: "BUYING SIGHT UNSEEN" },
  { id: uuid(), category: "Event", value: "A RAFFLE DRAWING" },
  { id: uuid(), category: "Event", value: "SEEING A MIRAGE" },
  { id: uuid(), category: "Event", value: "CHANGING YOUR MIND" },
  { id: uuid(), category: "Event", value: "DAYBREAK" },
  { id: uuid(), category: "Event", value: "BOWLING TOURNAMENT" },
  { id: uuid(), category: "Event", value: "PLAYING BEACH VOLLEYBALL" },
  { id: uuid(), category: "Event", value: "HORSEBACK RIDING" },
  { id: uuid(), category: "Event", value: "ROLLER COASTER RIDE" },
  { id: uuid(), category: "Event", value: "CROSSING TIME ZONES" },
  { id: uuid(), category: "Event", value: "RENTING A CAR" },
  { id: uuid(), category: "Event", value: "A DARING RESCUE" },
  { id: uuid(), category: "Event", value: "A GROUP HUG" },
  { id: uuid(), category: "Event", value: "A SHOW OF HANDS" },
  { id: uuid(), category: "Event", value: "BABBLING ON AND ON" },
  { id: uuid(), category: "Event", value: "BUYING A NEW SWIMSUIT" },
  { id: uuid(), category: "Event", value: "ASKING FOR DIRECTIONS" },
  { id: uuid(), category: "Event", value: "A RESTFUL NIGHT'S SLEEP" },
  { id: uuid(), category: "Event", value: "GETTING THE GO-AHEAD" },
  { id: uuid(), category: "Event", value: "DAILY WORKOUT" },
  { id: uuid(), category: "Event", value: "FUNDRAISING CAR WASH" },
  { id: uuid(), category: "Event", value: "JOB FAIR" },
  { id: uuid(), category: "Event", value: "SQUEAKING BY" },
  { id: uuid(), category: "Event", value: "FIRST DAY ON THE JOB" },
  { id: uuid(), category: "Event", value: "GAME OF CROQUET" },
  { id: uuid(), category: "Event", value: "SINGING IN THE SHOWER" },
  {
    id: uuid(),
    category: "Event",
    value: "A GONDOLA RIDE THROUGH THE CANALS OF VENICE",
  },
  { id: uuid(), category: "Event", value: "LOUNGING IN A HAMMOCK" },
  { id: uuid(), category: "Event", value: "BUILDING SANCASTLES" },
  { id: uuid(), category: "Event", value: "ACTING ON IMPULSE" },
  { id: uuid(), category: "Event", value: "MEETING A DEADLINE" },
  { id: uuid(), category: "Event", value: "GAME OF RACQUETBALL" },
  { id: uuid(), category: "Event", value: "A BAD HAIR DAY" },
  { id: uuid(), category: "Event", value: "PUTTING YOUR MAIL SERVICE ON HOLD" },
  { id: uuid(), category: "Event", value: "MAKING A SCRAPBOOK" },
  { id: uuid(), category: "Event", value: "SIGHTSEEING TOUR" },
  { id: uuid(), category: "Event", value: "BRING YOUR CHILD TO WORK DAY" },
  { id: uuid(), category: "Event", value: "HORSEBACK RIDING ALONG THE BEACH" },
  { id: uuid(), category: "Event", value: "FINISHING FIRST" },
  { id: uuid(), category: "Event", value: "A CASE OF THE GIGGLES" },
  { id: uuid(), category: "Event", value: "AN EVENING YOU'LL NEVER FORGET" },
  { id: uuid(), category: "Event", value: "LATE-NIGHT STUDY SESSION" },
  { id: uuid(), category: "Event", value: "SCIENTIFIC DISCOVERY" },
  { id: uuid(), category: "Event", value: "BUILDING A CAMPFIRE" },
  { id: uuid(), category: "Event", value: "SIGNING UP FOR SCUBA LESSONS" },
  { id: uuid(), category: "Event", value: "EATING NOODLES WITH CHOPSTICKS" },
  { id: uuid(), category: "Event", value: "THRILL OF A LIFETIME" },
  { id: uuid(), category: "Event", value: "FIREWORKS DISPLAY" },
  { id: uuid(), category: "Event", value: "EXCHANGING DOLLARS FOR EUROS" },
  { id: uuid(), category: "Event", value: "NAPPING IN A HAMMOCK ON THE BEACH" },
  { id: uuid(), category: "Event", value: "WALKING A TIGHTROPE" },
  { id: uuid(), category: "Event", value: "REGISTERING TO VOTE" },
  {
    id: uuid(),
    category: "Event",
    value: "ENJOYING WINE & CHEESE AT A SIDEWALK CAFE",
  },
  { id: uuid(), category: "Event", value: "FASHION SHOW" },
  { id: uuid(), category: "Event", value: "COLLECTING SEASHELLS" },
  { id: uuid(), category: "Event", value: "THE GRAVEYARD SHIFT" },
  { id: uuid(), category: "Event", value: "A STORYBOOK ENDING" },
  { id: uuid(), category: "Event", value: "WAXING A SURFBOARD" },
  { id: uuid(), category: "Event", value: "SECOND HONEYMOON" },
  { id: uuid(), category: "Event", value: "SIPPING AN ICE-COLD MARGARITA" },
  { id: uuid(), category: "Event", value: "ANNUAL FLOWER SHOW" },
  { id: uuid(), category: "Event", value: "CROWNING MISS AMERICA" },
  { id: uuid(), category: "Event", value: "DISCOVERING A JUNGLE WATERFALL" },
  { id: uuid(), category: "Event", value: "MONTHLY BANK STATEMENT" },
  { id: uuid(), category: "Event", value: "A FITTING SEND-OFF" },
  { id: uuid(), category: "Event", value: "SALSA DANCING LESSON" },
  { id: uuid(), category: "Event", value: "BEING KNIGHTED BY QUEEN ELIZABETH" },
  { id: uuid(), category: "Event", value: "A CLOSE CONTEST" },
  { id: uuid(), category: "Event", value: "HALF MARATHON" },
  { id: uuid(), category: "Event", value: "BASKET WEAVING" },
  { id: uuid(), category: "Event", value: "DIGGING YOUR TOES INTO THE SAND" },
  { id: uuid(), category: "Event", value: "SHOVELING THE DRIVEWAY" },
  { id: uuid(), category: "Event", value: "STRUMMING A UKELELE" },
  { id: uuid(), category: "Event", value: "WARMING YOUR HANDS BY THE FIRE" },
  { id: uuid(), category: "Event", value: "BLIZZARD" },
  { id: uuid(), category: "Event", value: "YEAR-END CLEARANCE SALE" },
  { id: uuid(), category: "Event", value: "SUNSET CATAMARAN CRUISE" },
  { id: uuid(), category: "Event", value: "LAST-MINUTE SHOPPING" },
  { id: uuid(), category: "Event", value: "LEARNING A FEW SPANISH PHRASES" },
  { id: uuid(), category: "Event", value: "TRADITIONAL LUAU FEAST" },
  { id: uuid(), category: "Event", value: "THE BUNNY HOP" },
  { id: uuid(), category: "Event", value: "VOYAGE" },
  { id: uuid(), category: "Event", value: "LUNAR ECLIPSE" },
  { id: uuid(), category: "Event", value: "NIGHTLY TURNDOWN SERVICE" },
  { id: uuid(), category: "Event", value: "JANUARY WHITE SALE" },
  { id: uuid(), category: "Event", value: "BASEBALL'S SPRING TRAINING" },
  { id: uuid(), category: "Event", value: "ARTS FESTIVAL" },
  { id: uuid(), category: "Event", value: "BATTLE OF THE BANDS" },
  { id: uuid(), category: "Event", value: "BUYING MUSIC DOWNLOADS" },
  { id: uuid(), category: "Event", value: "SUPER BOWL COMMERCIAL" },
  { id: uuid(), category: "Event", value: "SPRING BREAK" },
  {
    id: uuid(),
    category: "Event",
    value: "ANNUAL HULA FESTIVAL AND COMPETITION",
  },
  {
    id: uuid(),
    category: "Event",
    value: "BRITAIN'S PRINCE CHARLES ANNOUNCES ENGAGEMENT",
  },
  { id: uuid(), category: "Event", value: "WIPEOUT" },
  { id: uuid(), category: "Event", value: "APPLYING MORE SUNBLOCK" },
  { id: uuid(), category: "Event", value: "ONLINE AUCTION" },
  { id: uuid(), category: "Event", value: "FLIPPING A COIN" },
  { id: uuid(), category: "Event", value: "BAKE-OFF" },
  { id: uuid(), category: "Event", value: "SOOTHING BATH AND MASSAGE" },
  {
    id: uuid(),
    category: "Event",
    value: "GOING OVER NIAGRA FALLS IN A BARREL",
  },
  {
    id: uuid(),
    category: "Event",
    value: "WHITE-WATER RAFTING IN THE GRAND CANYON",
  },
  { id: uuid(), category: "Event", value: "A LEISURELY AFTERNOON SWIM" },
  { id: uuid(), category: "Event", value: "GIVING BIRTH" },
  { id: uuid(), category: "Event", value: "OUTRIGGER CANOE RACE" },
  { id: uuid(), category: "Event", value: "BOOK FAIR" },
  {
    id: uuid(),
    category: "Event",
    value: "FALLING ASLEEP TO THE SOUND OF THE OCEAN",
  },
  { id: uuid(), category: "Event", value: "DAZZLING FIREWORKS SHOW" },
  { id: uuid(), category: "Event", value: "WILD-GOOSE CHASE" },
  { id: uuid(), category: "Event", value: "LEARNING TO DANCE THE TANGO" },
  { id: uuid(), category: "Event", value: "A FOND FAREWELL" },
  { id: uuid(), category: "Event", value: "SIPPING HOT COCOA BY THE FIRE" },
  { id: uuid(), category: "Event", value: "THE ANNUAL RUNNING OF THE BULLS" },
  {
    id: uuid(),
    category: "Event",
    value: "SUBMITTING AN ASSIGNMENT BY E-MAIL",
  },
  { id: uuid(), category: "Event", value: "PIE-EATING CONTEST" },
  { id: uuid(), category: "Event", value: "APPLYING FOR A PASSPORT" },
  { id: uuid(), category: "Event", value: "AMEATEUR GOLF TOURNAMENT" },
  {
    id: uuid(),
    category: "Event",
    value: "THROWING OUT THE CEREMONIAL FIRST PITCH",
  },
  { id: uuid(), category: "Event", value: "SCIENCE FICTION CONVENTION" },
  { id: uuid(), category: "Event", value: "ADOPTING A PET" },
  { id: uuid(), category: "Event", value: "HALF-DAY SNORKELING EXCURSION" },
  { id: uuid(), category: "Event", value: "CHARTERING A FISING BOAT" },
  { id: uuid(), category: "Event", value: "RETIREMENT PARTY" },
  { id: uuid(), category: "Event", value: "ROYAL WEDDING" },
  {
    id: uuid(),
    category: "Event",
    value: "BEING SERENADED BY A MARIACHI BAND",
  },
  { id: uuid(), category: "Event", value: "LASER EYE SURGERY" },
  { id: uuid(), category: "Event", value: "PITCHING A TENT" },
  { id: uuid(), category: "Event", value: "INSTALLING NEW SOFTWARE" },
  { id: uuid(), category: "Event", value: "PAYING BILLS ONLINE" },
  { id: uuid(), category: "Event", value: "JOB-HUNTING" },
  { id: uuid(), category: "Event", value: "TAKING AN AFTERNOON SIESTA" },
  { id: uuid(), category: "Event", value: "THRILLING OVERTIME VICTORY" },
  { id: uuid(), category: "Event", value: "YEARLONG CENTENNIAL CELEBRATION" },
  { id: uuid(), category: "Event", value: "BIG BASH" },
  { id: uuid(), category: "Event", value: "BACKYARD BARBEQUE" },
  { id: uuid(), category: "Event", value: "TAKING A WEEK OFF" },
  { id: uuid(), category: "Event", value: "CHECKING E-MAIL" },
  { id: uuid(), category: "Event", value: "RESTORING A CLASSIC CAR" },
  { id: uuid(), category: "Event", value: "CLEARING CUSTOMS AND IMMIGRATION" },
  { id: uuid(), category: "Event", value: "BROWSING THROUGH SOUVENIR SHOPS" },
  { id: uuid(), category: "Event", value: "CHOPPING FIREWOOD" },
  { id: uuid(), category: "Event", value: "SEEING THE NORTHERN LIGHTS" },
  {
    id: uuid(),
    category: "Event",
    value: "HAVING THE ENTIRE BEACH TO YOURSELF",
  },
  { id: uuid(), category: "Event", value: "SINGING KARAOKE" },
  { id: uuid(), category: "Event", value: "LEARNING HOW TO SAIL" },
  { id: uuid(), category: "Event", value: "APPLYING FOR A PATENT" },
  { id: uuid(), category: "Event", value: "TWILIGHT WINE TASTING PARTY" },
  { id: uuid(), category: "Event", value: "PRE-GAME TAILGATE PARTY" },
  { id: uuid(), category: "Event", value: "AUTOGRAPH SHOW" },
  { id: uuid(), category: "Event", value: "A NIGHT ON THE TOWN" },
  { id: uuid(), category: "Event", value: "BUSINESS LUNCH" },
  { id: uuid(), category: "Event", value: "RENTING A TUXEDO" },
  { id: uuid(), category: "Event", value: "SOAKING IN NATURAL HOT SPRINGS" },
  { id: uuid(), category: "Event", value: "WATCHING THE SUNSET ON KEY WEST" },
  { id: uuid(), category: "Event", value: "SAMPLING THE LOCAL TEQUILA" },
  { id: uuid(), category: "Event", value: "SIPPING A HOT CAPPUCCINO" },
  { id: uuid(), category: "Event", value: "WINDOW SHOPPING ON FIFTH AVENUE" },
  { id: uuid(), category: "Event", value: "TOURING A MEDIEVAL CASTLE" },
  { id: uuid(), category: "Event", value: "EXCHANGING DOLLARS FOR PESOS" },
  { id: uuid(), category: "Event", value: "OPENING AN E-MAIL ATTACHMENT" },
  { id: uuid(), category: "Event", value: "TAKING INVENTORY" },
  { id: uuid(), category: "Event", value: "KISSING THE BLARNEY STONE" },
  { id: uuid(), category: "Event", value: "BACHELOR AUCTION" },
  { id: uuid(), category: "Event", value: "MATH QUIZ" },
  { id: uuid(), category: "Event", value: "WHITENING YOUR TEETH" },
  { id: uuid(), category: "Event", value: "GIVING BLOOD" },
  { id: uuid(), category: "Event", value: "APRIL FOOL'S DAY" },
  { id: uuid(), category: "Event", value: "BLOWING A FUSE" },
  { id: uuid(), category: "Event", value: "RECEIVING A BEAUTIFUL FLOWER LEI" },
  {
    id: uuid(),
    category: "Event",
    value: "ORDERING CHINESE FOOD FOR DELIVERY",
  },
  { id: uuid(), category: "Event", value: "EARTH DAY" },
  { id: uuid(), category: "Event", value: "SHOPPING ON THE INTERNET" },
  { id: uuid(), category: "Event", value: "RENAISSANCE FAIR" },
  { id: uuid(), category: "Event", value: "HAVING A BABY" },
  { id: uuid(), category: "Event", value: "PICKING OUT POSTCARDS" },
  { id: uuid(), category: "Event", value: "DOCTOR'S APPOINTMENT" },
  { id: uuid(), category: "Event", value: "HOMECOMING GAME" },
  { id: uuid(), category: "Event", value: "TAKING A ROAD TRIP" },
  { id: uuid(), category: "Event", value: "VISITING THE HOCKEY HALL OF FAME" },
  { id: uuid(), category: "Event", value: "A FANTASTIC FINISH" },
  { id: uuid(), category: "Event", value: "VIDEO GAME TOURNAMENT" },
  { id: uuid(), category: "Event", value: "PLANTING A TREE" },
  {
    id: uuid(),
    category: "Event",
    value: "MARRIAGE PROPOSAL AT THE TOP OF THE EIFFEL TOWER",
  },
  { id: uuid(), category: "Event", value: "SALSA DANCING COMPETITION" },
  { id: uuid(), category: "Event", value: "GROWING A BEARD" },
  { id: uuid(), category: "Event", value: "THREE-DAY WEEKEND" },
  { id: uuid(), category: "Event", value: "SOLVING A MYSTERY" },
  { id: uuid(), category: "Event", value: "MAKING A VOW" },
  { id: uuid(), category: "Event", value: "STAR TREK CONVENTION" },
  {
    id: uuid(),
    category: "Event",
    value: "LOUNGING IN A HAMMOCK ON THE BEACH",
  },
  { id: uuid(), category: "Event", value: "PLAYING THE BAGPIPES" },
  { id: uuid(), category: "Event", value: "FIRING UP THE GRILL" },
  {
    id: uuid(),
    category: "Event",
    value: "GETTING ADJUSTED TO THE TIME CHANGE",
  },
  { id: uuid(), category: "Event", value: "SHOPPING FOR SOUVENIRS" },
  { id: uuid(), category: "Event", value: "TOWN HALL MEETING" },
  {
    id: uuid(),
    category: "Event",
    value: "CATCHING A FOUL BALL IN THE STANDS",
  },
  { id: uuid(), category: "Event", value: "FLUFFING UP PILLOWS" },
  { id: uuid(), category: "Event", value: "WEDDING REHEARSAL" },
  {
    id: uuid(),
    category: "Event",
    value: "POSTING VACATION PHOTOS ON THE WEB",
  },
  { id: uuid(), category: "Event", value: "DOUBLE DATE" },
  { id: uuid(), category: "Event", value: "PICKING OUT AN ALOHA SHIRT" },
  { id: uuid(), category: "Event", value: "HIGH SCHOOL REUNION" },
  { id: uuid(), category: "Event", value: "SETTING UP BEACH CHAIRS" },
  { id: uuid(), category: "Event", value: "JULY FOURTH" },
  { id: uuid(), category: "Event", value: "CHILI COOK-OFF" },
  { id: uuid(), category: "Event", value: "POSING FOR A PORTRAIT" },
  {
    id: uuid(),
    category: "Event",
    value: "BLOWING OUT THE CANDLES ON A BIRTHDAY CAKE",
  },
  { id: uuid(), category: "Event", value: "POTLUCK DINNER" },
  { id: uuid(), category: "Event", value: "PSYCHIC READING" },
  { id: uuid(), category: "Event", value: "WARMING YOUR FEET BY THE FIRE" },
  { id: uuid(), category: "Event", value: "FAMILY GAME NIGHT" },
  { id: uuid(), category: "Event", value: "HELICOPTER RIDE" },
  { id: uuid(), category: "Event", value: "MOTORCYCLE RALLY" },
  { id: uuid(), category: "Event", value: "THE LONG JUMP" },
  { id: uuid(), category: "Event", value: "BALLROOM DANCING" },
  { id: uuid(), category: "Event", value: "BARGAIN MATINEE" },
  { id: uuid(), category: "Event", value: "WINNING THE OLYMPIC MARATHON" },
  { id: uuid(), category: "Event", value: "DIMMING THE LIGHTS" },
  {
    id: uuid(),
    category: "Event",
    value: "STROLLING HAND IN HAND ON THE BEACH",
  },
  { id: uuid(), category: "Event", value: "APPLE PICKING" },
  { id: uuid(), category: "Event", value: "SPRING FASHION SHOW" },
  { id: uuid(), category: "Event", value: "WINNING THE LOTTERY" },
  { id: uuid(), category: "Event", value: "STREET FAIR" },
  { id: uuid(), category: "Event", value: "RECITING THE PLEDGE OF ALLEGIANCE" },
  { id: uuid(), category: "Event", value: "SNACKING BETWEEN MEALS" },
  { id: uuid(), category: "Event", value: "DANCING TILL DAWN" },
  { id: uuid(), category: "Event", value: "BASKING IN THE SUN" },
  { id: uuid(), category: "Event", value: "WATCHING THE SUNRISE" },
  { id: uuid(), category: "Event", value: "SUNDAY BRUNCH" },
  { id: uuid(), category: "Event", value: "BUYING BOOKS" },
  { id: uuid(), category: "Event", value: "WILD WEST SHOW" },
  { id: uuid(), category: "Event", value: "HUGE OVATION" },
  { id: uuid(), category: "Event", value: "SINGING ALONG WITH THE RADIO" },
  { id: uuid(), category: "Event", value: "FILLING OUT A JOB APPLICATION" },
  { id: uuid(), category: "Event", value: "A SPECIAL CHAMPION" },
  { id: uuid(), category: "Event", value: "SIPPING COLD RUM PUNCH" },
  { id: uuid(), category: "Event", value: "AUTHENTIC HAWAIIAN LUAU" },
  { id: uuid(), category: "Event", value: "HONEYMOON IN EUROPE" },
  { id: uuid(), category: "Event", value: "SHOPPING FOR A NEW BATHING SUIT" },
  { id: uuid(), category: "Event", value: "GETTING A BIG RAISE" },
  { id: uuid(), category: "Event", value: "SILVER ANNIVERSARY" },
  { id: uuid(), category: "Event", value: "LEARNING TO DRIVE" },
  { id: uuid(), category: "Event", value: "WRITING A BLOG" },
  { id: uuid(), category: "Event", value: "PACKING YOUR BAGS" },
  { id: uuid(), category: "Event", value: "WATCHING MOVIE TRAILERS ONLINE" },
  { id: uuid(), category: "Event", value: "CREATING A SONG PLAYLIST" },
  { id: uuid(), category: "Event", value: "FOOD FIGHT" },
  { id: uuid(), category: "Event", value: "HORSE-DRAWN CARRIAGE RIDE" },
  { id: uuid(), category: "Event", value: "BLOWING A KISS" },
  { id: uuid(), category: "Event", value: "BLACK HISTORY MONTH" },
  { id: uuid(), category: "Event", value: "HARBOR CRUISE" },
  { id: uuid(), category: "Event", value: "COUNTY FAIR" },
  { id: uuid(), category: "Event", value: "SQUARE DANCE" },
  { id: uuid(), category: "Event", value: "BREAKING IN A NEW PAIR OF BOOTS" },
  { id: uuid(), category: "Event", value: "WRITING A TELL-ALL MEMOIR" },
  { id: uuid(), category: "Event", value: "REAL ESTATE TRANSITION" },
  { id: uuid(), category: "Event", value: "SEEING ALL THE SIGHTS" },
  { id: uuid(), category: "Event", value: "EATING TO YOUR HEART'S CONTENT" },
  { id: uuid(), category: "Event", value: "ONE-ON-ONE INTERVIEW" },
  { id: uuid(), category: "Event", value: "WINNING THE NOBEL PRIZE" },
  { id: uuid(), category: "Event", value: "MAKING A NEW FRIEND" },
  { id: uuid(), category: "Event", value: "TRADITIONAL FLAMENCO SHOW" },
  { id: uuid(), category: "Event", value: "GIRLS' NIGHT OUT" },
  { id: uuid(), category: "Event", value: "POLICE AUCTION" },
  { id: uuid(), category: "Event", value: "SATURDAY NIGHT DATE" },
  { id: uuid(), category: "Event", value: "REMODELING THE KITCHEN" },
  { id: uuid(), category: "Event", value: "A BIG DECISION" },
  { id: uuid(), category: "Event", value: "SIDEWALK SALE" },
  { id: uuid(), category: "Event", value: "DOZING OFF" },
  { id: uuid(), category: "Event", value: "FIRST DAY OF SPRING" },
  { id: uuid(), category: "Event", value: "ROMANTIC GONDOLA RIDE" },
  { id: uuid(), category: "Event", value: "HEAVYWEIGHT TITLE FIGHT" },
  { id: uuid(), category: "Event", value: "SIPPING A PINA COLADA BY THE POOL" },
  { id: uuid(), category: "Event", value: "MAKING SNOW ANGELS" },
  { id: uuid(), category: "Event", value: "NATURE WALK" },
  { id: uuid(), category: "Event", value: "INDULGING YOURSELF" },
  { id: uuid(), category: "Event", value: "TOWELING OFF AFTER A SWIM" },
  { id: uuid(), category: "Event", value: "CONDUCTING AN ORCHESTRA" },
  { id: uuid(), category: "Event", value: "AWARDS BANQUET" },
  { id: uuid(), category: "Event", value: "TAKING TANGO LESSONS" },
  { id: uuid(), category: "Event", value: "FILING YOUR TAX RETURN" },
  { id: uuid(), category: "Event", value: "READING THE MORNING PAPER" },
  { id: uuid(), category: "Event", value: "CLIPPING COUPONS" },
  { id: uuid(), category: "Event", value: "TRYING TASTY REGIONAL SPECIALTIES" },
  {
    id: uuid(),
    category: "Event",
    value: "SPENDING SOME MORE TIME WITH THE FAMILY",
  },
  { id: uuid(), category: "Event", value: "ORDERING DINNER IN SPANISH" },
  { id: uuid(), category: "Event", value: "DEVELOPING A PHOTOGRAPH" },
  { id: uuid(), category: "Event", value: "DAILY EXCERCISE" },
  { id: uuid(), category: "Event", value: "BABY'S FIRST STEP" },
  { id: uuid(), category: "Event", value: "JURY DUTY" },
  { id: uuid(), category: "Event", value: "COMIC BOOK CONVENTION" },
  { id: uuid(), category: "Event", value: "CROSSING THE ATLANTIC" },
  { id: uuid(), category: "Event", value: "PICNIC ON THE BEACH" },
  { id: uuid(), category: "Event", value: "BASIC TRAINING" },
  { id: uuid(), category: "Event", value: "SANDCASTLE COMPETITION" },
  { id: uuid(), category: "Event", value: "RECYCLING CANS AND BOTTLES" },
  { id: uuid(), category: "Event", value: "DESIGNING A FLORAL ARRANGEMENT" },
  { id: uuid(), category: "Event", value: "WAITING IN THE WINGS" },
  { id: uuid(), category: "Event", value: "RELAXING SUNSET STROLL" },
  { id: uuid(), category: "Event", value: "PLACING A PERSONAL AD" },
  { id: uuid(), category: "Event", value: "WALKING THE DOG" },
  { id: uuid(), category: "Event", value: "BOYS' NIGHT OUT" },
  { id: uuid(), category: "Event", value: "HOUSING BOOM" },
  { id: uuid(), category: "Event", value: "SWEET SIXTEEN PARTY" },
  { id: uuid(), category: "Event", value: "TOTAL ECLIPSE OF THE SUN" },
  { id: uuid(), category: "Event", value: "CHAMPAGNE BRUNCH" },
  { id: uuid(), category: "Event", value: "MARRIAGE PROPOSAL" },
  { id: uuid(), category: "Event", value: "WEEKEND ROAD TRIP" },
  { id: uuid(), category: "Event", value: "FULFILLING A LIFELONG DREAM" },
  { id: uuid(), category: "Event", value: "GARDEN WEDDING CEREMONY" },
  { id: uuid(), category: "Event", value: "TOURING A WINERY" },
  { id: uuid(), category: "Event", value: "ANNUAL CONVENTION" },
  { id: uuid(), category: "Event", value: "BREAKFAST MEETING" },
  { id: uuid(), category: "Event", value: "BUILDING A BONFIRE" },
  {
    id: uuid(),
    category: "Event",
    value: "SITTING DOWN TO DINNER WITH THE WHOLE FAMILY",
  },
  { id: uuid(), category: "Event", value: "PUBLISHING A FIRST NOVEL" },
  { id: uuid(), category: "Event", value: "CATERED LUNCH" },
  { id: uuid(), category: "Event", value: "PIANO LESSON" },
  { id: uuid(), category: "Event", value: "NEW ENGLAND CLAMBAKE" },
  {
    id: uuid(),
    category: "Event",
    value: "RECEIVING A BOUQUET OF FLOWERS AT WORK",
  },
  { id: uuid(), category: "Event", value: "COOKING CLASS" },
  { id: uuid(), category: "Event", value: "VICTORY PARADE" },
  { id: uuid(), category: "Event", value: "A QUICK BREAK" },
  { id: uuid(), category: "Event", value: "CLEARANCE SALE" },
  { id: uuid(), category: "Event", value: "PASSING INSPECTION" },
  { id: uuid(), category: "Event", value: "THE GRAND TOUR" },
  { id: uuid(), category: "Event", value: "GETTING A MAKEOVER" },
  {
    id: uuid(),
    category: "Event",
    value: "WINNING THE NEW YORK CITY MARATHON",
  },
  { id: uuid(), category: "Event", value: "CONFERENCE CALL" },
  { id: uuid(), category: "Event", value: "THE SUN SETTING OVER THE PACIFIC" },
  { id: uuid(), category: "Event", value: "SPELLING TEST" },
  { id: uuid(), category: "Event", value: "TRADITIONAL LUAU CEREMONIAL FEAST" },
  { id: uuid(), category: "Event", value: "AFTERNOON NAP" },
  { id: uuid(), category: "Event", value: "SALSA DANCING TILL DAWN" },
  { id: uuid(), category: "Event", value: "BUYING A HOME" },
  { id: uuid(), category: "Event", value: "EXPLORING AN EXCITING NEW CITY" },
  { id: uuid(), category: "Event", value: "GIVING BACK TO THE COMMUNITY" },
  { id: uuid(), category: "Event", value: "SPACE SHUTTLE LAUNCH" },
  { id: uuid(), category: "Event", value: "COUNTRY MUSIC AWARDS" },
  { id: uuid(), category: "Event", value: "GETTING YOUR PASSPORT STAMPED" },
  {
    id: uuid(),
    category: "Event",
    value: "THE CHANGING OF THE GUARD AT BUCKINGHAM PALACE",
  },
  { id: uuid(), category: "Event", value: "SILENT AUCTION" },
  { id: uuid(), category: "Event", value: "FIGHT NIGHT IN LAS VEGAS" },
  { id: uuid(), category: "Event", value: "FAMILY REUNION" },
  { id: uuid(), category: "Event", value: "HIGHLY RECOMMENDED WALKING TOUR" },
  { id: uuid(), category: "Event", value: "GARAGE SALE" },
  { id: uuid(), category: "Event", value: "SCORING A TOUCHDOWN" },
  { id: uuid(), category: "Event", value: "JOB FAIR" },
  { id: uuid(), category: "Event", value: "MUSEUM TOUR" },
  { id: uuid(), category: "Event", value: "FOUR-COURSE GOURMET DINNER" },
  { id: uuid(), category: "Event", value: "MEXICAN HAT DANCE" },
  { id: uuid(), category: "Event", value: "SHOPPING SPREE" },
  { id: uuid(), category: "Event", value: "SPECTACULAR SUNSET" },
  { id: uuid(), category: "Event", value: "CLASSIC CAR SHOW" },
  { id: uuid(), category: "Event", value: "ATTENDING A FIESTA" },
  { id: uuid(), category: "Event", value: "RITE OF PASSAGE" },
  { id: uuid(), category: "Event", value: "OCEAN VOYAGE" },
  { id: uuid(), category: "Event", value: "POLITICAL DEBATE" },
  { id: uuid(), category: "Event", value: "JOB INTERVIEW" },
  { id: uuid(), category: "Event", value: "BABY'S FIRST HAIRCUT" },
  { id: uuid(), category: "Event", value: "SEMI-ANNUAL SALE" },
  { id: uuid(), category: "Event", value: "GROUP DATE" },
  { id: uuid(), category: "Event", value: "CLASS REUNION" },
  { id: uuid(), category: "Event", value: "CHAMPAGNE TOAST" },
  { id: uuid(), category: "Event", value: "CHAMPAGNE TOAST" },
  { id: uuid(), category: "Event", value: "COCKTAIL RECEPTION" },
  { id: uuid(), category: "Event", value: "CELEBRATING A BIG PROMOTION" },
  { id: uuid(), category: "Event", value: "PHOTO SHOOT" },
  { id: uuid(), category: "Event", value: "SPRING CLEANING" },
  { id: uuid(), category: "Event", value: "LAZY SUNDAY MORNING" },
  { id: uuid(), category: "Event", value: "REGIONAL SALES CONVENTION" },
  { id: uuid(), category: "Event", value: "HIKE IN PAY" },
  { id: uuid(), category: "Event", value: "FUNDRAISING CAR WASH" },
  { id: uuid(), category: "Event", value: "PET ADOPTION FAIR" },
  { id: uuid(), category: "Event", value: "PANCAKE BREAKFAST" },
  { id: uuid(), category: "Event", value: "QUITTING A JOB" },
  { id: uuid(), category: "Event", value: "AN AFTERNOON OF SIGHTSEEING" },
  { id: uuid(), category: "Event", value: "A SEMESTER ABROAD" },
  { id: uuid(), category: "Event", value: "POSTING A VIDEO ON YOUTUBE" },
  { id: uuid(), category: "Event", value: "MOTHER'S DAY DINNER" },
  { id: uuid(), category: "Event", value: "LIVELY STREET FESTIVAL" },
  { id: uuid(), category: "Event", value: "LONG WEEKEND" },
  { id: uuid(), category: "Event", value: "CATCHING THE BRIDE'S BOUQUET" },
  { id: uuid(), category: "Event", value: "FIRST DAY OF SCHOOL" },
  { id: uuid(), category: "Event", value: "A LONG CHAT ON THE PHONE" },
  { id: uuid(), category: "Event", value: "FACTORY TOUR" },
  { id: uuid(), category: "Event", value: "SADIE HAWKINS DANCE" },
  { id: uuid(), category: "Event", value: "BACKYARD BARBEQUE" },
  { id: uuid(), category: "Event", value: "PALM READING" },
  { id: uuid(), category: "Event", value: "ANNUAL LIVESTOCK SHOW AND RODEO" },
  { id: uuid(), category: "Event", value: "SETTING A NEW WORLD RECORD" },
  { id: uuid(), category: "Event", value: "SHOPPING SPREE" },
  { id: uuid(), category: "Event", value: "GUITAR LESSON" },
  { id: uuid(), category: "Event", value: "APPLYING TO COLLEGE" },
  { id: uuid(), category: "Event", value: "THE OLYMPIC GAMES" },
  { id: uuid(), category: "Event", value: "WAREHOUSE SALE" },
  { id: uuid(), category: "Event", value: "GUIDED WALKING TOUR" },
  { id: uuid(), category: "Event", value: "CHILDREN'S MUSIC CLASS" },
  { id: uuid(), category: "Event", value: "AMERICA'S CUP" },
  {
    id: uuid(),
    category: "Event",
    value: "BRIEF PERIOD OF WARM AFTERNOON SHOWERS",
  },
  { id: uuid(), category: "Event", value: "GOING ON SAFARI" },
  { id: uuid(), category: "Event", value: "PANNING FOR GOLD" },
  { id: uuid(), category: "Event", value: "A REFRESHING DIP IN THE OCEAN" },
  { id: uuid(), category: "Event", value: "FIREWORKS SHOW" },
  { id: uuid(), category: "Event", value: "ESTATE SALE" },
  { id: uuid(), category: "Event", value: "HEAVY DOWNPOUR" },
  { id: uuid(), category: "Event", value: "LANDSLIDE VICTORY" },
  { id: uuid(), category: "Event", value: "PARTIAL ECLIPSE" },
  { id: uuid(), category: "Event", value: "HELICOPTER TOUR" },
  { id: uuid(), category: "Event", value: "FLYING OVER THE EQUATOR" },
  { id: uuid(), category: "Event", value: "SUNSET DINNER CRUISE" },
  { id: uuid(), category: "Event", value: "BUMPY FLIGHT ATTENDANT" },
  { id: uuid(), category: "Event", value: "TWO-FOR-ONE SALE" },
  {
    id: uuid(),
    category: "Event",
    value: "SOARING ABOVE GLACIERS IN A SEAPLANE",
  },
  { id: uuid(), category: "Event", value: "EXPLORING ANCIENT RUINS" },
  { id: uuid(), category: "Event", value: "ANNUAL HULA FESTIVAL" },
  { id: uuid(), category: "Event", value: "OPENING CEREMONIES" },
  { id: uuid(), category: "Event", value: "METEOR SHOWER" },
  { id: uuid(), category: "Event", value: "MAIDEN VOYAGE" },
  { id: uuid(), category: "Event", value: "FAMILY GATHERING" },
  {
    id: uuid(),
    category: "Event",
    value: "RUDOLPH'S RED NOSE GUIDES SANTA'S SLEIGH",
  },
  { id: uuid(), category: "Event", value: "FOOD & WINE FESTIVAL" },
  { id: uuid(), category: "Event", value: "REPORTING FOR DUTY" },
  { id: uuid(), category: "Event", value: "BLOWOUT" },
  { id: uuid(), category: "Event", value: "AN ENORMOUS UNDERTAKING" },
  { id: uuid(), category: "Event", value: "MAKING THE HONOR ROLL" },
  { id: uuid(), category: "Event", value: "SAILING OUT WITH THE TIDE" },
  { id: uuid(), category: "Event", value: "BIGGEST GAME OF THE SEASON" },
  { id: uuid(), category: "Event", value: "FLYING OFF TO A TROPICAL PARADISE" },
  { id: uuid(), category: "Event", value: "CASUAL FRIDAY" },
  { id: uuid(), category: "Event", value: "A NICE LONG WEEKEND" },
  {
    id: uuid(),
    category: "Event",
    value: "UNIQUE OCEANFRONT DINING EXPERIENCE",
  },
  { id: uuid(), category: "Event", value: "SOPHOMORE YEAR" },
  {
    id: uuid(),
    category: "Event",
    value: "WATCHING CLIFF DIVERS FROM THE DECK OF A SHIP",
  },
  { id: uuid(), category: "Event", value: "ROMANTIC GETAWAY" },
  { id: uuid(), category: "Event", value: "CHERRY BLOSSOM FESTIVAL" },
  { id: uuid(), category: "Event", value: "ALL-STAR GAME" },
  { id: uuid(), category: "Event", value: "RUNNING OFF TO AN ISLAND HIDEAWAY" },
  { id: uuid(), category: "Event", value: "WEDDING RECEPTION" },
  { id: uuid(), category: "Event", value: "HIGH TIDE" },
  { id: uuid(), category: "Event", value: "BRIDAL SHOWER" },
  { id: uuid(), category: "Event", value: "A HUGE MILESTONE" },
  { id: uuid(), category: "Event", value: "FRESH SEAFOOD AND SOURDOUGH BREAD" },
  { id: uuid(), category: "Event", value: "EMBARKING ON A TROPICAL ADVENTURE" },
  { id: uuid(), category: "Event", value: "CROSSING THE FINISH LINE" },
  {
    id: uuid(),
    category: "Event",
    value: "GRADUATING AT THE TOP OF YOUR CLASS",
  },
  { id: uuid(), category: "Event", value: "HANGING OUT AT A FRESHWATER POOL" },
  { id: uuid(), category: "Event", value: "TOO CLOSE TO CALL" },
  {
    id: uuid(),
    category: "Event",
    value: "PAMPERING YOURSELF WITH A FULL-BODY MASSAGE",
  },
  { id: uuid(), category: "Event", value: "EPIC JOURNEY" },
  { id: uuid(), category: "Event", value: "GRADUATION CEREMONY" },
  { id: uuid(), category: "Event", value: "OCEANFRONT LUAU WITH TIKI TORCHES" },
  { id: uuid(), category: "Event", value: "ANNIVERSARY PARTY" },
  { id: uuid(), category: "Event", value: "ANNUAL NATIONAL CONVENTION" },
  { id: uuid(), category: "Event", value: "TAKING A DREAM VACATION" },
  { id: uuid(), category: "Event", value: "BEING SERENADED IN A GONDOLA" },
  { id: uuid(), category: "Event", value: "SURPRISE VISIT" },
  { id: uuid(), category: "Event", value: "BICYCLE RACE" },
  { id: uuid(), category: "Event", value: "AUTUMN FESTIVAL" },
  { id: uuid(), category: "Event", value: "VICTORY CELEBRATION" },
  { id: uuid(), category: "Event", value: "COMPETING IN A TRIATHLON" },
  { id: uuid(), category: "Event", value: "A SUNSET STROLL ALONG THE BEACH" },
  { id: uuid(), category: "Event", value: "COSTUME CONTEST" },
  { id: uuid(), category: "Event", value: "DISCOVERING A SECLUDED WATERFALL" },
  { id: uuid(), category: "Event", value: "VICTORY LAP" },
  { id: uuid(), category: "Event", value: "HALFTIME HIGHLIGHTS" },
  { id: uuid(), category: "Event", value: "GRADUATION DAY" },
  { id: uuid(), category: "Event", value: "SAILING TO MARTHA'S VINEYARD" },
  { id: uuid(), category: "Event", value: "TAILGATE PARTY" },
  { id: uuid(), category: "Event", value: "BACKYARD LOBSTER BAKE" },
  { id: uuid(), category: "Event", value: "A STELLAR PERFORMANCE" },
  { id: uuid(), category: "Event", value: "ALL-DAY SIGHTSEEING TOUR" },
  { id: uuid(), category: "Event", value: "GRADUATION DAY" },
  { id: uuid(), category: "Event", value: "SAILING TO MARTHA'S VINEYARD" },
  { id: uuid(), category: "Event", value: "TAILGATE PARTY" },
  { id: uuid(), category: "Event", value: "BACKYARD LOBSTER BAKE" },
  { id: uuid(), category: "Event", value: "A STELLAR PERFORMANCE" },
  { id: uuid(), category: "Event", value: "ALL-DAY SIGHTSEEING TOUR" },
  {
    id: uuid(),
    category: "Event",
    value: "PLACING A STAR ON THE TOP OF THE CHRISTMAS TREE",
  },
  { id: uuid(), category: "Event", value: "COUNTY FAIR" },
  { id: uuid(), category: "Event", value: "PLAYOFF GAME" },
  {
    id: uuid(),
    category: "Event",
    value: "MOLTEN LAVA FLOWING FROM A VOLCANO",
  },
  { id: uuid(), category: "Event", value: "ARTS FESTIVAL" },
  { id: uuid(), category: "Event", value: "BUYING A WHOLE NEW WARDROBE" },
  { id: uuid(), category: "Event", value: "FINE DINING UNDER THE STARS" },
  { id: uuid(), category: "Event", value: "HIGH SCHOOL REUNION" },
  { id: uuid(), category: "Event", value: "CONCERT IN THE PARK" },
  { id: uuid(), category: "Event", value: "OUR FIRST KISS" },
  { id: uuid(), category: "Event", value: "WEDDING SHOWER" },
  { id: uuid(), category: "Event", value: "SEEING A SHOOTING STAR" },
  { id: uuid(), category: "Event", value: "I'M PUZZLED" },
  { id: uuid(), category: "Event", value: "HAVING BREAKFAST IN BED" },
  { id: uuid(), category: "Event", value: "A GENTLE SOOTHING MASSAGE" },
  { id: uuid(), category: "Event", value: "ROMANTIC CANDLELIGHT DINNER" },
  { id: uuid(), category: "Event", value: "A BIG WIN" },
  { id: uuid(), category: "Event", value: "SECOND HONEYMOON" },
  { id: uuid(), category: "Event", value: "A RIP-ROARING GOOD TIME" },
  { id: uuid(), category: "Event", value: "PICNIC LUNCH" },
  { id: uuid(), category: "Event", value: "FEEDING FRENZY" },
  { id: uuid(), category: "Event", value: "MOVIE PREMIERE" },
  { id: uuid(), category: "Event", value: "PHOTO FINISH" },
  { id: uuid(), category: "Event", value: "GRAND-SLAM HOME RUN" },
  { id: uuid(), category: "Event", value: "RECEIVEING A HANDWRITTEN LETTER" },
  { id: uuid(), category: "Event", value: "SHOCKING DEVELOPMENT" },
  { id: uuid(), category: "Event", value: "LIVESTOCK AUCTION" },
  { id: uuid(), category: "Event", value: "CHILI COOK-OFF" },
  { id: uuid(), category: "Event", value: "WILD WEST SHOW" },
  { id: uuid(), category: "Event", value: "TRACTOR PULL" },
  { id: uuid(), category: "Event", value: "THE GOLD RUSH" },
  { id: uuid(), category: "Event", value: "REHEARSAL DINNER" },
  { id: uuid(), category: "Event", value: "BLOWING A FUSE" },
  {
    id: uuid(),
    category: "Event",
    value: "RIDING A CABLE CAR TO FISHERMAN'S WHARF",
  },
  { id: uuid(), category: "Event", value: "THREE-DAY WEEKEND" },
  { id: uuid(), category: "Event", value: "GIFT EXCHANGE" },
  { id: uuid(), category: "Event", value: "MUSIC FESTIVAL" },
  { id: uuid(), category: "Event", value: "WINNING STREAK" },
  { id: uuid(), category: "Event", value: "CASHING IN A HUGE STACK OF CHIPS" },
  { id: uuid(), category: "Event", value: "HAPPY HOUR" },
  { id: uuid(), category: "Event", value: "ACT OF HEROISM" },
  { id: uuid(), category: "Event", value: "DINNER WITH FRIENDS" },
  { id: uuid(), category: "Event", value: "CATCHING THE PERFECT WAVE" },
  { id: uuid(), category: "Event", value: "COLUMBUS DISCOVERS THE NEW WORLD" },
  { id: uuid(), category: "Event", value: "COSTUME PARTY" },
  { id: uuid(), category: "Event", value: "WRESTLING MATCH" },
  { id: uuid(), category: "Event", value: "A FULL MOON" },
  { id: uuid(), category: "Event", value: "OSCAR NIGHT" },
  { id: uuid(), category: "Event", value: "A FIRM GRIP" },
  { id: uuid(), category: "Event", value: "TRADITIONAL HAWAIIAN LUAU" },
  { id: uuid(), category: "Event", value: "A PERFECT THREE-POINT LANDING" },
  { id: uuid(), category: "Event", value: "GRAND ENTRANCE" },
  { id: uuid(), category: "Event", value: "TICKER-TAPE PARADE" },
  { id: uuid(), category: "Event", value: "A VISIT FROM LADY LUCK" },
  { id: uuid(), category: "Event", value: "SCIENCE EXPERIMENT" },
  { id: uuid(), category: "Event", value: "SIDEWALK SALE" },
  { id: uuid(), category: "Event", value: "HELICOPTER" },
  { id: uuid(), category: "Event", value: "COCKTAIL PARTY" },
  { id: uuid(), category: "Event", value: "PULLING A RABBIT OUT OF A HAT" },
  {
    id: uuid(),
    category: "Event",
    value: "WATCHING THE NEW YEAR'S EVE BALL DROP",
  },
  { id: uuid(), category: "Event", value: "WINNING A PLAYOFF GAME" },
  { id: uuid(), category: "Event", value: "MY FIRST TIME PARASAILING" },
  { id: uuid(), category: "Event", value: "NIGHTFALL" },
  { id: uuid(), category: "Event", value: "FINISHING A MARATHON" },
  { id: uuid(), category: "Event", value: "BIKE TOUR" },
  { id: uuid(), category: "Event", value: "PEP RALLY" },
  { id: uuid(), category: "Event", value: "SURPRISE MARRIAGE PROPOSAL" },
  { id: uuid(), category: "Event", value: "WINNING THE LOTTERY" },
  { id: uuid(), category: "Event", value: "SPECIAL OCCASION" },
  { id: uuid(), category: "Event", value: "A SOOTHING EXPERIENCE AT THE SPA" },
  { id: uuid(), category: "Event", value: "RISING TIDE" },
  { id: uuid(), category: "Event", value: "CELEBRITY AUCTION" },
  { id: uuid(), category: "Event", value: "SEEING A GAME AT WRIGLEY FIELD" },
  { id: uuid(), category: "Event", value: "SPRING CLEANING" },
  { id: uuid(), category: "Event", value: "BREAKING NEWS" },
  { id: uuid(), category: "Event", value: "THE RUNNING OF THE BULLS" },
  { id: uuid(), category: "Event", value: "APRIL FOOL'S DAY" },
  { id: uuid(), category: "Event", value: "THROWING OUT THE FIRST PITCH" },
  { id: uuid(), category: "Event", value: "GETTING A HOLE IN ONE" },
  { id: uuid(), category: "Event", value: "GIRLS' NIGHT OUT" },
  { id: uuid(), category: "Event", value: "SEEING A MIRAGE" },
  { id: uuid(), category: "Event", value: "EPIC VOYAGE" },
  { id: uuid(), category: "Event", value: "A MOONLIGHT NIGHT" },
  { id: uuid(), category: "Event", value: "SEEING A SHOW IN THE BIG APPLE" },
  { id: uuid(), category: "Event", value: "WEEKEND ROAD TRIP" },
  { id: uuid(), category: "Event", value: "SPRING BREAK" },
  { id: uuid(), category: "Event", value: "CANDLELIGHT DINNER" },
  { id: uuid(), category: "Event", value: "CATCHING A SOUVENIR FOUL BALL" },
  {
    id: uuid(),
    category: "Event",
    value: "RIDING THE FERRY TO ALCATRAZ ISLAND",
  },
  { id: uuid(), category: "Event", value: "CLASS REUNION" },
  { id: uuid(), category: "Event", value: "PUBLICITY STUNT" },
  { id: uuid(), category: "Event", value: "SUNDAY BRUNCH" },
  { id: uuid(), category: "Event", value: "FIREWORKS DISPLAY" },
  { id: uuid(), category: "Event", value: "BATTLE OF THE BANDS" },
  { id: uuid(), category: "Event", value: "JOB FAIR" },
  { id: uuid(), category: "Event", value: "LONG WEEKEND" },
  { id: uuid(), category: "Event", value: "VETERAN'S DAY PARADE" },
  { id: uuid(), category: "Event", value: "GARAGE SALE" },
  { id: uuid(), category: "Event", value: "BRIEF VISIT" },
  { id: uuid(), category: "Event", value: "CELEBRITY SIGHTING" },
  { id: uuid(), category: "Event", value: "ONLINE AUCTION" },
  { id: uuid(), category: "Event", value: "SETTING A NEW WORLD RECORD" },
  { id: uuid(), category: "Event", value: "VICTORY PARADE" },
  { id: uuid(), category: "Event", value: "LUNAR ECLIPSE" },
  { id: uuid(), category: "Event", value: "FAMILY GATHERING" },
  { id: uuid(), category: "Event", value: "THE BOSTON MARATHON" },
  { id: uuid(), category: "Event", value: "DINING AT A GOURMET RESTAURANT" },
  { id: uuid(), category: "Event", value: "LONG JOURNEY" },
  { id: uuid(), category: "Event", value: "MAKING A HOLE IN ONE" },
  {
    id: uuid(),
    category: "Event",
    value: "FINDING MONEY IN THE CLOTHES DRYER",
  },
  { id: uuid(), category: "Event", value: "OPENING PRESENTS" },
  { id: uuid(), category: "Event", value: "SURPRISE ENDING" },
  {
    id: uuid(),
    category: "Event",
    value: "RINGING IN THE NEW YEAR IN TIMES SQUARE",
  },
  { id: uuid(), category: "Event", value: "THE BIGGEST GAME OF THE SEASON" },
  { id: uuid(), category: "Event", value: "GRAND OPENING" },
  { id: uuid(), category: "Event", value: "BLACK-TIE AFFAIR" },
  { id: uuid(), category: "Event", value: "PSYCHIC READING" },
  { id: uuid(), category: "Event", value: "DINNER FOR TWO" },
  { id: uuid(), category: "Event", value: "PIZZA PARTY" },
  { id: uuid(), category: "Event", value: "ANNIVERSARY DINNER" },
  { id: uuid(), category: "Event", value: "BRIDAL SHOWER" },
  { id: uuid(), category: "Event", value: "ANNUAL SALES CONVENTION" },
  { id: uuid(), category: "Event", value: "SYMPHONY ORCHESTRA CONCERT" },
  { id: uuid(), category: "Event", value: "DINNER BY CANDLELIGHT" },
  { id: uuid(), category: "Event", value: "IN-DEPTH INTERVIEW" },
  { id: uuid(), category: "Event", value: "PARACHUTE JUMP" },
  { id: uuid(), category: "Event", value: "PASSING INSPECTION" },
  { id: uuid(), category: "Event", value: "BASIC TRAINING" },
  { id: uuid(), category: "Event", value: "CELEBRATING A SPECIAL OCCASION" },
  { id: uuid(), category: "Event", value: "ESCAPING TO AN ISLAND HIDEAWAY" },
  { id: uuid(), category: "Event", value: "SIGNING A CONTRACT" },
  { id: uuid(), category: "Event", value: "THE GRAND TOUR" },
  { id: uuid(), category: "Event", value: "PRESS CONFERENCE" },
  { id: uuid(), category: "Event", value: "YEAR OF THE DRAGON" },
  { id: uuid(), category: "Event", value: "CASUAL FRIDAY" },
  { id: uuid(), category: "Event", value: "CROSSING THE FINISH LINE" },
  { id: uuid(), category: "Event", value: "FINDING A FOUR-LEAF CLOVER" },
  { id: uuid(), category: "Event", value: "THE SUN SETTING OVER THE PACIFIC" },
  { id: uuid(), category: "Event", value: "LANDMARK DECISION" },
  { id: uuid(), category: "Event", value: "ALL-STAR GAME" },
  { id: uuid(), category: "Event", value: "PAMPERING YOURSELF WITH A MASSAGE" },
  { id: uuid(), category: "Event", value: "STANDING UP ON A SURFBOARD" },
  {
    id: uuid(),
    category: "Event",
    value: "TRADITIONAL LUAU WITH TIKI TORCHES",
  },
  { id: uuid(), category: "Event", value: "TRACK & FIELD MEET" },
  { id: uuid(), category: "Event", value: "SADIE HAWKINS DANCE" },
  { id: uuid(), category: "Event", value: "THE BEST SPRING BREAK OF ALL TIME" },
  { id: uuid(), category: "Event", value: "A VISIT TO THE STATE CAPITAL" },
  { id: uuid(), category: "Event", value: "AN AFTERNOON NAP IN MY HAMMOCK" },
  { id: uuid(), category: "Event", value: "FISHING TRIP" },
  {
    id: uuid(),
    category: "Event",
    value: "SITTING DOWN TO DINNER WITH THE WHOLE FAMILY",
  },
  { id: uuid(), category: "Event", value: "MAIDEN VOYAGE" },
  { id: uuid(), category: "Event", value: "MAGNIFICENT CARRIBEAN SUNSET" },
  { id: uuid(), category: "Event", value: "THE CUTTING OF THE WEDDING CAKE" },
  { id: uuid(), category: "Event", value: "MARRIAGE PROPOSAL" },
  { id: uuid(), category: "Event", value: "BEST MAN'S SPEECH" },
  { id: uuid(), category: "Event", value: "THROWING THE BOQUET" },
  { id: uuid(), category: "Event", value: "A REFRESHING DIP IN THE OCEAN" },
  { id: uuid(), category: "Event", value: "SIGHTSEEING EXPEDITION" },
  { id: uuid(), category: "Event", value: "TREASURE HUNT" },
  { id: uuid(), category: "Event", value: "WAREHOUSE SALE" },
  {
    id: uuid(),
    category: "Event",
    value: "BLOWING OUT THE CANDLES ON A BIRTHDAY CAKE",
  },
  { id: uuid(), category: "Event", value: "GYMNASTICS MEET" },
  { id: uuid(), category: "Event", value: "DINING AT A SEASIDE RESTAURANT" },
  { id: uuid(), category: "Event", value: "ROLLING OUT THE RED CARPET" },
  { id: uuid(), category: "Event", value: "DINING AT THE CAPTAIN'S TABLE" },
  { id: uuid(), category: "Event", value: "ARTS FESTIVAL" },
  { id: uuid(), category: "Event", value: "FOOD FIGHT IN THE CAFETERIA" },
  { id: uuid(), category: "Event", value: "FLY-FISHING" },
  { id: uuid(), category: "Event", value: "VISITING AN ACTIVE VOLCANO" },
  { id: uuid(), category: "Event", value: "WINNING A COSTUME CONTEST" },
  { id: uuid(), category: "Event", value: "TURNING INTO A WEREWOLF" },
  { id: uuid(), category: "Event", value: "HITTING THE JACKPOT" },
  { id: uuid(), category: "Event", value: "SURPRISE VISIT" },
  { id: uuid(), category: "Event", value: "AWARDS BANQUET" },
  { id: uuid(), category: "Event", value: "TAILGATE PARTY" },
  { id: uuid(), category: "Event", value: "SECOND HONEYMOON" },
  { id: uuid(), category: "Event", value: "GUIDED TOUR" },
  { id: uuid(), category: "Event", value: "BREAKING THE WISHBONE" },
  { id: uuid(), category: "Event", value: "CARVING THE TURKEY" },
  { id: uuid(), category: "Event", value: "ENJOYING BREAKFAST IN BED" },
  { id: uuid(), category: "Event", value: "HULA DANCING COMPETITION" },
  { id: uuid(), category: "Event", value: "WEEKEND GETAWAY" },
  { id: uuid(), category: "Event", value: "FOLK FESTIVAL" },
  { id: uuid(), category: "Event", value: "POWER OUTAGE" },
  { id: uuid(), category: "Event", value: "WASHINGTON CROSSING THE DELAWARE" },
  { id: uuid(), category: "Event", value: "THE WRIGHT BROTHERS' FIRST FLIGHT" },
  { id: uuid(), category: "Event", value: "WINNING AN ELECTION" },
  { id: uuid(), category: "Event", value: "NEW YEAR'S EVE PARTY" },
  { id: uuid(), category: "Event", value: "TOTAL ECLIPSE OF THE SUN" },
  { id: uuid(), category: "Event", value: "THE ADVENTURE OF A LIFETIME" },
  { id: uuid(), category: "Event", value: "VICTORY DANCE" },
  { id: uuid(), category: "Event", value: "FAMILY REUNION" },
  {
    id: uuid(),
    category: "Event",
    value: "CATCHING A SNOWFLAKE ON THE TIP OF YOUR TONGUE",
  },
  { id: uuid(), category: "Event", value: "THE GOLD RUSH" },
  { id: uuid(), category: "Event", value: "MY FIRST HAWAIIAN LUAU" },
  { id: uuid(), category: "Event", value: "ESCAPING TO A TROPICAL PARADISE" },
  { id: uuid(), category: "Event", value: "CLEARANCE SALE" },
  { id: uuid(), category: "Event", value: "HOCKEY GAME" },
  { id: uuid(), category: "Event", value: "AUCTION" },
  { id: uuid(), category: "Event", value: "DINNER WITH FRIENDS" },
  { id: uuid(), category: "Event", value: "CATCH A POP FLY" },
  { id: uuid(), category: "Event", value: "FASHION WEEK" },
  { id: uuid(), category: "Event", value: "WINNING STREAK" },
  { id: uuid(), category: "Event", value: "HALF MARATHON" },
  { id: uuid(), category: "Event", value: "WRESTLING MATCH" },
  { id: uuid(), category: "Event", value: "PITCHING A NO-HITTER" },
  { id: uuid(), category: "Event", value: "DINNER AT A TRADITIONAL LUAU" },
  { id: uuid(), category: "Event", value: "LAVA FLOWING FROM A VOLCANO" },
  { id: uuid(), category: "Event", value: "FLYING IN A HELICOPTER" },
]
export default puzzleList
