import { v4 as uuid } from "uuid"
import { Puzzle } from "../../types/Puzzle"
const puzzleList: Puzzle[] = [
  {
    id: uuid(),
    category: "Food & Drink",
    value: "TOMATO SOUP & A GRILLED CHEESE SANDWICH",
  },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "HONEY MUSTARD SALAD DRESSING",
  },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "THINLY SLICED BLACK FOREST HAM",
  },
  { id: uuid(), category: "Food & Drink", value: "TOASTED SANDWICHES" },
  { id: uuid(), category: "Food & Drink", value: "LOCALLY CAUGHT TUNA STEAKS" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "CRISPY ROASTED DUCK WITH ORANGE SAUCE",
  },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "IRISH COFFEE WITH WHIPPED CREAM",
  },
  { id: uuid(), category: "Food & Drink", value: "APPLE MARTINI" },
  { id: uuid(), category: "Food & Drink", value: "TAPIOCA PUDDING" },
  { id: uuid(), category: "Food & Drink", value: "COLD MACARONI SALAD" },
  { id: uuid(), category: "Food & Drink", value: "PORK FRIED RICE" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "ASSORTMENT OF SPANISH OLIVES",
  },
  { id: uuid(), category: "Food & Drink", value: "JUICY PINEAPPLE CHUNKS" },
  { id: uuid(), category: "Food & Drink", value: "BUFFALO BURGER" },
  { id: uuid(), category: "Food & Drink", value: "PULLED PORK STEAK" },
  { id: uuid(), category: "Food & Drink", value: "HEARTY BEEF STEW" },
  { id: uuid(), category: "Food & Drink", value: "HOT WINGS" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "GREEK SALAD WITH CRUMBLED FETA CHEESE",
  },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "CHOCOLATE CHOCOLATE CHIP COOKIES",
  },
  { id: uuid(), category: "Food & Drink", value: "BEAN AND CHEESE BURRITO" },
  { id: uuid(), category: "Food & Drink", value: "SOUTHERN PECAN PIE" },
  { id: uuid(), category: "Food & Drink", value: "CHICKEN CAESAR SALAD WRAP" },
  { id: uuid(), category: "Food & Drink", value: "JALAPENO PEPPERS" },
  { id: uuid(), category: "Food & Drink", value: "PINK LEMONADE" },
  { id: uuid(), category: "Food & Drink", value: "BLACKBERRY COBBLER" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "THIN RICE NOODLES WITH SHRIMP",
  },
  { id: uuid(), category: "Food & Drink", value: "ROSEMARY & TARRAGON" },
  { id: uuid(), category: "Food & Drink", value: "SHARED APPETIZERS" },
  { id: uuid(), category: "Food & Drink", value: "GARLIC TOAST" },
  { id: uuid(), category: "Food & Drink", value: "PURE MOUNTAIN SPRING WATER" },
  { id: uuid(), category: "Food & Drink", value: "BEEFSTEAK TOMATOES" },
  { id: uuid(), category: "Food & Drink", value: "BROWN GRAVY" },
  { id: uuid(), category: "Food & Drink", value: "FRESHLY PREPARED" },
  { id: uuid(), category: "Food & Drink", value: "JAMAICAN JERK CHICKEN" },
  { id: uuid(), category: "Food & Drink", value: "SMOKED GOUDA" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "FRENCH ONION SOUP TOPPED WITH MELTED CHEESE",
  },
  { id: uuid(), category: "Food & Drink", value: "SWEDISH MEATBALLS" },
  { id: uuid(), category: "Food & Drink", value: "HUNGARIAN GOULASH" },
  { id: uuid(), category: "Food & Drink", value: "JUNIOR MINTS" },
  { id: uuid(), category: "Food & Drink", value: "DILL PICKLES" },
  { id: uuid(), category: "Food & Drink", value: "CHOCOLATE MOUSSE" },
  { id: uuid(), category: "Food & Drink", value: "HOT CINNAMON BUNS" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "TURKEY AVOCADO AND BACON CLUB SANDWICH",
  },
  { id: uuid(), category: "Food & Drink", value: "CORNED BEEF AND CABBAGE" },
  { id: uuid(), category: "Food & Drink", value: "CREAM OF WHEAT" },
  { id: uuid(), category: "Food & Drink", value: "PIGS IN A BLANKET" },
  { id: uuid(), category: "Food & Drink", value: "CHABLIS" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "MILK CHOCOLATE AND DARK CHOCOLATE",
  },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "BROILED DOUBLE PORTERHOUSE STEAK",
  },
  { id: uuid(), category: "Food & Drink", value: "FUDGE CAKE" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "GARLIC MUSHROOM CHICKEN ALFREDO",
  },
  { id: uuid(), category: "Food & Drink", value: "BLUEBERRY MUFFIN" },
  { id: uuid(), category: "Food & Drink", value: "FRUIT SALAD" },
  { id: uuid(), category: "Food & Drink", value: "SPARERIBS & EGG ROLLS" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "SAUSAGE EGG AND CHEESE BREAKFAST SANDWICH",
  },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "SLOW-BAKED SALMON FILLETS WITH HERBED OLIVE OIL",
  },
  { id: uuid(), category: "Food & Drink", value: "SUGAR SNAP PEAS" },
  { id: uuid(), category: "Food & Drink", value: "FROZEN YOGURT" },
  { id: uuid(), category: "Food & Drink", value: "BARBECUED BAKED BEANS" },
  { id: uuid(), category: "Food & Drink", value: "EGGS FLORENTINE" },
  { id: uuid(), category: "Food & Drink", value: "CRISPY BACON" },
  { id: uuid(), category: "Food & Drink", value: "SEASONED CURLY FRIES" },
  { id: uuid(), category: "Food & Drink", value: "FRESH-BAKED COOKIES" },
  { id: uuid(), category: "Food & Drink", value: "GRAPE JUICE" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "SAUTEED SHRIMP SERVED OVER CHEESE GRITS",
  },
  { id: uuid(), category: "Food & Drink", value: "BOILED PEANUTS" },
  { id: uuid(), category: "Food & Drink", value: "BUTTERY ENGLISH TOFFEE" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "EXTRA CRISPY FRIED CHICKEN WITH MASHED POTATOES",
  },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "WARM DUTCH APPLE PIE A LA MODE",
  },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "FRIED GREEN TOMATOES WITH RANCH DRESSING",
  },
  { id: uuid(), category: "Food & Drink", value: "CHICKEN AND DUMPLINGS" },
  { id: uuid(), category: "Food & Drink", value: "PAPRIKA" },
  { id: uuid(), category: "Food & Drink", value: "CREAMY BANANA PUDDING" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "CHOCOLATE PEANUT BUTTER CHEESECAKE",
  },
  { id: uuid(), category: "Food & Drink", value: "FRENCH VANILLA ICE CREAM" },
  { id: uuid(), category: "Food & Drink", value: "FRUITY FROZEN COCKTAILS" },
  { id: uuid(), category: "Food & Drink", value: "SPANISH RICE" },
  { id: uuid(), category: "Food & Drink", value: "HOMEMADE BIRTHDAY CAKE" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "ALMONDS HAZELNUTS AND CASHEWS",
  },
  { id: uuid(), category: "Food & Drink", value: "CHAMPAGNE COCKTAIL" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "A SLICE OF COCONUT LAYER CAKE",
  },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "SWEET & SPICY POLISH SAUSAGE",
  },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "CHOCOLATE MACADAMIA CLUSTERS",
  },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "STEAMED MUSSELS WITH TARRAGON CREAM SAUCE",
  },
  { id: uuid(), category: "Food & Drink", value: "TOLL HOUSE COOKIES" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "ASIAN CHICKEN SALAD WITH GINGER-SOY DRESSING",
  },
  { id: uuid(), category: "Food & Drink", value: "PEPPERED BEEF JERKY" },
  { id: uuid(), category: "Food & Drink", value: "DRIED FIGS" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "SEAFOOD PASTA DRIZZLED WITH TRUFFLE OIL",
  },
  { id: uuid(), category: "Food & Drink", value: "TWO EGGS ANY STYLE" },
  { id: uuid(), category: "Food & Drink", value: "CRINKLE-CUT FRENCH FRIES" },
  { id: uuid(), category: "Food & Drink", value: "SALTWATER TAFFY" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "COLD BOTTLE OF BEER WITH A WEDGE OF LIME",
  },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "A GLASS OF FRESH PINEAPPLE JUICE",
  },
  { id: uuid(), category: "Food & Drink", value: "UNSALTED BUTTER" },
  { id: uuid(), category: "Food & Drink", value: "CORNISH GAME HEN" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "LINGUINE WITH RED CLAM SAUCE",
  },
  { id: uuid(), category: "Food & Drink", value: "TATER TOTS" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "OREO COOKIES DUNKED IN COLD MILK",
  },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "CLASSIC FRIED SEAFOOD PLATTER",
  },
  { id: uuid(), category: "Food & Drink", value: "BROCCOLI CHEDDAR SOUP" },
  { id: uuid(), category: "Food & Drink", value: "BIRTHDAY CUPCAKES" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "MOZZERELLA TOMATO AND BASIL SALAD",
  },
  { id: uuid(), category: "Food & Drink", value: "HEALTHY SNACKS" },
  { id: uuid(), category: "Food & Drink", value: "GRILLED SHRIMP & SCALLOPS" },
  { id: uuid(), category: "Food & Drink", value: "REFRESHING PINEAPPLE" },
  { id: uuid(), category: "Food & Drink", value: "CHILI POWDER" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "POTATO SKINS WITH CHEESE BACON",
  },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "SPICY CHICKEN STRIPS WITH DIPPING SAUCE",
  },
  { id: uuid(), category: "Food & Drink", value: "HOMEMADE SPINACH LASAGNA" },
  { id: uuid(), category: "Food & Drink", value: "HONEY-BAKED HAM" },
  { id: uuid(), category: "Food & Drink", value: "STRAWBERRY PRESERVES" },
  { id: uuid(), category: "Food & Drink", value: "NAVY BEAN SOUP" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "FIRST CUP OF COFFEE IN THE MORNING",
  },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "CHEESE ENCHILADA WITH SOUR CREAM",
  },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "WEDDING CAKE WITH BUTTERCREAM FROSTING",
  },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "PEANUT BUTTER ON CELERY STICKS",
  },
  { id: uuid(), category: "Food & Drink", value: "FUDGE CHOCOLATE BROWNIE" },
  { id: uuid(), category: "Food & Drink", value: "PEPPERMINT STICK ICE CREAM" },
  { id: uuid(), category: "Food & Drink", value: "GERMAN POTATO SALAD" },
  { id: uuid(), category: "Food & Drink", value: "MILD MEDIUM & HOT SALSA" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "THICK STRAWBERRY MILK SHAKE",
  },
  { id: uuid(), category: "Food & Drink", value: "FLANK STEAK" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "STEAMING CUP OF CAPPUCCCINO",
  },
  { id: uuid(), category: "Food & Drink", value: "FLORIDA ORANGE JUICE" },
  { id: uuid(), category: "Food & Drink", value: "BANANA SPLIT" },
  { id: uuid(), category: "Food & Drink", value: "CANDY INSIDE A PINATA" },
  { id: uuid(), category: "Food & Drink", value: "RAMEN NOODLES" },
  { id: uuid(), category: "Food & Drink", value: "WHITE GRAVY" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "EGG AND CHEESE BREAKFAST BURRITO",
  },
  { id: uuid(), category: "Food & Drink", value: "ORANGES AND TANGERINES" },
  { id: uuid(), category: "Food & Drink", value: "RED VELVET CAKE" },
  { id: uuid(), category: "Food & Drink", value: "WISCONSIN CHEDDAR" },
  { id: uuid(), category: "Food & Drink", value: "ZUCCHINI BREAD" },
  { id: uuid(), category: "Food & Drink", value: "PORTERHOUSE STEAK FOR TWO" },
  { id: uuid(), category: "Food & Drink", value: "CHEESE AND CRACKERS" },
  { id: uuid(), category: "Food & Drink", value: "CORNED BEEF SANDWICH" },
  { id: uuid(), category: "Food & Drink", value: "A SLICE OF CHEESECAKE" },
  { id: uuid(), category: "Food & Drink", value: "JUICY BURGER" },
  { id: uuid(), category: "Food & Drink", value: "FRESH-BAKED BAGELS" },
  { id: uuid(), category: "Food & Drink", value: "MANHATTAN CLAM CHOWDER" },
  { id: uuid(), category: "Food & Drink", value: "CREAM OF TOMATO SOUP" },
  { id: uuid(), category: "Food & Drink", value: "HOT PEPPER SAUCE" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "HONEY BARBECUE CHICKEN WINGS",
  },
  { id: uuid(), category: "Food & Drink", value: "SOUTHERN COLLARD GREENS" },
  { id: uuid(), category: "Food & Drink", value: "MARGARITA ON THE ROCKS" },
  { id: uuid(), category: "Food & Drink", value: "PISTACHIOS" },
  { id: uuid(), category: "Food & Drink", value: "CARAMEL APPLE" },
  { id: uuid(), category: "Food & Drink", value: "FRESH-BAKED FRENCH BREAD" },
  { id: uuid(), category: "Food & Drink", value: "CANDIED PEARS" },
  { id: uuid(), category: "Food & Drink", value: "GERMAN CHOCOLATE CAKE" },
  { id: uuid(), category: "Food & Drink", value: "BUTTERNUT SQUASH SOUP" },
  { id: uuid(), category: "Food & Drink", value: "THINLY SLICED SWISS CHEESE" },
  { id: uuid(), category: "Food & Drink", value: "WHITE CHOCOLATE MOUSSE" },
  { id: uuid(), category: "Food & Drink", value: "ALASKAN KING SALMON FILLET" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "SKIPPY AND SMUCKER'S ON WHOLE WHEAT BREAD",
  },
  { id: uuid(), category: "Food & Drink", value: "KETCHUP" },
  { id: uuid(), category: "Food & Drink", value: "SLICE OF COCONUT CREAM PIE" },
  { id: uuid(), category: "Food & Drink", value: "PREMIUM ROAST COFFEE" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "HALF-RACK OF BABY BACK RIBS",
  },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "HOMEMADE PASTA WITH TOMATO SAUCE",
  },
  { id: uuid(), category: "Food & Drink", value: "BRICK OVEN PIZZA" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "SOUR CREAM AND ONION POTATO CHIPS",
  },
  { id: uuid(), category: "Food & Drink", value: "TACO COMBO PLATE" },
  { id: uuid(), category: "Food & Drink", value: "CRISPY CHICKEN" },
  { id: uuid(), category: "Food & Drink", value: "ICING" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "CARROT CAKE WITH CREAM CHEESE FROSTING",
  },
  { id: uuid(), category: "Food & Drink", value: "VEGGIE DIP" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "CHINESE STIR-FIRED BEEF AND BROCCOLI",
  },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "LARGE PIZZA WITH EVERYTHING ON IT",
  },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "GREEN BEANS WITH SLIVERED ALMONDS",
  },
  { id: uuid(), category: "Food & Drink", value: "SILVER DOLLAR PANCAKES" },
  { id: uuid(), category: "Food & Drink", value: "MINI SPRING ROLLS" },
  { id: uuid(), category: "Food & Drink", value: "DEEP-DISH PEACH PIE" },
  { id: uuid(), category: "Food & Drink", value: "HOMEMADE SALAD DRESSING" },
  { id: uuid(), category: "Food & Drink", value: "SALES SUPERVISOR" },
  { id: uuid(), category: "Food & Drink", value: "BANANA BREAD" },
  { id: uuid(), category: "Food & Drink", value: "GARLIC FRIES" },
  { id: uuid(), category: "Food & Drink", value: "SPICY TORTILLA SOUP" },
  { id: uuid(), category: "Food & Drink", value: "CONTINENTAL CRUISE" },
  { id: uuid(), category: "Food & Drink", value: "ANIMAL CRACKERS" },
  { id: uuid(), category: "Food & Drink", value: "MOZZARELLA STICKS" },
  { id: uuid(), category: "Food & Drink", value: "IRISH BREAKFAST TEA" },
  { id: uuid(), category: "Food & Drink", value: "SCALLOPED POTATOES" },
  { id: uuid(), category: "Food & Drink", value: "CHEESE DANISH" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "RED AND GREEN CHILI PEPPERS",
  },
  { id: uuid(), category: "Food & Drink", value: "BRATWURST AND SAUERKRAUT" },
  { id: uuid(), category: "Food & Drink", value: "BLACK LICORICE" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "ROAST BEEF SANDWICH WITH HORSERADISH SAUCE",
  },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "GRILLED CENTER-CUT NEW YORK STRIP STEAK",
  },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "VIENNA SAUSAGES ON TOOTHPICKS",
  },
  { id: uuid(), category: "Food & Drink", value: "STEAMED SHRIMP DUMPLINGS" },
  { id: uuid(), category: "Food & Drink", value: "INSTANT OATMEAL" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "SCALLOPS SAUTEED IN WHITE WINE",
  },
  { id: uuid(), category: "Food & Drink", value: "ICE CREAM CAKE" },
  { id: uuid(), category: "Food & Drink", value: "FROZEN PINA COLADA" },
  { id: uuid(), category: "Food & Drink", value: "ICE-COLD LEMONADE" },
  { id: uuid(), category: "Food & Drink", value: "NACHOS SUPREME" },
  { id: uuid(), category: "Food & Drink", value: "PASTA PRIMAVERA" },
  { id: uuid(), category: "Food & Drink", value: "SOURDOUGH ROLL" },
  { id: uuid(), category: "Food & Drink", value: "SUBMARINE SANDWICH" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "COFFEE AND CREAM WITH TWO SUGARS",
  },
  { id: uuid(), category: "Food & Drink", value: "MASHED POTATOES AND GRAVY" },
  { id: uuid(), category: "Food & Drink", value: "FRESH CREAMED SPINACH" },
  { id: uuid(), category: "Food & Drink", value: "PEPPER JACK CHEESE" },
  { id: uuid(), category: "Food & Drink", value: "THE BEST PIZZA IN TOWN" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "GENEROUS HELPING OF LASAGNA",
  },
  { id: uuid(), category: "Food & Drink", value: "HOT DOG WITH EVERYTHING" },
  { id: uuid(), category: "Food & Drink", value: "ICED CAPPUCCINO" },
  { id: uuid(), category: "Food & Drink", value: "HOT PASTRAMI SANDWICH" },
  { id: uuid(), category: "Food & Drink", value: "TRADITIONAL FISH AND CHIPS" },
  { id: uuid(), category: "Food & Drink", value: "INSTANT PUDDING" },
  { id: uuid(), category: "Food & Drink", value: "DECADENT DESSERTS" },
  { id: uuid(), category: "Food & Drink", value: "SHREDDED COCONUT" },
  { id: uuid(), category: "Food & Drink", value: "LEFTOVERS" },
  { id: uuid(), category: "Food & Drink", value: "A GLASS OF SANGRIA" },
  { id: uuid(), category: "Food & Drink", value: "HOT COCOA MIX" },
  { id: uuid(), category: "Food & Drink", value: "FRESH FRUIT SALAD" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "CRANBERRY MUFFIN WITH ORANGE GLAZE",
  },
  { id: uuid(), category: "Food & Drink", value: "IMPORTED SWISS CHEESE" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "FRESH GUACAMOLE MADE FROM SCRATCH",
  },
  { id: uuid(), category: "Food & Drink", value: "BAKED MACARONI AND CHEESE" },
  { id: uuid(), category: "Food & Drink", value: "HOT FUDGE SUNDAE" },
  { id: uuid(), category: "Food & Drink", value: "WILD MUSHROOM RAVIOLI" },
  { id: uuid(), category: "Food & Drink", value: "DELI MUSTARD" },
  { id: uuid(), category: "Food & Drink", value: "LUMBERJACK BREAKFAST" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "FRENCH TOAST WITH BANANA & MACADAMIA NUTS",
  },
  { id: uuid(), category: "Food & Drink", value: "KLONDIKE BAR" },
  { id: uuid(), category: "Food & Drink", value: "APPLE FRITTER" },
  { id: uuid(), category: "Food & Drink", value: "DELICIOUS DARK RUM" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "PUMPKIN PIE WITH WHIPPED TOPPING",
  },
  { id: uuid(), category: "Food & Drink", value: "CHOCOLATE SYRUP" },
  { id: uuid(), category: "Food & Drink", value: "LOCALLY CAUGHT FRESH FISH" },
  { id: uuid(), category: "Food & Drink", value: "CANDY CORN" },
  { id: uuid(), category: "Food & Drink", value: "LEMONS AND LIMES" },
  { id: uuid(), category: "Food & Drink", value: "HAND-ROLLED SUSHI" },
  { id: uuid(), category: "Food & Drink", value: "TROPICAL FRUIT SMOOTHIE" },
  { id: uuid(), category: "Food & Drink", value: "FROZEN PINA COLADAS" },
  { id: uuid(), category: "Food & Drink", value: "PAN-SEARED CRAB CAKES" },
  { id: uuid(), category: "Food & Drink", value: "KONA COFFEE" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "FLAPJACKS HOME FRIES & CANADIAN BACON",
  },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "BUTTERCREAM FROSTED CUPCAKES",
  },
  { id: uuid(), category: "Food & Drink", value: "PEPPERMINT TEA" },
  { id: uuid(), category: "Food & Drink", value: "WALDROF SALAD" },
  { id: uuid(), category: "Food & Drink", value: "PIZZA BY THE SLICE" },
  { id: uuid(), category: "Food & Drink", value: "BREAKFAST CEREAL" },
  { id: uuid(), category: "Food & Drink", value: "CHERRY TOMATOES" },
  { id: uuid(), category: "Food & Drink", value: "SPINACH SALAD" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "HANDMADE TORTILLAS & SPICY SALSA",
  },
  { id: uuid(), category: "Food & Drink", value: "EXTRA VIRGIN OLIVE OIL" },
  { id: uuid(), category: "Food & Drink", value: "CHILLED EGGNOG" },
  { id: uuid(), category: "Food & Drink", value: "GUMDROPS & LOLLIPOPS" },
  { id: uuid(), category: "Food & Drink", value: "PINK CHAMPAGNE" },
  { id: uuid(), category: "Food & Drink", value: "PICKLES & SAUERKRAUT" },
  { id: uuid(), category: "Food & Drink", value: "CHEWY LICORICE" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "BLACKENED CATFISH WITH GUMBO",
  },
  { id: uuid(), category: "Food & Drink", value: "FISH TACOS" },
  { id: uuid(), category: "Food & Drink", value: "FRESH PINEAPPLE JUICE" },
  { id: uuid(), category: "Food & Drink", value: "GRILLED GERMAN BRATWURST" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "AN EXTRA SCOOP OF ICE CREAM",
  },
  { id: uuid(), category: "Food & Drink", value: "MINERAL WATER" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "GRILLED ALBACORE TUNA WITH LEMON",
  },
  { id: uuid(), category: "Food & Drink", value: "HERBAL TEA" },
  { id: uuid(), category: "Food & Drink", value: "SLICE OF CANTALOUPE" },
  { id: uuid(), category: "Food & Drink", value: "ROASTED CHESTNUTS" },
  { id: uuid(), category: "Food & Drink", value: "BANANA COCONUT PUDDING" },
  { id: uuid(), category: "Food & Drink", value: "HONEYDEW MELON" },
  { id: uuid(), category: "Food & Drink", value: "CREAM OF BROCCOLI SOUP" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "OPEN-FACED ROAST BEEF SANDWICH",
  },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "STEAK SALAD AND FRESH-CUT FRIES",
  },
  { id: uuid(), category: "Food & Drink", value: "SEEDLESS GRAPES" },
  { id: uuid(), category: "Food & Drink", value: "CHOCOLATE CHUNK BROWNIES" },
  { id: uuid(), category: "Food & Drink", value: "VERMONT MAPLE SYRUP" },
  { id: uuid(), category: "Food & Drink", value: "CORN ON THE COB" },
  { id: uuid(), category: "Food & Drink", value: "PEANUT BRITTLE" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "CRISPY NACHO CHIPS AND CREAMY GUACAMOLE",
  },
  { id: uuid(), category: "Food & Drink", value: "GRANOLA BAR" },
  { id: uuid(), category: "Food & Drink", value: "MUFFIN TOPS" },
  { id: uuid(), category: "Food & Drink", value: "PINEAPPLE FOOD CAKE" },
  { id: uuid(), category: "Food & Drink", value: "GOOEY TAFFY" },
  { id: uuid(), category: "Food & Drink", value: "MICROWAVE POPCORN" },
  { id: uuid(), category: "Food & Drink", value: "MEATBALL SUB" },
  { id: uuid(), category: "Food & Drink", value: "GOLDFISH CRACKERS" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "BLACK BEAN AND CHEESE BURRITO",
  },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "SLICED PORTOBELLO MUSHROOMS",
  },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "BONELESS CENTER-CUT PORK CHOPS",
  },
  { id: uuid(), category: "Food & Drink", value: "BISCUITS AND GRAVY" },
  { id: uuid(), category: "Food & Drink", value: "CRANBERRY WALNUT SCONE" },
  { id: uuid(), category: "Food & Drink", value: "SUPERB FIVE-STAR CUISINE" },
  { id: uuid(), category: "Food & Drink", value: "CREAM AND SUGAR" },
  { id: uuid(), category: "Food & Drink", value: "JUMBO SHRIMP" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "SPICY SMOKED POLISH SAUSAGE",
  },
  { id: uuid(), category: "Food & Drink", value: "BEEF BARLEY SOUP" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "MANDARIN DUCK WITH VEGETABLE SPRING ROLLS",
  },
  { id: uuid(), category: "Food & Drink", value: "FORTUNE COOKIES" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "CAJUN CHICKEN OVER WILD RICE",
  },
  { id: uuid(), category: "Food & Drink", value: "CRUSHED RED PEPPER" },
  { id: uuid(), category: "Food & Drink", value: "CONTINENTAL BREAKFAST" },
  { id: uuid(), category: "Food & Drink", value: "SUN-DRIED TOMATOES" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "YOUR CHOICE OF WHITE WHEAT OR RYE TOAST",
  },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "COCONUT CHEESECAKE WITH MACAROON CRUST",
  },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "BLUEBERRY PANCAKES WITH MAPLE SYRUP",
  },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "TOASTED BAGELS WITH LOX AND CREAM CHEESE",
  },
  { id: uuid(), category: "Food & Drink", value: "PUMPKIN PIE" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "HOMEMADE GUACAMOLE & TORTILLA CHIPS",
  },
  { id: uuid(), category: "Food & Drink", value: "ROTISSERIE CHICKEN" },
  { id: uuid(), category: "Food & Drink", value: "SOFT PRETZEL" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "CHEDDAR CHEESE OMELET & CANADIAN BACON",
  },
  { id: uuid(), category: "Food & Drink", value: "PEACH COBBLER" },
  { id: uuid(), category: "Food & Drink", value: "SCRUMPTOUS CUPCAKES" },
  { id: uuid(), category: "Food & Drink", value: "SIZZLING STEAK FAJITAS" },
  { id: uuid(), category: "Food & Drink", value: "SPICY BUFFALO WINGS" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "RED APPLES DIPPED IN CARAMEL",
  },
  { id: uuid(), category: "Food & Drink", value: "OYSTERS ON THE HALF SHELL" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "COLORFUL COCKTAILS WITH TINY UMBRELLAS",
  },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "GLAZED HAM WITH MOLASSES BISCUITS",
  },
  { id: uuid(), category: "Food & Drink", value: "TURKEY DRUMSTICKS" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "CHEESE ENCHILADA TOPPED WITH GREEN SAUCE",
  },
  { id: uuid(), category: "Food & Drink", value: "VEGGIE BURGER" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "COLORFUL COCKTAILS WITH TINY UMBRELLAS",
  },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "GLAZED HAM WITH MOLASSES BISCUITS",
  },
  { id: uuid(), category: "Food & Drink", value: "TURKEY DRUMSTICKS" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "CHEESE ENCHILADA TOPPED WITH GREEN SAUCE",
  },
  { id: uuid(), category: "Food & Drink", value: "VEGGIE BURGER" },
  { id: uuid(), category: "Food & Drink", value: "CANDY CANES" },
  { id: uuid(), category: "Food & Drink", value: "HOMEMADE EGGNOG" },
  { id: uuid(), category: "Food & Drink", value: "HOT CHOCOLATE" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "BUTTERMILK PANCAKES WITH FRESH COCONUT",
  },
  { id: uuid(), category: "Food & Drink", value: "BROWN SUGAR" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "CLAM CHOWDER WITH PIPING HOT ROLLS",
  },
  { id: uuid(), category: "Food & Drink", value: "SWEDISH MEATBALLS" },
  { id: uuid(), category: "Food & Drink", value: "APPLE STRUDEL" },
  { id: uuid(), category: "Food & Drink", value: "WONTON SOUP" },
  { id: uuid(), category: "Food & Drink", value: "BEEF CURRY" },
  { id: uuid(), category: "Food & Drink", value: "ORANGE POPPY SEED MUFFINS" },
  { id: uuid(), category: "Food & Drink", value: "CHERRY COLA" },
  { id: uuid(), category: "Food & Drink", value: "ROASTED BUTTERNUT SQUASH" },
  { id: uuid(), category: "Food & Drink", value: "SPICED APPLE CIDER" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "GRILLED PORK WITH SLICED PINEAPPLE",
  },
  { id: uuid(), category: "Food & Drink", value: "CANTALOUPE & HONEYDEW" },
  { id: uuid(), category: "Food & Drink", value: "TOMATO JUICE" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "CHOCOLATE CHIP COOKIE DOUGH",
  },
  { id: uuid(), category: "Food & Drink", value: "TABASCO SAUCE" },
  { id: uuid(), category: "Food & Drink", value: "MIDNIGHT SNACK" },
  { id: uuid(), category: "Food & Drink", value: "GRAHAM CRACKERS" },
  { id: uuid(), category: "Food & Drink", value: "FETTUCCINE ALFREDO" },
  { id: uuid(), category: "Food & Drink", value: "GERMAN POTATO SALAD" },
  { id: uuid(), category: "Food & Drink", value: "HUNGARIAN GOULASH" },
  { id: uuid(), category: "Food & Drink", value: "SWISS CHEESE" },
  { id: uuid(), category: "Food & Drink", value: "LONDON BROIL" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "GRILLED SNAPPER WITH MACADAMIA NUT CRUST",
  },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "MILD MEDIUM OR EXTRA HOT SALSA",
  },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "WARM APPLE PIE SPRINKLED WITH NUTMEG",
  },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "SEARED SCALLOPS WITH SNOW PEAS",
  },
  { id: uuid(), category: "Food & Drink", value: "LOCALLY GROWN VEGTABLES" },
  { id: uuid(), category: "Food & Drink", value: "FROZEN YOGURT" },
  { id: uuid(), category: "Food & Drink", value: "FLORIDA ORANGES" },
  { id: uuid(), category: "Food & Drink", value: "EGGS OVER EASY" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "BEF BURRITO SMOTHERED IN CHEESE",
  },
  { id: uuid(), category: "Food & Drink", value: "CRISPY COCONUT SHRIMP" },
  { id: uuid(), category: "Food & Drink", value: "DEEP-DISH PIZZA" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "CHUNKY GUACAMOLE MADE TABLESIDE",
  },
  { id: uuid(), category: "Food & Drink", value: "CORN DOG ON A STICK" },
  { id: uuid(), category: "Food & Drink", value: "SHAVED ICE" },
  { id: uuid(), category: "Food & Drink", value: "SHREDDED WHEAT" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "BRAISED PORK CHOPS WITH WILD MILD MUSHROOMS",
  },
  { id: uuid(), category: "Food & Drink", value: "PINK LEMONADE" },
  { id: uuid(), category: "Food & Drink", value: "TAPIOCA PUDDING" },
  { id: uuid(), category: "Food & Drink", value: "WEDGE OF LIME" },
  { id: uuid(), category: "Food & Drink", value: "GIANT LOLLIPOP" },
  { id: uuid(), category: "Food & Drink", value: "JUICY BEEF" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "CHOCOLATE MACADAMIA NUT COOKIES",
  },
  { id: uuid(), category: "Food & Drink", value: "LINGUINE WITH CLAM SAUCE" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "PITCHER OF FROZEN MARGARITAS",
  },
  { id: uuid(), category: "Food & Drink", value: "FRESH FRUIT PLATE" },
  { id: uuid(), category: "Food & Drink", value: "A CUP OF GREEN TEA" },
  { id: uuid(), category: "Food & Drink", value: "RED VELVET CUPCAKES" },
  { id: uuid(), category: "Food & Drink", value: "BELGIAN CHOCOLATE" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "NACHOS SUPREME WITH GRILLED CHICKEN",
  },
  { id: uuid(), category: "Food & Drink", value: "SLICE OF DEVIL'S FOOD CAKE" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "SOFT TACOS FROM A SEASIDE GRILL",
  },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "MARGARITAS MADE FROM SCRATCH",
  },
  { id: uuid(), category: "Food & Drink", value: "WINE & CHEESE" },
  { id: uuid(), category: "Food & Drink", value: "STEAK FAJITA PLATTER" },
  { id: uuid(), category: "Food & Drink", value: "TOASTED ENGLISH MUFFIN" },
  { id: uuid(), category: "Food & Drink", value: "CHAMPAGNE & CAVIAR" },
  { id: uuid(), category: "Food & Drink", value: "HOT BUTTERMILK BISCUITS" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "CHICKEN ENCHILADA WITH CHILI SAUCE",
  },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "A SECOND HELPING OF TURKEY AND STUFFING",
  },
  { id: uuid(), category: "Food & Drink", value: "CRANBERRY SAUCE" },
  { id: uuid(), category: "Food & Drink", value: "SLICE OF COCONUT CREAM PIE" },
  { id: uuid(), category: "Food & Drink", value: "CHARBROILED STEAK TACOS" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "FRENCH TOAST SMOTHERED IN MAPLE SYRUP",
  },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "HOMEMADE TORTILLAS FRESH FROM THE KITCHEN",
  },
  { id: uuid(), category: "Food & Drink", value: "GINGERBREAD COOKIES" },
  { id: uuid(), category: "Food & Drink", value: "CINNAMON STICKY BUNS" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "HOT OATMEAL SPRINKLED WITH BROWN SUGAR",
  },
  { id: uuid(), category: "Food & Drink", value: "CANDIED YAMS" },
  { id: uuid(), category: "Food & Drink", value: "CHERRY COBBLER" },
  { id: uuid(), category: "Food & Drink", value: "STRAWBERRY JAM" },
  { id: uuid(), category: "Food & Drink", value: "CRISPY CHIPS AND GUACAMOLE" },
  { id: uuid(), category: "Food & Drink", value: "HEALTHY SNACKS" },
  { id: uuid(), category: "Food & Drink", value: "KIDNEY BEANS" },
  { id: uuid(), category: "Food & Drink", value: "SAUTEED SHRIMP" },
  { id: uuid(), category: "Food & Drink", value: "THE MAIN COURSE" },
  { id: uuid(), category: "Food & Drink", value: "GRAHAM CRACKER PIE CRUST" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "BRAISED BEEF WITH CARAMELIZED ONIONS",
  },
  { id: uuid(), category: "Food & Drink", value: "CANDY HEARTS" },
  { id: uuid(), category: "Food & Drink", value: "PECAN PIE" },
  { id: uuid(), category: "Food & Drink", value: "STRAWBERRY SMOOTHIE" },
  { id: uuid(), category: "Food & Drink", value: "BUFFALO BURGER" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "STRAWBERRY MARGARITA ON THE ROCKS",
  },
  { id: uuid(), category: "Food & Drink", value: "ICE CREAM SANDWICH" },
  { id: uuid(), category: "Food & Drink", value: "ROASTED ALMONDS" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "MILD HOT AND EXTRA HOT SALSA",
  },
  { id: uuid(), category: "Food & Drink", value: "BOWL OF FRUIT" },
  { id: uuid(), category: "Food & Drink", value: "SEASONED CURLY FRIES" },
  { id: uuid(), category: "Food & Drink", value: "PINEAPPLE UPSIDE-DOWN CAKE" },
  { id: uuid(), category: "Food & Drink", value: "SLICED HONEYDEW" },
  { id: uuid(), category: "Food & Drink", value: "GARLIC BREAD" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "THE FRESHEST PINEAPPLE JUICE",
  },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "A DELICIOUS CUP OF HOT COCOA",
  },
  { id: uuid(), category: "Food & Drink", value: "A BUNCH OF GRAPES" },
  { id: uuid(), category: "Food & Drink", value: "BOTTLED MINERAL WATER" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "STEAK BEAN AND CHEESE BURRITO",
  },
  { id: uuid(), category: "Food & Drink", value: "BANANAS FOSTER" },
  { id: uuid(), category: "Food & Drink", value: "SHRIMP JAMBALAYA" },
  { id: uuid(), category: "Food & Drink", value: "FRIED CRAWFISH" },
  { id: uuid(), category: "Food & Drink", value: "SEAFOOD GUMBO" },
  { id: uuid(), category: "Food & Drink", value: "OYSTERS ROCKEFELLER" },
  { id: uuid(), category: "Food & Drink", value: "BREAD PUDDING" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "RED AND GREEN CHILI PEPPERS",
  },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "SUNDAE WITH A CHERRY ON TOP",
  },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "OPEN-FACED CORNED BEEF SANDWICH",
  },
  { id: uuid(), category: "Food & Drink", value: "SUMMER SQUASH" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "SPICY JAMAICAN JERK CHICKEN",
  },
  { id: uuid(), category: "Food & Drink", value: "ICE-COLD LEMONADE" },
  { id: uuid(), category: "Food & Drink", value: "SPRINKLES ON MY CUPCAKES" },
  { id: uuid(), category: "Food & Drink", value: "RED DELICIOUS APPLES" },
  { id: uuid(), category: "Food & Drink", value: "SPARKLING MINERAL WATER" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "GRILLED SCALLOPS WITH ANGEL HAIR PASTA",
  },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "BELGIAN WAFFLES TOPPED WITH WHIPPED CREAM",
  },
  { id: uuid(), category: "Food & Drink", value: "CHOCOLATES ON MY PILLOW" },
  { id: uuid(), category: "Food & Drink", value: "TASTY JAMAICAN RUM PUNCH" },
  { id: uuid(), category: "Food & Drink", value: "MOIST BROWNIES" },
  { id: uuid(), category: "Food & Drink", value: "LEMON MERINGUE PIE" },
  { id: uuid(), category: "Food & Drink", value: "HAWAIIAN COCONUT PUDDING" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "OATMEAL WITH BLUBERRIES AND WALNUTS",
  },
  { id: uuid(), category: "Food & Drink", value: "ORANGE GUMDROPS" },
  { id: uuid(), category: "Food & Drink", value: "CANDY CORN" },
  { id: uuid(), category: "Food & Drink", value: "FRESH-CUT PINEAPPLE CHUNKS" },
  { id: uuid(), category: "Food & Drink", value: "MORNING CUP OF COFFEE" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "TOASTED BAGELS WITH CREAM CHEESE",
  },
  { id: uuid(), category: "Food & Drink", value: "PIZZA BY THE SLICE" },
  { id: uuid(), category: "Food & Drink", value: "SWISS CHOCOLATE" },
  { id: uuid(), category: "Food & Drink", value: "FRESH TROPICAL FRUIT SALAD" },
  { id: uuid(), category: "Food & Drink", value: "APPLE CIDER" },
  { id: uuid(), category: "Food & Drink", value: "FROZEN PINAPPLE SMOOTHIE" },
  { id: uuid(), category: "Food & Drink", value: "GEORGIA PEACH" },
  { id: uuid(), category: "Food & Drink", value: "SLICE OF CANTALOUPE" },
  { id: uuid(), category: "Food & Drink", value: "CHOICE CUTS OF BEEF" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "FRESHLY SQUEEZED ORANGE JUICE",
  },
  { id: uuid(), category: "Food & Drink", value: "BABY PEAS" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "A LARGE BUCKET OF BUTTERED POPCORN",
  },
  { id: uuid(), category: "Food & Drink", value: "CHILI CHEESE FRIES" },
  { id: uuid(), category: "Food & Drink", value: "HOMEMADE APPLE PIE" },
  { id: uuid(), category: "Food & Drink", value: "SALTWATER TAFFY" },
  { id: uuid(), category: "Food & Drink", value: "A KETTLE OF SEAFOOD GUMBO" },
  { id: uuid(), category: "Food & Drink", value: "COFFEE WITH CREAM & SUGAR" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "FRESH-BAKED BLUEBERRY MUFFIN",
  },
  { id: uuid(), category: "Food & Drink", value: "FRENCH ONION SOUP" },
  { id: uuid(), category: "Food & Drink", value: "VIENNA SAUSAGES" },
  { id: uuid(), category: "Food & Drink", value: "CHERRY TOMATOES" },
  { id: uuid(), category: "Food & Drink", value: "CAESAR SALAD" },
  { id: uuid(), category: "Food & Drink", value: "LOBSTER BISQUE" },
  { id: uuid(), category: "Food & Drink", value: "AUTHENTIC CAJUN CUISINE" },
  { id: uuid(), category: "Food & Drink", value: "HERBAL GREEN TEA" },
  { id: uuid(), category: "Food & Drink", value: "FRESH COCONUT MILK" },
  { id: uuid(), category: "Food & Drink", value: "SLICED PINEAPPLE" },
  { id: uuid(), category: "Food & Drink", value: "BAKED ALASKA" },
  { id: uuid(), category: "Food & Drink", value: "RED VELVET CAKE" },
  { id: uuid(), category: "Food & Drink", value: "GRILLED SWORDFISH" },
  { id: uuid(), category: "Food & Drink", value: "MOIST WARM BANANA BREAD" },
  { id: uuid(), category: "Food & Drink", value: "STUFFED GRAPE LEAVES" },
  { id: uuid(), category: "Food & Drink", value: "HONEYDEW MELON" },
  { id: uuid(), category: "Food & Drink", value: "LEMON POPPY SEED SCONE" },
  { id: uuid(), category: "Food & Drink", value: "ROASTED CHESNUTS" },
  { id: uuid(), category: "Food & Drink", value: "LEMONS AND LIMES" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "CHICKEN TENDERS WITH CREAMY HONEY MUSTARD",
  },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "HAMBURGER WITH EVERYTHING ON IT",
  },
  { id: uuid(), category: "Food & Drink", value: "SHRIMP SCAMPI" },
  { id: uuid(), category: "Food & Drink", value: "CORN ON THE COB" },
  { id: uuid(), category: "Food & Drink", value: "SLOW-COOKED PULLED PORK" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "DELICIOUS DEEP-DISH APPLE PIE",
  },
  { id: uuid(), category: "Food & Drink", value: "CREAM OF WHEAT" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "PAN-FRIED BONELESS PORK CHOPS",
  },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "A MIDNIGHT SNACK OF MICROWAVE POPCORN",
  },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "PEANUTS RAISINS AND CHOCOLATE CHIPS",
  },
  { id: uuid(), category: "Food & Drink", value: "GOOEY CINNAMON STICKY BUNS" },
  { id: uuid(), category: "Food & Drink", value: "SILVER DOLLAR PANCAKES" },
  { id: uuid(), category: "Food & Drink", value: "CREAM OF TOMATO SOUP" },
  { id: uuid(), category: "Food & Drink", value: "PEANUT BRITTLE" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "FROZEN STRAWBERRY MARGARITAS",
  },
  { id: uuid(), category: "Food & Drink", value: "BOSTON CREAM PIE" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "GRILLED HAM & CHEESE SANDWICH",
  },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "PAN-SEARED SALMON WITH DILL SAUCE",
  },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "CARAMEL MACADAMIA NUT CLUSTERS",
  },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "COCONUT SHRIMP WITH SWEET AND SOUR SAUCE",
  },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "FRUIT SALAD TOPPED WITH SHREDDED COCONUT",
  },
  { id: uuid(), category: "Food & Drink", value: "CRISPY CURLY FRIES" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "BAKED POTATO WITH SOUR CREAM & CHIVES",
  },
  { id: uuid(), category: "Food & Drink", value: "GREEN LEAFY SALAD" },
  { id: uuid(), category: "Food & Drink", value: "HOME-COOKED MEAL" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "BANANA-NUT OAT BRAN MUFFINS",
  },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "WARM APPLE FRITTERS WITH POWDERED SUGAR",
  },
  { id: uuid(), category: "Food & Drink", value: "SCALLOPED POTATOES" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "HAMBURGER PATTY WITH GRILLED PINEAPPLE",
  },
  { id: uuid(), category: "Food & Drink", value: "BAGS OF CANDY" },
  { id: uuid(), category: "Food & Drink", value: "DEVILED EGGS" },
  { id: uuid(), category: "Food & Drink", value: "ONE DOZEN GLAZED DOUGHNUTS" },
  { id: uuid(), category: "Food & Drink", value: "PORTERHOUSE STEAK" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "EXTRA-LARGE PIZZA WITH EVERYTHING ON IT",
  },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "OPEN-FACED ROAST BEEF SANDWICH",
  },
  { id: uuid(), category: "Food & Drink", value: "MASHED POTATOES AND GRAVY" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "PUMPKIN PIE WITH WHIPPED CREAM",
  },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "GREEN BEANS WITH SAUTED MUSHROOMS",
  },
  { id: uuid(), category: "Food & Drink", value: "ORANGES AND TANGERINES" },
  { id: uuid(), category: "Food & Drink", value: "TABASCO SAUCE" },
  { id: uuid(), category: "Food & Drink", value: "HOT APPLE CIDER" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "SWEET ROASTED BUTTERNUT SQUASH",
  },
  { id: uuid(), category: "Food & Drink", value: "HOMEMADE CHOCOLATE CAKE" },
  { id: uuid(), category: "Food & Drink", value: "NUTRITIOUS SNACK" },
  { id: uuid(), category: "Food & Drink", value: "FOOTLONG HOT DOG" },
  { id: uuid(), category: "Food & Drink", value: "TOMATO JUICE" },
  { id: uuid(), category: "Food & Drink", value: "PEPPERMINT STICKS" },
  { id: uuid(), category: "Food & Drink", value: "BUTTERED POPCORN" },
  { id: uuid(), category: "Food & Drink", value: "GOOEY BROWNIES" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "RICE PUDDING SPRINKLED WITH NUTMEG",
  },
  { id: uuid(), category: "Food & Drink", value: "VANILLA FROSTING" },
  { id: uuid(), category: "Food & Drink", value: "LEMON PINEAPPLE ICE CREAM" },
  { id: uuid(), category: "Food & Drink", value: "STRAWBERRY PRESERVES" },
  { id: uuid(), category: "Food & Drink", value: "BATCH OF FROSTED COOKIES" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "FULL RACK OF BABY BACK RIBS",
  },
  { id: uuid(), category: "Food & Drink", value: "FLORIDA ORANGES" },
  { id: uuid(), category: "Food & Drink", value: "PIZZA AND PARTY" },
  { id: uuid(), category: "Food & Drink", value: "SOFT PRETZEL" },
  { id: uuid(), category: "Food & Drink", value: "BREAKFAST CEREAL" },
  { id: uuid(), category: "Food & Drink", value: "TASTY COCONUT CHICKEN" },
  { id: uuid(), category: "Food & Drink", value: "DRY-ROASTED PEANUTS" },
  { id: uuid(), category: "Food & Drink", value: "SPAGHETTI AND MEATBALLS" },
  { id: uuid(), category: "Food & Drink", value: "BELGIAN WAFFLES" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "ROOT BEER FLOAT WITH TWO STRAWS",
  },
  { id: uuid(), category: "Food & Drink", value: "WEDDING CAKE" },
  { id: uuid(), category: "Food & Drink", value: "WHOLE WHEAT BREAD" },
  { id: uuid(), category: "Food & Drink", value: "COCONUT SHRIMP SKEWERS" },
  { id: uuid(), category: "Food & Drink", value: "BROCCOLI AND CAULIFLOWER" },
  { id: uuid(), category: "Food & Drink", value: "PINK COTTON CANDY" },
  { id: uuid(), category: "Food & Drink", value: "DEEP-DISH CHERRY PIE" },
  { id: uuid(), category: "Food & Drink", value: "GRAHAM CRACKERS" },
  { id: uuid(), category: "Food & Drink", value: "BELGIAN CHOCOLATE CAKE" },
  { id: uuid(), category: "Food & Drink", value: "PENNY CANDY" },
  { id: uuid(), category: "Food & Drink", value: "A CUP OF GREEN TEA" },
  { id: uuid(), category: "Food & Drink", value: "FETTUCCINE ALFREDO" },
  { id: uuid(), category: "Food & Drink", value: "WINE AND CHEESE" },
  { id: uuid(), category: "Food & Drink", value: "VEGGIE PIZZA" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "BONELESS SKINLESS CHICKEN TENDERS",
  },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "REFRESHING PINEAPPLE SMOOTHIE",
  },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "STRONG COFFEE AND SWEET TEA",
  },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "SUGAR COOKIES FRESH FROM THE OVEN",
  },
  { id: uuid(), category: "Food & Drink", value: "GUMDROPS & LOLLIPOPS" },
  { id: uuid(), category: "Food & Drink", value: "ANIMAL CRACKERS" },
  { id: uuid(), category: "Food & Drink", value: "ROASTED MACADAMIA NUTS" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "WARM CORN OR FLOUR TORTILLAS",
  },
  { id: uuid(), category: "Food & Drink", value: "MANHATTAN CLAM CHOWDER" },
  { id: uuid(), category: "Food & Drink", value: "SPICY BUFFALO WINGS" },
  { id: uuid(), category: "Food & Drink", value: "YELLOW MUSTARD" },
  { id: uuid(), category: "Food & Drink", value: "BAGELS AND CREAM CHEESE" },
  { id: uuid(), category: "Food & Drink", value: "HOT CHOCOLATE" },
  { id: uuid(), category: "Food & Drink", value: "FRESH FRUIT PLATE" },
  { id: uuid(), category: "Food & Drink", value: "PASTRAMI SANDWICH" },
  { id: uuid(), category: "Food & Drink", value: "A SLICE OF PIZZA" },
  { id: uuid(), category: "Food & Drink", value: "WALDORF SALAD" },
  { id: uuid(), category: "Food & Drink", value: "CORNED BEEF ON RYE" },
  { id: uuid(), category: "Food & Drink", value: "BLACK AND WHITE COOKIES" },
  { id: uuid(), category: "Food & Drink", value: "VERMONT MAPLE SYRUP" },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "FRENCH FRIES TOPPED WITH MELTED CHEESE",
  },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "BACON LETTUCE AND TOMATO SANDWICH",
  },
  {
    id: uuid(),
    category: "Food & Drink",
    value: "GUACAMOLE MADE FROM SCRATCH",
  },
]
export default puzzleList
