import { v4 as uuid } from "uuid"
import { Puzzle } from "../../types/Puzzle"
const puzzleList: Puzzle[] = [
  { id: uuid(), category: "Landmark", value: "TOMB OF THE UNKNOWN SOLDIER" },
  { id: uuid(), category: "Landmark", value: "MOUNT EVEREST" },
  { id: uuid(), category: "Landmark", value: "THE LINCOLN MEMORIAL" },
  { id: uuid(), category: "Landmark", value: "HANGING GARDENS OF BABYLON" },
  {
    id: uuid(),
    category: "Landmark",
    value: "SAN FRANCISO'S FISHERMAN'S WHARF",
  },
  {
    id: uuid(),
    category: "Landmark",
    value: "KENNEDY CENTER IN WASHINGTON D C",
  },
  { id: uuid(), category: "Landmark", value: "WORLD TRADE CENTER" },
  { id: uuid(), category: "Landmark", value: "THE ALAMO" },
  {
    id: uuid(),
    category: "Landmark",
    value: "THOMAS JEFFERSON\u2019S MONTICELLO",
  },
  { id: uuid(), category: "Landmark", value: "JOHN HANCOCK CENTER IN CHICAGO" },
  {
    id: uuid(),
    category: "Landmark",
    value: "CATHEDRAL OF NOTRE DAME IN PARIS",
  },
  { id: uuid(), category: "Landmark", value: "THOMAS JEFFERSON MEMORIAL" },
  { id: uuid(), category: "Landmark", value: "THE EIFFEL TOWER" },
  { id: uuid(), category: "Landmark", value: "TOWER OF LONDON" },
  {
    id: uuid(),
    category: "Landmark",
    value: "THE GOLDEN GATE BRIDGE IN CALIFORNIA",
  },
  { id: uuid(), category: "Landmark", value: "YOSEMITE FALLS" },
  { id: uuid(), category: "Landmark", value: "THE GREAT WALL OF CHINA" },
  { id: uuid(), category: "Landmark", value: "THE HIMALAYA MOUNTAINS" },
  { id: uuid(), category: "Landmark", value: "ROYAL ALBERT HALL IN LONDON" },
  { id: uuid(), category: "Landmark", value: "THE PARTHENON IN ATHENS" },
  { id: uuid(), category: "Landmark", value: "MOUNT EVEREST" },
  { id: uuid(), category: "Landmark", value: "THE ACROPOLIS IN ATHENS" },
  { id: uuid(), category: "Landmark", value: "HEARST CASTLE" },
  { id: uuid(), category: "Landmark", value: "THE BRONX ZOO" },
  { id: uuid(), category: "Landmark", value: "ROCK OF GIBRALTAR" },
  { id: uuid(), category: "Landmark", value: "PETRIFIED FOREST" },
  { id: uuid(), category: "Landmark", value: "NIAGRA FALLS" },
  { id: uuid(), category: "Landmark", value: "LINCOLN MEMORIAL" },
  { id: uuid(), category: "Landmark", value: "BRITAIN'S HOUSE OF COMMONS" },
  { id: uuid(), category: "Landmark", value: "THE TAJ MAHAL IN INDIA" },
  {
    id: uuid(),
    category: "Landmark",
    value: "ROCK AND ROLL HALL OF FAME MUSEUM",
  },
  { id: uuid(), category: "Landmark", value: "THE KREMLIN IN MOSCOW" },
  { id: uuid(), category: "Landmark", value: "GRACELAND IN MEMPHIS" },
  { id: uuid(), category: "Landmark", value: "THE WHITE HOUSE" },
  { id: uuid(), category: "Landmark", value: "THE GATEWAY ARCH IN ST. LOUIS" },
  {
    id: uuid(),
    category: "Landmark",
    value: "THE KENNEDY CENTER IN WASHINGTON D.C.",
  },
  { id: uuid(), category: "Landmark", value: "THE JEFFERSON MEMORIAL" },
  { id: uuid(), category: "Landmark", value: "NEW YORK'S TIMES SQUARE" },
  { id: uuid(), category: "Landmark", value: "CHURCHILL DOWNS IN KENTUCKY" },
  { id: uuid(), category: "Landmark", value: "GREAT WALL OF CHINA" },
  { id: uuid(), category: "Landmark", value: "GOLDEN GATE PARK" },
  {
    id: uuid(),
    category: "Landmark",
    value: "OLD FAITHFUL GEYSER IN YELLOWSTONE PARK",
  },
  { id: uuid(), category: "Landmark", value: "SAN JUAN CAPISTRANO" },
  { id: uuid(), category: "Landmark", value: "FOUR CORNERS MONUMENT" },
  { id: uuid(), category: "Landmark", value: "MOUNT MCKINLEY" },
  { id: uuid(), category: "Landmark", value: "VALLEY FORGE" },
  { id: uuid(), category: "Landmark", value: "FENWAY PARK" },
  { id: uuid(), category: "Landmark", value: "JOSHUA TREE NATIONAL PARK" },
  { id: uuid(), category: "Landmark", value: "MALL OF AMERICA" },
  { id: uuid(), category: "Landmark", value: "AFRICA'S VICTORIA FALLS" },
  { id: uuid(), category: "Landmark", value: "THE GREAT PYRAMID" },
  { id: uuid(), category: "Landmark", value: "KENNEDY SPACE CENTER" },
  { id: uuid(), category: "Landmark", value: "HEARST CASTLE" },
  { id: uuid(), category: "Landmark", value: "NEW YORK STOCK EXCHANGE" },
  { id: uuid(), category: "Landmark", value: "THE HOLLYWOOD SIGN" },
  { id: uuid(), category: "Landmark", value: "HOLLYWOOD WALK OF FAME" },
  { id: uuid(), category: "Landmark", value: "ROYAL PALM" },
  { id: uuid(), category: "Landmark", value: "GRANT'S TOMB" },
  { id: uuid(), category: "Landmark", value: "THE OREGON TRAIL" },
  { id: uuid(), category: "Landmark", value: "THE PARTHENON" },
  { id: uuid(), category: "Landmark", value: "BUCKINGHAM PALACE" },
  { id: uuid(), category: "Landmark", value: "PANAMA CANAL" },
  { id: uuid(), category: "Landmark", value: "THE LOUISIANA SUPERDOME" },
  { id: uuid(), category: "Landmark", value: "THE BROOKLYN BRIDGE" },
  { id: uuid(), category: "Landmark", value: "THE EIFFEL TOWER" },
  { id: uuid(), category: "Landmark", value: "EVERGLADES NATIONAL PARK" },
  { id: uuid(), category: "Landmark", value: "THE BREAKERS IN PALM BEACH" },
  { id: uuid(), category: "Landmark", value: "THE PENTAGON" },
  {
    id: uuid(),
    category: "Landmark",
    value: "VOLCANOES NATIONAL PARK IN HAWAII",
  },
  { id: uuid(), category: "Landmark", value: "CHICAGO'S WRIGLEY FIELD" },
  {
    id: uuid(),
    category: "Landmark",
    value: "ELVIS PRESLEY'S GRACELAND IN MEMPHIS",
  },
  { id: uuid(), category: "Landmark", value: "NOTRE DAME CATHEDRAL" },
  {
    id: uuid(),
    category: "Landmark",
    value: "THE WESTERN WHITE HOUSE IN CRAWFORD",
  },
  { id: uuid(), category: "Landmark", value: "THE ROMAN COLOSSEUM" },
  { id: uuid(), category: "Landmark", value: "DODGER STADIUM IN LOS ANGELES" },
  { id: uuid(), category: "Landmark", value: "ELLIS ISLAND" },
  { id: uuid(), category: "Landmark", value: "HARVARD YARD" },
  { id: uuid(), category: "Landmark", value: "THE TAJ MAHAL" },
  { id: uuid(), category: "Landmark", value: "THE LEANING TOWER OF PISA" },
  { id: uuid(), category: "Landmark", value: "THE GOLDEN GATE BRIDGE" },
  { id: uuid(), category: "Landmark", value: "THE GREAT WALL OF CHINA" },
  { id: uuid(), category: "Landmark", value: "YELLOWSTONE NATIONAL PARK" },
  { id: uuid(), category: "Landmark", value: "RADIO CITY MASIC HALL" },
  { id: uuid(), category: "Landmark", value: "CARLSBAD CAVERNS" },
  { id: uuid(), category: "Landmark", value: "THE BLARNEY STONE" },
  { id: uuid(), category: "Landmark", value: "MOUNT OLYMPUS" },
  { id: uuid(), category: "Landmark", value: "THE HOLLYWOOD BOWL" },
  { id: uuid(), category: "Landmark", value: "RED SQUARE IN MOSCOW" },
  { id: uuid(), category: "Landmark", value: "THE HOUSES OF PARLIAMENT" },
  { id: uuid(), category: "Landmark", value: "THE ROSE BOWL IN PASADENA" },
  { id: uuid(), category: "Landmark", value: "SEARS TOWER" },
  { id: uuid(), category: "Landmark", value: "CHURCHILL DOWNS" },
  { id: uuid(), category: "Landmark", value: "SYDNEY OPERA HOUSE" },
  { id: uuid(), category: "Landmark", value: "THE PANAMA CANAL" },
  { id: uuid(), category: "Landmark", value: "THE APOLLO THEATER IN HARLEM" },
  { id: uuid(), category: "Landmark", value: "THE PETRIFIED FOREST" },
  { id: uuid(), category: "Landmark", value: "NIAGRA FALLS" },
  { id: uuid(), category: "Landmark", value: "KINGS CANYON NATIONAL PARK" },
  { id: uuid(), category: "Landmark", value: "KENNEDY SPACE CENTER" },
  { id: uuid(), category: "Landmark", value: "MOUNT FUJI IN JAPAN" },
  { id: uuid(), category: "Landmark", value: "SAN DIEGO ZOO" },
  { id: uuid(), category: "Landmark", value: "THE HOLLYWOOD SIGN" },
  {
    id: uuid(),
    category: "Landmark",
    value: "GETTYSBURG NATIONAL MILITARY PARK",
  },
  { id: uuid(), category: "Landmark", value: "THE ALAMO" },
  { id: uuid(), category: "Landmark", value: "WALDEN POND" },
  { id: uuid(), category: "Landmark", value: "THE FORBIDDEN CITY" },
  {
    id: uuid(),
    category: "Landmark",
    value: "COUNTRY MUSIC HALL OF FAME AND MUSEUM",
  },
  { id: uuid(), category: "Landmark", value: "HOOVER DAM" },
  {
    id: uuid(),
    category: "Landmark",
    value: "THE NATIONAL MALL IN WASHINGTON D.C.",
  },
  {
    id: uuid(),
    category: "Landmark",
    value: "YELLOWSTONE NATIONAL PARK'S OLD FAITHFUL",
  },
  { id: uuid(), category: "Landmark", value: "DEVILS TOWER NATIONAL MONUMENT" },
  { id: uuid(), category: "Landmark", value: "THE PARTHENON IN ATHENS" },
  { id: uuid(), category: "Landmark", value: "THE WASHINGTON MONUMENT" },
  { id: uuid(), category: "Landmark", value: "THE GATEWAY ARCH IN ST. LOUIS" },
  { id: uuid(), category: "Landmark", value: "NEW YORK'S CENTRAL PARK" },
  { id: uuid(), category: "Landmark", value: "THE LIBRARY OF CONGRESS" },
  { id: uuid(), category: "Landmark", value: "BASKETBALL HALL OF FAME" },
  { id: uuid(), category: "Landmark", value: "THE GREEN MONSTER" },
  { id: uuid(), category: "Landmark", value: "STATUE OF LIBERTY" },
  { id: uuid(), category: "Landmark", value: "YOSEMITE NATIONAL PARK" },
  { id: uuid(), category: "Landmark", value: "PLYMOUTH ROCK" },
  { id: uuid(), category: "Landmark", value: "MOUNT RUSHMORE" },
  { id: uuid(), category: "Landmark", value: "BASKETBALL HALL OF FAME" },
  { id: uuid(), category: "Landmark", value: "THE GREEN MONSTER" },
  { id: uuid(), category: "Landmark", value: "STATUE OF LIBERTY" },
  { id: uuid(), category: "Landmark", value: "YOSEMITE NATIONAL PARK" },
  { id: uuid(), category: "Landmark", value: "PLYMOUTH ROCK" },
  { id: uuid(), category: "Landmark", value: "MOUNT RUSHMORE" },
  { id: uuid(), category: "Landmark", value: "ROCKEFELLER CENTER" },
  { id: uuid(), category: "Landmark", value: "CHRYSLER BUILDING" },
  { id: uuid(), category: "Landmark", value: "THE FAMOUS APOLLO THEATER" },
  { id: uuid(), category: "Landmark", value: "CAPITOL HILL" },
  { id: uuid(), category: "Landmark", value: "ALCATRAZ ISLAND" },
  { id: uuid(), category: "Landmark", value: "DODGER STADIUM" },
  { id: uuid(), category: "Landmark", value: "LINCOLN MEMORIAL" },
  { id: uuid(), category: "Landmark", value: "THE PENTAGON" },
  { id: uuid(), category: "Landmark", value: "NAVY PIER" },
  { id: uuid(), category: "Landmark", value: "SOLDIER FIELD" },
  { id: uuid(), category: "Landmark", value: "MOUNT RAIMER NATIONAL PARK" },
  { id: uuid(), category: "Landmark", value: "THE WHITE HOUSE" },
  { id: uuid(), category: "Landmark", value: "BUCKINGHAM PALACE" },
  { id: uuid(), category: "Landmark", value: "MONUMENT VALLEY" },
  { id: uuid(), category: "Landmark", value: "BRYCE CANYON" },
  { id: uuid(), category: "Landmark", value: "WINDSOR CASTLE" },
  { id: uuid(), category: "Landmark", value: "SAINT PATRICK'S CATHEDRAL" },
  { id: uuid(), category: "Landmark", value: "OLD FAITHFUL" },
  { id: uuid(), category: "Landmark", value: "THE FAMOUS GOLDEN GATE BRIDGE" },
  { id: uuid(), category: "Landmark", value: "EMPIRE STATE BUILDING" },
  { id: uuid(), category: "Landmark", value: "DEATH VALLEY NATIONAL PARK" },
  { id: uuid(), category: "Landmark", value: "JACKSON SQUARE" },
  { id: uuid(), category: "Landmark", value: "JOSHUA TREE NATIONAL PARK" },
  { id: uuid(), category: "Landmark", value: "THE GREAT PYRAMID" },
  { id: uuid(), category: "Landmark", value: "DEVIL'S TOWER" },
  { id: uuid(), category: "Landmark", value: "NEW YORK STOCK EXCHANGE" },
  { id: uuid(), category: "Landmark", value: "THE EIFFEL TOWER" },
  { id: uuid(), category: "Landmark", value: "THE SPACE NEEDLE" },
  { id: uuid(), category: "Landmark", value: "THE BROOKLYN BRIDGE" },
  { id: uuid(), category: "Landmark", value: "HAWAII VOLCANOES NATIONAL PARK" },
  { id: uuid(), category: "Landmark", value: "GOLDEN GATE PARK" },
  { id: uuid(), category: "Landmark", value: "THE PANAMA CANAL" },
  { id: uuid(), category: "Landmark", value: "KING TUT'S TOMB" },
  { id: uuid(), category: "Landmark", value: "THE GREAT WALL OF CHINA" },
  { id: uuid(), category: "Landmark", value: "MOUNT FUJI IN JAPAN" },
  { id: uuid(), category: "Landmark", value: "YANKEE STADIUM" },
  { id: uuid(), category: "Landmark", value: "THE GATEWAY ARCH" },
  { id: uuid(), category: "Landmark", value: "YELLOWSTONE NATIONAL PARK" },
  { id: uuid(), category: "Landmark", value: "LADY LIBERTY" },
  { id: uuid(), category: "Landmark", value: "ROSE BOWL STADIUM" },
  { id: uuid(), category: "Landmark", value: "LINCOLN CENTER" },
  { id: uuid(), category: "Landmark", value: "NIAGRA FALLS" },
  { id: uuid(), category: "Landmark", value: "THE FORBIDDEN CITY" },
  { id: uuid(), category: "Landmark", value: "MALL OF AMERICA" },
  { id: uuid(), category: "Landmark", value: "THE WASHINGTON MONUMENT" },
  {
    id: uuid(),
    category: "Landmark",
    value: "PRO FOOTBALL HALL OF FAME IN CANTON OHIO",
  },
  { id: uuid(), category: "Landmark", value: "HOOVER DAM" },
  { id: uuid(), category: "Landmark", value: "CHICAGO'S WRIGLEY FIELD" },
  { id: uuid(), category: "Landmark", value: "KENNEDY SPACE CENTER" },
  { id: uuid(), category: "Landmark", value: "THE HOLLYWOOD SIGN" },
  { id: uuid(), category: "Landmark", value: "THE NATIONAL MALL" },
  { id: uuid(), category: "Landmark", value: "THE LIBRARY OF CONGRESS" },
  { id: uuid(), category: "Landmark", value: "SAN DIEGO ZOO" },
  { id: uuid(), category: "Landmark", value: "THOMAS JEFFERSON MEMORIAL" },
  { id: uuid(), category: "Landmark", value: "STAPLES CENTER" },
  { id: uuid(), category: "Landmark", value: "THE TOWER OF LONDON" },
  { id: uuid(), category: "Landmark", value: "STATUE OF LIBERTY" },
  { id: uuid(), category: "Landmark", value: "ELLIS ISLAND" },
  { id: uuid(), category: "Landmark", value: "GRAND CANYON NATIONAL PARK" },
  { id: uuid(), category: "Landmark", value: "MOUNT OLYMPUS" },
]
export default puzzleList
