import { v4 as uuid } from "uuid"
import { Puzzle } from "../../types/Puzzle"
const puzzleList: Puzzle[] = [
  { id: uuid(), category: "Living Things", value: "HUSKIES" },
  { id: uuid(), category: "Living Things", value: "A LITTER OF PUPPIES" },
  { id: uuid(), category: "Living Things", value: "PEARL OYSTERS" },
  { id: uuid(), category: "Living Things", value: "TALKING PARROTS" },
  { id: uuid(), category: "Living Things", value: "LOW-FLYING PELICANS" },
  { id: uuid(), category: "Living Things", value: "ANNUALS & PERENNIALS" },
  { id: uuid(), category: "Living Things", value: "BARKING SEA LIONS" },
  { id: uuid(), category: "Living Things", value: "SCHOOL OF FISH" },
  { id: uuid(), category: "Living Things", value: "POLAR BEAR CUBS" },
  { id: uuid(), category: "Living Things", value: "CLYDESDALE HORSES" },
  { id: uuid(), category: "Living Things", value: "KANGAROOS AND KOALAS" },
  { id: uuid(), category: "Living Things", value: "WHITE DAFFODILS" },
  {
    id: uuid(),
    category: "Living Things",
    value: "HUMPBACK WHALES AND LEAPING DOLPHINS",
  },
  { id: uuid(), category: "Living Things", value: "BIRDS OF PREY" },
  { id: uuid(), category: "Living Things", value: "FOXES" },
  { id: uuid(), category: "Living Things", value: "AFRICAN ELEPHANTS" },
  { id: uuid(), category: "Living Things", value: "COTTONTAIL RABBITS" },
  { id: uuid(), category: "Living Things", value: "WATER LILIES" },
  { id: uuid(), category: "Living Things", value: "CHEETAHS & LEOPARDS" },
  { id: uuid(), category: "Living Things", value: "ORANGE BLOSSOMS" },
  { id: uuid(), category: "Living Things", value: "ELEPHANT SEALS" },
  { id: uuid(), category: "Living Things", value: "FLOCK OF CANADA GEESE" },
  { id: uuid(), category: "Living Things", value: "SPARROWS & PARAKEETS" },
  { id: uuid(), category: "Living Things", value: "SOARING EAGLES" },
  { id: uuid(), category: "Living Things", value: "SEAGULLS & PENGUINS" },
  { id: uuid(), category: "Living Things", value: "HERD OF ANTELOPE" },
  { id: uuid(), category: "Living Things", value: "PURRING KITTENS" },
  { id: uuid(), category: "Living Things", value: "ORCHIDS & VIOLETS" },
  { id: uuid(), category: "Living Things", value: "EXOTIC WILDLIFE" },
  { id: uuid(), category: "Living Things", value: "MIGRATORY BIRDS" },
  { id: uuid(), category: "Living Things", value: "STRIPED SEA BASS" },
  { id: uuid(), category: "Living Things", value: "RED GERANIUMS" },
  { id: uuid(), category: "Living Things", value: "PALMETTO TREES" },
  { id: uuid(), category: "Living Things", value: "SEA HORSES AND ANGELFISH" },
  { id: uuid(), category: "Living Things", value: "HOMING PIGEONS" },
  { id: uuid(), category: "Living Things", value: "SPANISH MOSS" },
  { id: uuid(), category: "Living Things", value: "PERFORMING DOLPHINS" },
  { id: uuid(), category: "Living Things", value: "PET TARANTULA" },
  {
    id: uuid(),
    category: "Living Things",
    value: "FLAMINGOS KOALAS & GIANT PANDAS",
  },
  {
    id: uuid(),
    category: "Living Things",
    value: "BEAUTIFUL ORCHIDS IN BLOOM",
  },
  { id: uuid(), category: "Living Things", value: "KING PENGUINS" },
  { id: uuid(), category: "Living Things", value: "SAINT BERNARD" },
  {
    id: uuid(),
    category: "Living Things",
    value: "BRIGHT YELLOW HIBISCUS FLOWERS",
  },
  { id: uuid(), category: "Living Things", value: "CENTIPEDES & MILLIPEDES" },
  { id: uuid(), category: "Living Things", value: "LONGHORN CATTLE" },
  { id: uuid(), category: "Living Things", value: "HERD OF ZEBRAS" },
  {
    id: uuid(),
    category: "Living Things",
    value: "MIGRATING HUMPBACK & GRAY WHALES",
  },
  {
    id: uuid(),
    category: "Living Things",
    value: "SEA TURTLES CROCODILE & MANATEES",
  },
  { id: uuid(), category: "Living Things", value: "THE BIRDS AND THE BEES" },
  { id: uuid(), category: "Living Things", value: "HORSESHOE CRABS" },
  { id: uuid(), category: "Living Things", value: "PINK CARNATIONS" },
  { id: uuid(), category: "Living Things", value: "A GAGGLE OF GEESE" },
  { id: uuid(), category: "Living Things", value: "A PRIDE OF LIONS" },
  { id: uuid(), category: "Living Things", value: "CARPENTER ANTS" },
  { id: uuid(), category: "Living Things", value: "TRUMPETER SWAN" },
  { id: uuid(), category: "Living Things", value: "DOUGLAS FIR" },
  { id: uuid(), category: "Living Things", value: "A FAMILY OF BLACK BEARS" },
  { id: uuid(), category: "Living Things", value: "WHALE SHARKS & MANTA RAYS" },
  { id: uuid(), category: "Living Things", value: "CALLA LILIES" },
  { id: uuid(), category: "Living Things", value: "BEGONIAS" },
  { id: uuid(), category: "Living Things", value: "RAIN FOREST WILDLIFE" },
  { id: uuid(), category: "Living Things", value: "DAIRY COWS" },
  { id: uuid(), category: "Living Things", value: "SNAPDRAGONS" },
  { id: uuid(), category: "Living Things", value: "THE GREAT APES" },
  { id: uuid(), category: "Living Things", value: "CELL PHONE PACKAGE" },
  { id: uuid(), category: "Living Things", value: "SWAYING COCONUT PALMS" },
  { id: uuid(), category: "Living Things", value: "GUIDE DOGS" },
  {
    id: uuid(),
    category: "Living Things",
    value: "BIRDS FLYING SOUTH FOR THE WINTER",
  },
  { id: uuid(), category: "Living Things", value: "WILDFLOWERS" },
  { id: uuid(), category: "Living Things", value: "POPLAR TREES" },
  { id: uuid(), category: "Living Things", value: "BIRDS OF PARADISE" },
  { id: uuid(), category: "Living Things", value: "ANIMAL ACTORS" },
  { id: uuid(), category: "Living Things", value: "GIANT SEQUOIA TREES" },
  { id: uuid(), category: "Living Things", value: "SIAMESE KITTENS" },
  { id: uuid(), category: "Living Things", value: "FLIGHTLESS BIRDS" },
  { id: uuid(), category: "Living Things", value: "HONEYBEES" },
  { id: uuid(), category: "Living Things", value: "WHITE AND YELLOW DAISIES" },
  { id: uuid(), category: "Living Things", value: "BANACLES" },
  { id: uuid(), category: "Living Things", value: "BELUGA WHALES" },
  { id: uuid(), category: "Living Things", value: "PUREBRED DOGS" },
  { id: uuid(), category: "Living Things", value: "MAJESTIC HUMPBACK WHALES" },
  { id: uuid(), category: "Living Things", value: "GIANT REDWOOD TREES" },
  { id: uuid(), category: "Living Things", value: "HERD OF BIGHORN SHEEP" },
  { id: uuid(), category: "Living Things", value: "BLUEBIRDS" },
  { id: uuid(), category: "Living Things", value: "SCHOOL OF TROPICAL FISH" },
  { id: uuid(), category: "Living Things", value: "GIANT PANDAS" },
  { id: uuid(), category: "Living Things", value: "YELLOW DAFFODILS" },
  { id: uuid(), category: "Living Things", value: "CIRCUS ELEPHANTS" },
  { id: uuid(), category: "Living Things", value: "STRIPED SEA BASS" },
  { id: uuid(), category: "Living Things", value: "TABBY CATS" },
  { id: uuid(), category: "Living Things", value: "LIONESS AND HER CUBS" },
  { id: uuid(), category: "Living Things", value: "FLOCK OF CANADA GEESE" },
  { id: uuid(), category: "Living Things", value: "MINIATURE HORSES" },
  { id: uuid(), category: "Living Things", value: "EMPEROR PENGUINS" },
  { id: uuid(), category: "Living Things", value: "ANNUALS & PERENNIALS" },
  { id: uuid(), category: "Living Things", value: "INDOOR PLANTS" },
  { id: uuid(), category: "Living Things", value: "WILD TURKEYS" },
  { id: uuid(), category: "Living Things", value: "BLACK BEARS" },
  { id: uuid(), category: "Living Things", value: "PIGEONS AND DOVES" },
  { id: uuid(), category: "Living Things", value: "MAGNOLIA BLOSSOMS" },
  { id: uuid(), category: "Living Things", value: "GIANT SEA TURTLES" },
  { id: uuid(), category: "Living Things", value: "APPALOOSA HOUSE" },
  { id: uuid(), category: "Living Things", value: "SAGEBRUSH" },
  { id: uuid(), category: "Living Things", value: "BUTTERCUPS" },
  { id: uuid(), category: "Living Things", value: "FINICKY CATS" },
  {
    id: uuid(),
    category: "Living Things",
    value: "PUPPIES WAGGING THEIR TAILS",
  },
  { id: uuid(), category: "Living Things", value: "LEOPARD CUBS" },
  { id: uuid(), category: "Living Things", value: "CHERRY BLOSSOMS" },
  { id: uuid(), category: "Living Things", value: "WHITE ORCHIDS" },
  { id: uuid(), category: "Living Things", value: "FIREFLIES IN A JAR" },
  { id: uuid(), category: "Living Things", value: "WATER LILIES" },
  { id: uuid(), category: "Living Things", value: "CHIRPING CRICKETS" },
  { id: uuid(), category: "Living Things", value: "CLYDESDALE HORSES" },
  { id: uuid(), category: "Living Things", value: "WHITE CARNATIONS" },
  { id: uuid(), category: "Living Things", value: "TULIPS & IRISES" },
  { id: uuid(), category: "Living Things", value: "BUMBLEBEES" },
  {
    id: uuid(),
    category: "Living Things",
    value: "DESERT WILDFLOWERS IN BLOOM",
  },
  { id: uuid(), category: "Living Things", value: "YELLOW LILIES" },
  { id: uuid(), category: "Living Things", value: "SOARING EAGLES" },
  { id: uuid(), category: "Living Things", value: "BIRDS OF PREY" },
  { id: uuid(), category: "Living Things", value: "PONDEROSA PINES" },
  { id: uuid(), category: "Living Things", value: "YELLOW HIBISCUS BLOSSOMS" },
  { id: uuid(), category: "Living Things", value: "A FLOCK OF CARDINALS" },
  { id: uuid(), category: "Living Things", value: "LIGHTNING BUGS" },
  { id: uuid(), category: "Living Things", value: "BLUEBIRDS & BLACKBIRDS" },
  { id: uuid(), category: "Living Things", value: "GUPPIES" },
  { id: uuid(), category: "Living Things", value: "PURRING KITTENS" },
  { id: uuid(), category: "Living Things", value: "EASTER LILIES" },
  { id: uuid(), category: "Living Things", value: "GENTLY SWAYING PALM TREES" },
  { id: uuid(), category: "Living Things", value: "PURPLE CARNATIONS" },
  { id: uuid(), category: "Living Things", value: "SQUIRRELS AND CHIPMUNKS" },
  {
    id: uuid(),
    category: "Living Things",
    value: "BRIGHTLY COLORED TROPICAL FISH",
  },
  { id: uuid(), category: "Living Things", value: "DRAGONFLIES" },
  { id: uuid(), category: "Living Things", value: "BLUE JAYS" },
  { id: uuid(), category: "Living Things", value: "HOUSEPLANTS" },
  { id: uuid(), category: "Living Things", value: "ROBIN REDBREAST" },
  { id: uuid(), category: "Living Things", value: "PERFORMING SEALS" },
  { id: uuid(), category: "Living Things", value: "HERD OF ANTELOPE" },
  { id: uuid(), category: "Living Things", value: "HANGING FERNS" },
  { id: uuid(), category: "Living Things", value: "WOLVERINES" },
  { id: uuid(), category: "Living Things", value: "SEA OTTERS" },
  { id: uuid(), category: "Living Things", value: "BEGONIAS AND PETUNIAS" },
  { id: uuid(), category: "Living Things", value: "CROCODILES" },
  { id: uuid(), category: "Living Things", value: "DALMATIANS" },
  { id: uuid(), category: "Living Things", value: "EVERGREEN TREES" },
  { id: uuid(), category: "Living Things", value: "PET GERBILS" },
  { id: uuid(), category: "Living Things", value: "HUMPBACK WHALES" },
  { id: uuid(), category: "Living Things", value: "STATE FLOWER & STATE BIRD" },
  { id: uuid(), category: "Living Things", value: "PORCUPINES" },
  { id: uuid(), category: "Living Things", value: "OSTRICH & PEACOCK" },
  { id: uuid(), category: "Living Things", value: "CHAMELEONS" },
  { id: uuid(), category: "Living Things", value: "AFRICAN VIOLETS" },
  {
    id: uuid(),
    category: "Living Things",
    value: "PUREBRED IRISH SETTER PUPPIES",
  },
  { id: uuid(), category: "Living Things", value: "PARTRIDGE & PHEASANT" },
  { id: uuid(), category: "Living Things", value: "ORANGE BLOSSOMS" },
  { id: uuid(), category: "Living Things", value: "RED POPPIES" },
  { id: uuid(), category: "Living Things", value: "BUFFALO HERD" },
  { id: uuid(), category: "Living Things", value: "TEXAS LONGHORN CATTLE" },
  { id: uuid(), category: "Living Things", value: "YELLOW JACKETS" },
  { id: uuid(), category: "Living Things", value: "MEOWING KITTENS" },
  { id: uuid(), category: "Living Things", value: "CACTUS FLOWERS" },
  { id: uuid(), category: "Living Things", value: "BLACK BEAR AND BROWN BEAR" },
  { id: uuid(), category: "Living Things", value: "FLOCK OF SNOW GEESE" },
  { id: uuid(), category: "Living Things", value: "HERD OF MOOSE" },
  { id: uuid(), category: "Living Things", value: "KANGAROOS AND KOALAS" },
  { id: uuid(), category: "Living Things", value: "ELK AND BISON" },
  { id: uuid(), category: "Living Things", value: "GRAZING SHEEP" },
  { id: uuid(), category: "Living Things", value: "WHALE SHARKS" },
  { id: uuid(), category: "Living Things", value: "SAILFISH & SWORD FISH" },
  { id: uuid(), category: "Living Things", value: "STARGAZER LILIES" },
  { id: uuid(), category: "Living Things", value: "SIBERIAN HUSKIES" },
  { id: uuid(), category: "Living Things", value: "MIGRATING HUMPBACK WHALES" },
  {
    id: uuid(),
    category: "Living Things",
    value: "SEA OTTERS SWIMMING NEAR ICEBERGS",
  },
  {
    id: uuid(),
    category: "Living Things",
    value: "A LITTER OF SIAMESE KITTENS",
  },
  { id: uuid(), category: "Living Things", value: "RARE ORCHIDS" },
  { id: uuid(), category: "Living Things", value: "PACK OF WOLVES" },
  { id: uuid(), category: "Living Things", value: "PINK TULIPS" },
  { id: uuid(), category: "Living Things", value: "ROARING LIONS" },
  { id: uuid(), category: "Living Things", value: "LAKE TROUT" },
  { id: uuid(), category: "Living Things", value: "A SCHOOL OF MINNOWS" },
  { id: uuid(), category: "Living Things", value: "ENGLISH BULLDOGS" },
  { id: uuid(), category: "Living Things", value: "WILD HORSES" },
  {
    id: uuid(),
    category: "Living Things",
    value: "BALD EAGLES GLIDING OVERHEAD",
  },
  { id: uuid(), category: "Living Things", value: "MARINE MAMMALS" },
  { id: uuid(), category: "Living Things", value: "WHITE GARDENIAS" },
  { id: uuid(), category: "Living Things", value: "MONARCH BUTTERFLIES" },
  { id: uuid(), category: "Living Things", value: "POLAR BEAR CUBS" },
  { id: uuid(), category: "Living Things", value: "PINK FLAMINGOS" },
  { id: uuid(), category: "Living Things", value: "HOWLING COYOTES" },
  { id: uuid(), category: "Living Things", value: "ALLIGATORS & CROCODILES" },
  { id: uuid(), category: "Living Things", value: "CHIRPING PARAKEETS" },
  { id: uuid(), category: "Living Things", value: "A FLOCK OF SEAGULLS" },
  { id: uuid(), category: "Living Things", value: "MOURNING DOVE" },
  { id: uuid(), category: "Living Things", value: "HERD OF CARIBOU" },
  { id: uuid(), category: "Living Things", value: "WOODLAND CREATURES" },
  { id: uuid(), category: "Living Things", value: "CALICO CATS" },
  {
    id: uuid(),
    category: "Living Things",
    value: "CHIPMUNKS GATHERING ACORNS",
  },
  { id: uuid(), category: "Living Things", value: "YELLOW DAISIES" },
  { id: uuid(), category: "Living Things", value: "BABY DUCKLINGS" },
  {
    id: uuid(),
    category: "Living Things",
    value: "BALD EAGLES PERCHED IN TREETOPS",
  },
  { id: uuid(), category: "Living Things", value: "FOUR-LEGGED FRIENDS" },
  {
    id: uuid(),
    category: "Living Things",
    value: "BALD EAGLES PERCHED IN TREETOPS",
  },
  { id: uuid(), category: "Living Things", value: "FOUR-LEGGED FRIENDS" },
  { id: uuid(), category: "Living Things", value: "RED POINSETTIAS" },
  { id: uuid(), category: "Living Things", value: "TURTLE DOVES" },
  { id: uuid(), category: "Living Things", value: "WILD ORCHIDS" },
  { id: uuid(), category: "Living Things", value: "GIANT REDWOOD TREES" },
  { id: uuid(), category: "Living Things", value: "DALMATIAN PUPPIES" },
  { id: uuid(), category: "Living Things", value: "SEA TURTLES" },
  { id: uuid(), category: "Living Things", value: "BIRDS OF PARADISE" },
  { id: uuid(), category: "Living Things", value: "WATER LILIES" },
  { id: uuid(), category: "Living Things", value: "BOBCATS AND COYOTES" },
  { id: uuid(), category: "Living Things", value: "A POD OF DOLPHINS" },
  { id: uuid(), category: "Living Things", value: "WILD STALLIONS" },
  { id: uuid(), category: "Living Things", value: "CHERRY BLOSSOMS" },
  { id: uuid(), category: "Living Things", value: "MOUNTAIN LIONS" },
  { id: uuid(), category: "Living Things", value: "HERD OF BUFFALO" },
  { id: uuid(), category: "Living Things", value: "TIGER LILIES" },
  { id: uuid(), category: "Living Things", value: "PINK DAISIES" },
  { id: uuid(), category: "Living Things", value: "HAWKS AND DOVES" },
  { id: uuid(), category: "Living Things", value: "PUREBRED PUPPIES" },
  { id: uuid(), category: "Living Things", value: "SEAGULLS & PELICANS" },
  { id: uuid(), category: "Living Things", value: "PRAIRIE DOGS" },
  { id: uuid(), category: "Living Things", value: "PURPLE IRISES" },
  { id: uuid(), category: "Living Things", value: "FLOCK OF BIRDS" },
  { id: uuid(), category: "Living Things", value: "FROGS & TOADS" },
  { id: uuid(), category: "Living Things", value: "TIGER CUBS" },
  { id: uuid(), category: "Living Things", value: "BIRDS OF PREY" },
  { id: uuid(), category: "Living Things", value: "SPARROWS & PARAKEETS" },
  { id: uuid(), category: "Living Things", value: "BLACK BEARS" },
  {
    id: uuid(),
    category: "Living Things",
    value: "GIANT REDWOODS OF YOSEMITE",
  },
  { id: uuid(), category: "Living Things", value: "THREE FRENCH HENS" },
  { id: uuid(), category: "Living Things", value: "A GAGGLE OF GEESE" },
  { id: uuid(), category: "Living Things", value: "CENTIPEDES & MILLIPEDES" },
  { id: uuid(), category: "Living Things", value: "SIAMESE KITTENS" },
  { id: uuid(), category: "Living Things", value: "AMPHIBIANS & REPTILES" },
  { id: uuid(), category: "Living Things", value: "FLOWERS IN FULL BLOOM" },
  { id: uuid(), category: "Living Things", value: "A PRIDE OF LIONS" },
  { id: uuid(), category: "Living Things", value: "LAUGHING HYENAS" },
  { id: uuid(), category: "Living Things", value: "CACTUS FLOWERS" },
  { id: uuid(), category: "Living Things", value: "LIGHTNING BUGS" },
  { id: uuid(), category: "Living Things", value: "CROCODILES AND GATORS" },
  { id: uuid(), category: "Living Things", value: "MAGNOLIA BLOSSOMS" },
  { id: uuid(), category: "Living Things", value: "CARDINALS & CANARIES" },
  { id: uuid(), category: "Living Things", value: "CHIRPING CRICKETS" },
  {
    id: uuid(),
    category: "Living Things",
    value: "ALL KINDS OF EXOTIC PLANTS AND ANIMALS",
  },
  { id: uuid(), category: "Living Things", value: "GENTLY SWAYING PALM TREES" },
  { id: uuid(), category: "Living Things", value: "YELLOW DAFFODILS" },
  { id: uuid(), category: "Living Things", value: "CLYDESDALE HORSES" },
  { id: uuid(), category: "Living Things", value: "SNAPDRAGONS" },
  { id: uuid(), category: "Living Things", value: "HARBOR SEALS" },
  { id: uuid(), category: "Living Things", value: "BLUE JAYS AND CARDINALS" },
  { id: uuid(), category: "Living Things", value: "BLOOMING WILDFLOWERS" },
  { id: uuid(), category: "Living Things", value: "HERD OF ELEPHANTS" },
  { id: uuid(), category: "Living Things", value: "FLUTTERING BUTTERFLIES" },
  { id: uuid(), category: "Living Things", value: "POTTED PLANTS" },
  { id: uuid(), category: "Living Things", value: "A LITTER OF PUPPIES" },
  { id: uuid(), category: "Living Things", value: "PONDEROSA PINES" },
  { id: uuid(), category: "Living Things", value: "PINK CARNATIONS" },
  { id: uuid(), category: "Living Things", value: "TROPICAL FISH" },
  { id: uuid(), category: "Living Things", value: "EVERGREEN TREES" },
  { id: uuid(), category: "Living Things", value: "ROARING LIONS" },
  { id: uuid(), category: "Living Things", value: "CROCODILES" },
  { id: uuid(), category: "Living Things", value: "WHITE ORCHIDS" },
  { id: uuid(), category: "Living Things", value: "PINK FLAMINGOS" },
  { id: uuid(), category: "Living Things", value: "SOARING EAGLES" },
  { id: uuid(), category: "Living Things", value: "YELLOW LILIES" },
  { id: uuid(), category: "Living Things", value: "MIGRATING BLUE WHALES" },
  { id: uuid(), category: "Living Things", value: "FLYING SQUIRRELS" },
  { id: uuid(), category: "Living Things", value: "COLORFUL NATIVE FLOWERS" },
  { id: uuid(), category: "Living Things", value: "CHIRPING SPARROWS" },
  { id: uuid(), category: "Living Things", value: "GRAZING SHEEP" },
  { id: uuid(), category: "Living Things", value: "ORANGE BLOSSOMS" },
  { id: uuid(), category: "Living Things", value: "WHITE GARDENIAS" },
  { id: uuid(), category: "Living Things", value: "TULIPS AND IRISES" },
  {
    id: uuid(),
    category: "Living Things",
    value: "CHIPMUNKS GATHERING ACORNS",
  },
  { id: uuid(), category: "Living Things", value: "HERD OF CATTLE" },
  { id: uuid(), category: "Living Things", value: "GUPPIES" },
  { id: uuid(), category: "Living Things", value: "SEVEN SWANS A-SWIMMING" },
  { id: uuid(), category: "Living Things", value: "FLOCK OF SNOW GEESE" },
  { id: uuid(), category: "Living Things", value: "DALMATIANS" },
  {
    id: uuid(),
    category: "Living Things",
    value: "TOUCANS PARROTS AND GREEN IGUANAS",
  },
  { id: uuid(), category: "Living Things", value: "TWO TURTLEDOVES" },
  { id: uuid(), category: "Living Things", value: "HIBERNATING ANIMALS" },
  { id: uuid(), category: "Living Things", value: "MAJESTIC HUMPBACK WHALES" },
  { id: uuid(), category: "Living Things", value: "A COD OF DOLPHINS" },
  { id: uuid(), category: "Living Things", value: "GIANT SEQUOIA TREES" },
  { id: uuid(), category: "Living Things", value: "BEGONIAS" },
  { id: uuid(), category: "Living Things", value: "BUMBLEBEES" },
  { id: uuid(), category: "Living Things", value: "WILD MUSTANGS" },
  { id: uuid(), category: "Living Things", value: "PINK DAISIES" },
  { id: uuid(), category: "Living Things", value: "FRENCH BULLDOG" },
  { id: uuid(), category: "Living Things", value: "PRAIRIE DOGS" },
  { id: uuid(), category: "Living Things", value: "DUCKS AND GEESE" },
  { id: uuid(), category: "Living Things", value: "BIRDS OF PREY" },
  { id: uuid(), category: "Living Things", value: "GIANT ROSEWOODS" },
]
export default puzzleList
