import { v4 as uuid } from "uuid"
import { Puzzle } from "../../types/Puzzle"
const puzzleList: Puzzle[] = [
  { id: uuid(), category: "On the Map", value: "ATHENS" },
  { id: uuid(), category: "On the Map", value: "THE HUDSON RIVER" },
  { id: uuid(), category: "On the Map", value: "BOGOTA COLUMBIA" },
  { id: uuid(), category: "On the Map", value: "MICHIGAN" },
  { id: uuid(), category: "On the Map", value: "PYRENEES MOUNTAINS" },
  { id: uuid(), category: "On the Map", value: "DETROIT MICHIGAN" },
  { id: uuid(), category: "On the Map", value: "THE DELAWARE BAY" },
  { id: uuid(), category: "On the Map", value: "THE ARABIAN DESERT" },
  { id: uuid(), category: "On the Map", value: "KINGSTON JAMAICA" },
  { id: uuid(), category: "On the Map", value: "URUGUAY" },
  { id: uuid(), category: "On the Map", value: "GREAT SALT LAKE" },
  { id: uuid(), category: "On the Map", value: "QUEBEC" },
  { id: uuid(), category: "On the Map", value: "THE RHINE RIVER" },
  { id: uuid(), category: "On the Map", value: "THE EAST RIVER" },
  { id: uuid(), category: "On the Map", value: "SAN JUAN ISLANDS" },
  { id: uuid(), category: "On the Map", value: "GREAT BARRIER REEF" },
  { id: uuid(), category: "On the Map", value: "INDONESIA" },
  { id: uuid(), category: "On the Map", value: "PARAGUAY" },
  { id: uuid(), category: "On the Map", value: "PHILIPPINE SEA" },
  { id: uuid(), category: "On the Map", value: "HAMBURG" },
  { id: uuid(), category: "On the Map", value: "THE FAR EAST" },
  { id: uuid(), category: "On the Map", value: "THE BERMUDA TRAINGLE" },
  { id: uuid(), category: "On the Map", value: "STATEN ISLAND" },
  { id: uuid(), category: "On the Map", value: "THE SOUTH OF FRANCE" },
  { id: uuid(), category: "On the Map", value: "THE CARIBBEAN SEA" },
  { id: uuid(), category: "On the Map", value: "GENEVA SWITZERLAND" },
  { id: uuid(), category: "On the Map", value: "PORT OF SPAIN" },
  { id: uuid(), category: "On the Map", value: "TENNESSEE RIVER VALLEY" },
  { id: uuid(), category: "On the Map", value: "THE FLORIDA EVERGLADES" },
  { id: uuid(), category: "On the Map", value: "KITTY HAWK" },
  { id: uuid(), category: "On the Map", value: "PUERTO RICO" },
  { id: uuid(), category: "On the Map", value: "SHREVEPORT LOUISIANA" },
  { id: uuid(), category: "On the Map", value: "CAPE OF GOOD HOPE" },
  { id: uuid(), category: "On the Map", value: "BURLINGTON VERMONT" },
  { id: uuid(), category: "On the Map", value: "GREEN BAY WINSCONSON" },
  { id: uuid(), category: "On the Map", value: "ROANOKE" },
  { id: uuid(), category: "On the Map", value: "KANSAS CITY MISSOURI" },
  { id: uuid(), category: "On the Map", value: "THE WESTERN HEMISPHERE" },
  { id: uuid(), category: "On the Map", value: "CATSKILL MOUNTAINS" },
  { id: uuid(), category: "On the Map", value: "THE AUSTRIAN ALPS" },
  { id: uuid(), category: "On the Map", value: "NOVA SCOTIA" },
  { id: uuid(), category: "On the Map", value: "WAIKIKI BEACH" },
  { id: uuid(), category: "On the Map", value: "GULF OF MEXICO" },
  { id: uuid(), category: "On the Map", value: "BUENOS AIRES ARGENTINA" },
  { id: uuid(), category: "On the Map", value: "PIKES PEAK" },
  { id: uuid(), category: "On the Map", value: "BRISBANE AUSTRALIA" },
  { id: uuid(), category: "On the Map", value: "THE CONTINENTAL DIVIDE" },
  { id: uuid(), category: "On the Map", value: "LISBON PORTUGAL" },
  { id: uuid(), category: "On the Map", value: "WARM APPLE CRISP A LA MODE" },
  { id: uuid(), category: "On the Map", value: "THE VIRGIN ISLANDS" },
  { id: uuid(), category: "On the Map", value: "VATICAN CITY IN ROME" },
  { id: uuid(), category: "On the Map", value: "STRAITS OF FLORIDA" },
  { id: uuid(), category: "On the Map", value: "HEIDELBERG GERMANY" },
  { id: uuid(), category: "On the Map", value: "ACAPULCO MEXICO" },
  { id: uuid(), category: "On the Map", value: "THE PAINTED DESERT" },
  { id: uuid(), category: "On the Map", value: "NORWAY AND SWEDEN" },
  { id: uuid(), category: "On the Map", value: "CENTRAL AMERICA" },
  { id: uuid(), category: "On the Map", value: "THE UNITED KINGDOM" },
  { id: uuid(), category: "On the Map", value: "EAST CHINA SEA" },
  { id: uuid(), category: "On the Map", value: "YOUNGSTOWN OHIO" },
  { id: uuid(), category: "On the Map", value: "THE GREAT PLAINS" },
  { id: uuid(), category: "On the Map", value: "LEWIS AND CLARK TRAIL" },
  { id: uuid(), category: "On the Map", value: "MALIBU BEACH" },
  { id: uuid(), category: "On the Map", value: "PLYMOUTH ROCK" },
  { id: uuid(), category: "On the Map", value: "REPUBLIC OF IRELAND" },
  { id: uuid(), category: "On the Map", value: "NEW DELHI INDIA" },
  { id: uuid(), category: "On the Map", value: "CORPUS CHRISTI" },
  { id: uuid(), category: "On the Map", value: "PENSACOLA FLORIDA" },
  { id: uuid(), category: "On the Map", value: "GLASGOW" },
  { id: uuid(), category: "On the Map", value: "KINGDOM OF MOROCCO" },
  { id: uuid(), category: "On the Map", value: "BULGARIA" },
  { id: uuid(), category: "On the Map", value: "THE GREEK ISLES" },
  { id: uuid(), category: "On the Map", value: "THE IVORY COAST" },
  { id: uuid(), category: "On the Map", value: "HAWAIIAN ISLANDS" },
  { id: uuid(), category: "On the Map", value: "THE GREAT LAKES" },
  { id: uuid(), category: "On the Map", value: "BOULDER COLORADO" },
  { id: uuid(), category: "On the Map", value: "THE OKLAHOMA PANHANDLE" },
  { id: uuid(), category: "On the Map", value: "CASCADE RANGE" },
  { id: uuid(), category: "On the Map", value: "SUN VALLEY IDAHO" },
  { id: uuid(), category: "On the Map", value: "THE SNAKE RIVER" },
  { id: uuid(), category: "On the Map", value: "NEWPORT RHODE ISLAND" },
  { id: uuid(), category: "On the Map", value: "EASTER ISLAND" },
  { id: uuid(), category: "On the Map", value: "BEIJING" },
  { id: uuid(), category: "On the Map", value: "HONG KONG" },
  { id: uuid(), category: "On the Map", value: "ARCTIC OCEAN" },
  { id: uuid(), category: "On the Map", value: "CHATTANOOGA TENNESSEE" },
  { id: uuid(), category: "On the Map", value: "TALLAHASSEE FLORIDA" },
  { id: uuid(), category: "On the Map", value: "NAPA CALIFORNIA" },
  { id: uuid(), category: "On the Map", value: "PANAMA CITY" },
  { id: uuid(), category: "On the Map", value: "KEY LARGO" },
  { id: uuid(), category: "On the Map", value: "PROVO UTAH" },
  { id: uuid(), category: "On the Map", value: "DELAWARE RIVER" },
  { id: uuid(), category: "On the Map", value: "JERSEY CITY NEW JERSEY" },
  { id: uuid(), category: "On the Map", value: "MONTERY BAY" },
  { id: uuid(), category: "On the Map", value: "SHRIMP SCAMPI" },
  { id: uuid(), category: "On the Map", value: "LAKE SUPERIOR" },
  { id: uuid(), category: "On the Map", value: "PEBBLE BEACH" },
  { id: uuid(), category: "On the Map", value: "EUGENE OREGON" },
  { id: uuid(), category: "On the Map", value: "BAVARIAN ALPS" },
  { id: uuid(), category: "On the Map", value: "LAKE GENEVA" },
  { id: uuid(), category: "On the Map", value: "SOUTH OF THE BORDER" },
  { id: uuid(), category: "On the Map", value: "NEW YORK'S FIFTH AVENUE" },
  { id: uuid(), category: "On the Map", value: "LAKE PLACID NEW YORK" },
  { id: uuid(), category: "On the Map", value: "THE PORT OF AMSTERDAM" },
  { id: uuid(), category: "On the Map", value: "CABO SAN LUCAS" },
  { id: uuid(), category: "On the Map", value: "SHANGHAI" },
  { id: uuid(), category: "On the Map", value: "CANTON OHIO" },
  { id: uuid(), category: "On the Map", value: "LITTLE ROCK ARKANSAS" },
  { id: uuid(), category: "On the Map", value: "THE CANADIAN BORDER" },
  { id: uuid(), category: "On the Map", value: "THE FRENCH RIVIERA" },
  { id: uuid(), category: "On the Map", value: "PARADISE ISLAND" },
  { id: uuid(), category: "On the Map", value: "SUNSET BOULEVARD" },
  { id: uuid(), category: "On the Map", value: "POCONO MOUNTAINS" },
  { id: uuid(), category: "On the Map", value: "WALLA WALLA WASHINGTON" },
  { id: uuid(), category: "On the Map", value: "THE AMAZON RIVER" },
  { id: uuid(), category: "On the Map", value: "DUBLIN IRELAND" },
  { id: uuid(), category: "On the Map", value: "MINNEAPOLIS & ST. PAUL" },
  { id: uuid(), category: "On the Map", value: "CAIRO EGYPT" },
  { id: uuid(), category: "On the Map", value: "EAST LANSING MICHIGAN" },
  { id: uuid(), category: "On the Map", value: "THE APPALACHIAN MOUNTAINS" },
  { id: uuid(), category: "On the Map", value: "MONTE CARLO" },
  { id: uuid(), category: "On the Map", value: "HAILFAX" },
  { id: uuid(), category: "On the Map", value: "CALCUTTA INDIA" },
  { id: uuid(), category: "On the Map", value: "THE GOBI DESERT" },
  { id: uuid(), category: "On the Map", value: "SARATOGA SPRINGS" },
  { id: uuid(), category: "On the Map", value: "ANCHORAGE ALASKA" },
  { id: uuid(), category: "On the Map", value: "TAIWAN" },
  { id: uuid(), category: "On the Map", value: "THE DEAD SEA" },
  { id: uuid(), category: "On the Map", value: "NANTUCKET" },
  { id: uuid(), category: "On the Map", value: "AUCKLAND NEW ZEALAND" },
  { id: uuid(), category: "On the Map", value: "MOBILE ALABAMA" },
  { id: uuid(), category: "On the Map", value: "MILAN ITALY" },
  { id: uuid(), category: "On the Map", value: "LUBBOCK" },
  { id: uuid(), category: "On the Map", value: "MISSISSIPPI MUD PIE" },
  { id: uuid(), category: "On the Map", value: "BUTTE MONTANA" },
  { id: uuid(), category: "On the Map", value: "CHAPEL HILL NORTH CAROLINA" },
  { id: uuid(), category: "On the Map", value: "GARY INDIANA" },
  { id: uuid(), category: "On the Map", value: "LAKE OF THE OZARKS" },
  { id: uuid(), category: "On the Map", value: "MIAMI BEACH FLORIDA" },
  { id: uuid(), category: "On the Map", value: "COSTA RICA" },
  { id: uuid(), category: "On the Map", value: "CEDAR RAPIDS IOWA" },
  { id: uuid(), category: "On the Map", value: "CAPE HATTERAS" },
  { id: uuid(), category: "On the Map", value: "SANTIAGO CHILE" },
  { id: uuid(), category: "On the Map", value: "HARTFORD CONNECTICUT" },
  { id: uuid(), category: "On the Map", value: "MADAGASCAR" },
  { id: uuid(), category: "On the Map", value: "THE NETHERLANDS" },
  { id: uuid(), category: "On the Map", value: "BROOKLYN NEW YORK" },
  {
    id: uuid(),
    category: "On the Map",
    value: "CANADA'S NORTHWEST TERRITORIES",
  },
  { id: uuid(), category: "On the Map", value: "THE RIO GRANDE" },
  { id: uuid(), category: "On the Map", value: "DODGE CITY KANSAS" },
  { id: uuid(), category: "On the Map", value: "DOVER DELAWARE" },
  { id: uuid(), category: "On the Map", value: "CALGARY ALBERTA" },
  {
    id: uuid(),
    category: "On the Map",
    value: "THE BLACK HILLS OF SOUTH DAKOTA",
  },
  { id: uuid(), category: "On the Map", value: "LUXEMBOURG" },
  { id: uuid(), category: "On the Map", value: "ST. LAWRENCE RIVER" },
  { id: uuid(), category: "On the Map", value: "THE HIMALAYAS" },
  { id: uuid(), category: "On the Map", value: "THE PACIFIC COAST" },
  { id: uuid(), category: "On the Map", value: "DOMINICAN REPUBLIC" },
  { id: uuid(), category: "On the Map", value: "CANARY ISLANDS" },
  { id: uuid(), category: "On the Map", value: "THE FLORIDA PANHANDLE" },
  { id: uuid(), category: "On the Map", value: "CASABLANCA MOROCCO" },
  { id: uuid(), category: "On the Map", value: "ASPEN & VAIL" },
  { id: uuid(), category: "On the Map", value: "SAVANNAH GEORGIA" },
  { id: uuid(), category: "On the Map", value: "CHARLESTON SOUTH CAROLINA" },
  { id: uuid(), category: "On the Map", value: "LAKE MICHIGAN" },
  { id: uuid(), category: "On the Map", value: "VATICAN CITY" },
  { id: uuid(), category: "On the Map", value: "HOT SPRINGS ARKANSAS" },
  { id: uuid(), category: "On the Map", value: "THE RHINE RIVER" },
  { id: uuid(), category: "On the Map", value: "MADISON WINSCONSIN" },
  { id: uuid(), category: "On the Map", value: "COPENHAGEN DENMARK" },
  { id: uuid(), category: "On the Map", value: "BURBANK" },
  { id: uuid(), category: "On the Map", value: "MOUNT KILIMANJARO" },
  { id: uuid(), category: "On the Map", value: "GRAND FORKS NORTH DAKOTA" },
  { id: uuid(), category: "On the Map", value: "SQUAW VALLEY" },
  { id: uuid(), category: "On the Map", value: "STEAMBOAT SPRINGS" },
  { id: uuid(), category: "On the Map", value: "PROVIDENCE RHODE ISLAND" },
  { id: uuid(), category: "On the Map", value: "THE CZECH REPUBLIC" },
  { id: uuid(), category: "On the Map", value: "THE BALTIC SEA" },
  {
    id: uuid(),
    category: "On the Map",
    value: "MONTGOMERY & TUSCALOOSA ALABAMA",
  },
  { id: uuid(), category: "On the Map", value: "LAKE ONTARIO" },
  { id: uuid(), category: "On the Map", value: "THE JORDAN RIVER" },
  { id: uuid(), category: "On the Map", value: "BRANSON MISSOURI" },
  { id: uuid(), category: "On the Map", value: "SACRAMENTO" },
  { id: uuid(), category: "On the Map", value: "HONOLULU HAWAII" },
  { id: uuid(), category: "On the Map", value: "GREAT SALT LAKE" },
  { id: uuid(), category: "On the Map", value: "JACKSON MISSISSIPPI" },
  { id: uuid(), category: "On the Map", value: "NEW BRUNSWICK" },
  { id: uuid(), category: "On the Map", value: "GUATEMALA CITY GUATEMALA" },
  { id: uuid(), category: "On the Map", value: "LAKE OKEECHOBEE" },
  { id: uuid(), category: "On the Map", value: "SCOTTISH HIGHLANDS" },
  { id: uuid(), category: "On the Map", value: "AUGUSTA GEORGIA" },
  { id: uuid(), category: "On the Map", value: "GREAT SMOKY MOUNTAINS" },
  { id: uuid(), category: "On the Map", value: "THE CAYMAN ISLANDS" },
  { id: uuid(), category: "On the Map", value: "LAKE TAHOE" },
  { id: uuid(), category: "On the Map", value: "MIDTOWN MANHATTAN" },
  { id: uuid(), category: "On the Map", value: "DUBUQUE IOWA" },
  { id: uuid(), category: "On the Map", value: "MARTHA'S VINEYARD" },
  { id: uuid(), category: "On the Map", value: "PACIFIC COAST HIGHWAY" },
  { id: uuid(), category: "On the Map", value: "TAHITI" },
  {
    id: uuid(),
    category: "On the Map",
    value: "THE WHITE MOUNTAINS OF NEW HAMPSHIRE",
  },
  { id: uuid(), category: "On the Map", value: "LAKE HURON" },
  { id: uuid(), category: "On the Map", value: "RENO NEVADA" },
  { id: uuid(), category: "On the Map", value: "PUEBLO" },
  { id: uuid(), category: "On the Map", value: "DISTRICT OF COLUMBIA" },
  { id: uuid(), category: "On the Map", value: "THE CASPIAN SEA" },
  { id: uuid(), category: "On the Map", value: "KUWAIT" },
  { id: uuid(), category: "On the Map", value: "GENEVA SWITZERLAND" },
  { id: uuid(), category: "On the Map", value: "NASHVILLE TENNESSEE" },
  { id: uuid(), category: "On the Map", value: "PANAMA CITY PANAMA" },
  { id: uuid(), category: "On the Map", value: "BRITISH VIRGIN ISLANDS" },
  { id: uuid(), category: "On the Map", value: "BOLIVIA" },
  { id: uuid(), category: "On the Map", value: "RIO DE JANEIRO" },
  { id: uuid(), category: "On the Map", value: "ST. PETERSBURG" },
  { id: uuid(), category: "On the Map", value: "THE CHICAGO RIVER" },
  { id: uuid(), category: "On the Map", value: "SYDNEY & MELBOURNE AUSTRALIA" },
  { id: uuid(), category: "On the Map", value: "PUERTO RICO" },
  { id: uuid(), category: "On the Map", value: "CINCINNATI OHIO" },
  { id: uuid(), category: "On the Map", value: "SAN JUAN ISLANDS" },
  { id: uuid(), category: "On the Map", value: "SCOTTSDALE ARIZONA" },
  { id: uuid(), category: "On the Map", value: "LOUISVILLE KENTUCKY" },
  { id: uuid(), category: "On the Map", value: "SAN FRANCISCO BAY AREA" },
  { id: uuid(), category: "On the Map", value: "NORTH CAROLINA" },
  { id: uuid(), category: "On the Map", value: "THE TWIN CITIES" },
  { id: uuid(), category: "On the Map", value: "MICHIGAN'S UPPER PENINSULA" },
  { id: uuid(), category: "On the Map", value: "FAIRFAX VIRGINIA" },
  { id: uuid(), category: "On the Map", value: "BOSTON HARBOR" },
  { id: uuid(), category: "On the Map", value: "MOUNT FUJI" },
  { id: uuid(), category: "On the Map", value: "CONNECTICUT RIVER" },
  {
    id: uuid(),
    category: "On the Map",
    value: "THE GREEN MOUNTAINS OF VERMONT",
  },
  { id: uuid(), category: "On the Map", value: "EASTERN EUROPE" },
  { id: uuid(), category: "On the Map", value: "WICHITA" },
  { id: uuid(), category: "On the Map", value: "SHENANDOAH RIVER" },
  { id: uuid(), category: "On the Map", value: "THE POTOMAC RIVER" },
  { id: uuid(), category: "On the Map", value: "BERLIN GERMANY" },
  { id: uuid(), category: "On the Map", value: "HELSINKI FINLAND" },
  { id: uuid(), category: "On the Map", value: "GULF OF CALIFORNIA" },
  { id: uuid(), category: "On the Map", value: "CAPE COD NATIONAL SEASHORE" },
  { id: uuid(), category: "On the Map", value: "SAGINAW" },
  { id: uuid(), category: "On the Map", value: "MOJAVE DESERT" },
  { id: uuid(), category: "On the Map", value: "BOWLING GREEN KETUCKY" },
  { id: uuid(), category: "On the Map", value: "THE CHARLES RIVER" },
  { id: uuid(), category: "On the Map", value: "HAMBURG" },
  { id: uuid(), category: "On the Map", value: "FARGO NORTH DAKOTA" },
  { id: uuid(), category: "On the Map", value: "SAN ANTONIO" },
  { id: uuid(), category: "On the Map", value: "SHREVEPORT LOUISIANA" },
  { id: uuid(), category: "On the Map", value: "URUGUAY" },
  { id: uuid(), category: "On the Map", value: "BRUSSELS BELGIUM" },
  { id: uuid(), category: "On the Map", value: "THE CONTINENT OF ANTARCTICA" },
  { id: uuid(), category: "On the Map", value: "GUADALAJARA" },
  { id: uuid(), category: "On the Map", value: "THE RIO GRANDE VALLEY" },
  { id: uuid(), category: "On the Map", value: "OKLAHOMA CITY" },
  { id: uuid(), category: "On the Map", value: "TROPIC OF CAPRICORN" },
  { id: uuid(), category: "On the Map", value: "FORT LAUDERDALE" },
  { id: uuid(), category: "On the Map", value: "THE SOUTH POLE" },
  { id: uuid(), category: "On the Map", value: "OSHKOSH" },
  { id: uuid(), category: "On the Map", value: "TUPELO MISSISSIPPI" },
  { id: uuid(), category: "On the Map", value: "VANCOUVER ISLAND" },
  { id: uuid(), category: "On the Map", value: "THE ITALIAN ALPS" },
  { id: uuid(), category: "On the Map", value: "GRAND RAPIDS MICHIGAN" },
  { id: uuid(), category: "On the Map", value: "LAKE HAVASU" },
  { id: uuid(), category: "On the Map", value: "HOBOKEN" },
  { id: uuid(), category: "On the Map", value: "THE YUKON TERRITORY" },
  { id: uuid(), category: "On the Map", value: "ATHENS GREECE" },
  { id: uuid(), category: "On the Map", value: "BALTIMORE MARYLAND" },
  { id: uuid(), category: "On the Map", value: "CONCORD NEW HAMPSHIRE" },
  { id: uuid(), category: "On the Map", value: "THE SOUTH CHINA SEA" },
  {
    id: uuid(),
    category: "On the Map",
    value: "ST. THOMAS UNITED STATES VIRGIN ISLANDS",
  },
  { id: uuid(), category: "On the Map", value: "IOWA CITY" },
  { id: uuid(), category: "On the Map", value: "EDMONTON" },
  { id: uuid(), category: "On the Map", value: "THE WEST INDIES" },
  { id: uuid(), category: "On the Map", value: "PARK CITY UTAH" },
  { id: uuid(), category: "On the Map", value: "MOUNT BALDY" },
  { id: uuid(), category: "On the Map", value: "FLORIDA KEYS" },
  { id: uuid(), category: "On the Map", value: "SOUTHEAST ASIA" },
  { id: uuid(), category: "On the Map", value: "CHAMPAGNE REGION OF FRANCE" },
  { id: uuid(), category: "On the Map", value: "KANSAS CITY MISSOURI" },
  { id: uuid(), category: "On the Map", value: "ISLAND OF MALTA" },
  { id: uuid(), category: "On the Map", value: "THE ANDES MOUNTAINS" },
  { id: uuid(), category: "On the Map", value: "DENVER COLORADO" },
  {
    id: uuid(),
    category: "On the Map",
    value: "PORTLAND OREGON & PORTLAND MAINE",
  },
  { id: uuid(), category: "On the Map", value: "THE ATLANTIC COAST" },
  { id: uuid(), category: "On the Map", value: "BLUE RIDGE MOUNTAINS" },
  { id: uuid(), category: "On the Map", value: "MISSOULA MONTANA" },
  { id: uuid(), category: "On the Map", value: "KNOXVILLE TENNESSEE" },
  { id: uuid(), category: "On the Map", value: "SAN JUAN PUERTO RICO" },
  { id: uuid(), category: "On the Map", value: "ATLANTA GEORGIA" },
  { id: uuid(), category: "On the Map", value: "CHESAPEAKE BAY" },
  { id: uuid(), category: "On the Map", value: "LAUGHLIN NEVADA" },
  { id: uuid(), category: "On the Map", value: "THE GRAND CANAL IN VENICE" },
  { id: uuid(), category: "On the Map", value: "BANGLADESH" },
  { id: uuid(), category: "On the Map", value: "REPUBLIC OF IRELAND" },
  { id: uuid(), category: "On the Map", value: "GULF OF ALASKA" },
  { id: uuid(), category: "On the Map", value: "TACOMA WASHINGTON" },
  { id: uuid(), category: "On the Map", value: "TELLURIDE COLORADO" },
  { id: uuid(), category: "On the Map", value: "DULUTH" },
  { id: uuid(), category: "On the Map", value: "RAPID CITY SOUTH DAKOTA" },
  { id: uuid(), category: "On the Map", value: "WEST VIRGINIA" },
  { id: uuid(), category: "On the Map", value: "BOISE IDAHO" },
  { id: uuid(), category: "On the Map", value: "AMSTERDAM" },
  { id: uuid(), category: "On the Map", value: "TORONTO ONTARIO CANADA" },
  { id: uuid(), category: "On the Map", value: "KALAMAZOO MICHIGAN" },
  { id: uuid(), category: "On the Map", value: "CLEARWATER FLORIDA" },
  { id: uuid(), category: "On the Map", value: "MOUNT VESUVIUS" },
  { id: uuid(), category: "On the Map", value: "OMAHA NEBRASKA" },
  { id: uuid(), category: "On the Map", value: "KITTY HAWK" },
  { id: uuid(), category: "On the Map", value: "THE SIERRA NEVADA MOUNTAINS" },
  { id: uuid(), category: "On the Map", value: "PEORIA ILLINOIS" },
  { id: uuid(), category: "On the Map", value: "STILLWATER OKLAHOMA" },
  { id: uuid(), category: "On the Map", value: "CASPER WYOMING" },
  { id: uuid(), category: "On the Map", value: "THE AMAZON & NILE RIVERS" },
  { id: uuid(), category: "On the Map", value: "THE UNITED KINGDOM" },
  { id: uuid(), category: "On the Map", value: "CATALINA ISLAND" },
  { id: uuid(), category: "On the Map", value: "THE BAJA PENINSULA" },
  { id: uuid(), category: "On the Map", value: "THE CANADIAN ROCKIES" },
  { id: uuid(), category: "On the Map", value: "PENSACOLA FLORIDA" },
  { id: uuid(), category: "On the Map", value: "THE GREAT LAKES" },
  { id: uuid(), category: "On the Map", value: "MISSISSIPPI RIVER" },
  { id: uuid(), category: "On the Map", value: "THE GALAPAGOS ISLANDS" },
  { id: uuid(), category: "On the Map", value: "ORANGE COUNTY CALIFORNIA" },
  { id: uuid(), category: "On the Map", value: "MINNEAPOLIS MINNESOTA" },
  { id: uuid(), category: "On the Map", value: "CHARLOTTE NORTH CAROLINA" },
  { id: uuid(), category: "On the Map", value: "BAKERSFIELD CALIFORNIA" },
  { id: uuid(), category: "On the Map", value: "MOUNT MCKINLEY" },
  { id: uuid(), category: "On the Map", value: "TUCSON ARIZONA" },
  { id: uuid(), category: "On the Map", value: "DAYTON OHIO" },
  { id: uuid(), category: "On the Map", value: "THE BERING SEA" },
  { id: uuid(), category: "On the Map", value: "BANGOR" },
  { id: uuid(), category: "On the Map", value: "BIRMINGHAM ALABAMA" },
  { id: uuid(), category: "On the Map", value: "BATTLE CREEK MICHIGAN" },
  { id: uuid(), category: "On the Map", value: "HILO HAWAII" },
  { id: uuid(), category: "On the Map", value: "TENNESSEE RIVER VALLEY" },
  { id: uuid(), category: "On the Map", value: "THE NORTH ATLANTIC" },
  { id: uuid(), category: "On the Map", value: "LOWER MANHATTAN" },
  { id: uuid(), category: "On the Map", value: "TEXARKANA" },
  { id: uuid(), category: "On the Map", value: "NEW ORLEANS LOUISIANA" },
  { id: uuid(), category: "On the Map", value: "MILWAUKEE WINSCONSIN" },
  { id: uuid(), category: "On the Map", value: "SPAIN & PORTUGAL" },
  { id: uuid(), category: "On the Map", value: "LAKE CHAMPLAIN" },
  { id: uuid(), category: "On the Map", value: "THE SOUTH OF FRANCE" },
  { id: uuid(), category: "On the Map", value: "BILLINGS MONTANA" },
  { id: uuid(), category: "On the Map", value: "JERUSALEM" },
  { id: uuid(), category: "On the Map", value: "THE ITALIAN RIVIERA" },
  { id: uuid(), category: "On the Map", value: "NEW JERSEY TURNPIKE" },
  { id: uuid(), category: "On the Map", value: "THE SOUTH BRONX" },
  { id: uuid(), category: "On the Map", value: "THE ADIRONDACKS" },
  { id: uuid(), category: "On the Map", value: "THE UPPER WEST SIDE" },
  { id: uuid(), category: "On the Map", value: "LONG ISLAND SOUND" },
  { id: uuid(), category: "On the Map", value: "THE HUDSON RIVER" },
  { id: uuid(), category: "On the Map", value: "FLAGSTAFF" },
  { id: uuid(), category: "On the Map", value: "THE GULF COAST" },
  { id: uuid(), category: "On the Map", value: "COSTA RICA" },
  { id: uuid(), category: "On the Map", value: "HOUSTON TEXAS" },
  { id: uuid(), category: "On the Map", value: "JEFFERSON CITY MISSOURI" },
  { id: uuid(), category: "On the Map", value: "THE AUSTRIAN ALPS" },
  { id: uuid(), category: "On the Map", value: "STOCKHOLM SWEDEN" },
  { id: uuid(), category: "On the Map", value: "SAUDI ARABIA" },
  { id: uuid(), category: "On the Map", value: "BOULDER COLORADO" },
  { id: uuid(), category: "On the Map", value: "THE PHILIPPINES" },
  { id: uuid(), category: "On the Map", value: "THE ENGLISH CHANNEL" },
  { id: uuid(), category: "On the Map", value: "CABO SAN LUCAS" },
  { id: uuid(), category: "On the Map", value: "ANNAPOLIS MARYLAND" },
  { id: uuid(), category: "On the Map", value: "BURLINGTON VERMONT" },
  { id: uuid(), category: "On the Map", value: "MOUNT RAINIER" },
  { id: uuid(), category: "On the Map", value: "KEY BISCAYNE" },
  { id: uuid(), category: "On the Map", value: "INDONESIA" },
  { id: uuid(), category: "On the Map", value: "ROSWELL NEW MEXICO" },
  { id: uuid(), category: "On the Map", value: "GLASGOW SCOTLAND" },
  { id: uuid(), category: "On the Map", value: "RHODE ISLAND" },
  { id: uuid(), category: "On the Map", value: "QUEBEC CANADA" },
  { id: uuid(), category: "On the Map", value: "ST. LOUIS MISSOURI" },
  { id: uuid(), category: "On the Map", value: "NORTH AFRICA" },
  { id: uuid(), category: "On the Map", value: "SANTO DOMINGO" },
  { id: uuid(), category: "On the Map", value: "FRENCH POLYNESIA" },
  { id: uuid(), category: "On the Map", value: "NORTHERN IRELAND" },
  { id: uuid(), category: "On the Map", value: "THE PACIFIC NORTHWEST" },
  { id: uuid(), category: "On the Map", value: "NEWARK NEW JERSEY" },
  { id: uuid(), category: "On the Map", value: "EAST AFRICA" },
  { id: uuid(), category: "On the Map", value: "MOUNT EVEREST" },
  { id: uuid(), category: "On the Map", value: "MISSOURI RIVER" },
  { id: uuid(), category: "On the Map", value: "COLOMBIA & VENEZUELA" },
  { id: uuid(), category: "On the Map", value: "THE GREEK ISLANDS" },
  { id: uuid(), category: "On the Map", value: "GULF OF MEXICO" },
  { id: uuid(), category: "On the Map", value: "THE TEXAS PANHANDLE" },
  { id: uuid(), category: "On the Map", value: "THE OREGON COAST" },
  { id: uuid(), category: "On the Map", value: "VIRGINIA BEACH VIRGINIA" },
  { id: uuid(), category: "On the Map", value: "THE SOUTH PACIFIC" },
  { id: uuid(), category: "On the Map", value: "GRAND JUNCTION COLORADO" },
  { id: uuid(), category: "On the Map", value: "CARSON CITY NEVADA" },
  { id: uuid(), category: "On the Map", value: "NOTTINGHAM ENGLAND" },
  { id: uuid(), category: "On the Map", value: "STRAIT OF GIBRALTAR" },
  { id: uuid(), category: "On the Map", value: "THE CATSKILL MOUNTAINS" },
  { id: uuid(), category: "On the Map", value: "THE MAINE COAST" },
  { id: uuid(), category: "On the Map", value: "THE BAHAMAS" },
  { id: uuid(), category: "On the Map", value: "CENTRAL ASIA" },
  { id: uuid(), category: "On the Map", value: "THE NORTHERN ROCKIES" },
  { id: uuid(), category: "On the Map", value: "LAKE SUPERIOR" },
  { id: uuid(), category: "On the Map", value: "WARSAW POLAND" },
  { id: uuid(), category: "On the Map", value: "SOUTH OF THE BORDER" },
  { id: uuid(), category: "On the Map", value: "BAJA CALIFORNIA" },
  { id: uuid(), category: "On the Map", value: "THE UPPER GREAT LAKES REGION" },
  { id: uuid(), category: "On the Map", value: "TOPEKA KANSAS" },
  { id: uuid(), category: "On the Map", value: "TOKYO JAPAN" },
  { id: uuid(), category: "On the Map", value: "THE OHIO RIVER VALLEY" },
  { id: uuid(), category: "On the Map", value: "MUNICH GERMANY" },
  { id: uuid(), category: "On the Map", value: "SOUTH BEND INDIANA" },
  { id: uuid(), category: "On the Map", value: "THE FRENCH RIVIERA" },
  { id: uuid(), category: "On the Map", value: "THE NORTHERN HEMISPHERE" },
  { id: uuid(), category: "On the Map", value: "THE NETHERLANDS" },
  { id: uuid(), category: "On the Map", value: "MEXICO CITY" },
  { id: uuid(), category: "On the Map", value: "THE PACIFIC COASTLINE" },
  { id: uuid(), category: "On the Map", value: "THE FRENCH WEST INDIES" },
  { id: uuid(), category: "On the Map", value: "ECUADOR & PERU" },
  { id: uuid(), category: "On the Map", value: "THE EASTERN SEABOARD" },
  { id: uuid(), category: "On the Map", value: "WESTERN EUROPE" },
  { id: uuid(), category: "On the Map", value: "GAINESVILLE FLORIDA" },
  { id: uuid(), category: "On the Map", value: "THE PACIFIC OCEAN" },
  { id: uuid(), category: "On the Map", value: "MALIBU BEACH CALIFORNIA" },
  { id: uuid(), category: "On the Map", value: "NEW YORK & NEW JERSEY" },
  { id: uuid(), category: "On the Map", value: "HILTON HEAD SOUTH CAROLINA" },
  { id: uuid(), category: "On the Map", value: "THE PACIFIC RIM" },
  { id: uuid(), category: "On the Map", value: "HAVANA CUBA" },
  { id: uuid(), category: "On the Map", value: "THE YUKON RIVER" },
  { id: uuid(), category: "On the Map", value: "HUDSON BAY" },
  { id: uuid(), category: "On the Map", value: "ALASKA HIGHWAY" },
  { id: uuid(), category: "On the Map", value: "THE ARCTIC CIRCLE" },
  { id: uuid(), category: "On the Map", value: "LAKE MICHIGAN" },
  { id: uuid(), category: "On the Map", value: "ORLANDO FLORDIA" },
  { id: uuid(), category: "On the Map", value: "THE OZARK MOUNTAINS" },
  { id: uuid(), category: "On the Map", value: "BRAZIL & CHILE" },
  { id: uuid(), category: "On the Map", value: "SOUTH CAROLINA" },
  { id: uuid(), category: "On the Map", value: "MEMPHIS TENNESSEE" },
  { id: uuid(), category: "On the Map", value: "VERMONT & NEW HAMPSHIRE" },
  { id: uuid(), category: "On the Map", value: "BEIJING" },
  { id: uuid(), category: "On the Map", value: "AUSTIN TEXAS" },
  { id: uuid(), category: "On the Map", value: "BARCELONA SPAIN" },
  { id: uuid(), category: "On the Map", value: "THE FRENCH ALPS" },
  { id: uuid(), category: "On the Map", value: "THE CONTINENT OF AUSTRALIA" },
  { id: uuid(), category: "On the Map", value: "SCOTLAND & WALES" },
  { id: uuid(), category: "On the Map", value: "JUNEAU" },
  { id: uuid(), category: "On the Map", value: "SCANDINAVIA" },
  { id: uuid(), category: "On the Map", value: "COLUMBUS OHIO" },
  { id: uuid(), category: "On the Map", value: "THE NORTH POLE" },
  { id: uuid(), category: "On the Map", value: "TIMES SQUARE" },
  { id: uuid(), category: "On the Map", value: "THE APPALACHIAN TRAIL" },
  { id: uuid(), category: "On the Map", value: "THE COLORADO RIVER" },
  { id: uuid(), category: "On the Map", value: "YUMA & PHOENIX" },
  { id: uuid(), category: "On the Map", value: "ALGERIA & MOROCCO" },
  { id: uuid(), category: "On the Map", value: "QUANTICO VIRGINIA" },
  { id: uuid(), category: "On the Map", value: "HALIFAX NOVA SCOTIA" },
  { id: uuid(), category: "On the Map", value: "THE PHILIPPINE ISLANDS" },
  { id: uuid(), category: "On the Map", value: "SIGNAPORE" },
  { id: uuid(), category: "On the Map", value: "DUBLIN IRELAND" },
  { id: uuid(), category: "On the Map", value: "ALBEQUERQUE NEW MEXICO" },
  { id: uuid(), category: "On the Map", value: "AMERICAN SAMOA" },
  { id: uuid(), category: "On the Map", value: "BISMARK NORTH DAKOTA" },
  { id: uuid(), category: "On the Map", value: "THE SIERRA MADRE MOUNTAINS" },
  { id: uuid(), category: "On the Map", value: "TAMPA BAY FLORIDA" },
  { id: uuid(), category: "On the Map", value: "LONDON ENGLAND" },
  { id: uuid(), category: "On the Map", value: "WITCHITA KANSAS" },
  { id: uuid(), category: "On the Map", value: "TULSA OKLAHOMA" },
  { id: uuid(), category: "On the Map", value: "NEW ZEALAND" },
  { id: uuid(), category: "On the Map", value: "LAKE ERIE" },
  { id: uuid(), category: "On the Map", value: "ST. LAWRENCE SEAWAY" },
  { id: uuid(), category: "On the Map", value: "NEW DELHI INDIA" },
  { id: uuid(), category: "On the Map", value: "PORTLAND OREGON" },
  { id: uuid(), category: "On the Map", value: "ANCHORAGE ALASKA" },
  { id: uuid(), category: "On the Map", value: "ATLANTIC CITY" },
  { id: uuid(), category: "On the Map", value: "THE ARABIAN SEA" },
  { id: uuid(), category: "On the Map", value: "CAIRO EGYPT" },
  { id: uuid(), category: "On the Map", value: "CANADIAN ROCKY MOUNTAINS" },
  { id: uuid(), category: "On the Map", value: "LAKE MEAD" },
  { id: uuid(), category: "On the Map", value: "WEST AFRICA" },
  { id: uuid(), category: "On the Map", value: "DEATH VALLEY" },
  { id: uuid(), category: "On the Map", value: "LEXINGTON AND CONCORD" },
  { id: uuid(), category: "On the Map", value: "NANTUCKET SOUND" },
  { id: uuid(), category: "On the Map", value: "LIBSON PORTUGAL" },
  { id: uuid(), category: "On the Map", value: "GREEN BAY WINSCONSIN" },
  { id: uuid(), category: "On the Map", value: "NEW HAVEN CONNETICUT" },
  { id: uuid(), category: "On the Map", value: "CHYENNE WYOMING" },
  { id: uuid(), category: "On the Map", value: "LIBSON PORTUGAL" },
  { id: uuid(), category: "On the Map", value: "GREEN BAY WINSCONSIN" },
  { id: uuid(), category: "On the Map", value: "NEW HAVEN CONNETICUT" },
  { id: uuid(), category: "On the Map", value: "CHYENNE WYOMING" },
  { id: uuid(), category: "On the Map", value: "VATICAN CITY" },
  { id: uuid(), category: "On the Map", value: "ALEXANDRIA VIRGINIA" },
  { id: uuid(), category: "On the Map", value: "CHICAGO ILLINOIS" },
  { id: uuid(), category: "On the Map", value: "KANSAS CITY KANSAS" },
  { id: uuid(), category: "On the Map", value: "CHARLESTON SOUTH CAROLINA" },
  { id: uuid(), category: "On the Map", value: "CHINATOWN" },
  { id: uuid(), category: "On the Map", value: "LITTLE ITALY" },
  { id: uuid(), category: "On the Map", value: "WALL STREET" },
  { id: uuid(), category: "On the Map", value: "DALLAS TEXAS" },
  { id: uuid(), category: "On the Map", value: "FLAGSTAFF ARIZONA" },
  { id: uuid(), category: "On the Map", value: "GRAND RAPIDS MICHIGAN" },
  { id: uuid(), category: "On the Map", value: "NAPA VALLEY" },
  { id: uuid(), category: "On the Map", value: "NORTH DAKOTA" },
  { id: uuid(), category: "On the Map", value: "JERSEY CITY NEW JERSEY" },
  { id: uuid(), category: "On the Map", value: "THE BLACK SEA" },
  { id: uuid(), category: "On the Map", value: "MADRID SPAIN" },
  { id: uuid(), category: "On the Map", value: "BRUSSELS BELGIUM" },
  { id: uuid(), category: "On the Map", value: "OSLO NORWAY" },
  { id: uuid(), category: "On the Map", value: "ROME ITALY" },
  { id: uuid(), category: "On the Map", value: "OTTAWA CANADA" },
  { id: uuid(), category: "On the Map", value: "EASTER ISLAND" },
  { id: uuid(), category: "On the Map", value: "VANCOUVER BRITISH COLUMBIA" },
  { id: uuid(), category: "On the Map", value: "PUGET SOUND" },
  { id: uuid(), category: "On the Map", value: "THE CANADIAN BORDER" },
  { id: uuid(), category: "On the Map", value: "BUTTE MONTANA" },
  { id: uuid(), category: "On the Map", value: "THE HIMALAYAS" },
  { id: uuid(), category: "On the Map", value: "THE AMAZON RIVER" },
  { id: uuid(), category: "On the Map", value: "SAVANNAH GEORGIA" },
  { id: uuid(), category: "On the Map", value: "COPENHAGEN DENMARK" },
  { id: uuid(), category: "On the Map", value: "CASABLANCA MOROCCO" },
  { id: uuid(), category: "On the Map", value: "BALTIMORE MARYLAND" },
  { id: uuid(), category: "On the Map", value: "ST. PETERSBURG" },
  { id: uuid(), category: "On the Map", value: "SOUTH KOREA" },
  { id: uuid(), category: "On the Map", value: "THE WESTERN HEMISPHERE" },
  { id: uuid(), category: "On the Map", value: "THE CASPIAN SEA" },
  { id: uuid(), category: "On the Map", value: "PACIFIC COAST HIGHWAY" },
  { id: uuid(), category: "On the Map", value: "NORTH CAROLINA" },
  { id: uuid(), category: "On the Map", value: "NORFOLK VIRGINIA" },
  { id: uuid(), category: "On the Map", value: "BOISE IDAHO" },
  { id: uuid(), category: "On the Map", value: "BATTLE CREEK MICHIGAN" },
  { id: uuid(), category: "On the Map", value: "NEW HAMPSHIRE" },
  { id: uuid(), category: "On the Map", value: "VENICE ITALY" },
  { id: uuid(), category: "On the Map", value: "NORWAY AND SWEDEN" },
  { id: uuid(), category: "On the Map", value: "ATHENS GREECE" },
  { id: uuid(), category: "On the Map", value: "SYDNEY AUSTRALIA" },
  { id: uuid(), category: "On the Map", value: "VIENNA AUSTRIA" },
  { id: uuid(), category: "On the Map", value: "KANSAS CITY MISSOURI" },
  { id: uuid(), category: "On the Map", value: "DENVER COLORADO" },
  { id: uuid(), category: "On the Map", value: "HAWAII" },
  { id: uuid(), category: "On the Map", value: "SAN DIEGO" },
  { id: uuid(), category: "On the Map", value: "BAR HARBOR MAINE" },
  { id: uuid(), category: "On the Map", value: "OLYMPIA WASHINGTON" },
  { id: uuid(), category: "On the Map", value: "GLAICER BAY" },
  { id: uuid(), category: "On the Map", value: "FORT WORTH TEXAS" },
  { id: uuid(), category: "On the Map", value: "THE POTOMAC RIVER" },
  { id: uuid(), category: "On the Map", value: "LINCOLN NEBRASKA" },
  { id: uuid(), category: "On the Map", value: "TALLAHASSEE FLORIDA" },
  { id: uuid(), category: "On the Map", value: "THE ARCTIC OCEAN" },
  { id: uuid(), category: "On the Map", value: "FLORIDA KEYS" },
  { id: uuid(), category: "On the Map", value: "CHESAPEAKE BAY" },
  { id: uuid(), category: "On the Map", value: "JACKSON HOLE WYOMING" },
  { id: uuid(), category: "On the Map", value: "GENEVA SWITZERLAND" },
  { id: uuid(), category: "On the Map", value: "SCOTTSDALE ARIZONA" },
  { id: uuid(), category: "On the Map", value: "KNOXVILLE TENNESSEE" },
  { id: uuid(), category: "On the Map", value: "PARIS FRANCE" },
  { id: uuid(), category: "On the Map", value: "AUCKLAND NEW ZEALAND" },
  { id: uuid(), category: "On the Map", value: "SALT LAKE CITY" },
  { id: uuid(), category: "On the Map", value: "ATLANTA GEORGIA" },
  { id: uuid(), category: "On the Map", value: "SAN FRANCISCO" },
  { id: uuid(), category: "On the Map", value: "CINCINNATI OHIO" },
  { id: uuid(), category: "On the Map", value: "SEATTLE WASHINGTON" },
  { id: uuid(), category: "On the Map", value: "ARGENTINA & CHILE" },
  { id: uuid(), category: "On the Map", value: "EASTERN EUROPE" },
  { id: uuid(), category: "On the Map", value: "SOUTH DAKOTA" },
  { id: uuid(), category: "On the Map", value: "MOUNT MCKINLEY" },
  { id: uuid(), category: "On the Map", value: "MINNEAPOLIS MINNESOTA" },
  { id: uuid(), category: "On the Map", value: "DISTRICT OF COLUMBIA" },
  { id: uuid(), category: "On the Map", value: "SAUDI ARABIA" },
  { id: uuid(), category: "On the Map", value: "MISSISSIPPI RIVER" },
  { id: uuid(), category: "On the Map", value: "GULF OF MEXICO" },
  { id: uuid(), category: "On the Map", value: "THE SOUTH OF FRANCE" },
  {
    id: uuid(),
    category: "On the Map",
    value: "THE FRENCH QUARTER IN NEW ORLEANS",
  },
  { id: uuid(), category: "On the Map", value: "FAIRBANKS ALASKA" },
  { id: uuid(), category: "On the Map", value: "SOUTH CAROLINA" },
  { id: uuid(), category: "On the Map", value: "LOUISVILLE KENTUCKY" },
  { id: uuid(), category: "On the Map", value: "NANTUCKET" },
  { id: uuid(), category: "On the Map", value: "SANTA FE NEW MEXICO" },
  { id: uuid(), category: "On the Map", value: "MOJAVE DESERT" },
  { id: uuid(), category: "On the Map", value: "CASPER WYOMING" },
  { id: uuid(), category: "On the Map", value: "TOMBSTONE ARIZONA" },
  { id: uuid(), category: "On the Map", value: "THE BRONX" },
  { id: uuid(), category: "On the Map", value: "THE ITALIAN ALPS" },
  { id: uuid(), category: "On the Map", value: "THE CONTINENT OF ANTARCTICA" },
  { id: uuid(), category: "On the Map", value: "SCOTLAND & WALES" },
  { id: uuid(), category: "On the Map", value: "LAKE SUPERIOR" },
  { id: uuid(), category: "On the Map", value: "MOUNT EVEREST" },
  { id: uuid(), category: "On the Map", value: "SCANDINAVIA" },
  { id: uuid(), category: "On the Map", value: "SUNSET BOULEVARD" },
  { id: uuid(), category: "On the Map", value: "THE PACIFIC OCEAN" },
  { id: uuid(), category: "On the Map", value: "COLUMBUS OHIO" },
  { id: uuid(), category: "On the Map", value: "CARSON CITY NEVADA" },
  { id: uuid(), category: "On the Map", value: "DAYTONA BEACH" },
  { id: uuid(), category: "On the Map", value: "DUBLIN IRELAND" },
  { id: uuid(), category: "On the Map", value: "THE AFRICAN CONTINENT" },
  { id: uuid(), category: "On the Map", value: "DURANGO COLORADO" },
  { id: uuid(), category: "On the Map", value: "SAN DIEGO CALIFORNIA" },
  { id: uuid(), category: "On the Map", value: "SAN ANTONIO TEXAS" },
  { id: uuid(), category: "On the Map", value: "ATLANTA GEORGIA" },
  { id: uuid(), category: "On the Map", value: "THE FRENCH RIVIERA" },
  { id: uuid(), category: "On the Map", value: "HAWAII'S BIG ISLAND" },
  { id: uuid(), category: "On the Map", value: "TOKYO JAPAN" },
  { id: uuid(), category: "On the Map", value: "THE PHILIPPINE ISLANDS" },
  { id: uuid(), category: "On the Map", value: "THAILAND AND VIETNAM" },
  { id: uuid(), category: "On the Map", value: "THE SOUTH CHINA SEA" },
  { id: uuid(), category: "On the Map", value: "HONG KONG" },
  { id: uuid(), category: "On the Map", value: "TAMPA BAY FLORIDA" },
  { id: uuid(), category: "On the Map", value: "TROPIC OF CAPRICORN" },
  { id: uuid(), category: "On the Map", value: "BURINGTON VERMONT" },
  { id: uuid(), category: "On the Map", value: "THE PACIFIC NORTHWEST" },
  { id: uuid(), category: "On the Map", value: "THE COLUMBIA RIVER" },
  { id: uuid(), category: "On the Map", value: "HARTFORD CONNETICUT" },
  { id: uuid(), category: "On the Map", value: "ANCHORAGE ALASKA" },
  { id: uuid(), category: "On the Map", value: "MOUNT HOOD" },
  { id: uuid(), category: "On the Map", value: "DETROIT MICHIGAN" },
  { id: uuid(), category: "On the Map", value: "THE COLORADO RIVER" },
  { id: uuid(), category: "On the Map", value: "FARGO NORTH DAKOTA" },
  { id: uuid(), category: "On the Map", value: "THE MISSOURI RIVER" },
  { id: uuid(), category: "On the Map", value: "SWITZERLAND" },
  { id: uuid(), category: "On the Map", value: "STOCKHOLM SWEDEN" },
  { id: uuid(), category: "On the Map", value: "ISTANBUL TURKEY" },
  { id: uuid(), category: "On the Map", value: "BERLIN GERMANY" },
  { id: uuid(), category: "On the Map", value: "SOUTHEAST ASIA" },
  { id: uuid(), category: "On the Map", value: "BOLIVIA" },
  { id: uuid(), category: "On the Map", value: "NEW HAVEN CONNECTICUT" },
  { id: uuid(), category: "On the Map", value: "VENICE BEACH" },
  { id: uuid(), category: "On the Map", value: "BILLINGS MONTANA" },
  { id: uuid(), category: "On the Map", value: "TUCSON ARIZONA" },
  { id: uuid(), category: "On the Map", value: "BOULDER COLORADO" },
  { id: uuid(), category: "On the Map", value: "TULSA OKLAHOMA" },
  { id: uuid(), category: "On the Map", value: "BISMARCK NORTH DAKOTA" },
  { id: uuid(), category: "On the Map", value: "ANNAPOLIS MARYLAND" },
  { id: uuid(), category: "On the Map", value: "BILOXI MISSISSIPPI" },
  { id: uuid(), category: "On the Map", value: "BOSTON HARBOR" },
  { id: uuid(), category: "On the Map", value: "DALLAS TEXAS" },
  { id: uuid(), category: "On the Map", value: "NEW ENGLAND" },
  { id: uuid(), category: "On the Map", value: "MARTHA'S VINEYARD" },
  { id: uuid(), category: "On the Map", value: "ALBUQUERQUE NEW MEXICO" },
  { id: uuid(), category: "On the Map", value: "SCOTTISH HIGHLANDS" },
  { id: uuid(), category: "On the Map", value: "TOPEKA KANSAS" },
  { id: uuid(), category: "On the Map", value: "IOWA CITY IOWA" },
  { id: uuid(), category: "On the Map", value: "THE SWISS ALPS" },
  { id: uuid(), category: "On the Map", value: "MEMPHIS TENNESSEE" },
  { id: uuid(), category: "On the Map", value: "DOVER DELAWARE" },
  { id: uuid(), category: "On the Map", value: "PORTLAND OREGON" },
  { id: uuid(), category: "On the Map", value: "OAKLAND CALIFORNIA" },
  { id: uuid(), category: "On the Map", value: "CLEVELAND OHIO" },
  { id: uuid(), category: "On the Map", value: "HOUSTON TEXAS" },
  { id: uuid(), category: "On the Map", value: "SANTA BARBARA" },
  { id: uuid(), category: "On the Map", value: "SAN FRANCISCO BAY" },
  { id: uuid(), category: "On the Map", value: "HOLLYWOOD BOULEVARD" },
  { id: uuid(), category: "On the Map", value: "BIG SUR CALIFORNIA" },
  { id: uuid(), category: "On the Map", value: "THE OZARK MOUNTAINS" },
  { id: uuid(), category: "On the Map", value: "ATLANTIC CITY" },
  { id: uuid(), category: "On the Map", value: "SAVANNAH GEORGIA" },
  { id: uuid(), category: "On the Map", value: "MILWAUKEE WISCONSIN" },
  { id: uuid(), category: "On the Map", value: "THE FLORIDA PANHANDLE" },
  { id: uuid(), category: "On the Map", value: "LITTLE ROCK ARKANSAS" },
  { id: uuid(), category: "On the Map", value: "FORT LAUDERDALE" },
  { id: uuid(), category: "On the Map", value: "PALM SPRINGS CALIFORNIA" },
  { id: uuid(), category: "On the Map", value: "OMAHA NEBRASKA" },
  { id: uuid(), category: "On the Map", value: "SPRINGFIELD ILLINOIS" },
  { id: uuid(), category: "On the Map", value: "TIMES SQUARE" },
  { id: uuid(), category: "On the Map", value: "CENTRAL PARK" },
  { id: uuid(), category: "On the Map", value: "THE WESTERN HEMISPHERE" },
  { id: uuid(), category: "On the Map", value: "TEXAS AND ARKANSAS" },
  { id: uuid(), category: "On the Map", value: "GREEN BAY WISCONSIN" },
  { id: uuid(), category: "On the Map", value: "GRAND RAPIDS MICHIGAN" },
  { id: uuid(), category: "On the Map", value: "BAR HARBOR MAINE" },
  { id: uuid(), category: "On the Map", value: "MONTANA AND WYOMING" },
  { id: uuid(), category: "On the Map", value: "ALEXANDRIA VIRGINIA" },
  { id: uuid(), category: "On the Map", value: "ORLANDO FLORIDA" },
]
export default puzzleList
