import { v4 as uuid } from "uuid"
import { Puzzle } from "../../types/Puzzle"
const puzzleList: Puzzle[] = [
  { id: uuid(), category: "People", value: "BOSTON RED SOX" },
  { id: uuid(), category: "People", value: "CHEECH AND CHONG" },
  { id: uuid(), category: "People", value: "KNIGHTS OF COLUMBUS" },
  { id: uuid(), category: "People", value: "DOCTORS AND NURSES" },
  { id: uuid(), category: "People", value: "BASKETBALL TEAM" },
  { id: uuid(), category: "People", value: "ALCOHOLICS ANONYMOUS" },
  { id: uuid(), category: "People", value: "THE NATIONAL GUARD" },
  { id: uuid(), category: "People", value: "GOSPEL SINGERS" },
  { id: uuid(), category: "People", value: "LOS ANGELES DODGERS" },
  { id: uuid(), category: "People", value: "UNITED STATES AIR FORCE" },
  { id: uuid(), category: "People", value: "JUDGE AND JURY" },
  { id: uuid(), category: "People", value: "PART-TIME WORKERS" },
  { id: uuid(), category: "People", value: "BRASS BAND" },
  { id: uuid(), category: "People", value: "KANSAS CITY ROYALS" },
  { id: uuid(), category: "People", value: "UNINSURED MOTORISTS" },
  { id: uuid(), category: "People", value: "MORAL MAJORITY" },
  { id: uuid(), category: "People", value: "FLOWER CHILDREN" },
  { id: uuid(), category: "People", value: "HIGH SCHOOL FOOTBALL TEAM" },
  { id: uuid(), category: "People", value: "NEW YORK METS" },
  { id: uuid(), category: "People", value: "RADIO CITY MUSIC HALL ROCKETTES" },
  { id: uuid(), category: "People", value: "ANTISMOKING GROUP" },
  { id: uuid(), category: "People", value: "NEW YORK RANGERS" },
  { id: uuid(), category: "People", value: "STRING QUARTET" },
  { id: uuid(), category: "People", value: "WEIGHT WATCHERS" },
  { id: uuid(), category: "People", value: "ROMANTIC TRIANGLE" },
  { id: uuid(), category: "People", value: "HIGH SCHOOL SENIORS" },
  { id: uuid(), category: "People", value: "PITTSBURGH PIRATES" },
  { id: uuid(), category: "People", value: "THE GREATEST NAMES IN SPORTS" },
  { id: uuid(), category: "People", value: "TENNESSEE VALLEY AUTHORITY" },
  { id: uuid(), category: "People", value: "JOHN MCENROE AND TATUM O'NEAL" },
  { id: uuid(), category: "People", value: "MEXICAN AMERICANS" },
  { id: uuid(), category: "People", value: "SQUADRON" },
  { id: uuid(), category: "People", value: "GEORGE C SCOTT AS PATTON" },
  { id: uuid(), category: "People", value: "MONTREAL EXPOS" },
  {
    id: uuid(),
    category: "People",
    value: "MALCOM FORBES AND ELIZABETH TAYLOR",
  },
  { id: uuid(), category: "People", value: "BUSINESS ASSOCIATES" },
  { id: uuid(), category: "People", value: "JESUS MARY AND JOESEPH" },
  { id: uuid(), category: "People", value: "EAST GERMANS" },
  {
    id: uuid(),
    category: "People",
    value: "THE EXECTIVE OFFICE OF THE PRESIDENT",
  },
  { id: uuid(), category: "People", value: "THE POWERS THAT BE" },
  { id: uuid(), category: "People", value: "CAVALCADE" },
  { id: uuid(), category: "People", value: "CLEVELAND INDIANS" },
  { id: uuid(), category: "People", value: "MOUNTAIN CLIMBERS" },
  { id: uuid(), category: "People", value: "THE GREAT CHEFS OF EUROPE" },
  { id: uuid(), category: "People", value: "MEN WOMEN AND CHILDREN" },
  { id: uuid(), category: "People", value: "POLAR BEAR CLUB" },
  { id: uuid(), category: "People", value: "AMERICAN HOSTAGES IN LEBANON" },
  { id: uuid(), category: "People", value: "BIBLE STUDY CLASS" },
  { id: uuid(), category: "People", value: "MOVIE CRITICS SISKEL AND EBERT" },
  { id: uuid(), category: "People", value: "JAPANESE AUTOMAKERS" },
  { id: uuid(), category: "People", value: "AIRLINE PILOTS ASSOCIATION" },
  { id: uuid(), category: "People", value: "BOARD OF GOVERNORS" },
  { id: uuid(), category: "People", value: "RED-BLOODED AMERICANS" },
  { id: uuid(), category: "People", value: "CROSBY STILLS & NASH" },
  { id: uuid(), category: "People", value: "CAVALCADE OF STARS" },
  { id: uuid(), category: "People", value: "DAVID & BATHSHEBA" },
  {
    id: uuid(),
    category: "People",
    value: "ACADEMY OF MOTION PICTURE ARTS & SCIENCES",
  },
  { id: uuid(), category: "People", value: "SENATE FINANCE COMMITTEE" },
  { id: uuid(), category: "People", value: "CLOSE FRIENDS" },
  { id: uuid(), category: "People", value: "ADULTS" },
  { id: uuid(), category: "People", value: "BOY SCOUTS OF AMERICA" },
  { id: uuid(), category: "People", value: "GROUPIES" },
  { id: uuid(), category: "People", value: "UMPIRE CATCHER & BATTER" },
  { id: uuid(), category: "People", value: "WORLD CUP CHAMPIONS BRAZIL" },
  { id: uuid(), category: "People", value: "CROWD" },
  { id: uuid(), category: "People", value: "THE JUDGE & THE JURY" },
  { id: uuid(), category: "People", value: "PARTYGOERS" },
  { id: uuid(), category: "People", value: "THE SHERIFF & HIS POSSE" },
  { id: uuid(), category: "People", value: "LAS VEGAS SHOWGIRLS" },
  { id: uuid(), category: "People", value: "MOVERS & SHAKERS" },
  { id: uuid(), category: "People", value: "COHORTS" },
  { id: uuid(), category: "People", value: "MARY & JOSEPH" },
  { id: uuid(), category: "People", value: "FUTURE GENERATIONS" },
  { id: uuid(), category: "People", value: "EXPERTS IN THE FIELD" },
  { id: uuid(), category: "People", value: "FUNK & WAGNALLS" },
  { id: uuid(), category: "People", value: "SEQUESTERED JURY" },
  { id: uuid(), category: "People", value: "OFFENSIVE & DEFENSIVE PLAYERS" },
  { id: uuid(), category: "People", value: "AIR FORCE" },
  { id: uuid(), category: "People", value: "PAUL REISER & HELEN HUNT" },
  { id: uuid(), category: "People", value: "NATIVE NEW YORKERS" },
  { id: uuid(), category: "People", value: "UNIVERSITY GLEE CLUB" },
  { id: uuid(), category: "People", value: "GAME SHOW AUDIENCE" },
  { id: uuid(), category: "People", value: "HUGH DOWNS & BARBARA WALTERS" },
  {
    id: uuid(),
    category: "People",
    value: "WORLD SERIES CHAMPS ATLANTA BRAVES",
  },
  { id: uuid(), category: "People", value: "LOVED ONES" },
  { id: uuid(), category: "People", value: "THE PHARAOHS OF EGYPT" },
  { id: uuid(), category: "People", value: "POLYNESIAN DANCERS" },
  { id: uuid(), category: "People", value: "MARCHING BAND" },
  { id: uuid(), category: "People", value: "CAPACITY CROWD" },
  { id: uuid(), category: "People", value: "JOAN LUNDEN & CHARLES GIBSON" },
  { id: uuid(), category: "People", value: "JAZZ QUARTET" },
  { id: uuid(), category: "People", value: "LOS ANGELES DODGERS" },
  { id: uuid(), category: "People", value: "KURT RUSSELL & GOLDIE HAWN" },
  { id: uuid(), category: "People", value: "ROCK STAR'S GROUPIES" },
  { id: uuid(), category: "People", value: "JUNIORS" },
  { id: uuid(), category: "People", value: "JAZZ MUSICIANS" },
  { id: uuid(), category: "People", value: "AUNTS UNCLES & COUSINS" },
  { id: uuid(), category: "People", value: "FLIGHT CREW" },
  { id: uuid(), category: "People", value: "VIRGOS" },
  { id: uuid(), category: "People", value: "COLONISTS" },
  { id: uuid(), category: "People", value: "STUDY GROUP" },
  { id: uuid(), category: "People", value: "WALK-INS" },
  { id: uuid(), category: "People", value: "SWIMMERS" },
  { id: uuid(), category: "People", value: "FAMILY" },
  { id: uuid(), category: "People", value: "CELEBRITIES" },
  { id: uuid(), category: "People", value: "HOCKEY FANS" },
  { id: uuid(), category: "People", value: "MOMS AND DADS" },
  { id: uuid(), category: "People", value: "TEENAGERS" },
  { id: uuid(), category: "People", value: "EXTENDED FAMILY" },
  { id: uuid(), category: "People", value: "BIRD WATCHERS" },
  { id: uuid(), category: "People", value: "BLUE-RIBBON PANEL" },
  { id: uuid(), category: "People", value: "STRICT VEGETARIANS" },
  { id: uuid(), category: "People", value: "STRING QUARTET" },
  { id: uuid(), category: "People", value: "POSITIVE THINKERS" },
  { id: uuid(), category: "People", value: "CHEERING FANS" },
  {
    id: uuid(),
    category: "People",
    value: "EASTERN AND WESTERN CONFERENCE CHAMPIONS",
  },
  { id: uuid(), category: "People", value: "HIGH ROLLERS" },
  { id: uuid(), category: "People", value: "AUNTS AND UNCLES" },
  { id: uuid(), category: "People", value: "TRAIN PASSENGERS" },
  { id: uuid(), category: "People", value: "HAPPY CAMPERS" },
  { id: uuid(), category: "People", value: "CONCERT TICKET HOLDERS" },
  { id: uuid(), category: "People", value: "BOBSLED TEAM" },
  { id: uuid(), category: "People", value: "NEW ZEALANDERS" },
  { id: uuid(), category: "People", value: "POOLSIDE SUNBATHERS" },
  { id: uuid(), category: "People", value: "SUPER BOWL CHAMPS" },
  { id: uuid(), category: "People", value: "ROWDY CROWD" },
  { id: uuid(), category: "People", value: "HUBBIES" },
  { id: uuid(), category: "People", value: "VIRGOS" },
  { id: uuid(), category: "People", value: "IDENTICAL TWINS" },
  { id: uuid(), category: "People", value: "PING-PONG PLAYERS" },
  { id: uuid(), category: "People", value: "AVID READERS" },
  { id: uuid(), category: "People", value: "BOARD OF TRUSTEES" },
  { id: uuid(), category: "People", value: "REGISTERED VOTERS" },
  { id: uuid(), category: "People", value: "STROLLING MARIACHI BAND" },
  { id: uuid(), category: "People", value: "NEWBORN BABIES" },
  { id: uuid(), category: "People", value: "CHOCOLATE LOVERS" },
  { id: uuid(), category: "People", value: "ADVISORY COMMITTEE" },
  { id: uuid(), category: "People", value: "SORORITY SISTERS" },
  { id: uuid(), category: "People", value: "GRACIOUS HOSTS" },
  { id: uuid(), category: "People", value: "MIDDLE SCHOOL CLASSMATES" },
  { id: uuid(), category: "People", value: "FAMILIAR FACES" },
  { id: uuid(), category: "People", value: "A YOUTH GROUP" },
  { id: uuid(), category: "People", value: "MISS USA AND MISS UNIVERSE" },
  {
    id: uuid(),
    category: "People",
    value: "A COLORFUL STEEL DRUM CALYPSO BAND",
  },
  { id: uuid(), category: "People", value: "SWEEPSTAKES WINNERS" },
  { id: uuid(), category: "People", value: "SKELETON CREW" },
  { id: uuid(), category: "People", value: "LEAGUE OF WOMEN VOTERS" },
  { id: uuid(), category: "People", value: "A BLUE-RIBBON PANEL" },
  { id: uuid(), category: "People", value: "SECOND COUSINS ONCE REMOVED" },
  { id: uuid(), category: "People", value: "REGULAR VIEWERS" },
  { id: uuid(), category: "People", value: "THE FOLKS BACK HOME" },
  { id: uuid(), category: "People", value: "CHOIRBOYS" },
  { id: uuid(), category: "People", value: "SKIPPER FIRST MATE & SECOND MATE" },
  { id: uuid(), category: "People", value: "DIE-HARD FANS" },
  { id: uuid(), category: "People", value: "FAMOUS RENAISSANCE ARTISTS" },
  { id: uuid(), category: "People", value: "SUN WORSHIPERS" },
  { id: uuid(), category: "People", value: "OUT-OF-TOWN GUESTS" },
  { id: uuid(), category: "People", value: "SCREAMING ROLLER COASTER RIDERS" },
  { id: uuid(), category: "People", value: "PROM KING & QUEEN" },
  { id: uuid(), category: "People", value: "BRIDESMAIDS & GROOMSMEN" },
  { id: uuid(), category: "People", value: "CELEBRITY LOOK-ALIKES" },
  { id: uuid(), category: "People", value: "OUR NEIGHBORS TO THE NORTH" },
  { id: uuid(), category: "People", value: "THE RANK AND FILE" },
  { id: uuid(), category: "People", value: "LANDLUBBERS" },
  { id: uuid(), category: "People", value: "BEACH BUMS" },
  { id: uuid(), category: "People", value: "BUSINESS TRAVELERS" },
  { id: uuid(), category: "People", value: "REDHEADS WITH FRECKLES" },
  { id: uuid(), category: "People", value: "EXTENDED FAMILY" },
  { id: uuid(), category: "People", value: "SOCCER MOMS" },
  { id: uuid(), category: "People", value: "JAZZ LEGENDS" },
  { id: uuid(), category: "People", value: "PROUD PARENTS" },
  { id: uuid(), category: "People", value: "LONGTIME RIVALS" },
  { id: uuid(), category: "People", value: "HAWAIIANS" },
  { id: uuid(), category: "People", value: "FLAMENCO DANCERS" },
  { id: uuid(), category: "People", value: "EXPECTANT FATHERS" },
  { id: uuid(), category: "People", value: "HIGH SCHOOL SWEETHEARTS" },
  { id: uuid(), category: "People", value: "FRIENDS OF FRIENDS" },
  { id: uuid(), category: "People", value: "ORCHESTRA'S BRASS SECTION" },
  { id: uuid(), category: "People", value: "FOSTER PARENTS" },
  { id: uuid(), category: "People", value: "COLLEGE INTERNS" },
  { id: uuid(), category: "People", value: "GIFTED CHILDREN" },
  { id: uuid(), category: "People", value: "HELPFUL SALES STAFF" },
  { id: uuid(), category: "People", value: "FRIENDS AND NEIGHBORS" },
  { id: uuid(), category: "People", value: "STAGE MOTHERS" },
  { id: uuid(), category: "People", value: "PEP SQUAD" },
  { id: uuid(), category: "People", value: "GOLF FORSOME" },
  { id: uuid(), category: "People", value: "PARENTS OF TWINS" },
  { id: uuid(), category: "People", value: "TENANTS AND LANDLORDS" },
  { id: uuid(), category: "People", value: "NOSY NEIGHBORS" },
  { id: uuid(), category: "People", value: "HIKERS BOATERS AND FISHERMEN" },
  { id: uuid(), category: "People", value: "IMMEDIATE FAMILY" },
  { id: uuid(), category: "People", value: "THE BEST AND THE BRIGHTEST" },
  { id: uuid(), category: "People", value: "YOUNG HIP CROWD" },
  { id: uuid(), category: "People", value: "DECORATED VETERANS" },
  { id: uuid(), category: "People", value: "YOUTH CHORUS" },
  { id: uuid(), category: "People", value: "EARLY BIRDS & NIGHT OWLS" },
  { id: uuid(), category: "People", value: "MOTORCYCLE ENTHUSIASTS" },
  { id: uuid(), category: "People", value: "ADOPTIVE PARENTS" },
  { id: uuid(), category: "People", value: "ANIMAL LOVERS" },
  { id: uuid(), category: "People", value: "BARGAIN HUNTERS" },
  { id: uuid(), category: "People", value: "LIFELONG FRIENDS" },
  { id: uuid(), category: "People", value: "COLLEGE ROOMMATES" },
  { id: uuid(), category: "People", value: "SCUBA DIVERS AND SNORKELERS" },
  { id: uuid(), category: "People", value: "OHIOANS" },
  { id: uuid(), category: "People", value: "RING BEARER & FLOWER GIRL" },
  { id: uuid(), category: "People", value: "GOLF PARTNERS" },
  { id: uuid(), category: "People", value: "BUSINESS PARTNERS" },
  { id: uuid(), category: "People", value: "TWINS AND TRIPLETS" },
  { id: uuid(), category: "People", value: "FIRST-TIME HOMEBUYERS" },
  { id: uuid(), category: "People", value: "FRIENDS AND FAMILY" },
  { id: uuid(), category: "People", value: "BEAUTIFUL BRAZILIAN SUPERMODELS" },
  { id: uuid(), category: "People", value: "BRITISH SUBJECTS" },
  { id: uuid(), category: "People", value: "TRAVELING COMPANIONS" },
  { id: uuid(), category: "People", value: "THE POWERS THAT BE" },
  { id: uuid(), category: "People", value: "STUDENT COUNCIL" },
  { id: uuid(), category: "People", value: "HOUSEGUESTS" },
  { id: uuid(), category: "People", value: "BRAZILIANS" },
  { id: uuid(), category: "People", value: "COMPARISON SHOPPERS" },
  { id: uuid(), category: "People", value: "DISTANT COUSINS" },
  { id: uuid(), category: "People", value: "SEASONED TRAVELERS" },
  { id: uuid(), category: "People", value: "LOYAL CUSTOMERS" },
  { id: uuid(), category: "People", value: "ROLLER COASTER ENTHUSIASTS" },
  { id: uuid(), category: "People", value: "FRATERNAL TWINS" },
  { id: uuid(), category: "People", value: "ITALIAN OPERA SINGERS" },
  { id: uuid(), category: "People", value: "THE BIG BRASS" },
  { id: uuid(), category: "People", value: "PARTYGOERS" },
  { id: uuid(), category: "People", value: "CELEBRITY COUPLE" },
  { id: uuid(), category: "People", value: "LIVELY CALYPSO BAND" },
  { id: uuid(), category: "People", value: "LEADERS AND FOLLOWERS" },
  { id: uuid(), category: "People", value: "VISITING TEAM" },
  { id: uuid(), category: "People", value: "WIVES" },
  { id: uuid(), category: "People", value: "MOVERS AND SHAKERS" },
  { id: uuid(), category: "People", value: "DEVOTED TV VIEWERS" },
  { id: uuid(), category: "People", value: "PART-TIME EMPLOYEES" },
  { id: uuid(), category: "People", value: "THE CAPTAIN AND CREW" },
  { id: uuid(), category: "People", value: "AMATEUR ATHLETES" },
  { id: uuid(), category: "People", value: "HIGH ACHIEVERS" },
  { id: uuid(), category: "People", value: "EXPERIENCED HORSEBACK RIDERS" },
  { id: uuid(), category: "People", value: "PET OWNERS" },
  { id: uuid(), category: "People", value: "BOY SCOUTS" },
  { id: uuid(), category: "People", value: "JUDGE AND JURY" },
  { id: uuid(), category: "People", value: "DUKE AND DUCHESS" },
  { id: uuid(), category: "People", value: "SKILLED CRAFTSMAN" },
  { id: uuid(), category: "People", value: "SWEDES AND NORWEGIANS" },
  { id: uuid(), category: "People", value: "DARING AND GRACEFUL CLIFF DIVERS" },
  { id: uuid(), category: "People", value: "THRILL SEEKERS" },
  { id: uuid(), category: "People", value: "SIGNIFICANT OTHERS" },
  { id: uuid(), category: "People", value: "BEAUTY PAGEANT CONTESTANTS" },
  { id: uuid(), category: "People", value: "TREASURE HUNTERS" },
  { id: uuid(), category: "People", value: "EVERYDAY HEROES" },
  { id: uuid(), category: "People", value: "ABSOLUTE BEGINNERS" },
  { id: uuid(), category: "People", value: "CHINESE ACROBATS" },
  { id: uuid(), category: "People", value: "CHILDHOOD SWEETHEARTS" },
  { id: uuid(), category: "People", value: "EUROPEAN ROYALTY" },
  { id: uuid(), category: "People", value: "LOYAL FANS" },
  { id: uuid(), category: "People", value: "STROLLING MARIACHI BAND" },
  { id: uuid(), category: "People", value: "OPTIMISTS" },
  { id: uuid(), category: "People", value: "MISMATCHED ROOMMATES" },
  { id: uuid(), category: "People", value: "OLYMPIC ATHLETES" },
  { id: uuid(), category: "People", value: "SUMO WRESTLERS" },
  { id: uuid(), category: "People", value: "COLLEGE ROCK BAND" },
  { id: uuid(), category: "People", value: "NEWBORN BABIES" },
  { id: uuid(), category: "People", value: "TWIN BOYS" },
  { id: uuid(), category: "People", value: "FIRST-TIME VISITORS" },
  { id: uuid(), category: "People", value: "IOWANS" },
  { id: uuid(), category: "People", value: "TENNIS PARTNERS" },
  { id: uuid(), category: "People", value: "SECOND COUSINS" },
  { id: uuid(), category: "People", value: "ELITE ATHLETES" },
  { id: uuid(), category: "People", value: "MEMBERS OF PARLIAMENT" },
  { id: uuid(), category: "People", value: "OUR NEIGHBORS" },
  { id: uuid(), category: "People", value: "NAVAL OFFICERS" },
  { id: uuid(), category: "People", value: "YOUTH GROUP" },
  { id: uuid(), category: "People", value: "EXPERT DRIVERS" },
  { id: uuid(), category: "People", value: "EARLY BIRDS & BARGAIN HUNTERS" },
  { id: uuid(), category: "People", value: "BARBERSHOP QUARTET" },
  { id: uuid(), category: "People", value: "LAST-MINUTE SHOPPERS" },
  { id: uuid(), category: "People", value: "SMILING CHILDREN" },
  { id: uuid(), category: "People", value: "INTROVERTS & EXTROVERTS" },
  { id: uuid(), category: "People", value: "CIRCUS PERFORMERS" },
  { id: uuid(), category: "People", value: "FIRE DANCERS AT A LUAU" },
  { id: uuid(), category: "People", value: "DRIVERS AND PASSENGERS" },
  { id: uuid(), category: "People", value: "INFANTS & TODDLERS" },
  { id: uuid(), category: "People", value: "SAFETY PATROL" },
  { id: uuid(), category: "People", value: "HALL OF FAMERS" },
  { id: uuid(), category: "People", value: "GRANDKIDS" },
  { id: uuid(), category: "People", value: "TIGHT-KNIT GROUP" },
  { id: uuid(), category: "People", value: "VARSITY SQUAD" },
  { id: uuid(), category: "People", value: "KISSING COUSINS" },
  { id: uuid(), category: "People", value: "THE IN-LAWS" },
  { id: uuid(), category: "People", value: "WELCOMING COMMITTE" },
  { id: uuid(), category: "People", value: "ROYAL CANADIAN MOUNTED POLICE" },
  { id: uuid(), category: "People", value: "DEDICATED VIEWERS" },
  { id: uuid(), category: "People", value: "FUTURE GENERATIONS" },
  {
    id: uuid(),
    category: "People",
    value: "FRATERNITY BROTHERS & SORORITY SISTERS",
  },
  { id: uuid(), category: "People", value: "HAPPY NEWLYWEDS" },
  { id: uuid(), category: "People", value: "COLLEGE FOOTBALL TEAM" },
  { id: uuid(), category: "People", value: "FRIENDLY NEIGHBORS" },
  { id: uuid(), category: "People", value: "HIGH ROLLERS" },
  { id: uuid(), category: "People", value: "CHEERING SECTION" },
  { id: uuid(), category: "People", value: "OUT-OF-TOWN VISITORS" },
  { id: uuid(), category: "People", value: "TASK FORCE" },
  { id: uuid(), category: "People", value: "CHOSEN FEW" },
  { id: uuid(), category: "People", value: "CHOCOLATE LOVERS" },
  { id: uuid(), category: "People", value: "INCOMING FRESHMEN" },
  { id: uuid(), category: "People", value: "DEBATE TEAM" },
  { id: uuid(), category: "People", value: "RED SOX NATION" },
  { id: uuid(), category: "People", value: "MARATHON RUNNERS" },
  { id: uuid(), category: "People", value: "WHIZ KIDS" },
  { id: uuid(), category: "People", value: "YOUNG COUPLE" },
  { id: uuid(), category: "People", value: "RED SOX NATION" },
  { id: uuid(), category: "People", value: "MARATHON RUNNERS" },
  { id: uuid(), category: "People", value: "WHIZ KIDS" },
  { id: uuid(), category: "People", value: "YOUNG COUPLE" },
  { id: uuid(), category: "People", value: "BOBSLED TEAM" },
  { id: uuid(), category: "People", value: "HIP CROWD" },
  { id: uuid(), category: "People", value: "FORMER PRESIDENTS" },
  { id: uuid(), category: "People", value: "RUGBY TEAM" },
  { id: uuid(), category: "People", value: "JET-SETTERS" },
  { id: uuid(), category: "People", value: "PROUD PARENTS" },
  { id: uuid(), category: "People", value: "HIGH SCHOOL SWEETHARTS" },
  { id: uuid(), category: "People", value: "MARCHING BAND" },
  { id: uuid(), category: "People", value: "JUNIORS & SENIORS" },
  { id: uuid(), category: "People", value: "DORM ROOMATES" },
  { id: uuid(), category: "People", value: "GIRL SCOUT TROOP" },
  { id: uuid(), category: "People", value: "THE GOOD GUYS" },
  { id: uuid(), category: "People", value: "COLLEGE STUDENTS" },
  { id: uuid(), category: "People", value: "WORLD LEADERS" },
  { id: uuid(), category: "People", value: "OPTIMISTS AND PESSIMISTS" },
  { id: uuid(), category: "People", value: "WORTHY OPPONENTS" },
  { id: uuid(), category: "People", value: "JUGGLERS AND CLOWNS" },
  { id: uuid(), category: "People", value: "FRIENDS IN HIGH PLACES" },
  { id: uuid(), category: "People", value: "SCUBA DIVERS AND SNORKELERS" },
  { id: uuid(), category: "People", value: "EXTENDED FAMILY" },
  { id: uuid(), category: "People", value: "YOUNG FOLKS" },
  { id: uuid(), category: "People", value: "TWINS AND TRIPLETS" },
  { id: uuid(), category: "People", value: "TRAVELING COMPANIONS" },
  { id: uuid(), category: "People", value: "CHRISTMAS CAROLERS" },
  { id: uuid(), category: "People", value: "AUNTS AND UNCLES" },
  { id: uuid(), category: "People", value: "TWELVE DRUMMERS DRUMMING" },
  { id: uuid(), category: "People", value: "DANCERS WEARING GLASS SKIRTS" },
  { id: uuid(), category: "People", value: "YOUTH OF TODAY" },
  { id: uuid(), category: "People", value: "GIVERS AND TAKERS" },
  { id: uuid(), category: "People", value: "THE WHOLE FAMILY" },
  { id: uuid(), category: "People", value: "JAZZ BAND" },
  { id: uuid(), category: "People", value: "HISTORICAL FIGURES" },
  { id: uuid(), category: "People", value: "WINNING TEAM" },
  { id: uuid(), category: "People", value: "JUNIOR VARSITY SQUAD" },
  { id: uuid(), category: "People", value: "BUSINESS PARTNERS" },
  { id: uuid(), category: "People", value: "EARLY BIRDS" },
  { id: uuid(), category: "People", value: "ABSOLUTE BEGINNERS" },
  { id: uuid(), category: "People", value: "CHILDHOOD SWEETHEARTS" },
  { id: uuid(), category: "People", value: "ALL-STAR TEAM" },
  { id: uuid(), category: "People", value: "FLOWER CHILDREN" },
  { id: uuid(), category: "People", value: "DISTANT COUSINS" },
  { id: uuid(), category: "People", value: "HITCHHIKERS" },
  { id: uuid(), category: "People", value: "PITCHER & CATCHER" },
  { id: uuid(), category: "People", value: "COLLEGE ROOMMATES" },
  { id: uuid(), category: "People", value: "POETS & WRITERS" },
  { id: uuid(), category: "People", value: "JUNIORS & SENIORS" },
  { id: uuid(), category: "People", value: "UNITED STATES SENATORS" },
  { id: uuid(), category: "People", value: "DOUBLES PARTNERS" },
  { id: uuid(), category: "People", value: "UNIVERSITY MARCHING BAND" },
  { id: uuid(), category: "People", value: "HAPPY CAMPERS" },
  { id: uuid(), category: "People", value: "FRIENDS AND FAMILY" },
  { id: uuid(), category: "People", value: "MARRIED COUPLE" },
  { id: uuid(), category: "People", value: "FOOTBALL PLAYERS" },
  { id: uuid(), category: "People", value: "NEWLYWED COUPLE" },
  { id: uuid(), category: "People", value: "AMAZING FIRE DANCERS AT THE LUAU" },
  { id: uuid(), category: "People", value: "NEW NEIGHBORS" },
  { id: uuid(), category: "People", value: "HEROES AND VILLANS" },
  { id: uuid(), category: "People", value: "PEP SQUAD" },
  { id: uuid(), category: "People", value: "LEGENDARY JAZZ MUSICIANS" },
  { id: uuid(), category: "People", value: "STARS AND STARLETS" },
  { id: uuid(), category: "People", value: "FRIENDLY CO-WORKERS" },
  { id: uuid(), category: "People", value: "OUR NEIGHBORS TO THE NORTH" },
  { id: uuid(), category: "People", value: "THE WHOLE GANG" },
  {
    id: uuid(),
    category: "People",
    value: "THE BEST SCUBA INSTRUCTORS AROUND",
  },
  { id: uuid(), category: "People", value: "KIDS OF ALL AGES" },
  { id: uuid(), category: "People", value: "VISITING TEAM" },
  { id: uuid(), category: "People", value: "LIFELONG FRIENDS" },
  { id: uuid(), category: "People", value: "PANEL OF JUDGES" },
  { id: uuid(), category: "People", value: "PRINCE AND PRINCESS" },
  { id: uuid(), category: "People", value: "BARBERSHOP QUARTET" },
  { id: uuid(), category: "People", value: "FRESHMAN AND SOPHOMORES" },
  { id: uuid(), category: "People", value: "COMMUNITY LEADERS" },
  { id: uuid(), category: "People", value: "PERFECT STRANGERS" },
  { id: uuid(), category: "People", value: "RING BEARER & FLOWER GIRL" },
  { id: uuid(), category: "People", value: "AMATEUR ATHLETES" },
  { id: uuid(), category: "People", value: "FRIENDLY FLIGHT ATTENDANTS" },
  { id: uuid(), category: "People", value: "BROTHERS & SISTERS" },
  { id: uuid(), category: "People", value: "CLOSE-KNIT FAMILY" },
  { id: uuid(), category: "People", value: "STUDENT COUNCIL" },
  { id: uuid(), category: "People", value: "SUMO WRESTLER" },
  { id: uuid(), category: "People", value: "SOLDIERS & SAILORS" },
  { id: uuid(), category: "People", value: "DYNAMIC DUO" },
  { id: uuid(), category: "People", value: "ACTORS AND ACTRESSES" },
  { id: uuid(), category: "People", value: "AUNTS UNCLES AND COUSINS" },
  { id: uuid(), category: "People", value: "WIFE AND KIDS" },
  { id: uuid(), category: "People", value: "GIGGLING GIRLS" },
  { id: uuid(), category: "People", value: "TEN LORDS A-LEAPING" },
  { id: uuid(), category: "People", value: "JAM-PACKED CROWD" },
  { id: uuid(), category: "People", value: "WELCOMING COMMITTEE" },
  { id: uuid(), category: "People", value: "WEDDING BAND" },
  { id: uuid(), category: "People", value: "DAREDEVIL CLIFF DIVERS" },
  { id: uuid(), category: "People", value: "MY CLOSEST FRIENDS" },
  { id: uuid(), category: "People", value: "MARCHING BAND" },
  { id: uuid(), category: "People", value: "SEASON TICKET HOLDERS" },
  { id: uuid(), category: "People", value: "DEFENDING CHAMPION" },
  { id: uuid(), category: "People", value: "CENTERS FORWARDS AND GUARDS" },
  { id: uuid(), category: "People", value: "HALL OF FAME LEGENDS" },
  { id: uuid(), category: "People", value: "TENNIS PARTNERS" },
  { id: uuid(), category: "People", value: "HIGH SCHOOL SWEETHEARTS" },
  { id: uuid(), category: "People", value: "CHEERING SECTION" },
  { id: uuid(), category: "People", value: "GOLF FOURSOME" },
  { id: uuid(), category: "People", value: "GUESTS AT THE ROYAL PALACE" },
  { id: uuid(), category: "People", value: "SEASONED TRAVELERS" },
  { id: uuid(), category: "People", value: "SUNBATHER" },
  { id: uuid(), category: "People", value: "WORLD LEADERS" },
  { id: uuid(), category: "People", value: "VICTORIOUS PLAYERS" },
  { id: uuid(), category: "People", value: "BOSOM BUDDIES" },
  { id: uuid(), category: "People", value: "LIMOUSINE PASSENGERS" },
  { id: uuid(), category: "People", value: "HOME VIEWERS" },
  { id: uuid(), category: "People", value: "TWINS AND TRIPLETS" },
  { id: uuid(), category: "People", value: "SOCCER MOMS" },
]
export default puzzleList
