import { v4 as uuid } from "uuid"
import { Puzzle } from "../../types/Puzzle"
const puzzleList: Puzzle[] = [
  { id: uuid(), category: "Person", value: "BURT LANCASTER" },
  { id: uuid(), category: "Person", value: "SPENCER TRACY" },
  { id: uuid(), category: "Person", value: "RODNEY DANGERFIELD" },
  { id: uuid(), category: "Person", value: "UNITED STATES AMBASSADOR" },
  { id: uuid(), category: "Person", value: "FIVE-STAR GENERAL" },
  { id: uuid(), category: "Person", value: "GEORGE C SCOTT" },
  { id: uuid(), category: "Person", value: "JERRY LEWIS" },
  { id: uuid(), category: "Person", value: "ROCK HUDSON" },
  { id: uuid(), category: "Person", value: "CHAPERON" },
  { id: uuid(), category: "Person", value: "WOODROW WILSON" },
  { id: uuid(), category: "Person", value: "ALEXANDER GRAHAM BELL" },
  { id: uuid(), category: "Person", value: "LEONARD NIMOY" },
  { id: uuid(), category: "Person", value: "SCREWBALL" },
  { id: uuid(), category: "Person", value: "STEPHANIE POWERS" },
  { id: uuid(), category: "Person", value: "WARREN BEATTY" },
  { id: uuid(), category: "Person", value: "FASHION PLATE" },
  { id: uuid(), category: "Person", value: "THE LIFE OF THE PARTY" },
  { id: uuid(), category: "Person", value: "FAYE DUNAWAY" },
  { id: uuid(), category: "Person", value: "MICHELE LEE" },
  { id: uuid(), category: "Person", value: "CAPTAIN OF THE FOOTBALL TEAM" },
  { id: uuid(), category: "Person", value: "LOU RAWLS" },
  { id: uuid(), category: "Person", value: "BRUCE SPRINGSTEEN" },
  { id: uuid(), category: "Person", value: "RINGMASTER" },
  { id: uuid(), category: "Person", value: "STEVE MARTIN" },
  { id: uuid(), category: "Person", value: "RAVISHING BEAUTY" },
  { id: uuid(), category: "Person", value: "DRILL SERGEANT" },
  { id: uuid(), category: "Person", value: "FRANK SINATRA" },
  { id: uuid(), category: "Person", value: "PRIMA DONNA" },
  { id: uuid(), category: "Person", value: "FAMILY DOCTOR" },
  { id: uuid(), category: "Person", value: "STARTING PITCHER" },
  { id: uuid(), category: "Person", value: "LIZA MINNELLI" },
  { id: uuid(), category: "Person", value: "BRYANT GUMBEL" },
  { id: uuid(), category: "Person", value: "IRATE CUSTOMER" },
  { id: uuid(), category: "Person", value: "NEW YORK CABBY" },
  { id: uuid(), category: "Person", value: "DICK CAVETT" },
  { id: uuid(), category: "Person", value: "JOE NAMATH" },
  { id: uuid(), category: "Person", value: "JANE PAULEY" },
  { id: uuid(), category: "Person", value: "CHARLTON HESTON" },
  { id: uuid(), category: "Person", value: "MARILYN MONROE LOOK-ALIKE" },
  { id: uuid(), category: "Person", value: "DEBBIE REYNOLDS" },
  { id: uuid(), category: "Person", value: "SUGAR DADDY" },
  { id: uuid(), category: "Person", value: "THE STAR OF THE SHOW" },
  { id: uuid(), category: "Person", value: "MARLA GIBBS" },
  { id: uuid(), category: "Person", value: "PRINCESS CAROLINE OF MONACO" },
  { id: uuid(), category: "Person", value: "JAMES GARNER" },
  { id: uuid(), category: "Person", value: "ARSENIO HALL" },
  { id: uuid(), category: "Person", value: "CARROLL O'CONNOR" },
  { id: uuid(), category: "Person", value: "PABLO PICASSO" },
  { id: uuid(), category: "Person", value: "GOOD WILL AMBASSADOR" },
  { id: uuid(), category: "Person", value: "YOKO ONO" },
  { id: uuid(), category: "Person", value: "WILLIE MAYS" },
  { id: uuid(), category: "Person", value: "REDD FOXX" },
  { id: uuid(), category: "Person", value: "DENNIS QUAID" },
  { id: uuid(), category: "Person", value: "JIMMY STEWART" },
  { id: uuid(), category: "Person", value: "COUNTRY MUSIC SINGER" },
  { id: uuid(), category: "Person", value: "GROWN-UP" },
  { id: uuid(), category: "Person", value: "MISCHIEF MAKER" },
  { id: uuid(), category: "Person", value: "MISSIONARY" },
  { id: uuid(), category: "Person", value: "MONARCH" },
  { id: uuid(), category: "Person", value: "SCOTTISH BAGPIPER" },
  { id: uuid(), category: "Person", value: "A FLIRT" },
  { id: uuid(), category: "Person", value: "VAGABOND" },
  { id: uuid(), category: "Person", value: "MIKHAIL GORBACHEV" },
  {
    id: uuid(),
    category: "Person",
    value: "PEANUTS CARTOONIST CHARLES SCHULZ",
  },
  { id: uuid(), category: "Person", value: "CHOIRBOY" },
  { id: uuid(), category: "Person", value: "DESIGNATED DRIVER" },
  { id: uuid(), category: "Person", value: "DICTATOR" },
  { id: uuid(), category: "Person", value: "HOCKEY PLAYER" },
  { id: uuid(), category: "Person", value: "ALEX TREBEK" },
  { id: uuid(), category: "Person", value: "MARVIN HAMLISCH" },
  { id: uuid(), category: "Person", value: "PRIMA BALLERINA" },
  { id: uuid(), category: "Person", value: "MALCOLM FORBES" },
  { id: uuid(), category: "Person", value: "PICKLE-PUSS" },
  { id: uuid(), category: "Person", value: "GENERAL COLIN POWELL" },
  { id: uuid(), category: "Person", value: "COVER GIRL" },
  { id: uuid(), category: "Person", value: "SIDEKICK" },
  { id: uuid(), category: "Person", value: "JAZZ GREAT DIZZY GILLESPIE" },
  { id: uuid(), category: "Person", value: "NATURALIZED AMERICAN CITIZEN" },
  { id: uuid(), category: "Person", value: "VIOLIN VIRTUOSO" },
  { id: uuid(), category: "Person", value: "VINCENT VAN GOGH" },
  { id: uuid(), category: "Person", value: "TEXAS BILLIONAIRE ROSS PEROT" },
  { id: uuid(), category: "Person", value: "OLYMPIC DISCUS THROWER" },
  { id: uuid(), category: "Person", value: "ARKANSAS GOVERNOR BILL CLINTON" },
  { id: uuid(), category: "Person", value: "ELIGIBLE BACHELOR" },
  { id: uuid(), category: "Person", value: "GRANDFATHER" },
  { id: uuid(), category: "Person", value: "MADONNA" },
  { id: uuid(), category: "Person", value: "PR" },
  { id: uuid(), category: "Person", value: "GOURMET" },
  { id: uuid(), category: "Person", value: "TONY BENNETT" },
  { id: uuid(), category: "Person", value: "SUPERMODEL CINDY CRAWFORD" },
  { id: uuid(), category: "Person", value: "HOT SHOT" },
  { id: uuid(), category: "Person", value: "RUSH LIMBAUGH" },
  { id: uuid(), category: "Person", value: "ACTOR WESLEY SNIPES" },
  { id: uuid(), category: "Person", value: "NFL COACH DON SHULA" },
  { id: uuid(), category: "Person", value: "BASKETBALL STAR SHAQUILLE O'NEAL" },
  { id: uuid(), category: "Person", value: "OLYMPIC SKATER NANCY KERRIGAN" },
  {
    id: uuid(),
    category: "Person",
    value: "ACADEMY AWARD WINNER HOLLY HUNTER",
  },
  { id: uuid(), category: "Person", value: "JAZZ LEGEND MILES DAVIS" },
  { id: uuid(), category: "Person", value: "BEAU BRIDGES" },
  { id: uuid(), category: "Person", value: "BLUES SINGER BILLIE HOLIDAY" },
  { id: uuid(), category: "Person", value: "DANIEL DAY-LEWIS" },
  { id: uuid(), category: "Person", value: "\u00a0CHARLIE O'DONNELL" },
  { id: uuid(), category: "Person", value: "PUBLIC SPEAKER" },
  { id: uuid(), category: "Person", value: "COMEDIAN PAULA POUNDSTONE" },
  { id: uuid(), category: "Person", value: "OSCAR WINNER TOM HANKS" },
  { id: uuid(), category: "Person", value: "ENGLISH ACTRESS EMMA THOMPSON " },
  { id: uuid(), category: "Person", value: "BRIDEGROOM" },
  { id: uuid(), category: "Person", value: "TOMMY LEE JONES" },
  {
    id: uuid(),
    category: "Person",
    value: "FORMER FBI DIRECTOR J EDGAR HOOVER",
  },
  { id: uuid(), category: "Person", value: "JOHN MALKOVICH" },
  { id: uuid(), category: "Person", value: "SAXOPHONE PLAYER" },
  { id: uuid(), category: "Person", value: "HUNK" },
  { id: uuid(), category: "Person", value: "EDDIE MURPHY" },
  { id: uuid(), category: "Person", value: "MEG RYAN" },
  { id: uuid(), category: "Person", value: "WHOOPI GOLDBERG" },
  { id: uuid(), category: "Person", value: "NEWS ANCHOR DIANE SAWYER" },
  { id: uuid(), category: "Person", value: "VISIONARY" },
  { id: uuid(), category: "Person", value: "HOME IMPROVEMENT STAR TIM ALLEN" },
  { id: uuid(), category: "Person", value: "GURU" },
  { id: uuid(), category: "Person", value: "BRUCE WILLIS" },
  { id: uuid(), category: "Person", value: "SINGER BOZ SCAGGS" },
  { id: uuid(), category: "Person", value: "ROCK ICON JIMI HENDRIX" },
  { id: uuid(), category: "Person", value: "DUSTIN HOFFMAN" },
  { id: uuid(), category: "Person", value: "BLUES SINGER B B KING" },
  { id: uuid(), category: "Person", value: "KING HUSSEIN OF JORDAN" },
  {
    id: uuid(),
    category: "Person",
    value: "HEAVYWEIGHT CHAMPION GEORGE FOREMAN",
  },
  { id: uuid(), category: "Person", value: "CLOWN" },
  { id: uuid(), category: "Person", value: "JODIE FOSTER" },
  { id: uuid(), category: "Person", value: "PARTY ANIMAL" },
  { id: uuid(), category: "Person", value: "JEAN-CLAUDE VAN DAMME" },
  { id: uuid(), category: "Person", value: "COWBOY" },
  {
    id: uuid(),
    category: "Person",
    value: "SPEAKER OF THE HOUSE NEWT GINGRICH",
  },
  { id: uuid(), category: "Person", value: "SOPHIA LOREN" },
  { id: uuid(), category: "Person", value: "CHARLIE SHEEN" },
  { id: uuid(), category: "Person", value: "MIDDLEMAN" },
  { id: uuid(), category: "Person", value: "AMBULANCE CHASER" },
  { id: uuid(), category: "Person", value: "GRAMMY WINNER SHERYL CROW" },
  { id: uuid(), category: "Person", value: "COMEDIAN ELLEN DEGENERES" },
  { id: uuid(), category: "Person", value: "OSCAR WINNER JESSICA LANGE" },
  { id: uuid(), category: "Person", value: "SUPERMODEL ELLE MACPHERSON" },
  { id: uuid(), category: "Person", value: "BRAD PITT" },
  { id: uuid(), category: "Person", value: "JUNK FOOD JUNKIE" },
  { id: uuid(), category: "Person", value: "CHILD PRODIGY" },
  { id: uuid(), category: "Person", value: "DESIGNATED DRIVER" },
  { id: uuid(), category: "Person", value: "AUTHOR MICHAEL CRICHTON" },
  { id: uuid(), category: "Person", value: "CHOIRBOY" },
  { id: uuid(), category: "Person", value: "NORMAN ROCKWELL" },
  { id: uuid(), category: "Person", value: "OPERA STAR PLACIDO DOMINGO" },
  { id: uuid(), category: "Person", value: "AN UNBEATABLE COMBINATION" },
  { id: uuid(), category: "Person", value: "A PILLAR OF THE COMMUNITY" },
  { id: uuid(), category: "Person", value: "PUZZLE SOLVER" },
  { id: uuid(), category: "Person", value: "CHRISTIAN SLATER" },
  { id: uuid(), category: "Person", value: "ASTRONOMER CARL SAGAN" },
  { id: uuid(), category: "Person", value: "OPTIMIST" },
  { id: uuid(), category: "Person", value: "SIR ISAAC NEWTON" },
  { id: uuid(), category: "Person", value: "MERYL STREEP" },
  { id: uuid(), category: "Person", value: "FOLK HERO" },
  { id: uuid(), category: "Person", value: "INDIVIDUAL" },
  { id: uuid(), category: "Person", value: "AUTHOR HENRY DAVID THOREAU" },
  { id: uuid(), category: "Person", value: "COMEDIAN DANA CARVEY" },
  { id: uuid(), category: "Person", value: "ROBERT REDFORD" },
  { id: uuid(), category: "Person", value: "TRACK LEGEND JESSE OWENS" },
  { id: uuid(), category: "Person", value: "LEADING CONTENDER" },
  { id: uuid(), category: "Person", value: "NOTED AUTHORITY" },
  { id: uuid(), category: "Person", value: "ALBERT EINSTEIN" },
  { id: uuid(), category: "Person", value: "RETURNING CHAMPION" },
  { id: uuid(), category: "Person", value: "HEISMAN TROPHY WINNER" },
  { id: uuid(), category: "Person", value: "SERGEANT AT ARMS" },
  { id: uuid(), category: "Person", value: "SIDEKICK" },
  { id: uuid(), category: "Person", value: "ROLE MODEL" },
  { id: uuid(), category: "Person", value: "HEAD FOOTBALL COACH" },
  { id: uuid(), category: "Person", value: "GUEST LECTURER" },
  { id: uuid(), category: "Person", value: "ROSE PARADE GRAND MARSHAL" },
  { id: uuid(), category: "Person", value: "RAFFLE WINNER" },
  { id: uuid(), category: "Person", value: "SAXOPHONIST" },
  { id: uuid(), category: "Person", value: "FIGURE SKATER" },
  { id: uuid(), category: "Person", value: "NAVIGATOR" },
  { id: uuid(), category: "Person", value: "HOUSE SITTER" },
  { id: uuid(), category: "Person", value: "A PAYING CUSTOMER" },
  { id: uuid(), category: "Person", value: "A DUKE" },
  { id: uuid(), category: "Person", value: "A CREATURE OF HABIT" },
  { id: uuid(), category: "Person", value: "THRILL SEEKER" },
  { id: uuid(), category: "Person", value: "SHIPMATE" },
  { id: uuid(), category: "Person", value: "CIVIL WAR BUFF" },
  { id: uuid(), category: "Person", value: "GLAMOROUS MODEL" },
  { id: uuid(), category: "Person", value: "ASSISTANT COACH" },
  { id: uuid(), category: "Person", value: "SEASONED VETERAN" },
  { id: uuid(), category: "Person", value: "LIFEGUARD ON DUTY" },
  { id: uuid(), category: "Person", value: "CENSUS TAKER" },
  { id: uuid(), category: "Person", value: "A FRIEND OF A FRIEND" },
  { id: uuid(), category: "Person", value: "PUBLIC SPEAKER" },
  { id: uuid(), category: "Person", value: "THE RIGHTFUL OWNER" },
  { id: uuid(), category: "Person", value: "FOREIGN DIGNITARY" },
  { id: uuid(), category: "Person", value: "FAMILY DOCTOR" },
  { id: uuid(), category: "Person", value: "A KID AT HEART" },
  { id: uuid(), category: "Person", value: "COMPANY TREASURER" },
  { id: uuid(), category: "Person", value: "AUTOGRAPH COLLECTOR" },
  { id: uuid(), category: "Person", value: "THE HEAD HONCHO" },
  { id: uuid(), category: "Person", value: "A WORLD TRAVELER" },
  { id: uuid(), category: "Person", value: "FREE-LANCE ARTIST" },
  { id: uuid(), category: "Person", value: "AN OLD SOFTY" },
  { id: uuid(), category: "Person", value: "A HUMAN CANNONBALL" },
  { id: uuid(), category: "Person", value: "SUBSTITUTE TEACHER" },
  { id: uuid(), category: "Person", value: "A STUDY BUDDY" },
  { id: uuid(), category: "Person", value: "AN EXPERT IN THE FIELD" },
  { id: uuid(), category: "Person", value: "HOCKEY GOALIE" },
  { id: uuid(), category: "Person", value: "CLASS PRESIDENT" },
  { id: uuid(), category: "Person", value: "A HIRED HAND" },
  { id: uuid(), category: "Person", value: "HIKER" },
  { id: uuid(), category: "Person", value: "LANDSCAPE GARDENER" },
  { id: uuid(), category: "Person", value: "A HEAVY HITTER" },
  { id: uuid(), category: "Person", value: "OUR FEARLESS LEADER" },
  { id: uuid(), category: "Person", value: "A GENTLE GIANT" },
  { id: uuid(), category: "Person", value: "BANJO PLAYER" },
  { id: uuid(), category: "Person", value: "A SNAPPY DRESSER" },
  { id: uuid(), category: "Person", value: "ARMCHAIR PHILOSOPHER" },
  { id: uuid(), category: "Person", value: "MASTER OF ILLUSION" },
  { id: uuid(), category: "Person", value: "FINICKY EATER" },
  { id: uuid(), category: "Person", value: "MASTER OF CEREMONIES" },
  { id: uuid(), category: "Person", value: "TROPHY MAKER" },
  { id: uuid(), category: "Person", value: "SIGNIFICANT OTHER" },
  { id: uuid(), category: "Person", value: "NIGHTCLUB SINGER" },
  { id: uuid(), category: "Person", value: "WORLD CHESS CHAMPION" },
  { id: uuid(), category: "Person", value: "STUDENT TEACHER" },
  { id: uuid(), category: "Person", value: "AN IDEAL CANDIDATE" },
  { id: uuid(), category: "Person", value: "A HEAVY SLEEPER" },
  { id: uuid(), category: "Person", value: "SHARP DRESSER" },
  { id: uuid(), category: "Person", value: "A LEGEND IN HIS OWN TIME" },
  { id: uuid(), category: "Person", value: "BIG TIPPER" },
  { id: uuid(), category: "Person", value: "THE FIRST ONE IN LINE" },
  { id: uuid(), category: "Person", value: "MATH WHIZ" },
  { id: uuid(), category: "Person", value: "CAPTAIN OF THE SWIM TEAM" },
  { id: uuid(), category: "Person", value: "TRAVEL WRITER" },
  { id: uuid(), category: "Person", value: "TRUE BELIEVER" },
  { id: uuid(), category: "Person", value: "BODYBUILDER" },
  { id: uuid(), category: "Person", value: "LUCKY STIFF" },
  { id: uuid(), category: "Person", value: "SCAREDY-CAT" },
  { id: uuid(), category: "Person", value: "MAD SCIENTIST" },
  { id: uuid(), category: "Person", value: "HONORARY CHAIRMAN" },
  { id: uuid(), category: "Person", value: "THE GO-TO GUY" },
  { id: uuid(), category: "Person", value: "AN UNLIKELY HERO" },
  { id: uuid(), category: "Person", value: "SECRETARY OF COMMERCE" },
  { id: uuid(), category: "Person", value: "MONDAY MORNING QUARTERBACK" },
  {
    id: uuid(),
    category: "Person",
    value: "LONGTIME LISTENER FIRST-TIME CALLER",
  },
  { id: uuid(), category: "Person", value: "EAGER BEAVER" },
  { id: uuid(), category: "Person", value: "FOLK HERO" },
  { id: uuid(), category: "Person", value: "GUEST OF HONOR" },
  { id: uuid(), category: "Person", value: "SOCIAL BUTTERFLY" },
  { id: uuid(), category: "Person", value: "STRAIGHT-A STUDENT" },
  { id: uuid(), category: "Person", value: "DISTRICT ATTORNEY" },
  { id: uuid(), category: "Person", value: "COOL CUSTOMER" },
  { id: uuid(), category: "Person", value: "NATIONAL MERIT SCHOLAR" },
  { id: uuid(), category: "Person", value: "TEACHER OF THE YEAR" },
  { id: uuid(), category: "Person", value: "DRIVING INSTRUCTOR" },
  { id: uuid(), category: "Person", value: "KNIGHT IN SHINING ARMOR" },
  { id: uuid(), category: "Person", value: "SECRET ADMIRER" },
  { id: uuid(), category: "Person", value: "A REAL HUNK" },
  { id: uuid(), category: "Person", value: "LUCKY DOG" },
  { id: uuid(), category: "Person", value: "ELIGIBLE BACHELOR" },
  { id: uuid(), category: "Person", value: "A CREATURE OF HABIT" },
  { id: uuid(), category: "Person", value: "CURRENT RESIDENT" },
  { id: uuid(), category: "Person", value: "PRACTICAL JOKER" },
  { id: uuid(), category: "Person", value: "RED-BLOODED AMERICAN MALE" },
  { id: uuid(), category: "Person", value: "THE CONSUMATE SHOWMAN" },
  { id: uuid(), category: "Person", value: "A TOUGH COOKIE" },
  { id: uuid(), category: "Person", value: "A NATURAL BLONDE" },
  { id: uuid(), category: "Person", value: "DESIGNATED DRIVER" },
  { id: uuid(), category: "Person", value: "FRIENDLY NEIGHBOR" },
  { id: uuid(), category: "Person", value: "THE OLDEST LIVING HUMAN" },
  { id: uuid(), category: "Person", value: "GIRL SCOUT TROOP LEADER" },
  { id: uuid(), category: "Person", value: "WINE STEWARD" },
  { id: uuid(), category: "Person", value: "STRONG SWIMMER" },
  { id: uuid(), category: "Person", value: "POLITICAL CARTOONIST" },
  { id: uuid(), category: "Person", value: "BUSYBODY" },
  { id: uuid(), category: "Person", value: "MOVIE BUFF" },
  { id: uuid(), category: "Person", value: "MAN OF THE HOUR" },
  { id: uuid(), category: "Person", value: "TEEN HEARTTHROB" },
  { id: uuid(), category: "Person", value: "FAVORITE AUTHOR" },
  { id: uuid(), category: "Person", value: "UNSUNG HERO" },
  { id: uuid(), category: "Person", value: "FORMER EMPLOYER" },
  { id: uuid(), category: "Person", value: "SMART COOKIE" },
  { id: uuid(), category: "Person", value: "VOLUNTEER FIREFIGHTER" },
  { id: uuid(), category: "Person", value: "SILLY GOOSE" },
  { id: uuid(), category: "Person", value: "MODEL CITIZEN" },
  { id: uuid(), category: "Person", value: "HOMEBODY" },
  { id: uuid(), category: "Person", value: "A WORKOUT PARTNER" },
  { id: uuid(), category: "Person", value: "ARMY SERGEANT" },
  { id: uuid(), category: "Person", value: "ARMCHAIR QUARTERBACK" },
  { id: uuid(), category: "Person", value: "BLUSHING BRIDE" },
  { id: uuid(), category: "Person", value: "EAGLE SCOUT" },
  { id: uuid(), category: "Person", value: "MY BETTER HALF" },
  { id: uuid(), category: "Person", value: "BIRTHDAY BOY" },
  { id: uuid(), category: "Person", value: "HOPLESS ROMANTIC" },
  { id: uuid(), category: "Person", value: "A GOOD KISSER" },
  { id: uuid(), category: "Person", value: "WATERCOLOR ARTIST" },
  { id: uuid(), category: "Person", value: "SIBLING" },
  {
    id: uuid(),
    category: "Person",
    value: "CLASSICALLY TRAINED FLAMENCO GUITARIST",
  },
  { id: uuid(), category: "Person", value: "CASUAL OBSERVER" },
  { id: uuid(), category: "Person", value: "JUSTICE OF THE PEACE" },
  { id: uuid(), category: "Person", value: "DRAMA QUEEN" },
  { id: uuid(), category: "Person", value: "AMATEUR ASTRONOMER" },
  { id: uuid(), category: "Person", value: "THE BIG CHEESE" },
  { id: uuid(), category: "Person", value: "CIVIL WAR BUFF" },
  { id: uuid(), category: "Person", value: "GUEST LECTURER" },
  { id: uuid(), category: "Person", value: "ONE OF THE GANG" },
  { id: uuid(), category: "Person", value: "MASTER OF DISGUISE" },
  { id: uuid(), category: "Person", value: "DOG SHOW JUDGE" },
  { id: uuid(), category: "Person", value: "AMATEUR SLEUTH" },
  { id: uuid(), category: "Person", value: "PROMISING YOUNG PLAYWRIGHT" },
  { id: uuid(), category: "Person", value: "EMPLOYEE OF THE MONTH" },
  { id: uuid(), category: "Person", value: "AN OLD DEAR FRIEND" },
  { id: uuid(), category: "Person", value: "TOUGH GUY" },
  { id: uuid(), category: "Person", value: "SHORT-STORY WRITER" },
  {
    id: uuid(),
    category: "Person",
    value: "RESPECTED MEMBER OF THE COMMUNITY",
  },
  { id: uuid(), category: "Person", value: "QUICK STUDY" },
  { id: uuid(), category: "Person", value: "MEMORABILIA COLLECTOR" },
  { id: uuid(), category: "Person", value: "SMOOTH TALKER" },
  { id: uuid(), category: "Person", value: "FUSSY BABY" },
  { id: uuid(), category: "Person", value: "CROSSING GUARD" },
  { id: uuid(), category: "Person", value: "THE WORLD'S FASTEST MAN" },
  { id: uuid(), category: "Person", value: "THREE-SPORT ATHLETE" },
  { id: uuid(), category: "Person", value: "GRADUATION SPEAKER" },
  { id: uuid(), category: "Person", value: "PUBLISHED AUTHOR" },
  { id: uuid(), category: "Person", value: "MAID OF HONOR" },
  { id: uuid(), category: "Person", value: "RIGHT-HAND MAN" },
  { id: uuid(), category: "Person", value: "FAVORITE SON" },
  { id: uuid(), category: "Person", value: "FRIENDLY WAITRESS" },
  { id: uuid(), category: "Person", value: "SLEEPWALKER" },
  { id: uuid(), category: "Person", value: "CRUSADING DISTRICT ATTORNEY" },
  { id: uuid(), category: "Person", value: "A WORLD TAVELER" },
  { id: uuid(), category: "Person", value: "AVERAGE GUY" },
  { id: uuid(), category: "Person", value: "DIRECT SUPERVISOR" },
  { id: uuid(), category: "Person", value: "NURSING STUDENT" },
  { id: uuid(), category: "Person", value: "AUTOGRAPH COLLECTOR" },
  { id: uuid(), category: "Person", value: "POSTMASTER GENERAL" },
  { id: uuid(), category: "Person", value: "CELEBRITY CHEF" },
  { id: uuid(), category: "Person", value: "DEVOTED HUSBAND AND FATHER" },
  { id: uuid(), category: "Person", value: "CLASS CLOWN" },
  { id: uuid(), category: "Person", value: "FIERCE COMPETITOR" },
  { id: uuid(), category: "Person", value: "ANOTHER SATISFIED CUSTOMER" },
  { id: uuid(), category: "Person", value: "AMERICA'S SWEETHEART" },
  { id: uuid(), category: "Person", value: "GOURMET COOK" },
  { id: uuid(), category: "Person", value: "FARMER'S DAUGHTER" },
  { id: uuid(), category: "Person", value: "HOCKEY FAN" },
  { id: uuid(), category: "Person", value: "CAREER WOMAN" },
  { id: uuid(), category: "Person", value: "GRAND MARSHAL OF A PARADE" },
  { id: uuid(), category: "Person", value: "TRENSETTER" },
  { id: uuid(), category: "Person", value: "COIN COLLECTOR" },
  { id: uuid(), category: "Person", value: "PROUD MOTHER OF TWO" },
  { id: uuid(), category: "Person", value: "PLAYWRIGHT" },
  { id: uuid(), category: "Person", value: "CONCERT VIOLINIST" },
  { id: uuid(), category: "Person", value: "NATIVE NEW YORKER" },
  { id: uuid(), category: "Person", value: "BIOGRAPHER" },
  { id: uuid(), category: "Person", value: "THE BIG BOSS" },
  { id: uuid(), category: "Person", value: "BARGAIN SHOPPER" },
  { id: uuid(), category: "Person", value: "HIGH BIDDER" },
  { id: uuid(), category: "Person", value: "TRIVIA BUFF" },
  { id: uuid(), category: "Person", value: "CREATIVE GENIUS" },
  { id: uuid(), category: "Person", value: "WORKING MOTHER" },
  { id: uuid(), category: "Person", value: "DADDY'S LITTLE GIRL" },
  { id: uuid(), category: "Person", value: "GUEST SPEAKER" },
  { id: uuid(), category: "Person", value: "NIGHTCLUB DOORMAN" },
  { id: uuid(), category: "Person", value: "GROWING BOY" },
  { id: uuid(), category: "Person", value: "SELF-MADE MAN" },
  { id: uuid(), category: "Person", value: "A SPECIAL SOMEONE" },
  { id: uuid(), category: "Person", value: "HANDSOME DEVIL" },
  { id: uuid(), category: "Person", value: "OFF-DUTY COP" },
  { id: uuid(), category: "Person", value: "A DETECTIVE SEARCHING FOR CLUES" },
  { id: uuid(), category: "Person", value: "EARLY RISER" },
  { id: uuid(), category: "Person", value: "FREE SPIRIT" },
  { id: uuid(), category: "Person", value: "BOXING FAN" },
  { id: uuid(), category: "Person", value: "PARTY PLANNER" },
  { id: uuid(), category: "Person", value: "COLORFUL CHARACTER" },
  { id: uuid(), category: "Person", value: "PERFECT STRANGER" },
  { id: uuid(), category: "Person", value: "CLOSE RELATIVE" },
  { id: uuid(), category: "Person", value: "SILENT PARTNER" },
  { id: uuid(), category: "Person", value: "FIGURE SKATER" },
  { id: uuid(), category: "Person", value: "BEEKEEPER" },
  { id: uuid(), category: "Person", value: "CHESS MASTER" },
  { id: uuid(), category: "Person", value: "SMART ALECK" },
  { id: uuid(), category: "Person", value: "LICENSED PILOT" },
  { id: uuid(), category: "Person", value: "ASPIRING ARTIST" },
  { id: uuid(), category: "Person", value: "CONFIRMED BACHELOR" },
  { id: uuid(), category: "Person", value: "RODEO COWBOY" },
  { id: uuid(), category: "Person", value: "GOOD ROLE MODEL" },
  { id: uuid(), category: "Person", value: "SOUND SLEEPER" },
  { id: uuid(), category: "Person", value: "FAVORITE UNCLE" },
  { id: uuid(), category: "Person", value: "KNOW-IT-ALL" },
  { id: uuid(), category: "Person", value: "NEXT-DOOR NEIGHBOR" },
  { id: uuid(), category: "Person", value: "NATIVE OF CHICAGO" },
  { id: uuid(), category: "Person", value: "SECOND RUNNER-UP" },
  { id: uuid(), category: "Person", value: "CRUISE PASSENGER" },
  { id: uuid(), category: "Person", value: "HIS MAJESTY THE KING" },
  { id: uuid(), category: "Person", value: "SNAKE CHARMER" },
  { id: uuid(), category: "Person", value: "HAPPY CAMPER" },
  { id: uuid(), category: "Person", value: "HISTORY BUFF" },
  { id: uuid(), category: "Person", value: "FISHING BUDDY" },
  { id: uuid(), category: "Person", value: "MY BEST FRIEND FOREVER" },
  { id: uuid(), category: "Person", value: "VARSITY BASEBALL PLAYER" },
  { id: uuid(), category: "Person", value: "LICENSED DRIVER" },
  { id: uuid(), category: "Person", value: "THE BABY OF THE FAMILY" },
  { id: uuid(), category: "Person", value: "BACKSEAT DRIVER" },
  { id: uuid(), category: "Person", value: "VISIONARY" },
  { id: uuid(), category: "Person", value: "CRYBABY" },
  { id: uuid(), category: "Person", value: "SOCCER MOMS" },
  { id: uuid(), category: "Person", value: "MASTER MAGICIAN" },
  { id: uuid(), category: "Person", value: "TRUSTED FRIEND" },
  { id: uuid(), category: "Person", value: "WORKAHOLIC" },
  { id: uuid(), category: "Person", value: "BLOGGER" },
  { id: uuid(), category: "Person", value: "GRADUATE STUDENT" },
  { id: uuid(), category: "Person", value: "ELDER STATESMAN" },
  { id: uuid(), category: "Person", value: "HEAD COACH" },
  { id: uuid(), category: "Person", value: "COMMITTEE CHAIRMAN" },
  { id: uuid(), category: "Person", value: "CUTE KID" },
  { id: uuid(), category: "Person", value: "RISK TAKER" },
  { id: uuid(), category: "Person", value: "DOUBLE AGENT" },
  { id: uuid(), category: "Person", value: "AMETEUR INVENTOR" },
  { id: uuid(), category: "Person", value: "SLOWPOKE" },
  { id: uuid(), category: "Person", value: "SPEED DEMON" },
  { id: uuid(), category: "Person", value: "ASTRONOMER" },
  { id: uuid(), category: "Person", value: "OVERNIGHT SUCCESS" },
  { id: uuid(), category: "Person", value: "HOMECOMING QUEEN" },
  { id: uuid(), category: "Person", value: "REGULAR CUSTOMER" },
  { id: uuid(), category: "Person", value: "SPOILSPORT" },
  { id: uuid(), category: "Person", value: "FOREIGN DIPLOMAT" },
  { id: uuid(), category: "Person", value: "NAUGHTY BOY" },
  { id: uuid(), category: "Person", value: "A GOOD SPORT" },
  { id: uuid(), category: "Person", value: "A COMPLETE UNKNOWN" },
  { id: uuid(), category: "Person", value: "WEDDING MINISTER" },
  { id: uuid(), category: "Person", value: "FIFTH GRADER" },
  { id: uuid(), category: "Person", value: "CAPTAIN OF THE SHIP" },
  { id: uuid(), category: "Person", value: "NATURE LOVER" },
  { id: uuid(), category: "Person", value: "CAMP COUNSELOR" },
  { id: uuid(), category: "Person", value: "ESCAPE ARTIST" },
  { id: uuid(), category: "Person", value: "SPELLING BEE CHAMPION" },
  { id: uuid(), category: "Person", value: "KID SISTER" },
  { id: uuid(), category: "Person", value: "MAMA'S BOY" },
  { id: uuid(), category: "Person", value: "MATH TUTOR" },
  { id: uuid(), category: "Person", value: "BREADWINNER" },
  { id: uuid(), category: "Person", value: "SENIOR ADVISOR" },
  { id: uuid(), category: "Person", value: "BUSINESS TYCOON" },
  { id: uuid(), category: "Person", value: "GOLF PRO" },
  { id: uuid(), category: "Person", value: "AVID FAN" },
  { id: uuid(), category: "Person", value: "A CLASS ACT" },
  { id: uuid(), category: "Person", value: "COMEBACK KID" },
  { id: uuid(), category: "Person", value: "TRAILBLAZER" },
  { id: uuid(), category: "Person", value: "RESIDENT ASSISTANT" },
  { id: uuid(), category: "Person", value: "BIG MAN ON CAMPUS" },
  { id: uuid(), category: "Person", value: "RENAISSANCE MAN" },
  { id: uuid(), category: "Person", value: "CHIEF STRATEGIST" },
  { id: uuid(), category: "Person", value: "A TEAM PLAYER" },
  { id: uuid(), category: "Person", value: "FIRST-TIMER" },
  { id: uuid(), category: "Person", value: "DRIVING INSTRUCTOR" },
  { id: uuid(), category: "Person", value: "BIG WINNER" },
  { id: uuid(), category: "Person", value: "THE CAPTAIN OF A LUXURY VESSEL" },
  { id: uuid(), category: "Person", value: "MASTER CRAFTSMAN" },
  { id: uuid(), category: "Person", value: "A CREATURE OF HABIT" },
  { id: uuid(), category: "Person", value: "WHITE PICKET FENCE" },
  { id: uuid(), category: "Person", value: "RUNNER-UP" },
  { id: uuid(), category: "Person", value: "HIGHLY EXPERIENCED TOUR GUIDE" },
  { id: uuid(), category: "Person", value: "A FRIEND OF THE FAMILY" },
  { id: uuid(), category: "Person", value: "UNDERDOG" },
  { id: uuid(), category: "Person", value: "STAND-UP COMEDIAN" },
  { id: uuid(), category: "Person", value: "BRIDE-TO-BE" },
  { id: uuid(), category: "Person", value: "WORKOUT PARTNER" },
  { id: uuid(), category: "Person", value: "ETERNAL OPTIMIST" },
  { id: uuid(), category: "Person", value: "TOAST OF THE TOWN" },
  { id: uuid(), category: "Person", value: "BELLY DANCER" },
  { id: uuid(), category: "Person", value: "LIGHTHOUSE KEEPER" },
  { id: uuid(), category: "Person", value: "ACADEMIC ADVISOR" },
  { id: uuid(), category: "Person", value: "BOY GENIUS" },
  { id: uuid(), category: "Person", value: "THE MAN OF THE HOUR" },
  { id: uuid(), category: "Person", value: "RECENT COLLEGE GRADUATE" },
  { id: uuid(), category: "Person", value: "ACADEMIC ADVISOR" },
  { id: uuid(), category: "Person", value: "BOY GENIUS" },
  { id: uuid(), category: "Person", value: "THE MAN OF THE HOUR" },
  { id: uuid(), category: "Person", value: "RECENT COLLEGE GRADUATE" },
  { id: uuid(), category: "Person", value: "ONE OF THE GUYS" },
  { id: uuid(), category: "Person", value: "CIRCUS STRONGMAN" },
  { id: uuid(), category: "Person", value: "COOL CUSTOMER" },
  { id: uuid(), category: "Person", value: "SMALL-TOWN KID" },
  { id: uuid(), category: "Person", value: "ART CRITIC" },
  { id: uuid(), category: "Person", value: "LOYAL VIEWER" },
  { id: uuid(), category: "Person", value: "PARTY CRASHER" },
  { id: uuid(), category: "Person", value: "ANOTHER SATISFIED CUSTOMER" },
  { id: uuid(), category: "Person", value: "NEW KID ON THE BLOCK" },
  { id: uuid(), category: "Person", value: "FOLK HERO" },
  { id: uuid(), category: "Person", value: "JACKPOT WINNER" },
  { id: uuid(), category: "Person", value: "PICKY EATER" },
  { id: uuid(), category: "Person", value: "BORN LEADER" },
  { id: uuid(), category: "Person", value: "EAGLE SCOUT" },
  { id: uuid(), category: "Person", value: "HEAD CHEERLEADER" },
  { id: uuid(), category: "Person", value: "BODYBUILDER" },
  { id: uuid(), category: "Person", value: "LAW-ABIDING CITIZEN" },
  { id: uuid(), category: "Person", value: "ASPIRING ACTRESS" },
  { id: uuid(), category: "Person", value: "MASTER OF CEREMONIES" },
  { id: uuid(), category: "Person", value: "DEEP-SEA DIVER" },
  { id: uuid(), category: "Person", value: "BRIDEGROOM" },
  { id: uuid(), category: "Person", value: "RODEO CLOWN" },
  { id: uuid(), category: "Person", value: "AWARD RECIPIENT" },
  { id: uuid(), category: "Person", value: "WORLD TRAVELER" },
  { id: uuid(), category: "Person", value: "UNITED STATES AMBASSADOR" },
  { id: uuid(), category: "Person", value: "CELEBRATED PLAYWRIGHT" },
  { id: uuid(), category: "Person", value: "RELIEF PITCHER" },
  { id: uuid(), category: "Person", value: "FAITHFUL SIDEKICK" },
  { id: uuid(), category: "Person", value: "HEIR TO THE THRONE" },
  { id: uuid(), category: "Person", value: "MASTER OF DISGUISE" },
  { id: uuid(), category: "Person", value: "JAZZ MUSICIAN" },
  { id: uuid(), category: "Person", value: "SAVVY SHOPPER" },
  { id: uuid(), category: "Person", value: "UNDERCOVER AGENT" },
  { id: uuid(), category: "Person", value: "A MAN OF MANY TALENTS" },
  { id: uuid(), category: "Person", value: "NEW BEST FRIEND" },
  { id: uuid(), category: "Person", value: "PROBLEM SOLVER" },
  { id: uuid(), category: "Person", value: "THE HIGHEST BIDDER" },
  { id: uuid(), category: "Person", value: "JUSTICE OF THE PEACE" },
  { id: uuid(), category: "Person", value: "GROWN-UP" },
  { id: uuid(), category: "Person", value: "ANONYMOUS DONOR" },
  { id: uuid(), category: "Person", value: "TOUGH GUY" },
  { id: uuid(), category: "Person", value: "PRIME MINISTER" },
  { id: uuid(), category: "Person", value: "RUNNING BACK" },
  { id: uuid(), category: "Person", value: "THE MAN BEHIND THE MASK" },
  { id: uuid(), category: "Person", value: "RECORDING ARTIST" },
  { id: uuid(), category: "Person", value: "VOLUNTEER FIREFIGHTER" },
  { id: uuid(), category: "Person", value: "COMMANDING OFFICER" },
  { id: uuid(), category: "Person", value: "RIGHT-HAND MAN" },
  { id: uuid(), category: "Person", value: "MOUNTAIN CLIMBER" },
  { id: uuid(), category: "Person", value: "SKILLED CRAFTSMAN" },
  { id: uuid(), category: "Person", value: "FORMER BOYFRIEND" },
  { id: uuid(), category: "Person", value: "LIVING LEGEND" },
  {
    id: uuid(),
    category: "Person",
    value: "JACK-OF-ALL TRADES MASTER OF NONE",
  },
  { id: uuid(), category: "Person", value: "LIGHTWEIGHT CHAMP" },
  { id: uuid(), category: "Person", value: "MYSTERY GUEST" },
  { id: uuid(), category: "Person", value: "BLUSHING BRIDE" },
  { id: uuid(), category: "Person", value: "HOPELESS ROMANTIC" },
  { id: uuid(), category: "Person", value: "ART COLLECTOR" },
  { id: uuid(), category: "Person", value: "MAN OF MYSTERY" },
  { id: uuid(), category: "Person", value: "MOST VALUABLE PLAYER" },
  { id: uuid(), category: "Person", value: "KNIGHT IN SHINING ARMOR" },
  { id: uuid(), category: "Person", value: "LION TAMER" },
  { id: uuid(), category: "Person", value: "A REAL GO-GETTER" },
  { id: uuid(), category: "Person", value: "SECRET ADMIRER" },
  { id: uuid(), category: "Person", value: "CELEBRITY CHEF" },
  { id: uuid(), category: "Person", value: "GUEST SPEAKER" },
  { id: uuid(), category: "Person", value: "FRIENDLY SKI INSTRUCTOR" },
  { id: uuid(), category: "Person", value: "AVID HIKER" },
  { id: uuid(), category: "Person", value: "NOISY NEIGHBOR" },
  { id: uuid(), category: "Person", value: "AMATEUR ASTRONOMER" },
  { id: uuid(), category: "Person", value: "DANCE CHAPERONE" },
  { id: uuid(), category: "Person", value: "SOCCER PLAYER" },
  { id: uuid(), category: "Person", value: "STUDENT COUNCIL PRESIDENT" },
  { id: uuid(), category: "Person", value: "THE NARRATOR OF THE STORY" },
  { id: uuid(), category: "Person", value: "TEAM CAPTAIN" },
  { id: uuid(), category: "Person", value: "FIRST MATE" },
  { id: uuid(), category: "Person", value: "THE UNDISPUTED CHAMPION" },
  { id: uuid(), category: "Person", value: "ADMIRAL OF THE FLEET" },
  { id: uuid(), category: "Person", value: "HOMETOWN HERO" },
  { id: uuid(), category: "Person", value: "PALM READER" },
  { id: uuid(), category: "Person", value: "OFFICIAL BIOGRAPHER" },
  { id: uuid(), category: "Person", value: "BODYGUARD" },
  { id: uuid(), category: "Person", value: "A FRIEND OF A FRIEND" },
  { id: uuid(), category: "Person", value: "GRAND MARSHALL OF THE PARADE" },
  { id: uuid(), category: "Person", value: "A LOCAL EXPERIENCED TOUR GUIDE" },
  { id: uuid(), category: "Person", value: "NOBODY'S FOOL" },
  { id: uuid(), category: "Person", value: "STRAIGHT-A STUDENT" },
  { id: uuid(), category: "Person", value: "CLASS CLOWN" },
  { id: uuid(), category: "Person", value: "CUTE COUPLE" },
  { id: uuid(), category: "Person", value: "LITTLE BROTHER" },
  { id: uuid(), category: "Person", value: "EMPLOYEE OF THE MONTH" },
  { id: uuid(), category: "Person", value: "NEXT-DOOR NEIGHBOR" },
  { id: uuid(), category: "Person", value: "CAR ENTHUSIAST" },
  { id: uuid(), category: "Person", value: "FACEBOOK FRIEND" },
  { id: uuid(), category: "Person", value: "RIVERBOAT CAPTAIN" },
  { id: uuid(), category: "Person", value: "SAXOPHONE PLAYER" },
  { id: uuid(), category: "Person", value: "HOME PLATE UMPIRE" },
  { id: uuid(), category: "Person", value: "FAMILY MAN" },
  { id: uuid(), category: "Person", value: "WORLD'S GREATEST DAD" },
  { id: uuid(), category: "Person", value: "LINE JUDGE" },
  { id: uuid(), category: "Person", value: "THIRD-BASE COACH" },
  { id: uuid(), category: "Person", value: "CIRCUS RINGMASTER" },
  { id: uuid(), category: "Person", value: "THE PERFECT HOST" },
  { id: uuid(), category: "Person", value: "KNOW-IT-ALL" },
  { id: uuid(), category: "Person", value: "STREET PERFORMER" },
  { id: uuid(), category: "Person", value: "MODEL CITIZEN" },
  { id: uuid(), category: "Person", value: "DANCE PARTNER" },
  { id: uuid(), category: "Person", value: "TREASURE HUNTER" },
  { id: uuid(), category: "Person", value: "MAD SCIENTISTS" },
  { id: uuid(), category: "Person", value: "FIRST-ROUND DRAFT PICK" },
  { id: uuid(), category: "Person", value: "TEEN HEARTTHROB" },
  { id: uuid(), category: "Person", value: "SATISFIED CUSTOMER" },
  { id: uuid(), category: "Person", value: "BARGAIN HUNTER" },
  { id: uuid(), category: "Person", value: "THE STRONG SILENT TYPE" },
  { id: uuid(), category: "Person", value: "MAID OF HONOR" },
  { id: uuid(), category: "Person", value: "TEAM LEADER" },
  { id: uuid(), category: "Person", value: "OLYMPIC GYMNAST" },
  { id: uuid(), category: "Person", value: "CAPTAIN OF THE SHIP" },
  { id: uuid(), category: "Person", value: "WORLD-CLASS ATHLETE" },
  { id: uuid(), category: "Person", value: "INTERIOR DECORATOR TO THE STARS" },
  { id: uuid(), category: "Person", value: "BIG SPENDER" },
  { id: uuid(), category: "Person", value: "A SNAPPY DRESSER" },
  { id: uuid(), category: "Person", value: "MR. KNOW-IT-ALL" },
  { id: uuid(), category: "Person", value: "GOLDEN BOY" },
  { id: uuid(), category: "Person", value: "WORLD CHAMP" },
  {
    id: uuid(),
    category: "Person",
    value: "A PRIVATE EYE SEARCHING FOR CLUES",
  },
  { id: uuid(), category: "Person", value: "ROOKIE OF THE YEAR" },
  { id: uuid(), category: "Person", value: "SMART COOKIE" },
  { id: uuid(), category: "Person", value: "FIGHTER PILOT" },
  { id: uuid(), category: "Person", value: "DRILL SERGEANT" },
  { id: uuid(), category: "Person", value: "AMERICA'S SWEETHEART" },
  { id: uuid(), category: "Person", value: "HOMEBUYER" },
  { id: uuid(), category: "Person", value: "SEASONED VETERAN" },
  { id: uuid(), category: "Person", value: "THE BRAINS OF THE OPERATION" },
  { id: uuid(), category: "Person", value: "PRO BOWLER" },
  { id: uuid(), category: "Person", value: "COMIC BOOK COLLECTOR" },
  { id: uuid(), category: "Person", value: "SELF-MADE MILLIONAIRE" },
  { id: uuid(), category: "Person", value: "KID BROTHER" },
  { id: uuid(), category: "Person", value: "UNSUNG HERO" },
  { id: uuid(), category: "Person", value: "CHESS MASTER" },
  { id: uuid(), category: "Person", value: "IMMEDIATE SUPERVISOR" },
  { id: uuid(), category: "Person", value: "BLACK BELT IN KARATE" },
  { id: uuid(), category: "Person", value: "FOREIGN DIPLOMAT" },
  { id: uuid(), category: "Person", value: "ESCAPE ARTIST" },
  { id: uuid(), category: "Person", value: "FRIENDLY LIFEGUARD" },
  { id: uuid(), category: "Person", value: "CAMP COUNSELOR" },
  { id: uuid(), category: "Person", value: "BOYHOOD IDOL" },
  { id: uuid(), category: "Person", value: "WORKOUT PARTNER" },
  { id: uuid(), category: "Person", value: "COMPUTER WHIZ" },
  { id: uuid(), category: "Person", value: "NATURE LOVER" },
  { id: uuid(), category: "Person", value: "THE STAR OF THE SHOW" },
  { id: uuid(), category: "Person", value: "SENIOR ADVISOR" },
  { id: uuid(), category: "Person", value: "A GOOD SPORT" },
  { id: uuid(), category: "Person", value: "VARSITY COACH" },
  { id: uuid(), category: "Person", value: "A TELLER OF TALL TALES" },
  { id: uuid(), category: "Person", value: "COMEBACK KID" },
  { id: uuid(), category: "Person", value: "BLOGGER" },
  { id: uuid(), category: "Person", value: "BREADWINNER" },
  { id: uuid(), category: "Person", value: "FAMOUS AUTHOR" },
  { id: uuid(), category: "Person", value: "ORIGINAL OWNER" },
  { id: uuid(), category: "Person", value: "SMOOTH TALKER" },
  { id: uuid(), category: "Person", value: "RODEO COWBOY" },
  { id: uuid(), category: "Person", value: "THAT SPECIAL SOMEONE" },
  { id: uuid(), category: "Person", value: "TRUSTED FRIEND" },
  { id: uuid(), category: "Person", value: "ONE OF THE GANG" },
  { id: uuid(), category: "Person", value: "OLYMPIAN" },
  { id: uuid(), category: "Person", value: "YOUNG UPSTART" },
  { id: uuid(), category: "Person", value: "CHESS CHAMPION" },
  { id: uuid(), category: "Person", value: "REGULAR CUSTOMER" },
  { id: uuid(), category: "Person", value: "COLE PORTER" },
  { id: uuid(), category: "Person", value: "EARLY RISER" },
  { id: uuid(), category: "Person", value: "HANDSOME DEVIL" },
  { id: uuid(), category: "Person", value: "A DETECTIVE SEARCHING FOR CLUES" },
  { id: uuid(), category: "Person", value: "EXPERT IN THE FIELD" },
  { id: uuid(), category: "Person", value: "THE SKIPPER" },
  { id: uuid(), category: "Person", value: "CHATTERBOX" },
  { id: uuid(), category: "Person", value: "ASPIRING ARTIST" },
  { id: uuid(), category: "Person", value: "ANTIQUE COLLECTOR" },
  { id: uuid(), category: "Person", value: "SAXOPHONIST" },
  { id: uuid(), category: "Person", value: "HISTORIAN" },
  { id: uuid(), category: "Person", value: "LICENSED PILOT" },
  { id: uuid(), category: "Person", value: "UPSTANDING CITIZEN" },
  { id: uuid(), category: "Person", value: "JOE NAMATH" },
  { id: uuid(), category: "Person", value: "SIGNIFICANT OTHER" },
  { id: uuid(), category: "Person", value: "SPUNKY HERO" },
  { id: uuid(), category: "Person", value: "YOUNG PRODIGY" },
  { id: uuid(), category: "Person", value: "MASTER OF DISGUISE" },
  { id: uuid(), category: "Person", value: "MY BETTER HALF" },
  { id: uuid(), category: "Person", value: "TRUSTY SIDEKICK" },
  { id: uuid(), category: "Person", value: "HOMEOWNER" },
  { id: uuid(), category: "Person", value: "SOCIAL BUTTERFLY" },
  { id: uuid(), category: "Person", value: "CHAIRMAN OF THE BOARD" },
  { id: uuid(), category: "Person", value: "RODEO CLOWN" },
  { id: uuid(), category: "Person", value: "RISK TAKER" },
  { id: uuid(), category: "Person", value: "STUDENT DRIVER" },
  { id: uuid(), category: "Person", value: "FATHER OF THE BRIDE" },
  { id: uuid(), category: "Person", value: "RECENT COLLEGE GRADUATE" },
  { id: uuid(), category: "Person", value: "CHILD" },
  { id: uuid(), category: "Person", value: "MY NEW BEST FRIEND" },
  { id: uuid(), category: "Person", value: "STRONG SWIMMER" },
  { id: uuid(), category: "Person", value: "COLLEAGUE" },
  { id: uuid(), category: "Person", value: "PRIME MINISTER" },
  { id: uuid(), category: "Person", value: "COMPETITIVE CYCLIST" },
  { id: uuid(), category: "Person", value: "HAPPILY MARRIED MAN" },
  { id: uuid(), category: "Person", value: "BARGAIN SHOPPER" },
  { id: uuid(), category: "Person", value: "SPELLING BEE CHAMPION" },
  { id: uuid(), category: "Person", value: "HOMEWORK HELPER" },
  { id: uuid(), category: "Person", value: "CONSTANT COMPANION" },
  { id: uuid(), category: "Person", value: "ETERNAL OPTIMIST" },
  { id: uuid(), category: "Person", value: "FINICKY BABY" },
  { id: uuid(), category: "Person", value: "COMMANDING OFFICER" },
  { id: uuid(), category: "Person", value: "WILDLY HAPPY GUY" },
  { id: uuid(), category: "Person", value: "SILVER MEDALIST" },
  { id: uuid(), category: "Person", value: "STUDENT OF HISTORY" },
  { id: uuid(), category: "Person", value: "A CHIP OFF THE OLD BLOCK" },
  { id: uuid(), category: "Person", value: "LAW-ABIDING CITIZEN" },
]
export default puzzleList
