import { v4 as uuid } from "uuid"
import { Puzzle } from "../../types/Puzzle"
const puzzleList: Puzzle[] = [
  { id: uuid(), category: "Places", value: "THE FOUR CORNERS OF THE EARTH" },
  { id: uuid(), category: "Places", value: "ROCKY SHORELINES" },
  { id: uuid(), category: "Places", value: "RANCH STYLE HOMES" },
  { id: uuid(), category: "Places", value: "SOUTH AMERICAN RAIN FORESTS" },
  { id: uuid(), category: "Places", value: "COLORFUL CORAL REEFS" },
  { id: uuid(), category: "Places", value: "BASEMENT AND ATTIC" },
  { id: uuid(), category: "Places", value: "WEATHER STATIONS" },
  { id: uuid(), category: "Places", value: "POINTS OF INTEREST" },
  { id: uuid(), category: "Places", value: "FRAGRANT CITRUS GROVES" },
  { id: uuid(), category: "Places", value: "OLD HAUNTS" },
  { id: uuid(), category: "Places", value: "HANDSOME BROWNSTONE BUILDINGS" },
  { id: uuid(), category: "Places", value: "PORT AND STARBOARD" },
  { id: uuid(), category: "Places", value: "SNOW-CAPPED MOUNTAINS" },
  { id: uuid(), category: "Places", value: "ENCHANTING COASTAL VILLAGES" },
  { id: uuid(), category: "Places", value: "BOTANICAL GARDENS" },
  { id: uuid(), category: "Places", value: "SPECTACULAR VOLCANIC MOUNTAINS" },
  { id: uuid(), category: "Places", value: "IVY-COVERED BUILDINGS" },
  { id: uuid(), category: "Places", value: "DRAMATIC LAVA FIELDS" },
  { id: uuid(), category: "Places", value: "QUAINT COBBLESTONE STREETS" },
  { id: uuid(), category: "Places", value: "PEAKS AND VALLEYS" },
  { id: uuid(), category: "Places", value: "WINDOW MIDDLE AND AISLE SEATS" },
  { id: uuid(), category: "Places", value: "EXOTIC PORTS OF CALL" },
  { id: uuid(), category: "Places", value: "VICTORIAN MANSIONS" },
  { id: uuid(), category: "Places", value: "EXOTIC LOCATIONS" },
  { id: uuid(), category: "Places", value: "SECLUDED COVES AND SANDY BEACHES" },
  { id: uuid(), category: "Places", value: "COBBLESTONE STREETS" },
  { id: uuid(), category: "Places", value: "BUSY RESTAURANT KITCHENS" },
  {
    id: uuid(),
    category: "Places",
    value: "LANES STREETS AVENUES & BOULEVARDS",
  },
  { id: uuid(), category: "Places", value: "LUSH TROPICAL GARDENS" },
  { id: uuid(), category: "Places", value: "SAUNA AND STEAM ROOM" },
  { id: uuid(), category: "Places", value: "MILES OF UNSPOILED BEACHES" },
  { id: uuid(), category: "Places", value: "PICTURESQUE ALPINE VILLAGES" },
  { id: uuid(), category: "Places", value: "SNOW-CAPPED MOUNTAIN PEAKS" },
  { id: uuid(), category: "Places", value: "WORLD-CLASS ART MUSEUMS" },
  { id: uuid(), category: "Places", value: "SISTER CITIES" },
  { id: uuid(), category: "Places", value: "HISTORIC PUBS AND INNS" },
  { id: uuid(), category: "Places", value: "FIELDS OF CLOVER" },
  { id: uuid(), category: "Places", value: "ENCHANTING PORTS OF CALL" },
  {
    id: uuid(),
    category: "Places",
    value: "VAST WILDERNESS AND FRONTIER TOWNS",
  },
  { id: uuid(), category: "Places", value: "WINE CELLARS AND TASTING ROOMS" },
  { id: uuid(), category: "Places", value: "THE SEVEN HILLS OF ROME" },
  { id: uuid(), category: "Places", value: "EARTH'S AMAZING RAIN FORESTS" },
  { id: uuid(), category: "Places", value: "WILDLIFE SANCTUARIES" },
  { id: uuid(), category: "Places", value: "PORT & STARBOARD" },
  { id: uuid(), category: "Places", value: "OLD WORLD CATHEDRALS AND PALACES" },
  { id: uuid(), category: "Places", value: "ROLLING PRARIES & SOARING PEAKS" },
  { id: uuid(), category: "Places", value: "WIDE-OPEN SPACES" },
  {
    id: uuid(),
    category: "Places",
    value: "YOUR OWN PRIVATE POOL AND SUN DECK",
  },
  { id: uuid(), category: "Places", value: "INCREDIBLE VOLCANIC ISLANDS" },
  { id: uuid(), category: "Places", value: "POWDERY SOFT BEACHES" },
  { id: uuid(), category: "Places", value: "EXCLUSIVE CLUBS AND TRENDY SPOTS" },
  { id: uuid(), category: "Places", value: "PICTURESQUE FISHING VILLAGES" },
  { id: uuid(), category: "Places", value: "STEAM ROOM" },
  {
    id: uuid(),
    category: "Places",
    value: "WE HAVE TO STOP MEETING LIKE THIS",
  },
  { id: uuid(), category: "Places", value: "DAZZLING WHITE SAND BEACHES" },
  { id: uuid(), category: "Places", value: "EXOTIC PORTS OF CALL" },
  { id: uuid(), category: "Places", value: "MAJESTIC SOUTHERN PLANTATIONS" },
  { id: uuid(), category: "Places", value: "HISTORIC SITES" },
  { id: uuid(), category: "Places", value: "SPECTACULAR VOLCANIC ISLANDS" },
  { id: uuid(), category: "Places", value: "GORGEOUS PRIVATE BEACHES" },
  { id: uuid(), category: "Places", value: "UNSPOILED MOUNTAIN LANDSCAPES" },
  { id: uuid(), category: "Places", value: "STATE CAPITALS" },
  { id: uuid(), category: "Places", value: "NATIONAL PARKS" },
  {
    id: uuid(),
    category: "Places",
    value: "LANES STREETS AVENUES & BOULEVARDS",
  },
  { id: uuid(), category: "Places", value: "CLAY COURTS" },
  { id: uuid(), category: "Places", value: "SCENIC HIKING TRAILS" },
  { id: uuid(), category: "Places", value: "QUAINT SHOPS" },
  { id: uuid(), category: "Places", value: "BEAUTIFUL COURSES" },
  { id: uuid(), category: "Places", value: "WINE CELLARS & TASTING ROOMS" },
  { id: uuid(), category: "Places", value: "WIDE-OPEN SPACES" },
  { id: uuid(), category: "Places", value: "FIELDS OF FLOWERS" },
  { id: uuid(), category: "Places", value: "BEAUTIFUL BLACK SAND BEACES" },
  {
    id: uuid(),
    category: "Places",
    value: "BEACHES THAT WILL TAKE YOUR BREATH AWAY",
  },
  { id: uuid(), category: "Places", value: "SNOW-CAPPED MOUNTAIN PEAKS" },
  { id: uuid(), category: "Places", value: "SUGAR CANE PLANTATIONS" },
  { id: uuid(), category: "Places", value: "GOLDEN CARIBBEAN BEACHES" },
  { id: uuid(), category: "Places", value: "HILLS AND VALLEYS" },
  { id: uuid(), category: "Places", value: "BRIDGES AND TUNNELS" },
  { id: uuid(), category: "Places", value: "ENCHANTING PORTS OF CALL" },
]
export default puzzleList
