import { v4 as uuid } from "uuid"
import { Puzzle } from "../../types/Puzzle"
const puzzleList: Puzzle[] = [
  { id: uuid(), category: "Same Name", value: "MICHAEL AND JESSE JACKSON" },
  { id: uuid(), category: "Same Name", value: "ALEXANDER AND GEORGE HAMILTON" },
  { id: uuid(), category: "Same Name", value: "LUCILLE AND SOCCER BALL" },
  { id: uuid(), category: "Same Name", value: "WATERFORD AND BILLY CRYSTAL" },
  { id: uuid(), category: "Same Name", value: "BOWLING AND TIN PAN ALLEY" },
  { id: uuid(), category: "Same Name", value: "TOM AND JOAN COLLINS" },
  { id: uuid(), category: "Same Name", value: "QUARTER AND CHARLEY HORSE" },
  {
    id: uuid(),
    category: "Same Name",
    value: "BARBARA AND THE GARDEN OF EDEN",
  },
  { id: uuid(), category: "Same Name", value: "PEE-WEE AND WOODY HERMAN" },
  { id: uuid(), category: "Same Name", value: "JULIUS AND SID CAESAR" },
  { id: uuid(), category: "Same Name", value: "PUNCH AND CHORUS LINE" },
  { id: uuid(), category: "Same Name", value: "FOREST AND LONE RANGER" },
  { id: uuid(), category: "Same Name", value: "LANA AND PANCAKE TURNER" },
  { id: uuid(), category: "Same Name", value: "KENNY AND ROY ROGERS" },
  { id: uuid(), category: "Same Name", value: "WINDOW AND BEVERLY SILLS" },
  { id: uuid(), category: "Same Name", value: "VANNA AND SNOW WHITE" },
  { id: uuid(), category: "Same Name", value: "LUCILLE AND DEBUTANTE BALL" },
  { id: uuid(), category: "Same Name", value: "SPENCER AND DICK TRACY" },
  { id: uuid(), category: "Same Name", value: "IRVING AND WEST BERLIN" },
  { id: uuid(), category: "Same Name", value: "FOOTBALL AND NEW JERSEY" },
  { id: uuid(), category: "Same Name", value: "DAMN AND NEW YORK YANKEES" },
  { id: uuid(), category: "Same Name", value: "TED AND TINA TURNER" },
  { id: uuid(), category: "Same Name", value: "BUDDY AND FILTHY RICH" },
  { id: uuid(), category: "Same Name", value: "CHARLIE AND AMERICAN PRIDE" },
  { id: uuid(), category: "Same Name", value: "FOOTBALL AND TWENTY-MULE TEAM" },
  { id: uuid(), category: "Same Name", value: "SQUARE-CUT AND LEGS DIAMOND" },
  { id: uuid(), category: "Same Name", value: "MUSICAL & LOVE NOTES" },
  { id: uuid(), category: "Same Name", value: "SCARLETT & JOHN O'HARA" },
  { id: uuid(), category: "Same Name", value: "RHODE & NO MAN IS AN ISLAND" },
  { id: uuid(), category: "Same Name", value: "BERMUDA & SHORT SHORTS" },
  { id: uuid(), category: "Same Name", value: "DUNE & BABY BUGGY" },
  { id: uuid(), category: "Same Name", value: "EAGER & LEAVE IT TO BEAVER" },
  { id: uuid(), category: "Same Name", value: "AUDREY & GREEN MEADOWS" },
  { id: uuid(), category: "Same Name", value: "NEHRU & SAFARI JACKET" },
  { id: uuid(), category: "Same Name", value: "BETSY & DIANA ROSS" },
  { id: uuid(), category: "Same Name", value: "MICHAEL & BO JACKSON" },
  { id: uuid(), category: "Same Name", value: "LANA & TINA TURNER" },
  { id: uuid(), category: "Same Name", value: "LEGAL & MASS TRANSIT SYSTEM" },
  { id: uuid(), category: "Same Name", value: "QUINCY & SHIRLEY JONES" },
  { id: uuid(), category: "Same Name", value: "YOU SILLY & CHRISTMAS GOOSE" },
  { id: uuid(), category: "Same Name", value: "SARA & PEGGY LEE" },
  { id: uuid(), category: "Same Name", value: "LIGHT & TULIP BULB" },
  { id: uuid(), category: "Same Name", value: "PANCAKE TINA & TED TURNER" },
  {
    id: uuid(),
    category: "Same Name",
    value: "SWITCHBOARD & BIG-TIME OPERATOR",
  },
  { id: uuid(), category: "Same Name", value: "BUGS & PLAYBOY BUNNY" },
  {
    id: uuid(),
    category: "Same Name",
    value: "SHELLEY JONATHAN & LONG HARD WINTERS",
  },
  { id: uuid(), category: "Same Name", value: "APRIL IN & PLASTER OF PARIS" },
  { id: uuid(), category: "Same Name", value: "VAMPIRE & BASEBALL BAT" },
  {
    id: uuid(),
    category: "Same Name",
    value: "\u00a0CARLY NEIL & SIMPLE SIMON",
  },
  { id: uuid(), category: "Same Name", value: "TOURIST & PHYSICAL ATTRACTION" },
  { id: uuid(), category: "Same Name", value: "BLUE RIBBON & PLYWOOD PANEL" },
  { id: uuid(), category: "Same Name", value: "FLOWER & TASTE BUDS" },
  {
    id: uuid(),
    category: "Same Name",
    value: "BERMUDA ELECTRICAL & SHORT SHORTS",
  },
  { id: uuid(), category: "Same Name", value: "DIANE & TOM SAWYER" },
  { id: uuid(), category: "Same Name", value: "HITCHING & TRADING POST" },
  {
    id: uuid(),
    category: "Same Name",
    value: "PROJECTION & JOHN WILKES BOOTH",
  },
  { id: uuid(), category: "Same Name", value: "INDIANA & TOMMY LEE JONES" },
  { id: uuid(), category: "Same Name", value: "PANAMA & ROOT CANAL" },
  { id: uuid(), category: "Same Name", value: "MARRIAGE POETIC & DOG LICENSE" },
  { id: uuid(), category: "Same Name", value: "NICOLAS & PARAKEET CAGE" },
  {
    id: uuid(),
    category: "Same Name",
    value: "SHARON BLARNEY & ROLLING STONE",
  },
  { id: uuid(), category: "Same Name", value: "HELEN & TREASURE HUNT" },
  { id: uuid(), category: "Same Name", value: "NORTH & TELEPHONE POLE" },
  { id: uuid(), category: "Same Name", value: "IRISH & JET SETTER" },
  { id: uuid(), category: "Same Name", value: "WORLD WIDE & SPIDER WEB" },
  { id: uuid(), category: "Same Name", value: "MAPLE & GOLD LEAF" },
  { id: uuid(), category: "Same Name", value: "PILLOW & SNOWBALL FIGHT" },
  { id: uuid(), category: "Same Name", value: "ARABIAN & SEA HORSE" },
  { id: uuid(), category: "Same Name", value: "BOYSENBERRY & ESKIMO PIE" },
  { id: uuid(), category: "Same Name", value: "TUNA & ICE CREAM SANDWICH" },
  { id: uuid(), category: "Same Name", value: "GROCERY & TOP TEN LIST" },
  { id: uuid(), category: "Same Name", value: "LOADING & STRIKE ZONE" },
  { id: uuid(), category: "Same Name", value: "CURLING & STEAM IRON" },
  { id: uuid(), category: "Same Name", value: "SCREEN & MONEY-SAVER" },
  { id: uuid(), category: "Same Name", value: "DRESS & AREA CODE" },
  { id: uuid(), category: "Same Name", value: "HELICOPTER & PALM PILOT" },
  { id: uuid(), category: "Same Name", value: "EYE & LIGHT BULB SOCKET" },
  { id: uuid(), category: "Same Name", value: "NICOLAS & BIRD CAGE" },
  { id: uuid(), category: "Same Name", value: "DOG & FUNNY BONE" },
  { id: uuid(), category: "Same Name", value: "MAPLE & COUGH SYRUP" },
  { id: uuid(), category: "Same Name", value: "LILY & SHOULDER PADS" },
  { id: uuid(), category: "Same Name", value: "BRAIN & TIDAL WAVE" },
  { id: uuid(), category: "Same Name", value: "FIRE & SPACE STATION" },
  { id: uuid(), category: "Same Name", value: "BATHROOM & FISH SCALES" },
  { id: uuid(), category: "Same Name", value: "PHYSICAL & TOURIST ATTRACTION" },
  { id: uuid(), category: "Same Name", value: "AIRLINE & PALM PILOT" },
  { id: uuid(), category: "Same Name", value: "PRINTING & BENCH PRESS" },
  { id: uuid(), category: "Same Name", value: "DIANE & LEFT TURN LANE" },
  { id: uuid(), category: "Same Name", value: "FLU & THREE-POINT SHOT" },
  { id: uuid(), category: "Same Name", value: "CUCKOO & BIOLOGICAL CLOCK" },
  { id: uuid(), category: "Same Name", value: "JOHN D. & OYSTERS ROCKEFELLER" },
  { id: uuid(), category: "Same Name", value: "THE MILKY & RIGHT OF WAY" },
  { id: uuid(), category: "Same Name", value: "POGO & POPSICLE STICK" },
  { id: uuid(), category: "Same Name", value: "COMPUTER & CHEESE WHIZ" },
  { id: uuid(), category: "Same Name", value: "GOLF & REFRESHER COURSE" },
  { id: uuid(), category: "Same Name", value: "PANDORA'S & POST OFFICE BOX" },
  { id: uuid(), category: "Same Name", value: "VOLLEYBALL & SUPREME COURT" },
  { id: uuid(), category: "Same Name", value: "CARPOOL & LOVERS' LANE" },
  { id: uuid(), category: "Same Name", value: "HEAVY METAL & RUBBER BAND" },
  { id: uuid(), category: "Same Name", value: "PALOMINO & SEA HORSE" },
  { id: uuid(), category: "Same Name", value: "SPINAL & GOSSIP COLUMN" },
  { id: uuid(), category: "Same Name", value: "CHAMPAGNE & FRENCH TOAST" },
  {
    id: uuid(),
    category: "Same Name",
    value: "WEDDING & CELL PHONE RECEPTION",
  },
  { id: uuid(), category: "Same Name", value: "MUSICAL & POST-IT NOTES" },
  { id: uuid(), category: "Same Name", value: "GILLIGAN'S & THOUSAND ISLAND" },
  { id: uuid(), category: "Same Name", value: "PIANO & ALICIA KEYS" },
  { id: uuid(), category: "Same Name", value: "ELECTORAL & JUNIOR COLLEGE" },
  { id: uuid(), category: "Same Name", value: "DUTY & COLLECT CALLS" },
  { id: uuid(), category: "Same Name", value: "ASSEMBLY & THE DOTTED LINE" },
  { id: uuid(), category: "Same Name", value: "SURPRISE & POLITICAL PARTY" },
  { id: uuid(), category: "Same Name", value: "GOOSE & SPEED BUMPS" },
  { id: uuid(), category: "Same Name", value: "GETTYSBURG & E-MAIL ADDRESS" },
  { id: uuid(), category: "Same Name", value: "BICYCLE & CHEESE WHEEL" },
  { id: uuid(), category: "Same Name", value: "MOTHER'S DAY & REPORT CARD" },
  { id: uuid(), category: "Same Name", value: "SURF'S & THUMBS UP" },
  { id: uuid(), category: "Same Name", value: "LOS ANGELES & HEDGE CLIPPERS" },
  { id: uuid(), category: "Same Name", value: "FAITH & BLUEBERRY HILL" },
  { id: uuid(), category: "Same Name", value: "LOVE ME & LEGAL TENDER" },
  { id: uuid(), category: "Same Name", value: "CONGA & FINISHING LINE" },
  { id: uuid(), category: "Same Name", value: "LINGERIE & ROLE MODEL" },
  { id: uuid(), category: "Same Name", value: "BRIDAL & METEOR SHOWER" },
  { id: uuid(), category: "Same Name", value: "MADISON SQUARE & OLIVE GARDEN" },
  { id: uuid(), category: "Same Name", value: "ITALIAN & DRY ICE" },
  {
    id: uuid(),
    category: "Same Name",
    value: "THE BUDDY & DEWEY DECIMAL SYSTEM",
  },
  { id: uuid(), category: "Same Name", value: "EXPIRATION & STUDY DATE" },
  { id: uuid(), category: "Same Name", value: "MARRIAGE & POETIC LICENSE" },
  { id: uuid(), category: "Same Name", value: "KNOCKOUT & FRUIT PUNCH" },
  { id: uuid(), category: "Same Name", value: "ENGLISH & DISCOVERY CHANNEL" },
  { id: uuid(), category: "Same Name", value: "LOTTERY & MUSICAL NUMBERS" },
  { id: uuid(), category: "Same Name", value: "CAPTAIN'S & CHEESE LOG" },
  { id: uuid(), category: "Same Name", value: "BLARNEY & SHARON STONE" },
  { id: uuid(), category: "Same Name", value: "BERNIE & FLEETWOOD MAC" },
  { id: uuid(), category: "Same Name", value: "HISTORICAL & HOURGLASS FIGURE" },
  { id: uuid(), category: "Same Name", value: "WRITER'S & H&R BLOCK" },
  { id: uuid(), category: "Same Name", value: "STOCK MARKET & BABY BOOM" },
  { id: uuid(), category: "Same Name", value: "FINANCIAL & BAND-AID" },
  { id: uuid(), category: "Same Name", value: "EXPENSE & EYEWITNESS ACCOUNT" },
  { id: uuid(), category: "Same Name", value: "MONKEY & SINGLES BARS" },
  {
    id: uuid(),
    category: "Same Name",
    value: "BUFFALO & THE WIND BENEATH MY WINGS",
  },
  { id: uuid(), category: "Same Name", value: "BUFFALO & CREDIT CARD BILL" },
  { id: uuid(), category: "Same Name", value: "THE LION & BURGER KING" },
  { id: uuid(), category: "Same Name", value: "THE HUMAN & NASCAR RACE" },
  { id: uuid(), category: "Same Name", value: "COMMERCIAL & SPRING BREAK" },
  { id: uuid(), category: "Same Name", value: "DRUM & DECLARING A MAJOR" },
  { id: uuid(), category: "Same Name", value: "GUITAR & TOP DRAFT" },
  { id: uuid(), category: "Same Name", value: "ROOT BEER & MARDI GRAS FLOAT" },
  { id: uuid(), category: "Same Name", value: "COMMUTER & THE GRAVY TRAIN" },
  { id: uuid(), category: "Same Name", value: "LOUISIANA & PROOF OF PURCHASE" },
  { id: uuid(), category: "Same Name", value: "CORDLESS & FIRE DRILL" },
  { id: uuid(), category: "Same Name", value: "PERSONAL & REALITY CHECK" },
  { id: uuid(), category: "Same Name", value: "CHRISTMAS & VISA CARD" },
  { id: uuid(), category: "Same Name", value: "ELECTRICAL & CREATIVE OUTLET" },
  { id: uuid(), category: "Same Name", value: "BEDTIME & SUCCESS STORY" },
  {
    id: uuid(),
    category: "Same Name",
    value: "NEW YEAR'S & UNITED NATIONS RESOLUTION",
  },
  { id: uuid(), category: "Same Name", value: "HUGH & GOVERNMENT GRANT" },
  { id: uuid(), category: "Same Name", value: "RUMOR & PEPPER MILL" },
  { id: uuid(), category: "Same Name", value: "ECONOMIC & FUMBLE RECOVERY" },
  { id: uuid(), category: "Same Name", value: "TOUCHDOWN & WEDDING RECEPTION" },
  { id: uuid(), category: "Same Name", value: "TUPPERWARE & BACHELOR PARTY" },
  { id: uuid(), category: "Same Name", value: "MATTRESS & LILY PAD" },
  { id: uuid(), category: "Same Name", value: "SPRINKLER & JURY SYSTEM" },
  {
    id: uuid(),
    category: "Same Name",
    value: "ULTRAVIOLET & TAMPA BAY DEVIL RAYS",
  },
  { id: uuid(), category: "Same Name", value: "OCEAN & TRASH CAN LINER" },
  { id: uuid(), category: "Same Name", value: "BERMUDA & LOVE TRIANGLE" },
  { id: uuid(), category: "Same Name", value: "CHAMPAGNE & MAGNIFYING GLASS" },
  {
    id: uuid(),
    category: "Same Name",
    value: "UPPERCASE & REGISTERED LETTERS",
  },
  {
    id: uuid(),
    category: "Same Name",
    value: "INFERIORITY & APARTMENT COMPLEX",
  },
  { id: uuid(), category: "Same Name", value: "FIRE & SEARCH ENGINE" },
  {
    id: uuid(),
    category: "Same Name",
    value: "WITNESS PROTECTION & GET WITH THE PROGRAM",
  },
  { id: uuid(), category: "Same Name", value: "REMOTE & PEST CONTROL" },
  {
    id: uuid(),
    category: "Same Name",
    value: "INCOME TAX & POINT OF NO RETURN",
  },
  { id: uuid(), category: "Same Name", value: "ARTICHOKE & KING OF HEARTS" },
  {
    id: uuid(),
    category: "Same Name",
    value: "ROLLER COASTER & PAUL REVERE'S RIDE",
  },
  { id: uuid(), category: "Same Name", value: "CHARLOTTE'S & WORLD WIDE WEB" },
  {
    id: uuid(),
    category: "Same Name",
    value: "MUTUAL ADMIRATION & AUDUBON SOCIETY",
  },
  { id: uuid(), category: "Same Name", value: "WINDOW & SPA TREATMENTS" },
  { id: uuid(), category: "Same Name", value: "RECYCLING & SOFT CHEWY CENTER" },
  {
    id: uuid(),
    category: "Same Name",
    value: "CINNAMON & LET THE GOOD TIMES ROLL",
  },
  { id: uuid(), category: "Same Name", value: "JODIE & BANANAS FOSTER" },
  { id: uuid(), category: "Same Name", value: "BLACK-TIE & FOREIGN AFFAIRS" },
  { id: uuid(), category: "Same Name", value: "DENZEL & SEATTLE WASHINGTON" },
  { id: uuid(), category: "Same Name", value: "MICKEY & WIRELESS MOUSE" },
  {
    id: uuid(),
    category: "Same Name",
    value: "NATIONAL GEOGRAPHIC & HIGH SOCIETY",
  },
  { id: uuid(), category: "Same Name", value: "LEMON MERINGUE & CUTIE PIE" },
  { id: uuid(), category: "Same Name", value: "CHRIS & CLASSIC ROCK" },
  { id: uuid(), category: "Same Name", value: "ALEXANDER GRAHAM & TACO BELL" },
  { id: uuid(), category: "Same Name", value: "MINNESOTA & OLSEN TWINS" },
  { id: uuid(), category: "Same Name", value: "MICHAEL & CROSSING JORDAN" },
  { id: uuid(), category: "Same Name", value: "PIZZA & UPPER CRUST" },
  { id: uuid(), category: "Same Name", value: "MAGAZINE & MANHOLE COVER" },
  { id: uuid(), category: "Same Name", value: "WILLIE & HALF NELSON" },
  { id: uuid(), category: "Same Name", value: "TORTILLA & BARGAINING CHIP" },
  { id: uuid(), category: "Same Name", value: "ANIMAL & TAX SHELTER" },
  { id: uuid(), category: "Same Name", value: "PHONE & HAIR EXTENSIONS" },
  { id: uuid(), category: "Same Name", value: "ORLANDO & FULL BLOOM" },
  {
    id: uuid(),
    category: "Same Name",
    value: "MICROSOFT & DRIVE THRU WINDOWS",
  },
  { id: uuid(), category: "Same Name", value: "FRUIT & BELT LOOPS" },
  { id: uuid(), category: "Same Name", value: "COSMETICS & BEAN COUNTER" },
  { id: uuid(), category: "Same Name", value: "PAUL & SIMPLE SIMON" },
  { id: uuid(), category: "Same Name", value: "FORT & YOUR MONEY'S WORTH" },
  { id: uuid(), category: "Same Name", value: "DIANE & MEMORY LANE" },
  { id: uuid(), category: "Same Name", value: "BREATHING & GAME ROOM" },
  { id: uuid(), category: "Same Name", value: "TENNIS & KITCHEN MATCHES" },
  { id: uuid(), category: "Same Name", value: "FRONT PORCH & MOOD SWING" },
  { id: uuid(), category: "Same Name", value: "ORCHESTRA & PEACH PIT" },
  { id: uuid(), category: "Same Name", value: "STRAWBERRY & TRAFFIC JAM" },
  { id: uuid(), category: "Same Name", value: "DINNER & FASHION PLATE" },
  { id: uuid(), category: "Same Name", value: "PERSONNEL & NAIL FILE" },
  {
    id: uuid(),
    category: "Same Name",
    value: "THE O'REILLY & WIND-CHILL FACTOR",
  },
  { id: uuid(), category: "Same Name", value: "TIRE & PEER PRESSURE" },
  { id: uuid(), category: "Same Name", value: "FANTASTIC & FINAL FOUR" },
  { id: uuid(), category: "Same Name", value: "RAINBOW & INTERNET CONNECTION" },
  { id: uuid(), category: "Same Name", value: "CAKE & WITNESS STAND" },
  { id: uuid(), category: "Same Name", value: "BIRD & WEIGHT WATCHERS" },
  { id: uuid(), category: "Same Name", value: "ASPARAGUS & BEAUTY TIPS" },
  { id: uuid(), category: "Same Name", value: "PORK & COLD SHOULDER" },
  { id: uuid(), category: "Same Name", value: "EXCLAMATION & WEST POINT" },
  { id: uuid(), category: "Same Name", value: "ALL-STAR & PLASTER CAST" },
  { id: uuid(), category: "Same Name", value: "THREE-HOLE & FRUIT PUNCH" },
  { id: uuid(), category: "Same Name", value: "PROTEIN & SNOOZE BAR" },
  { id: uuid(), category: "Same Name", value: "OLIVER & PLOT TWIST" },
  { id: uuid(), category: "Same Name", value: "GINGERBREAD & RIGHT-HAND MAN" },
  { id: uuid(), category: "Same Name", value: "TOMATO & POWER PLANT" },
  { id: uuid(), category: "Same Name", value: "MATTRESS AND PALM SPRINGS" },
  { id: uuid(), category: "Same Name", value: "ARCTIC & INTERNET EXPLORER" },
  { id: uuid(), category: "Same Name", value: "CAREER & POCKET CHANGE" },
  { id: uuid(), category: "Same Name", value: "DAISY & SUPERMARKET CHANGE" },
  { id: uuid(), category: "Same Name", value: "PRARIE & CHILI DOG" },
  { id: uuid(), category: "Same Name", value: "SESAME & EASY STREET" },
  { id: uuid(), category: "Same Name", value: "EMOTIONAL & VACUUM CLEANER" },
  { id: uuid(), category: "Same Name", value: "ROCKEFELLER & MARSHMALLOW" },
  { id: uuid(), category: "Same Name", value: "ANNIE & CARNEGIE HALL" },
  { id: uuid(), category: "Same Name", value: "HONOR & SUBWAY SYSTEM" },
  { id: uuid(), category: "Same Name", value: "JAMES & SAVINGS BOND" },
  { id: uuid(), category: "Same Name", value: "STICK & FATHER FIGURE" },
  {
    id: uuid(),
    category: "Same Name",
    value: "HAMBURGER & SANTA'S LITTLE HELPER",
  },
  { id: uuid(), category: "Same Name", value: "DRASTIC & TAPE MEASURES" },
  { id: uuid(), category: "Same Name", value: "BRITISH & TOUCHY SUBJECT" },
  { id: uuid(), category: "Same Name", value: "VICTORY & SANTA'S LAP" },
  { id: uuid(), category: "Same Name", value: "BUTTE & HANNAH MONTANA" },
  { id: uuid(), category: "Same Name", value: "SALLY & SOCCER FIELD" },
  { id: uuid(), category: "Same Name", value: "OBSTACLE & APPETIZER COURSE" },
  { id: uuid(), category: "Same Name", value: "STUDENT & AUTO BODY" },
  { id: uuid(), category: "Same Name", value: "THE DA VINCI & AREA" },
  { id: uuid(), category: "Same Name", value: "ANN & CHICKEN CURRY" },
  { id: uuid(), category: "Same Name", value: "THANKLESS & BRAKE JOB" },
  { id: uuid(), category: "Same Name", value: "WILL & GRANNY SMITH" },
  { id: uuid(), category: "Same Name", value: "CAMPING & GUILT TRIP" },
  {
    id: uuid(),
    category: "Same Name",
    value: "THE WASHINGTON & SCRATCHING POST",
  },
  { id: uuid(), category: "Same Name", value: "TRYA & SAVINGS BANKS" },
  { id: uuid(), category: "Same Name", value: "CHARLIE & BAD BAD LEROY BROWN" },
  { id: uuid(), category: "Same Name", value: "CAMPAIGN & MUTE BUTTON" },
  { id: uuid(), category: "Same Name", value: "KIDDIE & GENE POOL" },
  { id: uuid(), category: "Same Name", value: "DECIMAL & STICKING POINT" },
  { id: uuid(), category: "Same Name", value: "AMERICAN & RHUBARB PIE" },
  { id: uuid(), category: "Same Name", value: "SUPREME & HANDBALL COURT" },
  { id: uuid(), category: "Same Name", value: "EXPIRATION & PROM DATE" },
  { id: uuid(), category: "Same Name", value: "BALD & SWEET SPOT" },
  { id: uuid(), category: "Same Name", value: "TWILIGHT & TOW-AWAY ZONE" },
  { id: uuid(), category: "Same Name", value: "LOVE & LOWER-CASE LETTERS" },
  { id: uuid(), category: "Same Name", value: "NICOLAS & HAMSTER CAGE" },
  { id: uuid(), category: "Same Name", value: "POLITICAL & COSTUME PARTY" },
  { id: uuid(), category: "Same Name", value: "ELECTRICAL & SHOPPING OUTLET" },
  { id: uuid(), category: "Same Name", value: "RACHAEL & MANTA RAY" },
  { id: uuid(), category: "Same Name", value: "JEFF & SUSPENSION BRIDGES" },
  { id: uuid(), category: "Same Name", value: "POKER & HELPING HAND" },
  { id: uuid(), category: "Same Name", value: "SALLY & LAVA FIELD" },
  { id: uuid(), category: "Same Name", value: "FACTS & ACTION FIGURES" },
  { id: uuid(), category: "Same Name", value: "HUMAN AND RELAY RACE" },
  { id: uuid(), category: "Same Name", value: "AIRCRAFT & MAIL CARRIER" },
  { id: uuid(), category: "Same Name", value: "TWICE-BAKED & COUCH POTATO" },
  { id: uuid(), category: "Same Name", value: "LASER & BALANCE BEAM" },
  {
    id: uuid(),
    category: "Same Name",
    value: "SAN DIEGO & CELL PHONE CHARGERS",
  },
  { id: uuid(), category: "Same Name", value: "PERIODIC & PICNIC TABLE" },
  { id: uuid(), category: "Same Name", value: "FRIAR & TUMMY TUCK" },
  { id: uuid(), category: "Same Name", value: "TACO & TINKER BELL" },
  { id: uuid(), category: "Same Name", value: "CONVERTIBLE & BIKINI TOP" },
  { id: uuid(), category: "Same Name", value: "WIRELESS & LOVE CONNECTION" },
  { id: uuid(), category: "Same Name", value: "FULL-TIME & NOSE JOB" },
  { id: uuid(), category: "Same Name", value: "LILY & LAUNCHING PAD" },
  { id: uuid(), category: "Same Name", value: "GOLF AND COLLISION COURSE" },
  { id: uuid(), category: "Same Name", value: "BRASS & BELLY BUTTONS" },
  { id: uuid(), category: "Same Name", value: "TERM & TISSUE PAPER" },
  { id: uuid(), category: "Same Name", value: "WRESTLING & FIREPLACE MATCH" },
  { id: uuid(), category: "Same Name", value: "CONGA & ASSEMBLY LINE" },
  { id: uuid(), category: "Same Name", value: "EASTER & ENERGIZER BUNNY" },
  { id: uuid(), category: "Same Name", value: "MUSEUM & CHICKEN WING" },
  { id: uuid(), category: "Same Name", value: "KARATE & PORK CHOP" },
  { id: uuid(), category: "Same Name", value: "SEMESTER & LUCKY BREAK" },
  { id: uuid(), category: "Same Name", value: "SHAINA & MARK TWAIN" },
  { id: uuid(), category: "Same Name", value: "BOWLING & IVY LEAGUE" },
  { id: uuid(), category: "Same Name", value: "SAUSAGE & MISSING LINK" },
  { id: uuid(), category: "Same Name", value: "FRATERNAL & MINNESOTA TWINS" },
  { id: uuid(), category: "Same Name", value: "TYRA & INVESTMENT BANKS" },
  { id: uuid(), category: "Same Name", value: "BOTTOMLESS & ORCHESTRA PIT" },
  { id: uuid(), category: "Same Name", value: "BASEBALL AND VAMPIRE BAT" },
  { id: uuid(), category: "Same Name", value: "BUNKER & FAITH HILL" },
  { id: uuid(), category: "Same Name", value: "LAUNDRY & DEAN'S LIST" },
  { id: uuid(), category: "Same Name", value: "GOLF & DESSERT CART" },
  { id: uuid(), category: "Same Name", value: "GINGERBREAD & LEADING MAN" },
  { id: uuid(), category: "Same Name", value: "LAUNDRY & DEAN'S LIST" },
  { id: uuid(), category: "Same Name", value: "GOLF & DESSERT CART" },
  { id: uuid(), category: "Same Name", value: "GINGERBREAD & LEADING MAN" },
  {
    id: uuid(),
    category: "Same Name",
    value: "THE NUTCRACKER & HONEYMOON SUITE",
  },
  { id: uuid(), category: "Same Name", value: "ESPRESSO & SLOT MACHINE" },
  { id: uuid(), category: "Same Name", value: "ENGAGEMENT & BOXING RING" },
  { id: uuid(), category: "Same Name", value: "KNOCKOUT & FRUIT PUNCH" },
  { id: uuid(), category: "Same Name", value: "DOTTED & CHORUS LINE" },
  { id: uuid(), category: "Same Name", value: "ARCTIC & WINNER'S CIRCLE" },
  { id: uuid(), category: "Same Name", value: "CHEVY AND WILD-GOOSE CHASE" },
  { id: uuid(), category: "Same Name", value: "ALLIGATOR & FAN BELT" },
  { id: uuid(), category: "Same Name", value: "POKER & CHOCOLATE CHIPS" },
  { id: uuid(), category: "Same Name", value: "CARPOOL & MEMORY LANE" },
  { id: uuid(), category: "Same Name", value: "POGO AND CELERY STICK" },
  { id: uuid(), category: "Same Name", value: "SATELLITE AND SIDE DISH" },
  { id: uuid(), category: "Same Name", value: "MARRIAGE & POETIC LICENSE" },
  { id: uuid(), category: "Same Name", value: "WEDDING & ONION RING" },
  { id: uuid(), category: "Same Name", value: "POLAR ICE & THINKING CAP" },
  { id: uuid(), category: "Same Name", value: "MOOD & PORCH SWINGS" },
  { id: uuid(), category: "Same Name", value: "BELLY & SNOOZE BUTTONS" },
  { id: uuid(), category: "Same Name", value: "RHUBARD AND SWEETIE PIE" },
  { id: uuid(), category: "Same Name", value: "PILLOW & TURKEY STUFFING" },
  { id: uuid(), category: "Same Name", value: "THE TWILIGHT & LOADING ZONE" },
  { id: uuid(), category: "Same Name", value: "BATTING & GRADE POINT AVERAGE" },
  { id: uuid(), category: "Same Name", value: "FAIRBANKS & BAKED ALASKA" },
  { id: uuid(), category: "Same Name", value: "BUTTON-DOWN & DOG COLLAR" },
  { id: uuid(), category: "Same Name", value: "ANDERSON & MINI COOPER" },
  { id: uuid(), category: "Same Name", value: "GARLIC & BENCH PRESS" },
  { id: uuid(), category: "Same Name", value: "SCRIMMAGE & CHORUS LINE" },
  { id: uuid(), category: "Same Name", value: "SWEET & COUCH POTATO" },
  { id: uuid(), category: "Same Name", value: "WEDDING & RUBBER BAND" },
  { id: uuid(), category: "Same Name", value: "DINNER & LICENSE PLATE" },
  { id: uuid(), category: "Same Name", value: "THE DA VINCI & MORSE CODE" },
  { id: uuid(), category: "Same Name", value: "GRANOLA & CHIN-UP BAR" },
  { id: uuid(), category: "Same Name", value: "NICOLAS & BATTING CAGE" },
  { id: uuid(), category: "Same Name", value: "TRAPEZE & GRAPHIC ARTIST" },
  { id: uuid(), category: "Same Name", value: "KNITTING & COMPASS NEEDLE" },
  { id: uuid(), category: "Same Name", value: "NORTH & BARBER POLE" },
  { id: uuid(), category: "Same Name", value: "SHERLOCK & KATIE HOLMES" },
  { id: uuid(), category: "Same Name", value: "BINGO & MESS HALL" },
  { id: uuid(), category: "Same Name", value: "BARGAIN AND BIG-GAME HUNTER" },
  { id: uuid(), category: "Same Name", value: "PASSENGER & BRIDAL TRAIN" },
  { id: uuid(), category: "Same Name", value: "MUSCLE & DIAL TONE" },
  { id: uuid(), category: "Same Name", value: "SUPREME & HOMECOMING COURT" },
  { id: uuid(), category: "Same Name", value: "ENGAGEMENT & ONION RING" },
  { id: uuid(), category: "Same Name", value: "SPELLING & QUEEN BEE" },
  { id: uuid(), category: "Same Name", value: "BRIDAL & METEOR SHOWER" },
  { id: uuid(), category: "Same Name", value: "BEDTIME & SUCESS STORY" },
  { id: uuid(), category: "Same Name", value: "DISCO & COTTON BALL" },
  { id: uuid(), category: "Same Name", value: "PUMPKIN & CUTIE PIE" },
  { id: uuid(), category: "Same Name", value: "GOOGLE AND JOB SEARCH" },
  { id: uuid(), category: "Same Name", value: "SEVEN-LAYER & SKINNY-DIP" },
  { id: uuid(), category: "Same Name", value: "ELEPHANT & CARGO TRUNK" },
  { id: uuid(), category: "Same Name", value: "SUPER AND CEREAL BOWL" },
  { id: uuid(), category: "Same Name", value: "POPSICLE AND HOCKEY STICK" },
  { id: uuid(), category: "Same Name", value: "MASSAGE AND POOL TABLE" },
  { id: uuid(), category: "Same Name", value: "DANCING AND DAIRY QUEEN" },
  { id: uuid(), category: "Same Name", value: "LAS VEGAS & COMIC STRIP" },
  { id: uuid(), category: "Same Name", value: "CANDY & PULL-UP BAR" },
  { id: uuid(), category: "Same Name", value: "NO-PARKING & TWILIGHT ZONE" },
  { id: uuid(), category: "Same Name", value: "BULLETIN & BOOGIE BOARD" },
  { id: uuid(), category: "Same Name", value: "BOWLING AND CARPOOL LANE" },
  { id: uuid(), category: "Same Name", value: "SURPRISE AND BRIDAL PARTY" },
  { id: uuid(), category: "Same Name", value: "ROOT BEER & PARADE FLOAT" },
  { id: uuid(), category: "Same Name", value: "PUNCHING & TOTE BAG" },
  { id: uuid(), category: "Same Name", value: "WRINKLE AND SOUR CREAM" },
  { id: uuid(), category: "Same Name", value: "BUFFALO & TELEPHONE BILLS" },
  { id: uuid(), category: "Same Name", value: "QUESTION AND BEAUTY MARK" },
  { id: uuid(), category: "Same Name", value: "GRAVY AND CHOO-CHOO TRAIN" },
  { id: uuid(), category: "Same Name", value: "BARGAINING & POTATO CHIP" },
  { id: uuid(), category: "Same Name", value: "BLUEBERRY AND FAITH HILL" },
  { id: uuid(), category: "Same Name", value: "SATELLITE AND SOAP DISH" },
  {
    id: uuid(),
    category: "Same Name",
    value: "WEDDING & CELL PHONE RECEPTION",
  },
  { id: uuid(), category: "Same Name", value: "REAL ESTATE & SECRET AGENT" },
  { id: uuid(), category: "Same Name", value: "GETTYSBURG & E-MAIL ADDRESS" },
  { id: uuid(), category: "Same Name", value: "LILY AND LEGAL PAD" },
  { id: uuid(), category: "Same Name", value: "SORORITY AND TREE HOUSE" },
  { id: uuid(), category: "Same Name", value: "RACQUETBALL AND TRAFFIC COURT" },
  { id: uuid(), category: "Same Name", value: "MATING AND CONFERENCE CALL" },
  { id: uuid(), category: "Same Name", value: "GINGERBREAD & SELF-MADE MAN" },
  { id: uuid(), category: "Same Name", value: "HOCKEY AND FISH STICKS" },
  { id: uuid(), category: "Same Name", value: "GARDEN AND SUPPORT HOSE" },
  { id: uuid(), category: "Same Name", value: "BOWLING AND DEBUTANTE BALL" },
  {
    id: uuid(),
    category: "Same Name",
    value: "THE SCARLET & REGISTERED LETTER",
  },
  { id: uuid(), category: "Same Name", value: "WILLIE AND FULL NELSON" },
  { id: uuid(), category: "Same Name", value: "BOOT AND BAND CAMP" },
  { id: uuid(), category: "Same Name", value: "MEG AND SAVING PRIVATE RYAN" },
  { id: uuid(), category: "Same Name", value: "BUFFALO AND DOLLAR BILLS" },
  { id: uuid(), category: "Same Name", value: "COMPUTER AND POTATO CHIPS" },
  { id: uuid(), category: "Same Name", value: "DR. AND THE WIZARD OF OZ" },
  { id: uuid(), category: "Same Name", value: "THREE-PIECE AND BIRTHDAY SUIT" },
  { id: uuid(), category: "Same Name", value: "ARCTIC AND SEWING CIRCLE" },
  { id: uuid(), category: "Same Name", value: "RUNWAY AND ROLE MODEL" },
  { id: uuid(), category: "Same Name", value: "ENGAGEMENT AND WRESTLING RING" },
  { id: uuid(), category: "Same Name", value: "MATING AND CURTAIN CALL" },
  {
    id: uuid(),
    category: "Same Name",
    value: "LEMON MERINGUE AND SWEETIE PIE",
  },
  { id: uuid(), category: "Same Name", value: "GROCERY AND SLEEPING BAG" },
  { id: uuid(), category: "Same Name", value: "KARATE AND LAMB CHOP" },
  { id: uuid(), category: "Same Name", value: "FISHING AND POETIC LICENSE" },
  { id: uuid(), category: "Same Name", value: "SHOWER AND BOTTLE CAP" },
  { id: uuid(), category: "Same Name", value: "NEON AND ZODIAC SIGN" },
  { id: uuid(), category: "Same Name", value: "CUFF AND SAUSAGE LINKS" },
]
export default puzzleList
