import { v4 as uuid } from "uuid"
import { Puzzle } from "../../types/Puzzle"
const puzzleList: Puzzle[] = [
  { id: uuid(), category: "Show Biz", value: "JOHNNY'S TONIGHT SHOW FAREWELL" },
  { id: uuid(), category: "Show Biz", value: "COACH STAR CRAIG T. NELSON" },
  {
    id: uuid(),
    category: "Show Biz",
    value: "GETTING A STAR ON HOLLYWOOD'S WALK OF FAME",
  },
  { id: uuid(), category: "Show Biz", value: "TALK SHOW HOST ROSIE O'DONNELL" },
  {
    id: uuid(),
    category: "Show Biz",
    value: "THE OSCAR GOES TO CUBA GOODING JR.",
  },
  { id: uuid(), category: "Show Biz", value: "COUNTRY SINGER TRAVIS TRITT" },
  { id: uuid(), category: "Show Biz", value: "DAVID DUCHOVNY IN THE X-FILES" },
  { id: uuid(), category: "Show Biz", value: "FLEETWOOD MAC REUNION TOUR" },
  { id: uuid(), category: "Show Biz", value: "WINNING A GOLDEN GLOBE AWARD" },
  {
    id: uuid(),
    category: "Show Biz",
    value: "SMILE YOU\u2019RE ON CANDID CAMERA",
  },
  { id: uuid(), category: "Show Biz", value: "KURT RUSSELL & GOLDIE HAWN" },
  { id: uuid(), category: "Show Biz", value: "BEN AFFLECK" },
  { id: uuid(), category: "Show Biz", value: "BROADWAY" },
  { id: uuid(), category: "Show Biz", value: "NYPD BLUE'S DENNIS FRANZ" },
  { id: uuid(), category: "Show Biz", value: "SPECIAL GUEST STAR" },
  {
    id: uuid(),
    category: "Show Biz",
    value: "LEAVING YOUR HANDPRINTS AT MANN'S CHINESE THEATRE",
  },
  { id: uuid(), category: "Show Biz", value: "HOLLYWOOD COLUMNIST" },
  { id: uuid(), category: "Show Biz", value: "COSTUME DESIGNER" },
  {
    id: uuid(),
    category: "Show Biz",
    value: "BRUCE SPRINGSTEEN & THE E STREET BAND",
  },
  { id: uuid(), category: "Show Biz", value: "COMEDY CLUB" },
  { id: uuid(), category: "Show Biz", value: "ALIAS SUPERSPY JENNIFER GARNER" },
  { id: uuid(), category: "Show Biz", value: "RAVE REVIEWS" },
  { id: uuid(), category: "Show Biz", value: "SET DECORATORS" },
  { id: uuid(), category: "Show Biz", value: "ROBERT DE NIRO MOVIES" },
  { id: uuid(), category: "Show Biz", value: "PLAYING TO A PACKED HOUSE" },
  { id: uuid(), category: "Show Biz", value: "MOVIE TRAILERS" },
  { id: uuid(), category: "Show Biz", value: "WILL FERRELL IN ELF" },
  { id: uuid(), category: "Show Biz", value: "GOLDEN GLOBE NOMINATIONS" },
  { id: uuid(), category: "Show Biz", value: "CASTING AGENT" },
  { id: uuid(), category: "Show Biz", value: "GRAMMY AWARD NOMINEE" },
  { id: uuid(), category: "Show Biz", value: "SOLD-OUT CONCERT" },
  { id: uuid(), category: "Show Biz", value: "PRIME TIME SITCOM GEORGE LOPEZ" },
  { id: uuid(), category: "Show Biz", value: "STAND-UP COMEDIAN" },
  { id: uuid(), category: "Show Biz", value: "BROADWAY PLAYWRIGHT" },
  { id: uuid(), category: "Show Biz", value: "LIGHTS CAMERA ACTION" },
  { id: uuid(), category: "Show Biz", value: "QUIET ON THE SET" },
  { id: uuid(), category: "Show Biz", value: "BRITISH POP STAR STING" },
  {
    id: uuid(),
    category: "Show Biz",
    value: "AMERICAN IDOL HOST RYAN SEACREST",
  },
  { id: uuid(), category: "Show Biz", value: "MOVIE SEQUEL" },
  { id: uuid(), category: "Show Biz", value: "CAST OF CHARACTERS" },
  { id: uuid(), category: "Show Biz", value: "HUEY LEWIS & THE NEWS" },
  { id: uuid(), category: "Show Biz", value: "SINGER ANNIE LENNOX" },
  { id: uuid(), category: "Show Biz", value: "SLAPSTICK COMEDY" },
  { id: uuid(), category: "Show Biz", value: "MARTIAL ARTS MOVIE" },
  { id: uuid(), category: "Show Biz", value: "ADAM SANDLER MOVIES" },
  {
    id: uuid(),
    category: "Show Biz",
    value: "SPIDER-MAN SEQUEL SETS BOX OFFICE RECORDS",
  },
  { id: uuid(), category: "Show Biz", value: "FAMED MUSICAL SOUTH PACIFIC" },
  { id: uuid(), category: "Show Biz", value: "THE WINNER'S CIRCLE" },
  { id: uuid(), category: "Show Biz", value: "IN-DEPTH INTERVIEW" },
  { id: uuid(), category: "Show Biz", value: "SITUATION COMEDY" },
  { id: uuid(), category: "Show Biz", value: "WINNING AN EMMY AWARD" },
  { id: uuid(), category: "Show Biz", value: "FILM FESTIVAL" },
  { id: uuid(), category: "Show Biz", value: "THE STAR TREATMENT" },
  { id: uuid(), category: "Show Biz", value: "ORIGINAL SCREENPLAY" },
  {
    id: uuid(),
    category: "Show Biz",
    value: "COMIC BOOK HEROES HIT THE BIG SCREEN",
  },
  { id: uuid(), category: "Show Biz", value: "HALL & OATES" },
  { id: uuid(), category: "Show Biz", value: "THE AMERICAN MUSIC AWARDS" },
  { id: uuid(), category: "Show Biz", value: "COLLECTOR'S EDITION DVD" },
  { id: uuid(), category: "Show Biz", value: "THE ROLE OF A LIFETIME" },
  {
    id: uuid(),
    category: "Show Biz",
    value: "THE FEEL-GOOD MOVIE OF THE YEAR",
  },
  {
    id: uuid(),
    category: "Show Biz",
    value: "THE ACADEMY AWARD FOR BEST COSTUME DESIGN",
  },
  {
    id: uuid(),
    category: "Show Biz",
    value: "WE'LL BE RIGHT BACK AFTER THESE MESSAGES",
  },
  { id: uuid(), category: "Show Biz", value: "TOP FORTY COUNTDOWN" },
  { id: uuid(), category: "Show Biz", value: "A GREAT DATE MOVIE" },
  { id: uuid(), category: "Show Biz", value: "YOUR NAME IN LIGHTS" },
  {
    id: uuid(),
    category: "Show Biz",
    value: "FOR MY NEXT TRICK I'LL NEED A VOLUNTEER",
  },
  {
    id: uuid(),
    category: "Show Biz",
    value: "IT'S AN HONOR JUST TO BE NOMINATED",
  },
  { id: uuid(), category: "Show Biz", value: "SURVIVOR HOST JEFF PROBST" },
  { id: uuid(), category: "Show Biz", value: "SATELLITE RADIO" },
  { id: uuid(), category: "Show Biz", value: "AMERICAN IDOL AUDITIONS" },
  { id: uuid(), category: "Show Biz", value: "NATURE DOCUMENTARY" },
  { id: uuid(), category: "Show Biz", value: "CELEBRITY ROAST" },
  { id: uuid(), category: "Show Biz", value: "TALK RADIO" },
  { id: uuid(), category: "Show Biz", value: "STEAMY DAYTIME SOAP OPERAS" },
  {
    id: uuid(),
    category: "Show Biz",
    value: "JOHN BELUSHI IN NATIONAL LAMPOON'S ANIMAL HOUSE",
  },
  { id: uuid(), category: "Show Biz", value: "THE BEACH BOYS" },
  { id: uuid(), category: "Show Biz", value: "APPLAUSE SIGN" },
  {
    id: uuid(),
    category: "Show Biz",
    value: "TWO-TIME ACADEMY AWARD WINNER HILARY SWANK",
  },
  {
    id: uuid(),
    category: "Show Biz",
    value: "A MAGICIAN NEVER REVEALS HIS SECRETS",
  },
  {
    id: uuid(),
    category: "Show Biz",
    value: "GARTH BROOKS DOMINATES THE DECADE'S MUSIC CHARTS",
  },
  { id: uuid(), category: "Show Biz", value: "A CAST OF THOUSANDS" },
  {
    id: uuid(),
    category: "Show Biz",
    value: "MARTIAL ARTS FILM STAR BRUCE LEE",
  },
  { id: uuid(), category: "Show Biz", value: "CELEBRITY ENDORSEMENT" },
  { id: uuid(), category: "Show Biz", value: "MYSTERIOUS DRAMA SERIES" },
  { id: uuid(), category: "Show Biz", value: "COMPOSER & LYRICIST" },
  { id: uuid(), category: "Show Biz", value: "BENEFIT CONCERT" },
  { id: uuid(), category: "Show Biz", value: "JUGGLER" },
  { id: uuid(), category: "Show Biz", value: "ROMANTIC COMEDIES" },
  { id: uuid(), category: "Show Biz", value: "BUDDY MOVIE" },
  { id: uuid(), category: "Show Biz", value: "ON LOCATION" },
  {
    id: uuid(),
    category: "Show Biz",
    value: "PATRICIA ARQUETTE STARS IN MEDIUM",
  },
  { id: uuid(), category: "Show Biz", value: "FASHION POLICE" },
  { id: uuid(), category: "Show Biz", value: "THE PEOPLE'S CHOICE AWARDS" },
  { id: uuid(), category: "Show Biz", value: "COSTUME FITTING" },
  { id: uuid(), category: "Show Biz", value: "HOSTING SATURDAY NIGHT LIVE" },
  { id: uuid(), category: "Show Biz", value: "GLITZ AND GLAMOUR" },
  { id: uuid(), category: "Show Biz", value: "HEADLINER & OPENING ACT" },
  {
    id: uuid(),
    category: "Show Biz",
    value: "GRAMMY AWARD FOR BEST REGGAE ALBUM",
  },
  { id: uuid(), category: "Show Biz", value: "DINNER THEATER" },
  { id: uuid(), category: "Show Biz", value: "ON-SET ROMANCE" },
  { id: uuid(), category: "Show Biz", value: "GUITAR SOLO" },
  { id: uuid(), category: "Show Biz", value: "DUELING PIANOS" },
  {
    id: uuid(),
    category: "Show Biz",
    value: "DISNEY'S CLASSIC ANIMATED FILMS",
  },
  {
    id: uuid(),
    category: "Show Biz",
    value: "JENNIFER LOVE HEWITT IN GHOST WHISPERER",
  },
  { id: uuid(), category: "Show Biz", value: "MOVIE MARATHON" },
  { id: uuid(), category: "Show Biz", value: "SATELLITE TELEVISION" },
  { id: uuid(), category: "Show Biz", value: "CHILDREN'S THEATER" },
  { id: uuid(), category: "Show Biz", value: "SLOW-MOTION INSTANT REPLAY" },
  { id: uuid(), category: "Show Biz", value: "JAZZ GUITAR" },
  { id: uuid(), category: "Show Biz", value: "OPENING NIGHT JITTERS" },
  {
    id: uuid(),
    category: "Show Biz",
    value: "ACTRESS & RECORDING ARTIST QUEEN LATIFAH",
  },
  { id: uuid(), category: "Show Biz", value: "DAYTIME DRAMAS" },
  { id: uuid(), category: "Show Biz", value: "OPENING NIGHT ON BROADWAY" },
  {
    id: uuid(),
    category: "Show Biz",
    value: "BEST SUPPORTING ACTOR GEORGE CLOONEY",
  },
  { id: uuid(), category: "Show Biz", value: "SING-ALONG" },
  { id: uuid(), category: "Show Biz", value: "MORNING DRIVE-TIME RADIO" },
  { id: uuid(), category: "Show Biz", value: "EASY LISTENING" },
  { id: uuid(), category: "Show Biz", value: "OPENING CREDITS" },
  { id: uuid(), category: "Show Biz", value: "HIT TV MEDICAL DRAMA HOUSE" },
  { id: uuid(), category: "Show Biz", value: "NEW AGE MUSIC" },
  { id: uuid(), category: "Show Biz", value: "MIDNIGHT MOVIES" },
  { id: uuid(), category: "Show Biz", value: "RHYTHM AND BLUES" },
  { id: uuid(), category: "Show Biz", value: "WEEKEND BOX OFFICE REPORT" },
  { id: uuid(), category: "Show Biz", value: "THE CROCODILE HUNTER" },
  { id: uuid(), category: "Show Biz", value: "SINGING A DUET" },
  { id: uuid(), category: "Show Biz", value: "STUNT COORDINATOR" },
  { id: uuid(), category: "Show Biz", value: "ADAPTED SCREENPLAY" },
  { id: uuid(), category: "Show Biz", value: "PUPPET THEATER" },
  { id: uuid(), category: "Show Biz", value: "THE VIENNA BOYS' CHOIR" },
  { id: uuid(), category: "Show Biz", value: "MASTER OF ILLUSION" },
  { id: uuid(), category: "Show Biz", value: "REGGAE MUSIC FESTIVAL" },
  { id: uuid(), category: "Show Biz", value: "TELEVISION MINISERIES" },
  { id: uuid(), category: "Show Biz", value: "BACKUP DANCERS" },
  {
    id: uuid(),
    category: "Show Biz",
    value: "TELEVISION PERSONALITY RACHEL RAY",
  },
  { id: uuid(), category: "Show Biz", value: "ROCK OPERA" },
  { id: uuid(), category: "Show Biz", value: "OLDIES RADIO" },
  {
    id: uuid(),
    category: "Show Biz",
    value: "DISNEY CHANNEL'S HIGH SCHOOL MUSICAL",
  },
  {
    id: uuid(),
    category: "Show Biz",
    value: "JAMES BOND RETURNS IN CASINO ROYALE",
  },
  { id: uuid(), category: "Show Biz", value: "RED HOT CHILI PEPPERS" },
  { id: uuid(), category: "Show Biz", value: "SPECIAL EFFECTS" },
  { id: uuid(), category: "Show Biz", value: "RECORDING A REGGAE ALBUM" },
  { id: uuid(), category: "Show Biz", value: "PLAYING AN ENCORE" },
  { id: uuid(), category: "Show Biz", value: "EUROPEAN CONCERT TOUR" },
  { id: uuid(), category: "Show Biz", value: "LET'S TAKE IT FROM THE TOP" },
  { id: uuid(), category: "Show Biz", value: "SPORTS TALK RADIO" },
  {
    id: uuid(),
    category: "Show Biz",
    value: "ROSIE O' DONNELL JOINS THE VIEW",
  },
  { id: uuid(), category: "Show Biz", value: "DETECTIVE DRAMAS" },
  {
    id: uuid(),
    category: "Show Biz",
    value: "POP MUSIC SUPERSTAR JUSTIN TIMBERLAKE",
  },
  { id: uuid(), category: "Show Biz", value: "VOICE-OVER NARRATION" },
  {
    id: uuid(),
    category: "Show Biz",
    value: "ACADEMY AWARDS HOSTED BY ELLEN DEGENERES",
  },
  { id: uuid(), category: "Show Biz", value: "RADIO JINGLE" },
  { id: uuid(), category: "Show Biz", value: "FREE OUTDOOR CONCERT" },
  { id: uuid(), category: "Show Biz", value: "CURTAIN CALL" },
  { id: uuid(), category: "Show Biz", value: "ADVENTURE MOVIES" },
  { id: uuid(), category: "Show Biz", value: "SUMMER MOVIE PREVIEW" },
  { id: uuid(), category: "Show Biz", value: "SHAKESPEARE IN THE PARK" },
  { id: uuid(), category: "Show Biz", value: "COMEDY DUO" },
  { id: uuid(), category: "Show Biz", value: "STAND-UP COMEDY" },
  { id: uuid(), category: "Show Biz", value: "STUNT DOUBLE" },
  { id: uuid(), category: "Show Biz", value: "TELEVISION THEME SONGS" },
  { id: uuid(), category: "Show Biz", value: "FORMER CHILD STARS" },
  { id: uuid(), category: "Show Biz", value: "SPORTS BLOOPERS" },
  { id: uuid(), category: "Show Biz", value: "AUTHENTIC FLAMENCO MUSIC" },
  { id: uuid(), category: "Show Biz", value: "THREE-DAY MUSIC FESTIVAL" },
  { id: uuid(), category: "Show Biz", value: "ONE-WOMAN SHOW" },
  { id: uuid(), category: "Show Biz", value: "RUSSELL CROWEW IN GLADIATOR" },
  { id: uuid(), category: "Show Biz", value: "HOSPITAL DRAMAS" },
  { id: uuid(), category: "Show Biz", value: "MOST ELIGIBLE BACHELORS" },
  { id: uuid(), category: "Show Biz", value: "PIANO RECITAL" },
  { id: uuid(), category: "Show Biz", value: "CONCERT IN CENTRAL PARK" },
  { id: uuid(), category: "Show Biz", value: "BOX OFFICE HITS" },
  { id: uuid(), category: "Show Biz", value: "SHOOTING ON LOCATION" },
  { id: uuid(), category: "Show Biz", value: "MOTORCYCLE STUNTS" },
  { id: uuid(), category: "Show Biz", value: "HISTORICAL DOCUMENTARY" },
  { id: uuid(), category: "Show Biz", value: "JERRY SEINFELD'S BEE MOVIE" },
  { id: uuid(), category: "Show Biz", value: "RECORDING A LIVE ALBUM" },
  { id: uuid(), category: "Show Biz", value: "LOUNGE SINGER" },
  { id: uuid(), category: "Show Biz", value: "MOVIE SEQUELS" },
  { id: uuid(), category: "Show Biz", value: "SATURDAY MATINEE" },
  { id: uuid(), category: "Show Biz", value: "THE TONY AWARDS" },
  { id: uuid(), category: "Show Biz", value: "PERFORMING A MAGIC TRICK" },
  { id: uuid(), category: "Show Biz", value: "COSTUMED FOLK DANCERS" },
  { id: uuid(), category: "Show Biz", value: "BROADWAY DEBUT" },
  { id: uuid(), category: "Show Biz", value: "REUNION CONCERT TOUR" },
  { id: uuid(), category: "Show Biz", value: "HIP-HOP MUSIC" },
  { id: uuid(), category: "Show Biz", value: "THE LADIES OF THE VIEW" },
  { id: uuid(), category: "Show Biz", value: "STUPID PET TRICKS" },
  { id: uuid(), category: "Show Biz", value: "STAGE MANAGER" },
  { id: uuid(), category: "Show Biz", value: "GRAMMY WINNER TRISHA YEARWOOD" },
  { id: uuid(), category: "Show Biz", value: "BANJO PLAYER" },
  { id: uuid(), category: "Show Biz", value: "CATCHY CALYPSO BEAT" },
  {
    id: uuid(),
    category: "Show Biz",
    value: "LEADING LADY OF DAYTIME TELEVISION",
  },
  { id: uuid(), category: "Show Biz", value: "FILM PRODUCERS AND DIRECTORS" },
  { id: uuid(), category: "Show Biz", value: "CAMEO APPEARANCE" },
  { id: uuid(), category: "Show Biz", value: "RHYTHM GUITAR" },
  { id: uuid(), category: "Show Biz", value: "COUNTRY & WESTERN BALLADS" },
  {
    id: uuid(),
    category: "Show Biz",
    value: "ORIGINAL MOTION PICTURE SOUNDTRACK",
  },
  { id: uuid(), category: "Show Biz", value: "OPENING NIGHT AT THE OPERA" },
  { id: uuid(), category: "Show Biz", value: "MOVIE REVIEWS" },
  { id: uuid(), category: "Show Biz", value: "HOLLYWOOD GOSSIP" },
  { id: uuid(), category: "Show Biz", value: "SISTER ACT" },
  { id: uuid(), category: "Show Biz", value: "OPRAH'S FAVORITE THINGS" },
  { id: uuid(), category: "Show Biz", value: "BLUES MUSICIANS" },
  { id: uuid(), category: "Show Biz", value: "AMERICAN IDOL VOTING RESULTS" },
  { id: uuid(), category: "Show Biz", value: "TELEVISION COMMERCIALS" },
  { id: uuid(), category: "Show Biz", value: "BOX OFFICE BLOCKBUSTER" },
  {
    id: uuid(),
    category: "Show Biz",
    value: "SCIENCE FICTION TELEVISION SERIES",
  },
  { id: uuid(), category: "Show Biz", value: "OUTDOOR CONCERT" },
  { id: uuid(), category: "Show Biz", value: "POLICE DRAMA" },
  { id: uuid(), category: "Show Biz", value: "STANDING OVATION" },
  { id: uuid(), category: "Show Biz", value: "THE BIG SCREEN" },
  { id: uuid(), category: "Show Biz", value: "REALITY TELEVISION" },
  { id: uuid(), category: "Show Biz", value: "IMAX MOVIE THEATER" },
  { id: uuid(), category: "Show Biz", value: "STUNT DRIVER" },
  { id: uuid(), category: "Show Biz", value: "NATIONAL GEOGRAPHIC CHANNEL" },
  { id: uuid(), category: "Show Biz", value: "SINGING SUPERSTAR CELINE DION" },
  { id: uuid(), category: "Show Biz", value: "JEOPARDY! HOST ALEX TREBEK" },
  {
    id: uuid(),
    category: "Show Biz",
    value: "MERYL STREEP STARS IN MAMMA MIA!",
  },
  { id: uuid(), category: "Show Biz", value: "SPECIAL EFFECTS" },
  { id: uuid(), category: "Show Biz", value: "MOVIE POSTER" },
  { id: uuid(), category: "Show Biz", value: "DISCOVERY CHANNEL" },
  {
    id: uuid(),
    category: "Show Biz",
    value: "PIRATES OF THE CARIBBEAN MOVIE TRILOGY",
  },
  { id: uuid(), category: "Show Biz", value: "INSTANT REPLAY" },
  {
    id: uuid(),
    category: "Show Biz",
    value: "SUPERMODEL AND TV HOST HEIDI KLUM",
  },
  { id: uuid(), category: "Show Biz", value: "ROCK MUSIC" },
  { id: uuid(), category: "Show Biz", value: "A FILM FOR THE WHOLE FAMILY" },
  { id: uuid(), category: "Show Biz", value: "DIRECTOR'S CUT" },
  { id: uuid(), category: "Show Biz", value: "READING CUE CARDS" },
  {
    id: uuid(),
    category: "Show Biz",
    value: "COMING SOON TO A THEATER NEAR YOU",
  },
  { id: uuid(), category: "Show Biz", value: "ANIMATED MOVIE" },
  { id: uuid(), category: "Show Biz", value: "HOLIDAY CONCERT" },
  { id: uuid(), category: "Show Biz", value: "AFTERSCHOOL SPECIAL" },
  { id: uuid(), category: "Show Biz", value: "ONE-ACT PLAY" },
  { id: uuid(), category: "Show Biz", value: "A FAMILY OF TRAPEZE ARTISTS" },
  { id: uuid(), category: "Show Biz", value: "LIVE BROADCAST" },
  { id: uuid(), category: "Show Biz", value: "SUPPORTING CAST" },
  { id: uuid(), category: "Show Biz", value: "DAVID LETTERMAN'S TOP TEN LIST" },
  { id: uuid(), category: "Show Biz", value: "IN THE SPOTLIGHT" },
  { id: uuid(), category: "Show Biz", value: "TV JUDGE" },
  {
    id: uuid(),
    category: "Show Biz",
    value: "MAKEUP WARDROBE AND ACCESSORIES",
  },
  { id: uuid(), category: "Show Biz", value: "ANIMATED HIT MOVIE WALL-E" },
  { id: uuid(), category: "Show Biz", value: "LIVE VIA SATELLITE" },
  { id: uuid(), category: "Show Biz", value: "THE MAGIC OF TELEVISION" },
  { id: uuid(), category: "Show Biz", value: "RAVE REVIEW" },
  { id: uuid(), category: "Show Biz", value: "OPENING ACT" },
  { id: uuid(), category: "Show Biz", value: "SMASH-HIT BROADWAY MUSICAL" },
  { id: uuid(), category: "Show Biz", value: "OUT-TAKES & BLOOPERS" },
  { id: uuid(), category: "Show Biz", value: "BACKSTAGE PASS" },
  {
    id: uuid(),
    category: "Show Biz",
    value: "VOTING FOR YOUR FAVORITE AMERICAN IDOL CONTESTANT",
  },
  { id: uuid(), category: "Show Biz", value: "TELEVISION SPIN-OFF" },
  { id: uuid(), category: "Show Biz", value: "CULT CLASSIC FILM" },
  { id: uuid(), category: "Show Biz", value: "CLIFFHANGER ENDING" },
  {
    id: uuid(),
    category: "Show Biz",
    value: "ACADEMY AWARD WINNER KATE WINSLET",
  },
  { id: uuid(), category: "Show Biz", value: "TIGHTROPE WALKER" },
  { id: uuid(), category: "Show Biz", value: "MEDIA BLITZ" },
  { id: uuid(), category: "Show Biz", value: "DIRECTOR'S CHAIR" },
  { id: uuid(), category: "Show Biz", value: "SMOOTH JAZZ" },
  { id: uuid(), category: "Show Biz", value: "CELEBRITY STYLIST" },
  { id: uuid(), category: "Show Biz", value: "ACTING COACH" },
  { id: uuid(), category: "Show Biz", value: "CAST OF CHARACTERS" },
  { id: uuid(), category: "Show Biz", value: "SNEAK PREVIEWS" },
  { id: uuid(), category: "Show Biz", value: "DELETED SCENES" },
  { id: uuid(), category: "Show Biz", value: "SCIENCE FICTION FILM" },
  {
    id: uuid(),
    category: "Show Biz",
    value: "AMERICAN IDOL SAYS GOODBYE TO PAULA",
  },
  { id: uuid(), category: "Show Biz", value: "BACKUP SINGERS" },
  { id: uuid(), category: "Show Biz", value: "INTERNET RADIO" },
  {
    id: uuid(),
    category: "Show Biz",
    value: "TOM HANKS STARS IN ANGELS & DEMONS",
  },
  { id: uuid(), category: "Show Biz", value: "DOCUMENTARY FILM" },
  { id: uuid(), category: "Show Biz", value: "TAKING CENTER STAGE" },
  { id: uuid(), category: "Show Biz", value: "HORROR MOVIE" },
  { id: uuid(), category: "Show Biz", value: "STUNT COORDINATOR" },
  { id: uuid(), category: "Show Biz", value: "OSCAR WINNER GEORGE CLOONEY" },
  { id: uuid(), category: "Show Biz", value: "STUNT COORDINATOR" },
  { id: uuid(), category: "Show Biz", value: "OSCAR WINNER GEORGE CLOONEY" },
  { id: uuid(), category: "Show Biz", value: "COMING ATTRACTIONS" },
  { id: uuid(), category: "Show Biz", value: "SITUATION COMEDY" },
  { id: uuid(), category: "Show Biz", value: "YOUR NAME IN LIGHTS" },
  { id: uuid(), category: "Show Biz", value: "SOLD-OUT PERFORMANCE" },
  { id: uuid(), category: "Show Biz", value: "STAGE FRIGHT" },
  { id: uuid(), category: "Show Biz", value: "SHORT FILM" },
  { id: uuid(), category: "Show Biz", value: "THE RED CARPET" },
  { id: uuid(), category: "Show Biz", value: "POP SINGER MARIAH CAREY" },
  { id: uuid(), category: "Show Biz", value: "LEADING LADY" },
  { id: uuid(), category: "Show Biz", value: "BROADWAY MUSICAL" },
  { id: uuid(), category: "Show Biz", value: "PLAYING RADIO CITY MUSIC HALL" },
  { id: uuid(), category: "Show Biz", value: "ROMANTIC COMEDY" },
  { id: uuid(), category: "Show Biz", value: "OPENING NUMBER" },
  { id: uuid(), category: "Show Biz", value: "FUTURISTIC BLOCKBUSTER AVATAR" },
  { id: uuid(), category: "Show Biz", value: "COURTROOM DRAMA" },
  { id: uuid(), category: "Show Biz", value: "CRITICALLY ACCLAIMED FILM" },
  { id: uuid(), category: "Show Biz", value: "SPORTS ANNOUNCER" },
  { id: uuid(), category: "Show Biz", value: "QUIET ON THE SET" },
  { id: uuid(), category: "Show Biz", value: "TELEVISION MEDICAL DRAMA HOUSE" },
  { id: uuid(), category: "Show Biz", value: "CHARACTER ACTOR" },
  { id: uuid(), category: "Show Biz", value: "ALTERNATIVE MUSIC" },
  { id: uuid(), category: "Show Biz", value: "DRESSING ROOM" },
  { id: uuid(), category: "Show Biz", value: "LIVE STUDIO AUDIENCE" },
  { id: uuid(), category: "Show Biz", value: "GUEST STAR" },
  { id: uuid(), category: "Show Biz", value: "GUITAR SOLO" },
  { id: uuid(), category: "Show Biz", value: "ANIMATED FILM" },
  { id: uuid(), category: "Show Biz", value: "DATE MOVIE" },
  { id: uuid(), category: "Show Biz", value: "HOLLYWOOD AGENT" },
  { id: uuid(), category: "Show Biz", value: "CLASSIC CARTOONS" },
  {
    id: uuid(),
    category: "Show Biz",
    value: "COUNTRY MUSIC STAR CARRIE UNDERWOOD",
  },
  { id: uuid(), category: "Show Biz", value: "SINGING A DUET" },
  {
    id: uuid(),
    category: "Show Biz",
    value: "POP MUSIC STARS THE BLACK EYED PEAS",
  },
  { id: uuid(), category: "Show Biz", value: "CELEBRITY LOOK-ALIKES" },
  { id: uuid(), category: "Show Biz", value: "MUST-SEE MOVIE" },
  { id: uuid(), category: "Show Biz", value: "GLITZ & GLAMOUR" },
  { id: uuid(), category: "Show Biz", value: "OPENING NIGHT" },
  { id: uuid(), category: "Show Biz", value: "BLUEGRASS MUSIC" },
  { id: uuid(), category: "Show Biz", value: "AN ALL-STAR CAST" },
  { id: uuid(), category: "Show Biz", value: "SEASON PREMIERE" },
  { id: uuid(), category: "Show Biz", value: "THE RAT PACK" },
  {
    id: uuid(),
    category: "Show Biz",
    value: "SCIENCE FICTION THRILLER INCEPTION",
  },
  { id: uuid(), category: "Show Biz", value: "ORIGINAL SCREENPLAY" },
  {
    id: uuid(),
    category: "Show Biz",
    value: "JULIA ROBERTS STARS IN EAT PRAY LOVE",
  },
  { id: uuid(), category: "Show Biz", value: "THE BRIGHT LIGHTS OF BROADWAY" },
  { id: uuid(), category: "Show Biz", value: "SUNDAY MATINEE" },
  { id: uuid(), category: "Show Biz", value: "TELEVISION STUDIO" },
  { id: uuid(), category: "Show Biz", value: "STARRING ROLE" },
  { id: uuid(), category: "Show Biz", value: "TAKE IT FROM THE TOP" },
  { id: uuid(), category: "Show Biz", value: "RAISING THE CURTAIN" },
  {
    id: uuid(),
    category: "Show Biz",
    value: "RECEIVING A STAR ON THE WALK OF FAME",
  },
  { id: uuid(), category: "Show Biz", value: "GOLDEN GLOBES" },
  {
    id: uuid(),
    category: "Show Biz",
    value: "ACADEMY AWARD WINNER JEFF BRIDGES",
  },
  { id: uuid(), category: "Show Biz", value: "MOVIE STARS" },
  { id: uuid(), category: "Show Biz", value: "DOCUMENTARY FILMMAKER" },
  { id: uuid(), category: "Show Biz", value: "ON-SET ROMANCE" },
  { id: uuid(), category: "Show Biz", value: "MOVIE SOUNDTRACK" },
  {
    id: uuid(),
    category: "Show Biz",
    value: "FRANKIE VALLI & THE FOUR SEASONS",
  },
  {
    id: uuid(),
    category: "Show Biz",
    value: "TELEVISION & RADIO HOST RYAN SEACREST",
  },
  {
    id: uuid(),
    category: "Show Biz",
    value: "COUNTRY MUSIC STAR KENNY CHESNEY",
  },
  { id: uuid(), category: "Show Biz", value: "THEATER IN THE PARK" },
  {
    id: uuid(),
    category: "Show Biz",
    value: "EMMYS GRAMMYS AND GOLDEN GLOBES",
  },
  {
    id: uuid(),
    category: "Show Biz",
    value: "HIGHLY ANTICIPATED FILM PREMIERE",
  },
  { id: uuid(), category: "Show Biz", value: "ACTION STAR" },
  { id: uuid(), category: "Show Biz", value: "LIMITED ENGAGEMENT" },
  {
    id: uuid(),
    category: "Show Biz",
    value: "FILM STAR ANNE HATHAWAY TO CO-HOST THE OSCARS",
  },
  { id: uuid(), category: "Show Biz", value: "WARDROBE CHANGE" },
  {
    id: uuid(),
    category: "Show Biz",
    value: "POP SINGER AND ACTOR JUSTIN TIMBERLAKE",
  },
  { id: uuid(), category: "Show Biz", value: "ONE-HIT WONDER" },
  { id: uuid(), category: "Show Biz", value: "SOLD-OUT CONCERT TOUR" },
  { id: uuid(), category: "Show Biz", value: "SINGING SUPERSTAR TAYLOR SWIFT" },
  { id: uuid(), category: "Show Biz", value: "OUTSTANDING BROADWAY MUSICAL" },
  { id: uuid(), category: "Show Biz", value: "INDEPENDENT FILM" },
  { id: uuid(), category: "Show Biz", value: "TALENT SCOUT" },
  {
    id: uuid(),
    category: "Show Biz",
    value: "AMERICAN IDOL JUDGE JENNIFER LOPEZ",
  },
  { id: uuid(), category: "Show Biz", value: "ANIMATED TELEVISION SERIES" },
  { id: uuid(), category: "Show Biz", value: "DINNER THEATER" },
  { id: uuid(), category: "Show Biz", value: "TEEN SENSATION JUSTIN BEIBER" },
  { id: uuid(), category: "Show Biz", value: "CAMEO APPEARANCE" },
  {
    id: uuid(),
    category: "Show Biz",
    value: "THE LORD OF THE RINGS MOVIE TRILOGY",
  },
  { id: uuid(), category: "Show Biz", value: "MOVIE TRAILERS" },
  { id: uuid(), category: "Show Biz", value: "MOVIE MARATHON" },
  { id: uuid(), category: "Show Biz", value: "OPENING CREDITS" },
  { id: uuid(), category: "Show Biz", value: "TWILIGHT STAR KRISTEN STEWART" },
  { id: uuid(), category: "Show Biz", value: "POP STAR KATY PERRY" },
  { id: uuid(), category: "Show Biz", value: "STAGE MANAGER" },
  { id: uuid(), category: "Show Biz", value: "JAZZ FESTIVAL" },
  { id: uuid(), category: "Show Biz", value: "MEDIA HYPE" },
  {
    id: uuid(),
    category: "Show Biz",
    value: "FAMOUS CROONER HARRY CONNICK JR.",
  },
  { id: uuid(), category: "Show Biz", value: "WALKING THE RED CARPET" },
  { id: uuid(), category: "Show Biz", value: "HOLLYWOOD MOVIE MAGIC" },
  { id: uuid(), category: "Show Biz", value: "TELEVISION THEME SONGS" },
  {
    id: uuid(),
    category: "Show Biz",
    value: "ACADEMY AWARD WINNER COLIN FIRTH",
  },
  { id: uuid(), category: "Show Biz", value: "WEEKEND BOX OFFICE REPORT" },
  {
    id: uuid(),
    category: "Show Biz",
    value: "NOW PLAYING AT A THEATER NEAR YOU",
  },
  { id: uuid(), category: "Show Biz", value: "LANDING THE LEAD ROLE" },
  { id: uuid(), category: "Show Biz", value: "INSTANT REPLAY" },
  { id: uuid(), category: "Show Biz", value: "SATELLITE RADIO" },
  { id: uuid(), category: "Show Biz", value: "WORLDWIDE SMASH-HIT MUSICAL" },
  { id: uuid(), category: "Show Biz", value: "PERFORMING A MAGIC TRICK" },
  { id: uuid(), category: "Show Biz", value: "BRASS BAND" },
  { id: uuid(), category: "Show Biz", value: "APPLAUSE SIGN" },
  { id: uuid(), category: "Show Biz", value: "THE ELEVEN O'CLOCK NEWS" },
  { id: uuid(), category: "Show Biz", value: "TELEVISION DIRECTOR" },
  {
    id: uuid(),
    category: "Show Biz",
    value: "SIMON COWELL RETURNS IN THE X FACTOR",
  },
  { id: uuid(), category: "Show Biz", value: "AWESOME MOVIE TRAILER" },
  { id: uuid(), category: "Show Biz", value: "THE LADIES OF THE VIEW" },
  { id: uuid(), category: "Show Biz", value: "HILARIOUS ROMANTIC COMEDY" },
  { id: uuid(), category: "Show Biz", value: "PLATINUM ALBUM" },
  { id: uuid(), category: "Show Biz", value: "BACKSTAGE TOUR" },
  { id: uuid(), category: "Show Biz", value: "I DO ALL MY OWN STUNTS" },
  {
    id: uuid(),
    category: "Show Biz",
    value: "TONY AWARD WINNING BROADWAY MUSICAL",
  },
  { id: uuid(), category: "Show Biz", value: "TRAPEZE ARTIST" },
  { id: uuid(), category: "Show Biz", value: "DIRECTOR'S CHAIR" },
  { id: uuid(), category: "Show Biz", value: "FILM FESTIVAL" },
  { id: uuid(), category: "Show Biz", value: "BRAD PITT STARS IN MONEYBALL" },
  {
    id: uuid(),
    category: "Show Biz",
    value: "HOLLYWOOD LEGEND CLINT EASTWOOD",
  },
  { id: uuid(), category: "Show Biz", value: "THE TALENTED CAST OF GLEE" },
  { id: uuid(), category: "Show Biz", value: "COUNTRY MUSIC ARTIST" },
  { id: uuid(), category: "Show Biz", value: "BOX OFFICE BLOCKBUSTER" },
  { id: uuid(), category: "Show Biz", value: "FULL-LENGTH ANIMATED FILM" },
  { id: uuid(), category: "Show Biz", value: "STANDING OVATION" },
  {
    id: uuid(),
    category: "Show Biz",
    value: "TOM CRUISE STARS IN MISSION: IMPOSSIBLE",
  },
  { id: uuid(), category: "Show Biz", value: "SEQUELS & PREQUELS" },
  { id: uuid(), category: "Show Biz", value: "STUNT DRIVER" },
  {
    id: uuid(),
    category: "Show Biz",
    value: "AMERICAN IDOL JUDGE RANDY JACKSON",
  },
  { id: uuid(), category: "Show Biz", value: "OPENING ACT" },
  { id: uuid(), category: "Show Biz", value: "IN THE SPOTLIGHT" },
  { id: uuid(), category: "Show Biz", value: "SUPPORTING CAST" },
  { id: uuid(), category: "Show Biz", value: "ACADEMY AWARD NOMINATION" },
  { id: uuid(), category: "Show Biz", value: "CIRCUS ACROBATS" },
  { id: uuid(), category: "Show Biz", value: "MAKEUP AND WARDROBE" },
  { id: uuid(), category: "Show Biz", value: "STAND-UP COMEDIAN" },
  { id: uuid(), category: "Show Biz", value: "TAKING CENTER STAGE" },
  { id: uuid(), category: "Show Biz", value: "OSCAR WINNER TOM HANKS" },
  { id: uuid(), category: "Show Biz", value: "REALITY TELEVISION" },
  {
    id: uuid(),
    category: "Show Biz",
    value: "COUNTRY MUSIC LEGEND DOLLY PARTON",
  },
  { id: uuid(), category: "Show Biz", value: "LIVE BROADCAST" },
  { id: uuid(), category: "Show Biz", value: "SPORTS BLOOPERS" },
  { id: uuid(), category: "Show Biz", value: "ENCORE PERFORMANCE" },
  { id: uuid(), category: "Show Biz", value: "SOLD-OUT CONCERT" },
  { id: uuid(), category: "Show Biz", value: "CLIFFHANGER ENDING" },
  { id: uuid(), category: "Show Biz", value: "CAST OF CHARACTERS" },
  { id: uuid(), category: "Show Biz", value: "YOUR NAME IN LIGHTS" },
  { id: uuid(), category: "Show Biz", value: "SINGING SENSATION MARIAH CAREY" },
  { id: uuid(), category: "Show Biz", value: "STAGE FRIGHT" },
  { id: uuid(), category: "Show Biz", value: "TALENT CONTEST" },
  { id: uuid(), category: "Show Biz", value: "THE HUMAN CANNONBALL" },
  { id: uuid(), category: "Show Biz", value: "ROMANTIC COMEDY" },
  { id: uuid(), category: "Show Biz", value: "THEME SONG FROM HAWAII FIVE-O" },
  {
    id: uuid(),
    category: "Show Biz",
    value: "ACADEMY AWARD WINNER SANDRA BULLOCK",
  },
  { id: uuid(), category: "Show Biz", value: "I'LL BE IN MY DRESSING ROOM" },
  {
    id: uuid(),
    category: "Show Biz",
    value: "ORIGINAL MOTION PICTURE SOUNDTRACK",
  },
  { id: uuid(), category: "Show Biz", value: "DOUBLE FEATURE" },
  {
    id: uuid(),
    category: "Show Biz",
    value: "AN ACTRESS MEMORIZING HER LINES",
  },
  {
    id: uuid(),
    category: "Show Biz",
    value: "TOP SPOT ON THE BILLBOARD CHARTS",
  },
  { id: uuid(), category: "Show Biz", value: "THE CRITICS AGREE" },
  {
    id: uuid(),
    category: "Show Biz",
    value: "COMING SOON TO A THEATER NEAR YOU",
  },
  { id: uuid(), category: "Show Biz", value: "MUST-SEE MOVIE" },
  { id: uuid(), category: "Show Biz", value: "RECORDING A DUET" },
  { id: uuid(), category: "Show Biz", value: "BACKUP SINGERS" },
  { id: uuid(), category: "Show Biz", value: "HIT TV SERIES THE VOICE" },
  { id: uuid(), category: "Show Biz", value: "WRITING A SCREENPLAY" },
  { id: uuid(), category: "Show Biz", value: "READING CUE CARDS" },
  { id: uuid(), category: "Show Biz", value: "DOCUMENTARY FILM" },
  { id: uuid(), category: "Show Biz", value: "SITUATION COMEDY" },
  { id: uuid(), category: "Show Biz", value: "CHARACTER ACTOR" },
  {
    id: uuid(),
    category: "Show Biz",
    value: "A STAR ON THE HOLLYWOOD WALK OF FAME",
  },
  { id: uuid(), category: "Show Biz", value: "LIVE STUDIO AUDIENCE" },
  { id: uuid(), category: "Show Biz", value: "FORMER CHILD STAR" },
  { id: uuid(), category: "Show Biz", value: "SATURDAY MATINEE" },
  { id: uuid(), category: "Show Biz", value: "TELEVISION STUDIO" },
  { id: uuid(), category: "Show Biz", value: "FREE OUTDOOR CONCERT" },
  { id: uuid(), category: "Show Biz", value: "THE BIG SCREEN" },
  { id: uuid(), category: "Show Biz", value: "RAISE THE CURTAIN" },
  { id: uuid(), category: "Show Biz", value: "STUNT DOUBLE" },
  { id: uuid(), category: "Show Biz", value: "BROADWAY DEBUT" },
  { id: uuid(), category: "Show Biz", value: "MOVIE & TELEVISION STARS" },
  {
    id: uuid(),
    category: "Show Biz",
    value: "MERYL STREEP STARS IN MAMMA MIA!",
  },
  {
    id: uuid(),
    category: "Show Biz",
    value: "I\u2019D LIKE TO THANK THE ACADEMY",
  },
  {
    id: uuid(),
    category: "Show Biz",
    value: "WRITERS DIRECTORS AND PRODUCERS",
  },
  { id: uuid(), category: "Show Biz", value: "LIVE PERFORMANCE" },
  { id: uuid(), category: "Show Biz", value: "COURTROOM DRAMA" },
  { id: uuid(), category: "Show Biz", value: "HALF-HOUR TELEVISION PROGRAM" },
  { id: uuid(), category: "Show Biz", value: "ORIGINAL SCREENPLAY" },
]
export default puzzleList
