import { v4 as uuid } from "uuid"
import { Puzzle } from "../../types/Puzzle"
const puzzleList: Puzzle[] = [
  { id: uuid(), category: "Things", value: "VITAL STATISTICS" },
  { id: uuid(), category: "Things", value: "NIELSEN RATINGS" },
  { id: uuid(), category: "Things", value: "IDAHO POTATOES" },
  { id: uuid(), category: "Things", value: "CORNED BEEF AND CABBAGE" },
  { id: uuid(), category: "Things", value: "CREDIT CARDS" },
  { id: uuid(), category: "Things", value: "DOLLARS AND CENTS" },
  { id: uuid(), category: "Things", value: "TEARS OF JOY" },
  { id: uuid(), category: "Things", value: "WINDSHIELD WIPERS" },
  { id: uuid(), category: "Things", value: "LETTERS TO THE EDITOR" },
  { id: uuid(), category: "Things", value: "OSTRICH FEATHERS" },
  { id: uuid(), category: "Things", value: "CLASS RING" },
  { id: uuid(), category: "Things", value: "BEAUTY BRAINS AND TALENT" },
  { id: uuid(), category: "Things", value: "LIFE'S SIMPLE PLEASURES" },
  { id: uuid(), category: "Things", value: "BITE-SIZE PIECES" },
  {
    id: uuid(),
    category: "Things",
    value: "DRUGS MOST COMMONLY DISPENSED BY DOCTORS",
  },
  { id: uuid(), category: "Things", value: "ROAST BEEF AND YORKSHIRE PUDDING" },
  { id: uuid(), category: "Things", value: "ALARMING STATISTICS" },
  { id: uuid(), category: "Things", value: "APPALACIAN MOUNTAINS" },
  { id: uuid(), category: "Things", value: "POKER CHIPS" },
  { id: uuid(), category: "Things", value: "HAT AND COAT" },
  { id: uuid(), category: "Things", value: "BUCKWHEAT PANCAKES" },
  { id: uuid(), category: "Things", value: "VOWELS" },
  { id: uuid(), category: "Things", value: "HOT DOG WITH MUSTARD AND PICKLES" },
  { id: uuid(), category: "Things", value: "PHOTOS IN THE FAMILY ALBUM" },
  { id: uuid(), category: "Things", value: "RAVE REVIEWS" },
  { id: uuid(), category: "Things", value: "ILLEGALLY PARKED CARS" },
  { id: uuid(), category: "Things", value: "HEREDITY AND ENVIRONMENT" },
  { id: uuid(), category: "Things", value: "UNANSWERED QUESTIONS" },
  { id: uuid(), category: "Things", value: "AREA CODE AND TELEPHONE NUMBER" },
  { id: uuid(), category: "Things", value: "TAX EVASION CHARGES" },
  { id: uuid(), category: "Things", value: "PARTY DECORATIONS" },
  { id: uuid(), category: "Things", value: "MAGNOLIA BLOSSOMS" },
  { id: uuid(), category: "Things", value: "SHEETS AND PILLOWCASES" },
  { id: uuid(), category: "Things", value: "CRAB CAKES" },
  { id: uuid(), category: "Things", value: "INNERMOST THOUGHTS" },
  { id: uuid(), category: "Things", value: "FOOD LABELING REGULATIONS" },
  { id: uuid(), category: "Things", value: "PASTRAMI ON RYE WITH MUSTARD" },
  { id: uuid(), category: "Things", value: "SINGING LESSONS" },
  { id: uuid(), category: "Things", value: "GHOSTS AND GOBLINS" },
  { id: uuid(), category: "Things", value: "PANCAKES" },
  { id: uuid(), category: "Things", value: "MEMORIES" },
  { id: uuid(), category: "Things", value: "SNEEZING FITS" },
  { id: uuid(), category: "Things", value: "COMFORTABLE SHOES" },
  { id: uuid(), category: "Things", value: "LIVERS & ONIONS" },
  { id: uuid(), category: "Things", value: "BOOTS" },
  { id: uuid(), category: "Things", value: "THUNDER LIGHTNING WIND & SLEET" },
  { id: uuid(), category: "Things", value: "HAM & SWEET POTATOES" },
  { id: uuid(), category: "Things", value: "SUSPENDERS" },
  { id: uuid(), category: "Things", value: "EYEBROWS" },
  { id: uuid(), category: "Things", value: "LIGHTLY SALTED PEANUTS" },
  { id: uuid(), category: "Things", value: "TACOS" },
  { id: uuid(), category: "Things", value: "PREHISTORIC ANIMALS" },
  { id: uuid(), category: "Things", value: "ONE-A-DAY VITAMINS" },
  { id: uuid(), category: "Things", value: "\u00a0COOKIES" },
  { id: uuid(), category: "Things", value: "VARSITY SPORTS" },
  { id: uuid(), category: "Things", value: "MASHED POTATOES" },
  { id: uuid(), category: "Things", value: "SPARKLERS" },
  { id: uuid(), category: "Things", value: "CLIMATE" },
  { id: uuid(), category: "Things", value: "BALL & CHAIN" },
  { id: uuid(), category: "Things", value: "ROLLER BLADES" },
  { id: uuid(), category: "Things", value: "RULES & REGULATIONS" },
  { id: uuid(), category: "Things", value: "BRACES" },
  { id: uuid(), category: "Things", value: "CALCIUM MAGNESIUM & IRON" },
  { id: uuid(), category: "Things", value: "EYEWITNESS ACCOUNTS" },
  { id: uuid(), category: "Things", value: "AIRWAVES" },
  {
    id: uuid(),
    category: "Things",
    value: "CENTRAL PARK'S HORSE-DRAWN CARRIAGES",
  },
  { id: uuid(), category: "Things", value: "CHILLS & FEVER" },
  {
    id: uuid(),
    category: "Things",
    value: "CLASSICAL JAZZ ROCK RAP & COUNTRY",
  },
  { id: uuid(), category: "Things", value: "ADVERBS & ADJECTIVES" },
  {
    id: uuid(),
    category: "Things",
    value: "STOP EJECT PLAY REWIND & RECORD BUTTONS",
  },
  { id: uuid(), category: "Things", value: "TRAVELER'S CHECKS" },
  { id: uuid(), category: "Things", value: "GOLDEN DELICIOUS APPLES" },
  { id: uuid(), category: "Things", value: "BODY MIND & SPIRIT" },
  { id: uuid(), category: "Things", value: "ROCKY MOUNTAIN OYSTERS" },
  { id: uuid(), category: "Things", value: "CLOSING REMARKS" },
  {
    id: uuid(),
    category: "Things",
    value: "PALETTE PAINT CANVAS EASEL & BRUSHES",
  },
  { id: uuid(), category: "Things", value: "WINDBREAKER & DECK SHOES" },
  { id: uuid(), category: "Things", value: "SEVEN NIGHTS A WEEK" },
  { id: uuid(), category: "Things", value: "BOW ARROW & QUIVER" },
  { id: uuid(), category: "Things", value: "TRACKS" },
  { id: uuid(), category: "Things", value: "FAMILY HEIRLOOMS" },
  { id: uuid(), category: "Things", value: "GUEST PRIVILEGES" },
  { id: uuid(), category: "Things", value: "SOAP BUBBLES" },
  { id: uuid(), category: "Things", value: "GLOVES" },
  { id: uuid(), category: "Things", value: "SOAPSUDS" },
  { id: uuid(), category: "Things", value: "JUMPER CABLES" },
  { id: uuid(), category: "Things", value: "ASPARAGUS SPEARS" },
  { id: uuid(), category: "Things", value: "BLUEBERRY PANCAKES & SYRUP" },
  {
    id: uuid(),
    category: "Things",
    value: "GALOSHES EARMUFFS & THERMAL UNDERWEAR",
  },
  { id: uuid(), category: "Things", value: "FLUTE & PICCOLO" },
  { id: uuid(), category: "Things", value: "PAPAYAS GUAVAS & MANGOES" },
  {
    id: uuid(),
    category: "Things",
    value: "DAFFODILS GERANIUMS AZALEAS & IRISES",
  },
  { id: uuid(), category: "Things", value: "COMPUTER GRAPHICS" },
  { id: uuid(), category: "Things", value: "BARTLETT PEARS" },
  { id: uuid(), category: "Things", value: "EMERALD PENDANT & EARRINGS" },
  { id: uuid(), category: "Things", value: "FREE SPIN LOSE A TURN & BANKRUPT" },
  { id: uuid(), category: "Things", value: "WALTZ POLKA FOX TROT & MAMBO" },
  { id: uuid(), category: "Things", value: "CAMPAIGN PROMISES" },
  { id: uuid(), category: "Things", value: "CUSTOM-MADE SUITS" },
  { id: uuid(), category: "Things", value: "HAM & CHEESE ON RYE BREAD TO GO" },
  { id: uuid(), category: "Things", value: "WHISKERS" },
  { id: uuid(), category: "Things", value: "LOVELY PARTING GIFTS" },
  { id: uuid(), category: "Things", value: "TRIVIA QUESTIONS" },
  { id: uuid(), category: "Things", value: "LIPSTICK MASCARA POWDER & BLUSH" },
  { id: uuid(), category: "Things", value: "GANDER GOOSE & GOSLING" },
  { id: uuid(), category: "Things", value: "WHOLE HALF & QUARTER NOTES" },
  { id: uuid(), category: "Things", value: "FREE REFILLS" },
  { id: uuid(), category: "Things", value: "JUMBO SHRIMP IN GARLIC BUTTER" },
  { id: uuid(), category: "Things", value: "PEPPERIDGE FARM COOKIES" },
  { id: uuid(), category: "Things", value: "JONQUILS MUMS & PANSIES" },
  { id: uuid(), category: "Things", value: "BUBBLES" },
  { id: uuid(), category: "Things", value: "PEACHES PLUMS & NECTARINES" },
  { id: uuid(), category: "Things", value: "KETCHUP MUSTARD & MAYONNAISE" },
  { id: uuid(), category: "Things", value: "ALPHA BETA GAMMA & DELTA" },
  {
    id: uuid(),
    category: "Things",
    value: "NOUNS PRONOUNS ADVERBS & ADJECTIVES",
  },
  { id: uuid(), category: "Things", value: "CHIPS & DIP" },
  { id: uuid(), category: "Things", value: "STEAK FRIES" },
  { id: uuid(), category: "Things", value: "HAND GESTURES" },
  { id: uuid(), category: "Things", value: "SKI BOOTS" },
  { id: uuid(), category: "Things", value: "BACON BITS" },
  { id: uuid(), category: "Things", value: "SOAPSUDS" },
  { id: uuid(), category: "Things", value: "CARNATIONS" },
  { id: uuid(), category: "Things", value: "PARK REVERSE NEUTRAL & DRIVE" },
  { id: uuid(), category: "Things", value: "PEA PODS" },
  { id: uuid(), category: "Things", value: "FASHIONS" },
  { id: uuid(), category: "Things", value: "COSTUMES" },
  { id: uuid(), category: "Things", value: "CONSONANTS & VOWELS" },
  { id: uuid(), category: "Things", value: "MESSAGES" },
  { id: uuid(), category: "Things", value: "GOOD-LUCK CHARMS" },
  { id: uuid(), category: "Things", value: "RYE BREAD & BUTTER" },
  { id: uuid(), category: "Things", value: "MISTLETOE & HOLLY" },
  { id: uuid(), category: "Things", value: "RAINCOAT & BOOTS" },
  { id: uuid(), category: "Things", value: "IN-ROOM MOVIES" },
  { id: uuid(), category: "Things", value: "MINUTES & HOURS" },
  { id: uuid(), category: "Things", value: "FALL FASHIONS" },
  { id: uuid(), category: "Things", value: "THIGHS" },
  { id: uuid(), category: "Things", value: "MATCHED LUGGAGE" },
  { id: uuid(), category: "Things", value: "HAWAIIAN VOLCANOES" },
  { id: uuid(), category: "Things", value: "BEST-LAID PLANS" },
  { id: uuid(), category: "Things", value: "KNITTING NEEDLES" },
  { id: uuid(), category: "Things", value: "TENNIS LESSONS" },
  { id: uuid(), category: "Things", value: "PORCELAIN FIGURINES" },
  { id: uuid(), category: "Things", value: "DESIGNER SUNGLASSES" },
  { id: uuid(), category: "Things", value: "GOOD INTENTIONS" },
  { id: uuid(), category: "Things", value: "HELPFUL HINTS" },
  { id: uuid(), category: "Things", value: "PEACHES AND NECTARINES" },
  { id: uuid(), category: "Things", value: "EXTRA CARRY-ON BAGGAGE" },
  { id: uuid(), category: "Things", value: "HOME MOVIES" },
  { id: uuid(), category: "Things", value: "GLORIOUS SUNSETS" },
  { id: uuid(), category: "Things", value: "PALM TREES AND COCONUT GROVES" },
  { id: uuid(), category: "Things", value: "HIDDEN TALENTS" },
  { id: uuid(), category: "Things", value: "STEALS AND ASSISTS" },
  { id: uuid(), category: "Things", value: "LUGGAGE TAGS" },
  { id: uuid(), category: "Things", value: "CHROME WHEELS" },
  { id: uuid(), category: "Things", value: "ADJECTIVES" },
  { id: uuid(), category: "Things", value: "BREAD CRUMBS" },
  { id: uuid(), category: "Things", value: "TONGUE TWISTERS" },
  { id: uuid(), category: "Things", value: "GOODS AND SERVICES" },
  { id: uuid(), category: "Things", value: "GADGETS AND GIZMOS" },
  { id: uuid(), category: "Things", value: "HANDMADE ORNAMENTS" },
  { id: uuid(), category: "Things", value: "CANDIED YAMS" },
  { id: uuid(), category: "Things", value: "QUICK REFLEXES" },
  { id: uuid(), category: "Things", value: "CROSSWORD PUZZLES" },
  {
    id: uuid(),
    category: "Things",
    value: "PALE BLUE SKIES AND MAJESTIC MOUNTAINS",
  },
  { id: uuid(), category: "Things", value: "MEGABYTES AND GIGABYTES" },
  { id: uuid(), category: "Things", value: "A FLEET OF SHIPS" },
  { id: uuid(), category: "Things", value: "TENNIS RACKETS" },
  { id: uuid(), category: "Things", value: "TRAVELER'S CHECKS" },
  { id: uuid(), category: "Things", value: "PURPLE LILACS" },
  { id: uuid(), category: "Things", value: "NICKELS AND DIMES" },
  { id: uuid(), category: "Things", value: "SOLID CREDENTIALS" },
  { id: uuid(), category: "Things", value: "DOT-COM COMPANIES" },
  { id: uuid(), category: "Things", value: "SWEET CONCORD GRAPES" },
  { id: uuid(), category: "Things", value: "BUMPER STICKERS" },
  { id: uuid(), category: "Things", value: "HIS & HERS MOUNTAIN BIKES" },
  { id: uuid(), category: "Things", value: "ROUGH ROADS" },
  { id: uuid(), category: "Things", value: "SCRABBLE & MONOPOLY" },
  { id: uuid(), category: "Things", value: "SPINNING PINWHEELS" },
  { id: uuid(), category: "Things", value: "HIGHWAYS" },
  { id: uuid(), category: "Things", value: "POUNDS PESOS AND FRACS" },
  { id: uuid(), category: "Things", value: "FABULOUS PRIZES" },
  { id: uuid(), category: "Things", value: "FUJI APPLES" },
  { id: uuid(), category: "Things", value: "SPEEDOMETER & ODOMETER" },
  { id: uuid(), category: "Things", value: "DISPOSABLE CONTACT LENSES" },
  { id: uuid(), category: "Things", value: "GUAVAS" },
  { id: uuid(), category: "Things", value: "BOOKS ON TAPE" },
  { id: uuid(), category: "Things", value: "POLYESTER LEISURE SUITS" },
  {
    id: uuid(),
    category: "Things",
    value: "CREAM FILLED CHOCOLATE EASTER EGGS",
  },
  { id: uuid(), category: "Things", value: "MYTHS" },
  { id: uuid(), category: "Things", value: "SELF-HELP BOOKS" },
  { id: uuid(), category: "Things", value: "COLORFUL PARASAILS" },
  { id: uuid(), category: "Things", value: "FREE ESTIMATES" },
  { id: uuid(), category: "Things", value: "FRAGRANT FLOWER LEIS" },
  { id: uuid(), category: "Things", value: "VACATION SNAPSHOTS" },
  {
    id: uuid(),
    category: "Things",
    value: "LEANING PALM TREES AND WHITE SAND BEACHES",
  },
  { id: uuid(), category: "Things", value: "HOPE & FAITH" },
  { id: uuid(), category: "Things", value: "EXTREME SPORTS" },
  { id: uuid(), category: "Things", value: "BASEBALL CAPS AND GOWNS" },
  { id: uuid(), category: "Things", value: "PRIZED POSSESSIONS" },
  { id: uuid(), category: "Things", value: "FAMOUS LAST WORDS" },
  { id: uuid(), category: "Things", value: "BRONZED BABY SHOES" },
  { id: uuid(), category: "Things", value: "RADIO WAVES" },
  { id: uuid(), category: "Things", value: "LOCAL CUSTOMS" },
  { id: uuid(), category: "Things", value: "FOGGY DAYS" },
  { id: uuid(), category: "Things", value: "GOOD MANNERS" },
  { id: uuid(), category: "Things", value: "NEW SKIS & BINDINGS" },
  { id: uuid(), category: "Things", value: "EERIE SOUND EFFECTS" },
  { id: uuid(), category: "Things", value: "RUBBER MASKS" },
  { id: uuid(), category: "Things", value: "TORTOISE SHELL EYEGLASSES" },
  {
    id: uuid(),
    category: "Things",
    value: "A PAIR OF KNEE-LENGTH KHAKI SHORTS",
  },
  { id: uuid(), category: "Things", value: "THOUGHTFUL BIRTHDAY GIFTS" },
  { id: uuid(), category: "Things", value: "FREQUENTLY ASKED QUESTIONS" },
  { id: uuid(), category: "Things", value: "ROSY CHEEKS" },
  { id: uuid(), category: "Things", value: "ANCIENT WORKS OF ART" },
  { id: uuid(), category: "Things", value: "STOCKING STUFFERS" },
  { id: uuid(), category: "Things", value: "RIBBONS AND BOWS" },
  { id: uuid(), category: "Things", value: "HOLLY & MISTLETOE" },
  { id: uuid(), category: "Things", value: "THANK-YOU NOTES" },
  { id: uuid(), category: "Things", value: "CREPE PAPER STREAMERS" },
  { id: uuid(), category: "Things", value: "BUMPS & BRUISES" },
  { id: uuid(), category: "Things", value: "SCORES & HIGHLIGHTS" },
  { id: uuid(), category: "Things", value: "FREE REFILLS" },
  { id: uuid(), category: "Things", value: "CARGO PANTS" },
  { id: uuid(), category: "Things", value: "CORNY JOKES" },
  { id: uuid(), category: "Things", value: "SWEET'N LOW EQUAL AND SPLENDA" },
  { id: uuid(), category: "Things", value: "RUBIES" },
  { id: uuid(), category: "Things", value: "TWIGS" },
  {
    id: uuid(),
    category: "Things",
    value: "DEGREES FAHRENHEIT & DEGREES CELSIUS",
  },
  { id: uuid(), category: "Things", value: "ULTRAVIOLET RAYS" },
  { id: uuid(), category: "Things", value: "KNITTING NEEDLES" },
  { id: uuid(), category: "Things", value: "CHECKS AND BALANCES" },
  { id: uuid(), category: "Things", value: "JUPITER & SATURN" },
  { id: uuid(), category: "Things", value: "PAINTINGS OF DOGS PLAYING POKER" },
  {
    id: uuid(),
    category: "Things",
    value: "WASHINGTON APPLES & IDAHO POTATOES",
  },
  { id: uuid(), category: "Things", value: "WAVES LAPPING AT THE SHORE" },
  { id: uuid(), category: "Things", value: "BICEPS & TRICEPS" },
  { id: uuid(), category: "Things", value: "HIKING BOOTS" },
  { id: uuid(), category: "Things", value: "GOOD STUDY HABITS" },
  { id: uuid(), category: "Things", value: "T-SHIRTS AND BLUE JEANS" },
  { id: uuid(), category: "Things", value: "GOOBERS AND RAISINETS" },
  { id: uuid(), category: "Things", value: "HAIR MAKEUP & WARDROBE" },
  { id: uuid(), category: "Things", value: "SEQUELS & PREQUELS" },
  { id: uuid(), category: "Things", value: "AVIATOR SUNGLASSES" },
  { id: uuid(), category: "Things", value: "OPENING CREDITS" },
  { id: uuid(), category: "Things", value: "CUFF LINKS" },
  { id: uuid(), category: "Things", value: "GRASS STAINS" },
  { id: uuid(), category: "Things", value: "DIGITS" },
  { id: uuid(), category: "Things", value: "ROASTED & SALTED MACADAMIAS" },
  { id: uuid(), category: "Things", value: "LASTING IMPRESSIONS" },
  { id: uuid(), category: "Things", value: "NATURAL RESOURCES" },
  { id: uuid(), category: "Things", value: "SMALL POTATOES" },
  { id: uuid(), category: "Things", value: "THE COLORS OF THE RAINBOW" },
  { id: uuid(), category: "Things", value: "TEXT MESSAGES" },
  { id: uuid(), category: "Things", value: "GYM SOCKS" },
  {
    id: uuid(),
    category: "Things",
    value: "PLUNGING WATERFALLS AND LUSH VALLEYS",
  },
  { id: uuid(), category: "Things", value: "JUMPING JACKS" },
  { id: uuid(), category: "Things", value: "HEAPING TABLESPOONS" },
  { id: uuid(), category: "Things", value: "FRUITY UMBRELLA" },
  { id: uuid(), category: "Things", value: "HUNGER PAINS" },
  { id: uuid(), category: "Things", value: "MANICURE AND PEDICURE" },
  { id: uuid(), category: "Things", value: "SEASHELL BRACELETS & NECKLACES" },
  { id: uuid(), category: "Things", value: "FOOTPRINTS IN THE SNOW" },
  { id: uuid(), category: "Things", value: "POST-IT NOTES" },
  { id: uuid(), category: "Things", value: "SMOKED ALMONDS" },
  { id: uuid(), category: "Things", value: "SKI GOGGLES" },
  { id: uuid(), category: "Things", value: "USERNAME AND PASSWORD" },
  { id: uuid(), category: "Things", value: "POLAR OPPOSITES" },
  { id: uuid(), category: "Things", value: "WIRELESS MOUSE AND MOUSEPAD" },
  { id: uuid(), category: "Things", value: "SUGAR COOKIES" },
  { id: uuid(), category: "Things", value: "SLEDS & TOBOGGANS" },
  { id: uuid(), category: "Things", value: "UNSPOILED OCEAN VIEWS" },
  { id: uuid(), category: "Things", value: "INFLATABLE POOL TOYS" },
  { id: uuid(), category: "Things", value: "PERCUSSION INSTRUMENTS" },
  { id: uuid(), category: "Things", value: "SUNSHINE AND BLUE SKIES" },
  { id: uuid(), category: "Things", value: "BALMY TROPICAL BREEZES" },
  { id: uuid(), category: "Things", value: "SKINNED KNEES" },
  { id: uuid(), category: "Things", value: "BRAINS AND BRAWN" },
  { id: uuid(), category: "Things", value: "BANDAGES" },
  { id: uuid(), category: "Things", value: "FOOTPRINTS IN THE SAND" },
  { id: uuid(), category: "Things", value: "HOURLY WAGES" },
  { id: uuid(), category: "Things", value: "LEAFY GREEN VEGETABLES" },
  { id: uuid(), category: "Things", value: "MEMORIES TO HAVE A LIFETIME" },
  { id: uuid(), category: "Things", value: "BOOK SMARTS & STREET SMARTS" },
  { id: uuid(), category: "Things", value: "LETTERS FROM HOME" },
  { id: uuid(), category: "Things", value: "VALUABLES" },
  { id: uuid(), category: "Things", value: "CLEAN-CUT GOOD LOOKS" },
  { id: uuid(), category: "Things", value: "HOBBIES" },
  { id: uuid(), category: "Things", value: "SNORKEL MASK AND FINS" },
  { id: uuid(), category: "Things", value: "FRIENDLY FACES" },
  { id: uuid(), category: "Things", value: "GOOD TABLE MANNERS" },
  { id: uuid(), category: "Things", value: "GENEROUS PORTIONS" },
  { id: uuid(), category: "Things", value: "WORKOUT CLOTHES" },
  { id: uuid(), category: "Things", value: "CELL PHONE RINGTONES" },
  { id: uuid(), category: "Things", value: "HAZY SKIES" },
  { id: uuid(), category: "Things", value: "QUESTIONS AND ANSWERS" },
  { id: uuid(), category: "Things", value: "JOB SKILLS" },
  { id: uuid(), category: "Things", value: "HARDCOVERS & PAPERBACKS" },
  { id: uuid(), category: "Things", value: "INCREDIBLE NATURAL WONDERS" },
  { id: uuid(), category: "Things", value: "BIG PROFITS" },
  { id: uuid(), category: "Things", value: "YOUR FAVORITE FLIP-FLOPS" },
  { id: uuid(), category: "Things", value: "COWBOY BOOTS" },
  { id: uuid(), category: "Things", value: "DISCOUNT COUPONS" },
  { id: uuid(), category: "Things", value: "BEAUTIFUL LANDSCAPES" },
  { id: uuid(), category: "Things", value: "PAPER CUPS AND PLATES" },
  { id: uuid(), category: "Things", value: "WISE INVESTMENTS" },
  { id: uuid(), category: "Things", value: "FACTS AND FIGURES" },
  { id: uuid(), category: "Things", value: "FIGURINES" },
  { id: uuid(), category: "Things", value: "DESIGNER PERFUMES & COLOGNES" },
  { id: uuid(), category: "Things", value: "INTERNET POP-UP ADS" },
  { id: uuid(), category: "Things", value: "COOL GEDGETS" },
  { id: uuid(), category: "Things", value: "BRIGHTLY COLORED BEACH UMBRELLAS" },
  { id: uuid(), category: "Things", value: "GLAZED POTS" },
  { id: uuid(), category: "Things", value: "CUSTOM-MADE BOOTS" },
  { id: uuid(), category: "Things", value: "ONE DOZEN YELLOW ROSES" },
  { id: uuid(), category: "Things", value: "CROSSWORD CLUES" },
  { id: uuid(), category: "Things", value: "WOOL GLOVES" },
  { id: uuid(), category: "Things", value: "WARM CARIBBEAN BREEZES" },
  { id: uuid(), category: "Things", value: "HIGH HOPES" },
  { id: uuid(), category: "Things", value: "DELICIOUS SMELLS" },
  { id: uuid(), category: "Things", value: "FLEXIBLE HOURS" },
  { id: uuid(), category: "Things", value: "LAWN ORNAMENTS" },
  { id: uuid(), category: "Things", value: "DESIGNER SUNGLASSES" },
  { id: uuid(), category: "Things", value: "SOFTWARE UPDATES" },
  { id: uuid(), category: "Things", value: "PIANO KEYS" },
  { id: uuid(), category: "Things", value: "FOREIGN WORDS" },
  { id: uuid(), category: "Things", value: "FOG AND MIST" },
  { id: uuid(), category: "Things", value: "PRECIOUS METALS" },
  { id: uuid(), category: "Things", value: "SKI BOOTS" },
  {
    id: uuid(),
    category: "Things",
    value: "NEATLY TRIMMED MUSTACHE AND BEARD",
  },
  { id: uuid(), category: "Things", value: "COMMON MISTAKES" },
  { id: uuid(), category: "Things", value: "CHUBBY CHEEKS" },
  { id: uuid(), category: "Things", value: "CLOSING REMARKS" },
  { id: uuid(), category: "Things", value: "ENGRAVED INVITATIONS" },
  { id: uuid(), category: "Things", value: "GLOSSY MAGAZINES" },
  { id: uuid(), category: "Things", value: "PERKS OF THE JOB" },
  { id: uuid(), category: "Things", value: "AGATHA CHRISITE MYSTERIES" },
  { id: uuid(), category: "Things", value: "CHOICE WORDS" },
  { id: uuid(), category: "Things", value: "FAIR WAGES" },
  { id: uuid(), category: "Things", value: "FUN FACTS" },
  { id: uuid(), category: "Things", value: "PRECIOUS MEMORIES" },
  { id: uuid(), category: "Things", value: "SAND AND SURF" },
  { id: uuid(), category: "Things", value: "CARE PACKAGES" },
  { id: uuid(), category: "Things", value: "SYMPHONIES BY MOZART" },
  { id: uuid(), category: "Things", value: "BYLAWS" },
  { id: uuid(), category: "Things", value: "LOFTY GOALS" },
  { id: uuid(), category: "Things", value: "WIND INSTRUMENTS" },
  { id: uuid(), category: "Things", value: "WIPER BLADES" },
  { id: uuid(), category: "Things", value: "HOME VIDEOS" },
  { id: uuid(), category: "Things", value: "VITAMIN SUPPLEMENTS" },
  { id: uuid(), category: "Things", value: "GIGABYTES" },
  { id: uuid(), category: "Things", value: "GENTLE TROPICAL BREEZES" },
  { id: uuid(), category: "Things", value: "A FEW LAUGHS" },
  { id: uuid(), category: "Things", value: "DIGITAL VACATION PHOTOS" },
  { id: uuid(), category: "Things", value: "SOCIAL NETWORKING SITES" },
  { id: uuid(), category: "Things", value: "TOUNGE TWISTERS" },
  { id: uuid(), category: "Things", value: "AFTER HOURS" },
  { id: uuid(), category: "Things", value: "HOT TOPICS" },
  { id: uuid(), category: "Things", value: "PAIR OF FRESH FLOWERS LEIS" },
  { id: uuid(), category: "Things", value: "TIKI TORCHES AROUND THE POOL" },
  { id: uuid(), category: "Things", value: "SOAP BUBBLES" },
  { id: uuid(), category: "Things", value: "SCREAMING HEADLINES" },
  { id: uuid(), category: "Things", value: "LOW PRICES" },
  { id: uuid(), category: "Things", value: "WAVES ROLLING ONTO THE SHORE" },
  { id: uuid(), category: "Things", value: "SLIP-ON SHOES" },
  { id: uuid(), category: "Things", value: "ACTIVE VOLCANOES" },
  { id: uuid(), category: "Things", value: "THE FIVE SENSES" },
  { id: uuid(), category: "Things", value: "HUGS AND KISSES" },
  { id: uuid(), category: "Things", value: "HANDCRAFTED WOODEN SHOES" },
  { id: uuid(), category: "Things", value: "GIFT CATALOGS" },
  { id: uuid(), category: "Things", value: "DOG BISCUITS" },
  { id: uuid(), category: "Things", value: "PEAK HOURS" },
  { id: uuid(), category: "Things", value: "RUM PUNCH RECIPES" },
  { id: uuid(), category: "Things", value: "FIRST MIDDLE AND LAST NAMES" },
  { id: uuid(), category: "Things", value: "UNWRITTEN RULES" },
  { id: uuid(), category: "Things", value: "THE SOOTHING SOUNDS OF THE OCEAN" },
  { id: uuid(), category: "Things", value: "SNOW FLURRIES" },
  { id: uuid(), category: "Things", value: "BOBBY PINS" },
  { id: uuid(), category: "Things", value: "TICKETS AND ITINERARY" },
  { id: uuid(), category: "Things", value: "PRICELESS WORKS OF ART" },
  { id: uuid(), category: "Things", value: "HARD WORK AND DEDICATION" },
  { id: uuid(), category: "Things", value: "STACKABLE CHAIRS" },
  { id: uuid(), category: "Things", value: "SPECTACLAR VIEWS" },
  { id: uuid(), category: "Things", value: "TAX & GRATUITY" },
  { id: uuid(), category: "Things", value: "COLORFUL PINATAS" },
  { id: uuid(), category: "Things", value: "COMMON SPANISH PHRASES" },
  { id: uuid(), category: "Things", value: "OPINIONS & ADVICE" },
  { id: uuid(), category: "Things", value: "SIMPLE PLEASURES" },
  { id: uuid(), category: "Things", value: "STEADY TRADE WINDS" },
  { id: uuid(), category: "Things", value: "CAP & GOWN" },
  { id: uuid(), category: "Things", value: "TRADING CARDS" },
  { id: uuid(), category: "Things", value: "DISPOSABLE CONTACT LENSES" },
  { id: uuid(), category: "Things", value: "BIG DREAMS" },
  { id: uuid(), category: "Things", value: "WONDERS OF NATURE" },
  { id: uuid(), category: "Things", value: "FRONT-ROW SEATS" },
  {
    id: uuid(),
    category: "Things",
    value: "MILES AND MILES OF PRISTINE COASTLINE",
  },
  { id: uuid(), category: "Things", value: "COMPOUND WORDS" },
  { id: uuid(), category: "Things", value: "WHITE SAND & GENTLE BLUE WAVES" },
  { id: uuid(), category: "Things", value: "ACRES OF LUSH FOREST" },
  { id: uuid(), category: "Things", value: "YEARBOOK PHOTOS" },
  { id: uuid(), category: "Things", value: "NICKELS DIMES AND QUARTERS" },
  { id: uuid(), category: "Things", value: "BINOCULARS & TELESCOPES" },
  { id: uuid(), category: "Things", value: "JEAN SHORTS" },
  { id: uuid(), category: "Things", value: "PUPPETS AND MARIONETTES" },
  { id: uuid(), category: "Things", value: "HYPHENS & DASHES" },
  { id: uuid(), category: "Things", value: "BRIGHTLY COLORED CATAMARANS" },
  { id: uuid(), category: "Things", value: "RULES & REGULATIONS" },
  { id: uuid(), category: "Things", value: "DICTIONARY DEFINITIONS" },
  { id: uuid(), category: "Things", value: "LUXURIOUS SUITES & FINE DINING" },
  { id: uuid(), category: "Things", value: "SHIPPING & HANDLING" },
  { id: uuid(), category: "Things", value: "LONG-TERM GOALS" },
  { id: uuid(), category: "Things", value: "PINE CONES" },
  { id: uuid(), category: "Things", value: "WOOL SOCKS" },
  { id: uuid(), category: "Things", value: "FREQUENTLY ASKED QUESTIONS" },
  { id: uuid(), category: "Things", value: "KILOGRAMS" },
  { id: uuid(), category: "Things", value: "VOCABULARY WORDS" },
  {
    id: uuid(),
    category: "Things",
    value: "THE SEVEN WONDERS OF THE ANCIENT WORLD",
  },
  { id: uuid(), category: "Things", value: "NOUNS & PRONOUNS" },
  { id: uuid(), category: "Things", value: "DOUBLE COUPONS" },
  { id: uuid(), category: "Things", value: "TEQUILA COCKTAIL RECIPES" },
  { id: uuid(), category: "Things", value: "PSYCHIC POWERS" },
  { id: uuid(), category: "Things", value: "FINS & FLIPPERS" },
  { id: uuid(), category: "Things", value: "GENTLY BLOWING TRADE WINDS" },
  { id: uuid(), category: "Things", value: "JUICY TIDBITS" },
  { id: uuid(), category: "Things", value: "AUDIO AND VIDEO" },
  { id: uuid(), category: "Things", value: "CITY STREETS AND COUNTRY ROADS" },
  { id: uuid(), category: "Things", value: "RULES OF THE ROAD" },
  { id: uuid(), category: "Things", value: "SOAPSUDS" },
  { id: uuid(), category: "Things", value: "CRYSTAL BLUE WATERS" },
  { id: uuid(), category: "Things", value: "SHOCK ABSORBERS" },
  { id: uuid(), category: "Things", value: "FOND MEMORIES" },
  { id: uuid(), category: "Things", value: "ADVERBS & ADJECTIVES" },
  { id: uuid(), category: "Things", value: "GUSTY WINDS" },
  { id: uuid(), category: "Things", value: "LEATHER GLOVES" },
  { id: uuid(), category: "Things", value: "TWIST & TURNS" },
  { id: uuid(), category: "Things", value: "LATITUDE & LONGITUDE" },
  { id: uuid(), category: "Things", value: "GOOSE BUMPS" },
  { id: uuid(), category: "Things", value: "HEART AND SOUL" },
  { id: uuid(), category: "Things", value: "THREE WISHES" },
  { id: uuid(), category: "Things", value: "MILES OF FLAWLESS SANDY" },
  { id: uuid(), category: "Things", value: "ROUND-TRIP TICKETS" },
  { id: uuid(), category: "Things", value: "TOOLS OF THE TRADE" },
  { id: uuid(), category: "Things", value: "GREETING CARDS" },
  { id: uuid(), category: "Things", value: "KHAKI PANTS" },
  { id: uuid(), category: "Things", value: "LOFTY AMBITIONS" },
  { id: uuid(), category: "Things", value: "CHARMING COVERED BRIDGES" },
  { id: uuid(), category: "Things", value: "PASSPORT STAMPS" },
  { id: uuid(), category: "Things", value: "MUSIC VIDEOS" },
  { id: uuid(), category: "Things", value: "MAPS AND CHARTS" },
  {
    id: uuid(),
    category: "Things",
    value: "ICEBERGS FLOATING IN PRISTINE WATERS",
  },
  { id: uuid(), category: "Things", value: "FOUNDING FATHERS" },
  { id: uuid(), category: "Things", value: "AFTERNOON TRADE WINDS" },
  { id: uuid(), category: "Things", value: "PALM TREES SWAYING IN THE BREEZE" },
  { id: uuid(), category: "Things", value: "MAJESTIC SNOW-CAPPED MOUNTAINS" },
  { id: uuid(), category: "Things", value: "MYSTERY AND INTRIGUE" },
  { id: uuid(), category: "Things", value: "LIMITLESS OPTIONS" },
  { id: uuid(), category: "Things", value: "OFFICIAL DUTIES" },
  { id: uuid(), category: "Things", value: "PAW PRINTS" },
  { id: uuid(), category: "Things", value: "LIMITLESS OPTIONS" },
  { id: uuid(), category: "Things", value: "OFFICIAL DUTIES" },
  { id: uuid(), category: "Things", value: "PAW PRINTS" },
  { id: uuid(), category: "Things", value: "NEW YEAR'S RESOLUTIONS" },
  { id: uuid(), category: "Things", value: "HIGH HOPES" },
  { id: uuid(), category: "Things", value: "VALUABLE OBJECTS" },
  { id: uuid(), category: "Things", value: "FUZZY EARMUFFS" },
  { id: uuid(), category: "Things", value: "TAP SHOES" },
  { id: uuid(), category: "Things", value: "RHYMING WORDS" },
  { id: uuid(), category: "Things", value: "NEON LIGHTS" },
  { id: uuid(), category: "Things", value: "BICEPS AND TRICEPS" },
  { id: uuid(), category: "Things", value: "HOME MOVIES" },
  { id: uuid(), category: "Things", value: "BRAIN WAVES" },
  { id: uuid(), category: "Things", value: "BALLET SLIPPERS" },
  { id: uuid(), category: "Things", value: "HIDDEN TALENTS" },
  { id: uuid(), category: "Things", value: "WATER CANNONS" },
  { id: uuid(), category: "Things", value: "FAMOUS LAST WORDS" },
  { id: uuid(), category: "Things", value: "NATURAL RESOURCES" },
  { id: uuid(), category: "Things", value: "FLOWERED SHIRTS AND GRASS SKIRTS" },
  { id: uuid(), category: "Things", value: "MY FAVORITE PAIR OF BLUE JEANS" },
  { id: uuid(), category: "Things", value: "MYTHS & LEGENDS" },
  { id: uuid(), category: "Things", value: "LOCAL CUSTOMS" },
  { id: uuid(), category: "Things", value: "JUMPING JACKS" },
  { id: uuid(), category: "Things", value: "FAMILIAR FACES" },
  { id: uuid(), category: "Things", value: "ROMAN NUMERALS" },
  { id: uuid(), category: "Things", value: "STUFFED ANIMALS" },
  { id: uuid(), category: "Things", value: "USERNAME AND PASSWORD" },
  { id: uuid(), category: "Things", value: "SCHOOL SUPPLIES" },
  { id: uuid(), category: "Things", value: "PREFIX AND SUFFIX" },
  { id: uuid(), category: "Things", value: "HIKING BOOTS" },
  { id: uuid(), category: "Things", value: "BANJO STRINGS" },
  { id: uuid(), category: "Things", value: "EDITORIAL CARTOONS" },
  { id: uuid(), category: "Things", value: "RED WHITE AND BLUE" },
  { id: uuid(), category: "Things", value: "FAR-FETCHED IDEA" },
  { id: uuid(), category: "Things", value: "ALL-DAY SKI LIFT TICKETS" },
  { id: uuid(), category: "Things", value: "BEST-LAID PLANS" },
  { id: uuid(), category: "Things", value: "SMILING FACES" },
  { id: uuid(), category: "Things", value: "MONOGRAMMED BATHROBES" },
  { id: uuid(), category: "Things", value: "JOKES AND PUNS" },
  { id: uuid(), category: "Things", value: "PRECIOUS METALS" },
  { id: uuid(), category: "Things", value: "SILVER & GOLD" },
  { id: uuid(), category: "Things", value: "SHOULDER PADS" },
  { id: uuid(), category: "Things", value: "MEDALS & RIBBONS" },
  { id: uuid(), category: "Things", value: "PUSH-UPS & PULL-UPS" },
  { id: uuid(), category: "Things", value: "BARBELLS & DUMBELLS" },
  { id: uuid(), category: "Things", value: "ROCK FORMATIONS" },
  { id: uuid(), category: "Things", value: "BLACK TIGHTS" },
  { id: uuid(), category: "Things", value: "CROSSWORD CLUES" },
  { id: uuid(), category: "Things", value: "PSYCHIC PREDICTIONS" },
  { id: uuid(), category: "Things", value: "NATURAL BRIDGES" },
  { id: uuid(), category: "Things", value: "HOT SPRINGS" },
  { id: uuid(), category: "Things", value: "BRAINS AND BRAWN" },
  { id: uuid(), category: "Things", value: "RANGER PROGRAMS" },
  { id: uuid(), category: "Things", value: "GENEROUS DONATIONS" },
  { id: uuid(), category: "Things", value: "PINE NEEDLES" },
  { id: uuid(), category: "Things", value: "GOGGLES POLES BINDINGS & BOOTS" },
  { id: uuid(), category: "Things", value: "GENTLE WAVES" },
  { id: uuid(), category: "Things", value: "SINKERS & BOBBERS" },
  { id: uuid(), category: "Things", value: "FOOTPRINTS IN THE SAND" },
  { id: uuid(), category: "Things", value: "MOTORCYCLE BOOTS" },
  { id: uuid(), category: "Things", value: "MATCHING OUTFITS" },
  { id: uuid(), category: "Things", value: "MAGIC TRICKS" },
  { id: uuid(), category: "Things", value: "CHILDHOOD DREAMS" },
  { id: uuid(), category: "Things", value: "MASTS AND SAILS" },
  { id: uuid(), category: "Things", value: "FAMILIAR QUOTATIONS" },
  { id: uuid(), category: "Things", value: "PEACE LOVE & HAPPINESS" },
  { id: uuid(), category: "Things", value: "ROADSIDE ATTRACTIONS" },
  { id: uuid(), category: "Things", value: "FOUR QUARTS" },
  { id: uuid(), category: "Things", value: "CLOSELY GUARDED SECRETS" },
  { id: uuid(), category: "Things", value: "GIGABYTES" },
  { id: uuid(), category: "Things", value: "AIRLINE TICKETS" },
  { id: uuid(), category: "Things", value: "SOLAR PANELS" },
  { id: uuid(), category: "Things", value: "BRIGHTLY COLORED BEACH UMBRELLAS" },
  { id: uuid(), category: "Things", value: "WINDSHIELD WIPERS" },
  { id: uuid(), category: "Things", value: "WOBBLY LEGS" },
  { id: uuid(), category: "Things", value: "FRIENDLY FACES" },
  { id: uuid(), category: "Things", value: "WOOL GLOVES" },
  { id: uuid(), category: "Things", value: "WOODEN RACQUETS" },
  { id: uuid(), category: "Things", value: "CHILDHOOD MEMORIES" },
  { id: uuid(), category: "Things", value: "BITE-SIZE PIECES" },
  { id: uuid(), category: "Things", value: "HEALTH & WELLNESS" },
  { id: uuid(), category: "Things", value: "HUGS AND KISSES" },
  { id: uuid(), category: "Things", value: "LUXURY SPA SERVICES" },
  { id: uuid(), category: "Things", value: "FAMILY TRADITIONS" },
  { id: uuid(), category: "Things", value: "PERKS OF THE JOB" },
  { id: uuid(), category: "Things", value: "SOOTHING SPA TREATMENT" },
  { id: uuid(), category: "Things", value: "SNORKEL MASK AND FINS" },
  { id: uuid(), category: "Things", value: "FLEECE EARMUFFS" },
  { id: uuid(), category: "Things", value: "HATS AND SCARFS" },
  { id: uuid(), category: "Things", value: "CHARMING LOCAL CUSTOMS" },
  { id: uuid(), category: "Things", value: "BIRDIES AND BOGIES" },
  { id: uuid(), category: "Things", value: "BINOCULARS & TELESCOPES" },
  { id: uuid(), category: "Things", value: "FOUR ACES" },
  { id: uuid(), category: "Things", value: "RETURNS & EXCHANGES" },
  { id: uuid(), category: "Things", value: "MANICURE AND PEDICURE" },
  { id: uuid(), category: "Things", value: "WEDDING VOWS" },
  { id: uuid(), category: "Things", value: "WARM DAYS AND COOL NIGHTS" },
  { id: uuid(), category: "Things", value: "FRINGE BENEFITS" },
  { id: uuid(), category: "Things", value: "ACE KING QUEEN JACK" },
  { id: uuid(), category: "Things", value: "COWBOY BOOTS" },
  { id: uuid(), category: "Things", value: "HALFTIME HIGHLIGHTS" },
  { id: uuid(), category: "Things", value: "VIVID COLORS" },
  { id: uuid(), category: "Things", value: "ACTIVE VOLCANOES" },
  { id: uuid(), category: "Things", value: "SHELLS WASHING UP ON THE BEACH" },
  { id: uuid(), category: "Things", value: "BIKE ROUTE" },
  { id: uuid(), category: "Things", value: "STOCKS AND BONDS" },
  { id: uuid(), category: "Things", value: "A FULL ARRAY OF WATERSPORTS" },
  { id: uuid(), category: "Things", value: "SATURDAY AND SUNDAY" },
  { id: uuid(), category: "Things", value: "WHITE GLOVES" },
  { id: uuid(), category: "Things", value: "DINOSAUR FOSSILS" },
  { id: uuid(), category: "Things", value: "UNWRITTEN RULES" },
  { id: uuid(), category: "Things", value: "FREQUENTLY ASKED QUESTIONS" },
  { id: uuid(), category: "Things", value: "PEAK HOURS" },
  { id: uuid(), category: "Things", value: "FABULOUS PRIZES" },
  { id: uuid(), category: "Things", value: "TRIVIA QUESTIONS" },
  { id: uuid(), category: "Things", value: "PSYCHIC POWERS" },
  { id: uuid(), category: "Things", value: "PORCELAIN FIGURINES" },
  { id: uuid(), category: "Things", value: "HEART AND SOUL" },
  { id: uuid(), category: "Things", value: "BOWS AND RIBBONS" },
  { id: uuid(), category: "Things", value: "TOOLS OF THE TRADE" },
  {
    id: uuid(),
    category: "Things",
    value: "INCREDIBLE VIEWS OF THE SHIP'S DECK",
  },
  { id: uuid(), category: "Things", value: "TWISTS AND TURNS" },
  { id: uuid(), category: "Things", value: "SIGNATURES ON A PETITION" },
  { id: uuid(), category: "Things", value: "HOPES AND AMBITIONS" },
  { id: uuid(), category: "Things", value: "SLEEPING BAGS" },
  { id: uuid(), category: "Things", value: "CASCADING WATERFALLS" },
  { id: uuid(), category: "Things", value: "ROUND-TRIP TICKETS" },
  { id: uuid(), category: "Things", value: "KHAKI SHORTS" },
  { id: uuid(), category: "Things", value: "PEARL EARRINGS" },
  { id: uuid(), category: "Things", value: "HARDWARE AND SOFTWARE" },
  { id: uuid(), category: "Things", value: "HOME MOVIES" },
  { id: uuid(), category: "Things", value: "SINGLES DOUBLES AND TRIPLES" },
  { id: uuid(), category: "Things", value: "DAZZLING DIAMONDS" },
  {
    id: uuid(),
    category: "Things",
    value: "TRAVEL-SIZE SHAMPOO & CONDITIONER",
  },
  { id: uuid(), category: "Things", value: "BABY CLOTHES" },
  { id: uuid(), category: "Things", value: "WEIGHTS AND MEASURES" },
  { id: uuid(), category: "Things", value: "GIGABYTES" },
  { id: uuid(), category: "Things", value: "MILES OF AMAZING LAVA FIELDS" },
  { id: uuid(), category: "Things", value: "NATURAL HOT MINERAL SPRINGS" },
  { id: uuid(), category: "Things", value: "RULES & REGULATIONS" },
  { id: uuid(), category: "Things", value: "SHOOTING STARS" },
  { id: uuid(), category: "Things", value: "TIMELESS TREASURES" },
  { id: uuid(), category: "Things", value: "FIVE GOLDEN RINGS" },
  { id: uuid(), category: "Things", value: "ROARING WATERFALLS" },
  { id: uuid(), category: "Things", value: "HOT TOPICS" },
  { id: uuid(), category: "Things", value: "PRECIOUS MOMENTS" },
  { id: uuid(), category: "Things", value: "A WINK AND A SMILE" },
  { id: uuid(), category: "Things", value: "WAVES CRASHING ALONG THE SHORE" },
  { id: uuid(), category: "Things", value: "DINNER AND A MOVIE" },
  { id: uuid(), category: "Things", value: "MUFFLED VOICES" },
  { id: uuid(), category: "Things", value: "WHITE SAND AND GENTLE BLUE WATER" },
  { id: uuid(), category: "Things", value: "BOXING GLOVES" },
  { id: uuid(), category: "Things", value: "FRIDAY SATURDAY AND SUNDAY" },
  { id: uuid(), category: "Things", value: "EIGHT OUNCES" },
  { id: uuid(), category: "Things", value: "HAPPY FACES" },
  { id: uuid(), category: "Things", value: "THIGH-HIGH BOOTS" },
  { id: uuid(), category: "Things", value: "ANCHOVIES" },
  { id: uuid(), category: "Things", value: "RADIO WAVES" },
  { id: uuid(), category: "Things", value: "WORDS OF LOVE" },
  { id: uuid(), category: "Things", value: "BOARDROOM CHAIRS" },
  { id: uuid(), category: "Things", value: "SHARES OF STOCK" },
  { id: uuid(), category: "Things", value: "MEMORIES TO LAST A LIFETIME" },
  { id: uuid(), category: "Things", value: "WAFFLES" },
  { id: uuid(), category: "Things", value: "ROWS AND ROWS OF BEACH UMBRELLAS" },
  { id: uuid(), category: "Things", value: "BOATS DOCKING AT THE MARINA" },
  { id: uuid(), category: "Things", value: "GENTLY BLOWING TRADE WINDS" },
  { id: uuid(), category: "Things", value: "DISPLAYS AND EXHIBITS" },
  { id: uuid(), category: "Things", value: "MYSTERY AND INTRIGUE" },
  { id: uuid(), category: "Things", value: "TIKI TORCHES" },
  { id: uuid(), category: "Things", value: "WEEKNIGHTS" },
  {
    id: uuid(),
    category: "Things",
    value: "HISTORY CULTURE AND NATURAL BEAUTY",
  },
  { id: uuid(), category: "Things", value: "CHEEKBONES" },
  { id: uuid(), category: "Things", value: "TRACTOR WHEELS" },
  { id: uuid(), category: "Things", value: "PUDGY CHEEKS" },
  { id: uuid(), category: "Things", value: "PIANO LESSONS" },
  { id: uuid(), category: "Things", value: "ELEVATOR DOORS" },
  {
    id: uuid(),
    category: "Things",
    value: "APRIL JUNE SEPTEMBER AND NOVEMBER",
  },
  { id: uuid(), category: "Things", value: "OIL & VINEGAR" },
  { id: uuid(), category: "Things", value: "PUFFY CLOUDS" },
  { id: uuid(), category: "Things", value: "PSYCHIC PREDICTIONS" },
]
export default puzzleList
