import { v4 as uuid } from "uuid"
import { Puzzle } from "../../types/Puzzle"
const puzzleList: Puzzle[] = [
  { id: uuid(), category: "What Are You Doing?", value: "PUTTING ON SUNBLOCK" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "PET SITTING FOR A FRIEND",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "SKIMMING THROUGH A GUIDEBOOK",
  },
  { id: uuid(), category: "What Are You Doing?", value: "EXCHANGING GIFTS" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "WALKING ACROSS THE BROOKLYN BRIDGE",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "BUYING MATCHING SOMBREROS",
  },
  { id: uuid(), category: "What Are You Doing?", value: "DIRECTING A PLAY" },
  { id: uuid(), category: "What Are You Doing?", value: "WASHING THE DISHES" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "EXCHANGING DOLLARS FOR EUROS",
  },
  { id: uuid(), category: "What Are You Doing?", value: "LAUGHING OUT LOUD" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "FROSTING A BATCH OF COOKIES",
  },
  { id: uuid(), category: "What Are You Doing?", value: "KNITTING A SCARF" },
  { id: uuid(), category: "What Are You Doing?", value: "COMMUTING TO WORK" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "BUILDING A SNOW FORT",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "REMINISCING WITH OLD FRIENDS",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "SIPPING A COLD DRINK BY THE POOL",
  },
  { id: uuid(), category: "What Are You Doing?", value: "TUNING A UKELELE" },
  { id: uuid(), category: "What Are You Doing?", value: "FIXING A SNACK" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "CLEANING OUT THE CLOSET",
  },
  { id: uuid(), category: "What Are You Doing?", value: "GOOFING OFF" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "UNLOADING THE DISHWASHER",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "WATCHING THE BIG GAME",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "TAKING NOTES IN CLASS",
  },
  { id: uuid(), category: "What Are You Doing?", value: "THROWING A PARTY" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "READING A BEDTIME STORY",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "DOWNLOADING A PODCAST",
  },
  { id: uuid(), category: "What Are You Doing?", value: "BUYING A VOWEL" },
  { id: uuid(), category: "What Are You Doing?", value: "DANCING IN THE SAND" },
  { id: uuid(), category: "What Are You Doing?", value: "GETTING ORGANIZED" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "LOOKING FOR BREAKING NEWS ON THE INTERNET",
  },
  { id: uuid(), category: "What Are You Doing?", value: "WRAPPING A PRESENT" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "SOAKING UP SOME RAYS",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "SLIDING DOWN THE BANISTER",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "PACKING LIGHTWEIGHT CLOTHES",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "RUNNING ERRANDS ON SATURDAY",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "ORDERING FETTUCCINE ALFREDO",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "BURYING MY FEET IN THE WARM SAND",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "SINGING THE NATIONAL ANTHEM",
  },
  { id: uuid(), category: "What Are You Doing?", value: "HOLDING HANDS" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "LEARNING HOW TO YODEL",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "SPLASHING IN A FOUNTAIN",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "DIGGING INTO A BOWL OF GUACAMOLE",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "RENTING A SNORKEL MASK & FINS",
  },
  { id: uuid(), category: "What Are You Doing?", value: "CARPOOLING TO WORK" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "SPENDING A QUIET EVENING AT HOME",
  },
  { id: uuid(), category: "What Are You Doing?", value: "PLANTING A GARDEN" },
  { id: uuid(), category: "What Are You Doing?", value: "SHUFFLING THE CARDS" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "CHECKING MY HOROSCOPE",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "KICKING BACK AND RELAXING",
  },
  { id: uuid(), category: "What Are You Doing?", value: "SLICING PINEAPPLES" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "SHARING A PITCHER OF MARGARITAS",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "FINISHING OFF THE CHIPS AND SALSA",
  },
  { id: uuid(), category: "What Are You Doing?", value: "DECORATING A CAKE" },
  { id: uuid(), category: "What Are You Doing?", value: "MOWING THE LAWN" },
  { id: uuid(), category: "What Are You Doing?", value: "GRILLING BURGERS" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "SAMPLING EXOTIC CHEESES",
  },
  { id: uuid(), category: "What Are You Doing?", value: "TOSSING A SALAD" },
  { id: uuid(), category: "What Are You Doing?", value: "LOUNGING POOLSIDE" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "SOAKING IN THE AWESOME SCENERY",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "RELAXING UNDER THE MIDDAY SUN",
  },
  { id: uuid(), category: "What Are You Doing?", value: "FLYING FIRST-CLASS" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "BUYING CONCERT TICKETS ONLINE",
  },
  { id: uuid(), category: "What Are You Doing?", value: "PARALLEL PARKING" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "KICKING BACK IN A PRIVATE CABANA",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "DOLPHIN & WHALE WATCHING",
  },
  { id: uuid(), category: "What Are You Doing?", value: "PEELING A BANANA" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "COLLECTING SEASHELLS AND CORAL",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "PICKING UP A GAME OF BEACH VOLLEYBALL",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "TAKING PARASAILING LESSONS",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "LOADING THE DISHWASHER",
  },
  { id: uuid(), category: "What Are You Doing?", value: "RAKING THE LEAVES" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "SETTING A GOOD EXAMPLE",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "HOPPING ON A TROLLEY CAR",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "EXCHANGING DOLLARS FOR FOREIGN CURRENCY",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "BAKING GINGERBREAD COOKIES",
  },
  { id: uuid(), category: "What Are You Doing?", value: "SLEEPING IN" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "ESCAPING TO THE ISLANDS",
  },
  { id: uuid(), category: "What Are You Doing?", value: "COUNTING SHEEP" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "COOLING OFF IN THE SHADE OF A PALM TREE",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "SHOPPING FOR A NEW SWIMSUIT",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "KISSING UNDER THE MISTLETOE",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "CURLING UP IN THE FRONT OF THE FIRE",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "ENJOYING AN AFTERNOON SIESTA IN A HAMMOCK",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "BAKING BROWNIES FROM SCRATCH",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "CHILLING OUT IN A SWAYING HAMMOCK",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "STROLLING BAREFOOT ALONG THE BEACH",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "SHARING DIGITAL PHOTOS OF MY VACATION",
  },
  { id: uuid(), category: "What Are You Doing?", value: "PLAYING CATCH-UP" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "PUTTING THE ICE ON THE CAKE",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "SHARING A BANANA SPLIT",
  },
  { id: uuid(), category: "What Are You Doing?", value: "TAKING ATTENDANCE" },
  { id: uuid(), category: "What Are You Doing?", value: "TAKING IT EASY" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "LINGERING OVER THE SUNDAY NEWSPAPER",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "GRABBING A BITE BEFORE THE SHOW",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "LOUNGING UNDER A BEACH UMBRELLA",
  },
  { id: uuid(), category: "What Are You Doing?", value: "CALLING IT A DAY" },
  { id: uuid(), category: "What Are You Doing?", value: "TELLING TALL TALES" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "SIPPING DELICIOUS RUM PUNCH",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "ENJOYING A FROZEN MARGARITA",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "SEARCHING FOR A FOUR-LEAF CLOVER",
  },
  { id: uuid(), category: "What Are You Doing?", value: "WATERING THE PLANTS" },
  { id: uuid(), category: "What Are You Doing?", value: "GOING BACKPACKING" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "PROGRAMMING YOUR DIGITAL VIDEO RECORDER",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "ADMIRING THE SUN SETTING OVER THE PACIFIC",
  },
  { id: uuid(), category: "What Are You Doing?", value: "THINKING OUT LOUD" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "SENDING A TEXT MESSAGE",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "BRUSHING UP ON MY SPANISH",
  },
  { id: uuid(), category: "What Are You Doing?", value: "GOOGLING MYSELF" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "SPORTING A NEW PAIR OF FLIP-FLOPS",
  },
  { id: uuid(), category: "What Are You Doing?", value: "DANCING THE HULA" },
  { id: uuid(), category: "What Are You Doing?", value: "READING A MAP" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "SHAKING THE SAND OUT OF MY SHOES",
  },
  { id: uuid(), category: "What Are You Doing?", value: "SIGNING A PETITION" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "PICKING UP PRODUCE AT THE FARMERS MARKET",
  },
  { id: uuid(), category: "What Are You Doing?", value: "DAYDREAMING" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "CATCHING A CABLE CAR",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "LOOKING AT PHOTOS ON FACEBOOK",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "LISTENING TO A PODCAST",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "SIZING UP THE COMPETITION",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "WHISPERING SWEET NOTHINGS",
  },
  { id: uuid(), category: "What Are You Doing?", value: "READING A COMPASS" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "SIPPING A MARGARITA ON THE BALCONY",
  },
  { id: uuid(), category: "What Are You Doing?", value: "MAKING A CHECKLIST" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "UNWINDING WITH A STROLL ON THE BEACH",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "WALKING UP TO THE SOUND OF WAVES",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "LISTENING TO LIVE REGGAE MUSIC",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "MAKING FRIENDS AT THE SWIM-UP BAR",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "WATCHING VIDEOS ON YOUTUBE",
  },
  { id: uuid(), category: "What Are You Doing?", value: "STRUMMING A UKULELE" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "DINING AT A SEASIDE BISTRO",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "FOLLOWING MY INSTINCTS",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "FEELING THE SPIRIT OF ALOHA",
  },
  { id: uuid(), category: "What Are You Doing?", value: "CUTTING THE CARDS" },
  { id: uuid(), category: "What Are You Doing?", value: "TAKING A BREATHER" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "NAPPING IN A HAMMOCK ON THE BEACH",
  },
  { id: uuid(), category: "What Are You Doing?", value: "GOING FOR BROKE" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "MAKING A GOOD FIRST IMPRESSION",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "FEELING THE COOL SEA BREEZE",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "DEEP-SEA FISHING FOR MARLIN",
  },
  { id: uuid(), category: "What Are You Doing?", value: "MAKING HISTORY" },
  { id: uuid(), category: "What Are You Doing?", value: "TRAVELING IN STYLE" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "FLIPPING THROUGH A TRAVEL MAGAZINE",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "HOOTING AND HOLLERING",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "INDULGING MYSELF AT THE SPA",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "UNWINDING AT THE INFINITY POOL",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "CHATTING ON THE TELEPHONE",
  },
  { id: uuid(), category: "What Are You Doing?", value: "PICKING APPLES" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "WALKING THE FREEDOM TRAIL",
  },
  { id: uuid(), category: "What Are You Doing?", value: "MAKING A BIG SPLASH" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "UPLOADING VIDEOS TO YOUTUBE",
  },
  { id: uuid(), category: "What Are You Doing?", value: "CATCHING SOME RAYS" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "TAKING TONS OF DIGITAL PHOTOS",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "FOLLOWING MY FRIENDS ON TWITTER",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "GOING FOR A MOONLIGHT SWIM",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "SAMPLING THE LOCAL CUISINE AT A SEASIDE GRILL",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "UPLOADING VIDEOS TO YOUTUBE",
  },
  { id: uuid(), category: "What Are You Doing?", value: "CATCHING SOME RAYS" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "TAKING TONS OF DIGITAL PHOTOS",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "FOLLOWING MY FRIENDS ON TWITTER",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "GOING FOR A MOONLIGHT SWIM",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "SAMPLING THE LOCAL CUISINE AT A SEASIDE GRILL",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "READING THE FINE PRINT",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "THE NEW YORK TIMES CROSSWORD PUZZLE",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "BROWSING THROUGH SOUVENIR SHOPS",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "POPPING OPEN A BOTTLE OF CHAMPAGNE",
  },
  { id: uuid(), category: "What Are You Doing?", value: "PUMPING IRON" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "PICKING FRESH FLOWERS",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "CURLING UP WITH A GOOD BOOK",
  },
  { id: uuid(), category: "What Are You Doing?", value: "HAILING A CAB" },
  { id: uuid(), category: "What Are You Doing?", value: "EARNING POINTS" },
  { id: uuid(), category: "What Are You Doing?", value: "WOOL CAP" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "LOOKING FOR A HOUSE SITTER",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "ASKING THE BOSS FOR SOME MORE TIME OFF",
  },
  { id: uuid(), category: "What Are You Doing?", value: "GOING TO A CONCERT" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "CHECKING MY BAGS AT THE AIRPORT",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "DISCOVERING MY FAVORITE MARGARITA",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "ENJOYING AFTERNOON TEA AND CRUMPETS",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "ORDERING DRINKS IN SPANISH",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "SEEING SPECTACULAR GLAICERS",
  },
  { id: uuid(), category: "What Are You Doing?", value: "MAKING A COMEBACK" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "GETTING DOWN TO BUSINESS",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "TAKING PHOTOS OF EXOTIC WILDLIFE",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "BIDDING IN AN ONLINE AUCTION",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "LIVING THE GOOD LIFE",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "SWINGING FOR THE FENCES",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "TAKING A DIP IN MY PRIVATE POOL",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "SNATCHING VICTORY FROM THE JAWS OF DEFEAT",
  },
  { id: uuid(), category: "What Are You Doing?", value: "THE TEXAS TWO-STEP" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "READING MY HOROSCOPE",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "MAKING BEAUTIFUL MUSIC TOGETHER",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "GRABBING ALL THE ATTENTION",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "CRUISING AROUND WITH THE TOP DOWN",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "PULL-UPS PUSH-UPS SIT-UPS AND CRUNCHES",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "BRINGING HOME THE BACON",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "SHOWING GREAT POTENTIAL",
  },
  { id: uuid(), category: "What Are You Doing?", value: "GETTING COMFORTABLE" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "BUYING A PAINTING FROM A LOCAL ARTIST",
  },
  { id: uuid(), category: "What Are You Doing?", value: "CATCHING WAVES" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "WARMING UP BY THE FIRE",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "STANDING OUT FROM THE CROWD",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "ADJUSTING THE THERMOSTAT",
  },
  { id: uuid(), category: "What Are You Doing?", value: "SAVING THE PLANET" },
  { id: uuid(), category: "What Are You Doing?", value: "WRITING A LETTER" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "RUNNING ON A TREADMILL",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "ORDERING MORE CHIPS AND SALSA",
  },
  { id: uuid(), category: "What Are You Doing?", value: "CHECKING MY E-MAIL" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "RIDING MY BICYCLE TO WORK",
  },
  { id: uuid(), category: "What Are You Doing?", value: "SITTING PRETTY" },
  { id: uuid(), category: "What Are You Doing?", value: "PLANTING A TREE" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "MAKING OUT LIKE A BANDIT",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "ATTENDING A SYMPHONY CONCERT",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "TAKING A GUIDED TOUR OF ANCIENT TEMPLES",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "COMING IN FOR A LANDING",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "ORDERING THE CHEF'S SPECIAL",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "RECHARGING MY BATTERIES",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "CHOOSING MY ELECTIVE COURSES",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "SENDING AND RECEIVING TEXT MESSAGES",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "HOLDING DOWN THE FORT",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "ENJOYING MY FIRST HAWAIIAN LUAU",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "KICKING BACK AT THE SKI LODGE",
  },
  { id: uuid(), category: "What Are You Doing?", value: "BEATING THE ODDS" },
  { id: uuid(), category: "What Are You Doing?", value: "GOING TO THE GYM" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "MAKING A TRIPLE PLAY",
  },
  { id: uuid(), category: "What Are You Doing?", value: "WORKING OVERTIME" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "WRITING OUR NAMES IN THE SAND",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "RIDING A CABLE CAR ACROSS TOWN",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "RELAXING UNDER A BEACH UMBRELLA",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "WEARING MY FAVORITE ALOHA SHIRT",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "POSTING VACATION PHOTOS ONLINE",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "PUTTING ON A NEW PAIR OF SKI BOOTS",
  },
  { id: uuid(), category: "What Are You Doing?", value: "TAGGING ALONG" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "TAKING THE INITIATIVE",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "MAKING A NAME FOR MYSELF",
  },
  { id: uuid(), category: "What Are You Doing?", value: "BALLROOM DANCING" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "MAKING A MENTAL NOTE",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "ORDERING ROOM SERVICE TO MY SUITE",
  },
  { id: uuid(), category: "What Are You Doing?", value: "GOING THE DISTANCE" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "SOUVENIR SHOPPING IN AN OPEN-AIR MARKET",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "GATHERING AROUND A ROARING FIRE",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "POSING FOR A PORTRAIT",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "ASKING FOR MORE VACATION DAYS",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "ATTRACTING ATTENTION",
  },
  { id: uuid(), category: "What Are You Doing?", value: "CASTING A SPELL" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "RENEWING MY MEMBERSHIP",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "SIPPING A PINA COLADA BY THE POOL",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "ENJOYING OCEANSIDE SPA TREATMENTS",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "FLYING UNDER THE RADAR",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "SEEING THE SIGHTS OF SOUTH BEACH",
  },
  { id: uuid(), category: "What Are You Doing?", value: "TAKING NOTES" },
  { id: uuid(), category: "What Are You Doing?", value: "PITCHING A TENT" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "SPENDING THE ENTIRE DAY AT THE SPA",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "GATHERING WOOD FOR THE FIRE",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "BUYING A NEW SET OF CARRY-ON LUGGAGE",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "TRYING TO KEEP A STRAIGHT FACE",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "WALKING BAREFOOT ALONG THE SHORE",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "ZIPPING DOWN THE WATER SLIDE",
  },
  { id: uuid(), category: "What Are You Doing?", value: "KEEPING WATCH" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "CHILLING OUT BY THE POOL",
  },
  { id: uuid(), category: "What Are You Doing?", value: "GAINING MOMENTUM" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "FLIPPING THROUGH A CATALOG",
  },
  { id: uuid(), category: "What Are You Doing?", value: "COMING ON STRONG" },
  { id: uuid(), category: "What Are You Doing?", value: "GIVING BACK" },
  { id: uuid(), category: "What Are You Doing?", value: "BREAKING THE ICE" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "SHOPPING FOR A NEW SURFBOARD",
  },
  { id: uuid(), category: "What Are You Doing?", value: "SHIFTING GEARS" },
  { id: uuid(), category: "What Are You Doing?", value: "MAKING A TOAST" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "GETTING MY FOOT IN THE DOOR",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "ORDERING DINNER IN SPANISH",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "CATCHING MY SECOND WIND",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "PASSING WITH FLYING COLORS",
  },
  { id: uuid(), category: "What Are You Doing?", value: "WASHING UP" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "BUYING MOVIE TICKETS ONLINE",
  },
  { id: uuid(), category: "What Are You Doing?", value: "DIMMING THE LIGHTS" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "TUNING IN TO MY FAVORITE SHOW",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "SKIING THROUGH FRESH POWDER SNOW",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "BREATHING A SIGH OF RELIEF",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "PLAYING MY LUCKY NUMBERS",
  },
  { id: uuid(), category: "What Are You Doing?", value: "RENTING A TUXEDO" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "UNCORKING A BOTTLE OF VINTAGE WINE",
  },
  { id: uuid(), category: "What Are You Doing?", value: "PUSHING MY LUCK" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "PULLING OUT ALL THE STOPS",
  },
  { id: uuid(), category: "What Are You Doing?", value: "CALLING THE SHOTS" },
  { id: uuid(), category: "What Are You Doing?", value: "MAKING TRAVEL PLANS" },
  { id: uuid(), category: "What Are You Doing?", value: "OPENING THE VAULT" },
  { id: uuid(), category: "What Are You Doing?", value: "DUTY-FREE SHOPPING" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "BURNING THE MIDNIGHT OIL",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "GETTING COZY BY THE FIREPLACE",
  },
  { id: uuid(), category: "What Are You Doing?", value: "TYING THE KNOT" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "DOWNLOADING DIGITAL BOOKS",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "READING TEXT MESSAGES",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "TAKING A LIMOUSINE TO THE PROM",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "CHANGING MY PROFILE PICTURE ON FACEBOOK",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "ENJOYING A PICNIC AT THE VINEYARD",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "STEALING THE SPOTLIGHT",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "CHECKING THE DAILY SURF REPORT",
  },
  { id: uuid(), category: "What Are You Doing?", value: "SETTING SAIL" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "ESCAPING TO A TROPICAL LOCATION",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "PLAYING A NEW SONG ON MY UKULELE",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "BORROWING A CUP OF SUGAR FROM MY NEIGHBORS",
  },
  { id: uuid(), category: "What Are You Doing?", value: "FIRING UP THE GRILL" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "TRYING ON A NEW PAIR OF SHOES",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "PROTECTING THE ENVIORNMENT",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "SUPPORTING THE LOCAL FARMERS MARKET",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "ASKING FOR DIRECTIONS",
  },
  { id: uuid(), category: "What Are You Doing?", value: "FEEDING THE METER" },
  { id: uuid(), category: "What Are You Doing?", value: "JOGGING IN PLACE" },
  { id: uuid(), category: "What Are You Doing?", value: "WORKING UP A SWEAT" },
  { id: uuid(), category: "What Are You Doing?", value: "MAKING A PIT STOP" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "LOUNGING BY THE POOL ALL DAY LONG",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "WEARING A BEAUTIFUL FLOWER LEI",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "STRIVING TO BE THE BEST",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "COMBING THE BEACH FOR SEASHELLS",
  },
  { id: uuid(), category: "What Are You Doing?", value: "CONNECTING THE DOTS" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "EATING LUNCH AT FISHERMAN'S WHARF",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "RELAXING IN A POOLSIDE CABANA",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "TASTING THE LOCAL RUM PUNCH",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "KICKING BACK IN THE JACUZZI",
  },
  { id: uuid(), category: "What Are You Doing?", value: "SOLVING A MYSTERY" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "HANGING OUT ON THE BEACH",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "ASKING MOM AND DAD FOR MONEY",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "WATCHING THE SUNSET FROM THE SHIP'S DECK",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "ENJOYING SCRUMPTOUS APPETIZERS",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "STOLLING THROUGH CENTRAL PARK",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "GETTING AWAY FROM IT ALL",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "TAKING THE NEXT STEP",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "TOURING COASTAL FISHING VILLAGES",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "JUMPING OVER THE NET",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "BURYING MY FEET IN THE SAND",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "SENDING POSTCARDS TO ALL MY FRIENDS",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "INVESTING IN THE FUTURE",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "ROLLING ON THE FLOOR LAUGHING",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "SETTING A GOOD EXAMPLE",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "TAKING A NICE LONG BREAK",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "WEARING A GRASS SKIRT",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "LENDING A HELPING HAND",
  },
  { id: uuid(), category: "What Are You Doing?", value: "SLEEPING IN" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "FEELING THE WARM TROPICAL BREEZE",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "CHECKING MY HOROSCOPE",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "ENJOYING THE ALOHA SPIRIT",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "JOGGING ON A TREADMILL",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "COOLING DOWN AFTER A HARD WORKOUT",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "BROADENING MY HORIZONS",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "CHECKING THE SKI & SNOW REPORT",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "BASKING IN THE WARM SUN",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "WRITING WISH YOU WERE HERE ON A POSTCARD",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "GOING THE EXTRA MILE",
  },
  { id: uuid(), category: "What Are You Doing?", value: "SOLVING A RIDDLE" },
  { id: uuid(), category: "What Are You Doing?", value: "CLIPPING COUPONS" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "WORKING AGAINST THE CLOCK",
  },
  { id: uuid(), category: "What Are You Doing?", value: "DECORATING A CAKE" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "TAKING PICTURES WITH AN UNDERWATER CAMERA",
  },
  { id: uuid(), category: "What Are You Doing?", value: "CUTTING THE GRASS" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "SWIMMING UP TO THE POOL BAR",
  },
  { id: uuid(), category: "What Are You Doing?", value: "PRACTICING MY SWING" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "READING A FILM REVIEW",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "LISTENING TO A STEEL DRUM BAND",
  },
  { id: uuid(), category: "What Are You Doing?", value: "BLOWING KISSES" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "PLAYING FOR ALL THE MARBLES",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "SLIDING DOWN THE BANISTER",
  },
  { id: uuid(), category: "What Are You Doing?", value: "POURING CHAMPAGNE" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "TOSSING A COIN INTO THE TREVI FOUNTAIN",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "BREAKING A NEW YEAR'S RESOLUTION",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "STRUMMING A SONG ON A UKULELE",
  },
  { id: uuid(), category: "What Are You Doing?", value: "PLANTING A GARDEN" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "LEARNING HOW TO KNIT",
  },
  { id: uuid(), category: "What Are You Doing?", value: "CROSSING MY FINGERS" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "GIVING IT THE OLD COLLEGE TRY",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "PATTING MYSELF ON THE BACK",
  },
  { id: uuid(), category: "What Are You Doing?", value: "POSING FOR PICTURES" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "SETTING UP THE CAMPSITE",
  },
  { id: uuid(), category: "What Are You Doing?", value: "SOAKING UP THE RAYS" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "SEEING THE SIGHTS ON THE LAS VEGAS STRIP",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "RUNNING THE OBSTACLE COURSE",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "READING A MYSTERY NOVEL",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "SHARING AN ICE CREAM SUNDAE",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "PUTTING THE ICING ON THE CAKE",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "JUMPING ON A TROLLEY CAR",
  },
  { id: uuid(), category: "What Are You Doing?", value: "LAUGHING OUT LOUD" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "INSTALLING NEW SOFTWARE",
  },
  { id: uuid(), category: "What Are You Doing?", value: "FLYING FIRST CLASS" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "JUMPING TO CONCLUSIONS",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "MAKING A WISE INVESTMENT",
  },
  { id: uuid(), category: "What Are You Doing?", value: "PLANNING MY ESCAPE" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "GETTING AN EARLY START",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "COUNTING MY NUMBER OF VACATION DAYS",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "FINDING A WAY TO WIN",
  },
  { id: uuid(), category: "What Are You Doing?", value: "THINKING OUT LOUD" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "EATING NOODLES WITH CHOPSTICKS",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "TAKING A DIP IN THE JACUZZI",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "WAITING IN THE WINGS",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "KEEPING UP WITH THE LATEST TRENDS",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "HITTING THE HOMESTRETCH",
  },
  { id: uuid(), category: "What Are You Doing?", value: "PLAYING CATCH-UP" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "LOUNGING UNDER A BEACH UMBRELLA",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "RELAXING IN THE AIRPORT LOUNGE",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "SIPPING A COLD DRINK BY THE POOL",
  },
  { id: uuid(), category: "What Are You Doing?", value: "TAKING A BREATHER" },
  { id: uuid(), category: "What Are You Doing?", value: "DAYDREAMING" },
  { id: uuid(), category: "What Are You Doing?", value: "READING THE LABEL" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "BASKING IN THE WARMTH OF THE SUN",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "RIDING IN THE BIKE LANE",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "POSTING NEW PHOTOS ON FACEBOOK",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "KICKING BACK ON MY BEACH TOWEL",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "HANDSTANDS SOMERSAULTS AND BACKFLIPS",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "CHECKING OUT VIDEOS ON YOUTUBE",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "SETTING THE RECORD STRAIGHT",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "LISTENING TO JAZZ IN THE FRENCH QUARTER",
  },
  { id: uuid(), category: "What Are You Doing?", value: "BREAKING INTO SONG" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "READING A BEDTIME STORY",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "WATCHING OUR FAVORITE SHOW",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "RISING TO THE OCCASION",
  },
  { id: uuid(), category: "What Are You Doing?", value: "THROWING A PARTY" },
  { id: uuid(), category: "What Are You Doing?", value: "WATERING THE PLANTS" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "GETTING INTO THE SWING OF THINGS",
  },
  { id: uuid(), category: "What Are You Doing?", value: "LEADING BY EXAMPLE" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "TOSSING COINS INTO A WISHING WELL",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "CHARTING A NEW COURSE",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "LISTENING TO A PLAYLIST",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "TRAINING FOR A MARATHON",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "EARNING BROWNIE POINTS",
  },
  { id: uuid(), category: "What Are You Doing?", value: "LIFTING WEIGHTS" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "SOAKING IN A HOT TUB UNDER THE STARS",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "GETTING LOST IN THE CROWD",
  },
  { id: uuid(), category: "What Are You Doing?", value: "MAKING MINT JULEPS" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "RELAXING UNDER THE CARIBBEAN SUN",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "MAKING AN EDUCATED GUESS",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "READING BETWEEN THE LINES",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "TRYING ON A NEW GRASS SKIRT",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "GETTING AN EDGE ON THE COMPETITION",
  },
  { id: uuid(), category: "What Are You Doing?", value: "HOWLING AT THE MOON" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "SHARING THE ALOHA SPIRIT",
  },
  { id: uuid(), category: "What Are You Doing?", value: "KIDDING AROUND" },
  { id: uuid(), category: "What Are You Doing?", value: "KNITTING A SWEATER" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "BARKING UP THE WRONG TREE",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "SITTING IN THE HOT SEAT",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "REQUESTING EXTENDED SHORE LEAVE",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "SOAKING IN THE SPECTACULAR SCENERY",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "SETTING THE DINNER TABLE",
  },
  { id: uuid(), category: "What Are You Doing?", value: "PLAYING FOR KEEPS" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "HEADING IN THE RIGHT DIRECTION",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "CHECKING MY DAILY HOROSCOPE",
  },
  { id: uuid(), category: "What Are You Doing?", value: "SHOPPING ONLINE" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "DRINKING LEMONADE ON THE PORCH SWING",
  },
  { id: uuid(), category: "What Are You Doing?", value: "IMPROVISING" },
  { id: uuid(), category: "What Are You Doing?", value: "POPPING THE CORK" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "LOOKING THROUGH A TELESCOPE",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "CURLING UP WITH A GOOD BOOK",
  },
  { id: uuid(), category: "What Are You Doing?", value: "SHUFFLING THE CARDS" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "SINGING ALONG WITH THE RADIO",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "BROWSING FOR SOUVENIRS AND KEEPSAKES",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "POSING FOR A FAMILY PHOTO",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "GETTING MY STORY STRAIGHT",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "COLLECTING MY THOUGHTS",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "RESEARCH AND DEVELOPMENT",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "WORKING UP AN APPETITE",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "STANDING OUT FROM THE CROWD",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "ORDERING DINNER POOLSIDE",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "WRITING IN A JOURNAL",
  },
  { id: uuid(), category: "What Are You Doing?", value: "BLAZING A TRAIL" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "HEADING SOUTH FOR THE WINTER",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "SHOPPING FOR A NEW FLOWERED SHIRT",
  },
  { id: uuid(), category: "What Are You Doing?", value: "GAINING ALTITUDE" },
  { id: uuid(), category: "What Are You Doing?", value: "READING A BIOGRAPHY" },
  { id: uuid(), category: "What Are You Doing?", value: "TAKING THE TOUR" },
  { id: uuid(), category: "What Are You Doing?", value: "LAUGHING OUT LOUD" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "SINGING AND DANCING TO THE MUSIC",
  },
  { id: uuid(), category: "What Are You Doing?", value: "WATCHING FIREWORKS" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "COMING THROUGH IN THE CLUTCH",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "SHOOTING FREE THROWS",
  },
  { id: uuid(), category: "What Are You Doing?", value: "LAUGHING IT UP" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "TASTING LOCAL SPECIALTIES",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "FLASHING A WINNING SMILE",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "RECHARGING OUR BATTERIES",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "ORDERING THE CHEF'S SPECIAL",
  },
  { id: uuid(), category: "What Are You Doing?", value: "BROWSING" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "SHARING PHOTOS OF THE VACATION I WON",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "GETTING THE HANG OF THINGS",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "SHOPPING DINING AND HAVING FUN IN THE SUN",
  },
  { id: uuid(), category: "What Are You Doing?", value: "FANNING THE FLAMES" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "COMING UP WITH A NOVEL IDEA",
  },
  { id: uuid(), category: "What Are You Doing?", value: "VACUUMING" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "HIKING ALONG THE GREAT WALL OF CHINA",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "PUTTING ON THE FINISHING TOUCHES",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "RESISTING TEMPTATION",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "LISTENING TO LIVE REGGAE MUSIC",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "SPENDING AN AFTERNOON IN THE SUN",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "CHATTING ON THE PHONE",
  },
  { id: uuid(), category: "What Are You Doing?", value: "GOING TO THE GYM" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "PULLING AWAY FROM THE PACK",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "TAKING A SUNSET STROLL",
  },
  { id: uuid(), category: "What Are You Doing?", value: "MAKING A BUDGET" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "GOING FOR A RIDE ON A RIVERBOAT",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "STAYING ONE STEP AHEAD",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "FINDING THE RIGHT ANSWER",
  },
  { id: uuid(), category: "What Are You Doing?", value: "WEARING FLIP FLOPS" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "LEAVING A LASTING IMPRESSION",
  },
  { id: uuid(), category: "What Are You Doing?", value: "SITTING SIDESADDLE" },
  { id: uuid(), category: "What Are You Doing?", value: "BANKING" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "PLAYING BY THE RULES",
  },
  { id: uuid(), category: "What Are You Doing?", value: "MY TAX RETURN" },
  { id: uuid(), category: "What Are You Doing?", value: "GOING THE DISTANCE" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "LOOKING THROUGH BINOCULARS",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "PLUCKING MY EYEBROWS",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "UNFOLDING THE ROAD MAP",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "SOARING TO NEW HEIGHTS",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "CONDUCTING AN EXPERIMENT",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "BENDING OVER BACKWARDS",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "RENEWING MY MEMBERSHIP",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "HOWLING WITH LAUGHTER",
  },
  { id: uuid(), category: "What Are You Doing?", value: "WAVING GOODBYE" },
  { id: uuid(), category: "What Are You Doing?", value: "HAILING A TAXI" },
  { id: uuid(), category: "What Are You Doing?", value: "ACTING ON IMPULSE" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "SETTING THE TIMER ON THE CROCK-POT",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "READING A BOOK BY THE POOL",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "LOOKING FORWARD TO HAPPY HOUR",
  },
  { id: uuid(), category: "What Are You Doing?", value: "JOKING AROUND" },
  { id: uuid(), category: "What Are You Doing?", value: "WORKING AS A TEAM" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "ATTRACTING ALL THE ATTENTION",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "SEEING ALL THE SIGHTS",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "MAKING QUITE A SPLASH",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "RESETTING MY PASSWORD",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "READING A DIGITAL BOOK",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "ESCAPING FROM ALL THE HUSTLE AND BUSTLE",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "CLIMBING ANCIENT MAYAN RUINS",
  },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "ENJOYING THE OLD WORLD CHARM",
  },
  { id: uuid(), category: "What Are You Doing?", value: "READING A COMPASS" },
  { id: uuid(), category: "What Are You Doing?", value: "THE LIMBO" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "STROLLING BAREFOOT ALONG THE SHORE",
  },
  { id: uuid(), category: "What Are You Doing?", value: "GAINING MOMENTUM" },
  { id: uuid(), category: "What Are You Doing?", value: "QUILTING" },
  { id: uuid(), category: "What Are You Doing?", value: "INTRODUCING MYSELF" },
  { id: uuid(), category: "What Are You Doing?", value: "PULLING DOUBLE DUTY" },
  { id: uuid(), category: "What Are You Doing?", value: "WORKING THE ROOM" },
  {
    id: uuid(),
    category: "What Are You Doing?",
    value: "GRILLING BURGERS IN THE BACKYARD",
  },
]
export default puzzleList
